### ISSUE TITLE
A new home for terminator

### ISSUE THREAD

**Issue by lazyfrosch** [gnome-terminator/terminator#1]
Sadly the old team of Terminator have given up maintaining the project, there hasn't been any activity on [Launchpad](https://launchpad.net/terminator) for years now.

As a user and the current maintainer of the package in Debian I have great interest in keeping the project alive.

This GitHub organization will be the new home for Terminator.

If you have contributed to terminator in the past, or are only a user who would like to contribute.

This organization on GitHub was started to give Terminator a new home, I think many user are still using it, and want to keep it.

Any help is appreciated!

Also see:
* https://bugs.launchpad.net/terminator/+bug/1849375 (others talking about forking)
* https://bugs.launchpad.net/terminator/+bug/1870202 (my info)

## Catching up with the old team

If you have any contact or relation to the "old" maintainers of Terminator, please contact me or them to get in touch.

We need to make this proper, and inform the users. At the moment I don't have any access to the Launchpad projects apart from filing and commenting on bugs.

## How can you help?

* Talk to me in this issue, or markus@lazyfrosch.de
* Join the new chat on https://gitter.im/gnome-terminator/community
* Open issues / port open issues from Launchpad
  - Make sure to link between GitHub and Launchpad in both directions
* Port your branches and code changes as Pull Requests to this repository

Or: Any other way you can think of!

## Joining the team

I want people to join this team, to help bringing Terminator to a better shape.

If you were a contributor to Terminator and I found your GitHub account, you should have received an invite!

**Comment by geckon** [comment]
Just a few words of support here :)

I have been using terminator for a long time and I still love it. I also am a Python developer and have been watching the porting efforts for a while now.

That said I don't feel I have enough time to become a proper maintainer unfortunately which is why I never volunteered to become one but I might be able to help with smaller things here and there and I definitely will report any issues found wherever the new active upstream ends up living.

**Comment by lazyfrosch** [comment]
@geckon Welcome, **any** help is welcome, we all have these problems...

**Comment by widhalmt** [comment]
+1 from me for keeping Terminator alive and well. As @geckon I might not have enough time (and coding knowledge) to be real maintainer, but if there are smaller tasks I can offer help. Terminator is well worth the effort.

And by the way: Thank you for keeping it alive.

**Comment by AdnanHodzic** [comment]
Happy to hear Terminator project is still alive as its my favorite terminal emulator :)

Looking forward to the updates and I'm hoping I'll have time to get involved with the project myself.

**Comment by lazyfrosch** [comment]
If you are opening issues here that were already on Launchpad, make sure to link between GitHub and Launchpad in both directions!

**Comment by grazzolini** [comment]
Hi, I'm the maintainer of terminator on Arch Linux. We have plans to drop python2 completely soon from Arch. I know @JAugusto42 fork and have been encouraging him with his python2 -> 3 efforts. I think it's great there's an effort to keep this project going. I want to switch the Arch Linux package to this, but for that I need a tagged release. Are there any plans to make a release in the near future? Thanks in advance.

**Comment by JAugusto42** [comment]
Hello @grazzolini , so as far as I know, @lazyfrosch is planning a release soon, we still have some adjustments that we want to make, however due to the lack of time it's a little complicated.

**Comment by lazyfrosch** [comment]
Indeed, currently master doesn't run on Python 2.7 anymore, not sure if we should support it for the time being.

I mainly want to make sure that metadata, and basic tests are in place, so that we at least test the compilation and dependencies.

Btw. I want to make a small website on gnome-terminator.github.io, if someone could contribute a bit of HTML and CSS...

**Comment by mckellyln** [comment]
Thanks so much, I am a big fan of Terminator and have been for years.
Can you make python -> python3 in the files so that if 2 and 3 are installed it works with 3 ?
I'll terst it soon, lmk if there is anything I can do to help.
thx,
-m

**Comment by lazyfrosch** [comment]
@mckellyln this is usually handled by setuptools, but not in this weird usage we are having here, see #8

**Comment by grazzolini** [comment]
I think we can wait a bit for a release. But, for example, that new vte version that broke the links, I think is the most pressing issue. I might backport a patch for this, but a point release with the "old" code here would be helpful.

**Comment by JAugusto42** [comment]
@grazzolini This has already been resolved at the master.

**Comment by grazzolini** [comment]
Yes, I'm aware. But I would need to backport it as a patch and apply to the current release on the package. Whereas if a point release is made here, I can simply switch the source to here.

**Comment by lazyfrosch** [comment]
I just published the first release here: 1.92
https://github.com/gnome-terminator/terminator/releases/tag/v1.92

Please help test, spread the news, and talk to your distribution if they would switch to our code base here.

**Comment by thomaklee** [comment]
> Hi, I'm the maintainer of terminator on Arch Linux. We have plans to drop python2 completely soon from Arch. I know @JAugusto42 fork and have been encouraging him with his python2 -> 3 efforts. I think it's great there's an effort to keep this project going. I want to switch the Arch Linux package to this, but for that I need a tagged release. Are there any plans to make a release in the near future? Thanks in advance.

I'm a loyal user of terminator on the arch Linux platform. I'm sorry that it stopped updating for a long time. Thank you for your contribution. I'm looking forward to the update.

**Comment by JAugusto42** [comment]
Yes, I also use it on arch linux and I am very happy with the possibility of keeping the terminator updated. We are going to improve a lot.

**Comment by grazzolini** [comment]
> I just published the first release here: 1.92
> https://github.com/gnome-terminator/terminator/releases/tag/v1.92
> 
> Please help test, spread the news, and talk to your distribution if they would switch to our code base here.

I have updated the terminator version on Arch Linux. Thanks for making a release. One small not is, your key seems to be expired @lazyfrosch. I have verified things manually and also by using keybase, but it would be nice if you had a non expired key, just saying.

**Comment by lazyfrosch** [comment]
@grazzolini My current subkeys are due for extension, but still valid until `2020-09-13`

I guess Keybase is the problem here, I update the normal keyservers, as you can see here:

http://pgp.zdv.uni-mainz.de:11371/pks/lookup?op=vindex&search=0x9A358BAB04A4ED27

Only on [db.debian.org](https://db.debian.org/search.cgi?uid=lazyfrosch&dosearch=1)

**Comment by grazzolini** [comment]
> @grazzolini My current subkeys are due for extension, but still valid until `2020-09-13`
> 
> I guess Keybase is the problem here, I update the normal keyservers, as you can see here:
> 
> http://pgp.zdv.uni-mainz.de:11371/pks/lookup?op=vindex&search=0x9A358BAB04A4ED27
> 
> Only on [db.debian.org](https://db.debian.org/search.cgi?uid=lazyfrosch&dosearch=1)

Don't worry. I've updated the key from a key server and all is good here.

**Comment by inoperable** [comment]
Maybe now team M$/Windows-Terminal will get some inspiration and stop (re)inventing terminator features the wrong way ;)

**Comment by thorian93** [comment]
Although many said it already, I am really grateful that someone keeps terminator alive, as it is my only terminal emulator, so matter which Linux I am on. Bis shout out thanks @lazyfrosch!

This is not only a thank you though: I am nowhere near being a developer, but my English is quite okay I think so I would love to help by porting issues from launchpad. My question is: Is you goal to have all issues from launchpad here or would I need development background to find the interesting issues? I don't want to spam the issues here.

**Comment by r2rien** [comment]
> Indeed, currently master doesn't run on Python 2.7 anymore, not sure if we should support it for the time being.
> 
> I mainly want to make sure that metadata, and basic tests are in place, so that we at least test the compilation and dependencies.
> 
> Btw. I want to make a small website on gnome-terminator.github.io, if someone could contribute a bit of HTML and CSS...

Another big shoutout thanks @lazyfrosch & all, what a good news to read !
+ you can count me in for python/html/css if I can be of any help, cheers !

**Comment by muraii** [comment]
I used Terminator for years on Slackware and now use it for WSL (1) on my Windows work machine. It's a great project and is a much better fit for how I work than ConEmu, which is nice but _massive_ and the settings feel labrynthine.

@lazyfrosch You mentioned something about starting up a site for it. I am a middling dolt with HTML and CSS but can muddle through and have made my way around a variety of Jekyll themes. Do you have particular ends in mind or something basic? Happy to help. I'd _really_ like to be able to work on the project myself, though it'll be a steep learning curve.

**Comment by lazyfrosch** [comment]
@muraii I want a basic website, hosted via GitHub pages. A simple Jekyll site would be fine, basically a short introduction, screenshots and reference to GitHub and Launchpad.

**Comment by FernandoBasso** [comment]
@muraii Are you already working on the website? I may be able to lend a hand as time permits.

**Comment by vishhvak** [comment]
@muraii @FernandoBasso, just came across this repo while looking for alternatives to my default Linux terminal, and I'd love to be a part of developing a new website for the revival of this project. Let me know if we can work together on this one.

**Comment by lazyfrosch** [comment]
I opened #62 for website discussions, feel free to join there.

**Comment by thorian93** [comment]
> This is not only a thank you though: I am nowhere near being a developer, but my English is quite okay I think so I would love to help by porting issues from launchpad. My question is: Is you goal to have all issues from launchpad here or would I need development background to find the interesting issues? I don't want to spam the issues here.

Any comment on my ticket migration question @lazyfrosch?

**Comment by lazyfrosch** [comment]
We should only port relevant issues, I try to keep the LP tracker open, while added a note: https://bugs.launchpad.net/terminator/+filebug

**Comment by Gu1nness** [comment]
I am happy to see this project maintained again and will gladly help improving it !

**Comment by balinbob** [comment]
Hi, I'm on Arch Linux (got lazy actually and moved to Manjaro about a year ago).   I keep up with Ubuntu when I have time.   I've been hacking on Terminator since before you could save your config in any way, and love using it.   Thank you for reviving the project.

I am a hobbyist python coder for years, beginning to learn to use PyLint and hoping to get some of my code posted on PyPi.   I'm not always available but will watch the site for any problems I may be able to solve.   My Terminator code is from Python 2 but I'm now using 3.

I've learned a lot of coding skills from hacking on Terminator.  Thanks again!

**Comment by kornicameister** [comment]
Count me in!

**Comment by sky-and-sand** [comment]
is there a snap package for it or Solus port?

**Comment by GrigLars** [comment]
I am a heavy user of Terminator since I discovered it in 2014.  I didn't realize it was in so much jeopardy. Sadly, I am not that strong a programmer. But I am a great administrator and can help with English documentation, if you need it.  I have been waiting to attach onto an open source project for a while now, since it's been assuring me a decent job since the 90s.  Time to give back to the community.

**Comment by b00f** [comment]
@lazyfrosch have you ever think about changing the name? Arnold was the last Terminator!

**Comment by lazyfrosch** [comment]
@sky-and-sand There is and will not be a snap, it doesn't make sense, since a terminal emulator should give you access to your local system, not a container with just your home directory.

**Comment by lazyfrosch** [comment]
@b00f Why should I change the name if it is well known to many users? There is nothing offensive to the name...

**Comment by thorian93** [comment]
> @b00f Why should I change the name if it is well known to many users? There is nothing offensive to the name...

I would argue it is quite the opposite. It is a nice little play on words while also giving a hint on the power of this tool. To me the name is quite the best one imaginable. And as you said: It is well known.

@b00f: I seem to reckon a joke from you, so don't get this wrong, but I am quite sure there will be little to now support for changing the name.

**Comment by haim0n** [comment]
Kudos for the effort :1st_place_medal: .
I actually failed in convincing the original terminator team moving to Github :) , well done !!
Had some humble contributions in the past, would love to keep on doing it. Count me in.

**Comment by mattrose** [comment]
Welcome, personally I tend to be on https://gitter.im/gnome-terminator/community a lot.

**Comment by vitaly-zdanevich** [comment]
I created [Wikipedia page](https://en.wikipedia.org/wiki/GNOME_Terminator), feel free to contribute.

**Comment by jooola** [comment]
Hey @lazyfrosch, sorry for reaching out on this ticket for this matter. I was wondering if there was any chances to get the latest version of terminator on Debian buster-backports ? The upstream version is not yet present on [Salsa](https://salsa.debian.org/python-team/packages/terminator), and was wondering of something was blocking this process ?

**Comment by lazyfrosch** [comment]
@jooola thanks for reaching out, I wanted to bring terminator to bullseye anyways and just uploaded 2.0.1 to unstable. Once this reached testing I will work on uploading a backport.

As usual, blocking point always is time and energy.

**Comment by lazyfrosch** [comment]
Since this is a pretty old topic, which only is merely a documentation of what happended, I'm going to close this issues.

Feel free to open new issues.

**Comment by andyl** [comment]
@lazyfrosch - long-time Terminator user - just discovered your fork - THANK YOU

**Comment by njames** [comment]
Like others I am a long time Terminator user and after seeing some fancy things like fig and warp in my feeds I thought I would find if I could contribute new features to Terminator.

Can promise I will be a contributor but I am a big time fan of the split screen and broadcast ability. 

Glad to have found the fork. :rocket: 

:+1:
