### ISSUE TITLE
Easier install and updating

### ISSUE THREAD

**Issue by Sarke** [gnome-terminator/terminator#101]
Any plans for a Snap/Flatpack or a deb repo?

Many users won't build from source.

EDIT: I thought https://launchpad.net/terminator/ was obsolete, is it still being pushed to?

**Comment by lazyfrosch** [comment]
How would a sandbox package work for a terminal emulator? It won't give you access to anything outside of your HOME, not even let you install packages or run sudo...

PPAs are closed for now, the LP project is merely kept for reference now.

**Comment by lazyfrosch** [comment]
You would have to SSH to your own system via localhost.

**Comment by mattrose** [comment]
Terminator is still being distributed in prepackaged form for most OSes, on linux it's as simple as "apt install terminator" or "dnf install terminator"

**Comment by mattrose** [comment]
There is a gnome-terminator snap on snapcraft.io that somebody uploaded, and it ... kinda works, but hasn't updated to 1.92 yet.  I'm not sure who is maintaining it, so I'm not sure how to get them to update to the code on github.

**Comment by Sarke** [comment]
I would much prefer an official deb repo, or even an official snap / flatpak.  Not sure I would trust an unofficial build in a snap.

> Terminator is still being distributed in prepackaged form for most OSes, on linux it's as simple as "apt install terminator" or "dnf install terminator"

Yes, but are they building those from this github code?

**Comment by lazyfrosch** [comment]
Many of them already have 1.92 in their current version:
https://github.com/gnome-terminator/terminator/blob/master/INSTALL.md#distributions

Of course you are free to reach out and point maintainers to our new project home.

**Comment by Sarke** [comment]
Perfect, that's what I was looking for.  Keep up the good work!
