### ISSUE TITLE
Remove gtk-update-icon-cache handling in setup

### ISSUE THREAD

**Issue by lazyfrosch** [gnome-terminator/terminator#102]
I don't see a reason why we should generate the cache like this, its even bad for packages. So (package) maintainers should disable it.

Debian:
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=959856

**Comment by mattrose** [comment]
Just noticed this hasn't been touched in a while and I'd like to get ready to release 2.0.  I'm going to remove the 2.0 milestone.  In the rpm manifest we just remove the icon-cache file.
