### ISSUE TITLE
Allow to open layout in a new tab

### ISSUE THREAD

**Issue by slaweet** [gnome-terminator/terminator#106]
By default, a new layout (from `alt+l` window) open in a new window. I prefer to have all terminator in one window, so it would be very useful to be able to open a new tab with a given layout. E.g. `ctrl+alt+l`, or from the context menu (similar to https://github.com/gnome-terminator/terminator/issues/63 )

If this is already possible, then I couldn't find it in docs.

**Comment by mattrose** [comment]
It's a good idea, but we'd have to be able to differentiate between layouts that contain windows and ones that are just panes.  We can't currently do that, but I think it's possible.

**Comment by slaweet** [comment]
Oh, I didn't know that layout can contain multiple windows. Can a layout also contain multiple tabs? That would help in my situation as well (maybe even better).

**Comment by mattrose** [comment]
Yep, layouts can contain any combination of windows tabs and panes.  The way you set it up is a little weird, but basically you go to layouts, add a new layout then open up all your windows the way you like, then select that new layout and hit save.

**Comment by mattrose** [comment]
If this works for you, feel free to close the issue.

**Comment by slaweet** [comment]
Thank you @mattrose, very helpful tip on setting up layouts :+1:  
So tabs is `type = Notebook` in `/.config/terminator/config` :bulb: :smile:

**Comment by Sobak** [comment]
My apologies for responding to a 6 year old question but I didn't understand from what's been written above, and I failed to fully grasp the code around it :/ Is this (opening a layout in new tab, rather than a window) possible today?

@mattrose @slaweet
