### ISSUE TITLE
Option to prevent accidental closing of tabs

### ISSUE THREAD

**Issue by bjfar** [gnome-terminator/terminator#108]
Surprisingly often I find that I accidentally close a tab where I am working in vim or some such, and lose work as a result. It would be nice if I could turn on a "safety" option somewhere that would cause an "are you sure" dialog box to appear, similar to what happens when you attempt to close a window containing multiple tabs. I understand this might annoy people so having it off by default would be fine. Perhaps you could also "shift-click" or some such to circumvent the dialog box.

**Comment by ohir** [comment]
Simply add to your global config `close_button_on_tab = False`

*This option is avaliable since at least 0.9x.*

**Comment by mattrose** [comment]
@bjfar will this work for you?

**Comment by bjfar** [comment]
Ah great, certainly that sounds fine! It's just rogue mouse clicks that
bother me, I never accidentally closed a tab via the keyboard, so removing
the close button sounds good. I'll give it a try.

**Comment by mattrose** [comment]
All right I'll close this.  Feel free to reopen if you're still having problems
