### ISSUE TITLE
Get a notification when terminal task is done

### ISSUE THREAD

**Issue by AdnanHodzic** [gnome-terminator/terminator#11]
It would be great if terminator would have an option to show a notification once a task has finished.

Similar to [NotiFyre](https://github.com/kaustubhhiware/NotiFyre), [undistract-me ](https://github.com/jml/undistract-me) and [Elemetnary OS terminal](https://github.com/elementary/terminal) projects.

![image](https://i.stack.imgur.com/OLzQD.jpg)

There are "In/ActivityWatch" plugins in Terminator, but I find them unreliable and complicated to configure.

**Comment by dmaphy** [comment]
The plugins seem to work quite fine for me on Fedora with terminator-1.91-15.fc32.noarch.

**Comment by x4lldux** [comment]
Enjoy https://github.com/x4lldux/terminator-long-cmd-notify

**Comment by mattrose** [comment]
@x4lldux I just looked at this.  It works amazingly, but I don't understand it at all.  Do you mind if I re-write it in straight python?

**Comment by x4lldux** [comment]
@mattrose Sure, go ahead! Don't mind me, I'm just a lisp guy trying to confuse everyone ;)
