### ISSUE TITLE
Adjust Line Height

### ISSUE THREAD

**Issue by srt0** [gnome-terminator/terminator#111]
It is really necessary to have the option to adjust the line height. To me its really compact right now. But as a terminal, Terminator is awesome!

**Comment by mattrose** [comment]
I'm having a little trouble understanding your request, can you give an example of another terminal program that does this, and how it's configured?

**Comment by mattrose** [comment]
You're in luck!  VTE has support for this (Egmont added it a couple of years back) so it shouldn't be too hard to add in to Terminator.  I will investigate further.
https://gitlab.gnome.org/GNOME/vte/-/commit/26c79c6dc93aae4d4f787f36b594cac151df0f07

**Comment by srt0** [comment]
Awesome! Can't wait to use Terminator as my default terminal again.

**Comment by mattrose** [comment]
@srt0 do you want to try out the associated PR?  I haven't wired in the preferences dialog yet, but you can try it out by following the instructions in the PR

**Comment by srt0** [comment]
@mattrose It works! :)
![terminator-test](https://user-images.githubusercontent.com/10282404/84398494-d70be280-ac21-11ea-9703-9ec1cdf9d255.png)

**Comment by mattrose** [comment]
Awesome!  Thank you so much for trying it out.  Getting the UI around it right is going to be tricky, because what you put in there is ... not really intuitive:  "A float between 1.0 and 2.0".  I'm probably going to add a slider like the transparency one.

**Comment by srt0** [comment]
I usually use 1.3. It was set to 2 just for the screenshot :)

**Comment by mattrose** [comment]
Yeah, the main reason I put in that PR in it's unfinished state was honestly so that you could use it right now, and it'll give me time to come up with a UI for a user that's not familiar with that feature to play with it intuitively.

**Comment by mattrose** [comment]
Putting a call out for somebody with more glade experience than I do.  Can somebody take a look at  this and see if they can add a slider on the profiles->General pane for values between 1.0 and 2.0 in increments of .1 for the `line_height` configuration?  I am having all kinds of bad luck with glade and I just want this to be done.

**Comment by FernandoBasso** [comment]
I think this is related to https://github.com/gnome-terminator/terminator/pull/552.
