### ISSUE TITLE
Strange character (edited to keep it clean)

### ISSUE THREAD

**Issue by SneaKoa** [gnome-terminator/terminator#117]
Hello,

I upgraded my fedora (31 to 32) and now it have only one big issues with terminator that i can't find how to correct.
I have weird character at the place of normal character, every are now little cube with an the unicode of the character.

Everything look to work anyway i can still exit or clean the tab, even do a ls with everything character write in a box and inside the unicode.

Thank you if you have any idea of how i could correct this.

**Comment by SneaKoa** [comment]
If you need more info i can send screen shot but i can't send them here, idk why

**Comment by mattrose** [comment]
Wow.  What language do you have set?
Also, it would greatly help if you could send a screenshot, maybe find a place to put a screenshot on another website and link to it here?

**Comment by mattrose** [comment]
Duplicate of #139 It's a later issue, but it has more information and a screenshot
