### ISSUE TITLE
Support desktop dark/light theme

### ISSUE THREAD

**Issue by gforcada** [gnome-terminator/terminator#119]
*I've seen https://github.com/gnome-terminator/terminator/issues/72 so if that's sort of the same, feel free to close it :)*

I'm a big fan of the dark/light theme changing the whole desktop (firefox, nautilus, etc etc) and I usually switch between two themes on terminator, so for my use case, it would be great that one could set a light theme and a dark theme on terminator and for the tabs with the default profile get that updated as soon as the desktop global theme is switched :rainbow:

**Comment by mattrose** [comment]
Same as #72

**Comment by yurenchen000** [comment]
https://github.com/yurenchen000/terminator-autotheme-plugin

hi,  @gforcada 
i made a plugin, maybe it's what you want
