### ISSUE TITLE
Putty style paste makes it impossible to reach preferences

### ISSUE THREAD

**Issue by uffejakobsen** [gnome-terminator/terminator#120]
Putty style paste makes it impossible to reach preferences

When putty style paste is enabled it is impossible to get into preferences (prefs) as it requires right click

This could be solved by adding a configurable hot key for opening Prefs and/or having access to prefs from the dropdown in the title bar

**Comment by mattrose** [comment]
the context key on your keyboard usually works, but I kinda agree with this.  One of the things I was thinking of doing was moving to a GTK headerbar like gnome-terminal has, and add a button to access the popup menu to that.

**Comment by uffejakobsen** [comment]
Sounds like at good idea.
Also not all keyboard does not seem to have a context key

**Comment by mattrose** [comment]
True that.  My macbook doesn't have one.  I have some code that I may publish on my fork to get more feedback for the headerbar idea.

**Comment by robertoetcheverryr** [comment]
When you set PuTTY style paste, the middle button takes the role of menu-opener... You also have Shift + F10 to open the menu.

**Comment by nicowilliams** [comment]
I just ran into this, and then found this issue quickly enough, so I've the workarounds (middle mouse button, Shift-F10), so I'm set.  But maybe the help and/or preferences putty-style-paste description could be clearer on this?  Also, the keybinding for Preferences is shown as Disabled, yet Shift-F10 works, so I couldn't have found it that way though I could have _added_ a keybinding for Preferences.
