### ISSUE TITLE
Feature request: configurable shortcut to open Prefs

### ISSUE THREAD

**Issue by UffeJakobsen** [gnome-terminator/terminator#121]
It would be nice wuth a configurable shortcut to open prefs window

**Comment by MKaras93** [comment]
Such shortcut would be very useful, especially with a shortcut to shortcuts tab :exploding_head: 
Currently when you want to look up a shortcut, you have to use the mouse.

When it comes to where to anchor the menu: does it really matter where it's anchored, maybe anchor at the active cursor? Or at the top of the window?
