### ISSUE TITLE
align maximize option spelling with gnome-terminal

### ISSUE THREAD

**Issue by uffejakobsen** [gnome-terminator/terminator#125]
terminator has the maximize option spelled differently from gnome-terminal (and xfce-terminal)

maximise (UK) versus maximize (US)

```
terminator --maximise

versus

gnome-terminal --maximize
xfce-terminal --maximize
```

As a drop-in replacement for gnome-terminal it would be nice if the most used cli options were somewhat in sync.

As terminator is already released with --maximise option one solution could be to recognoze both --maximise and --maximize options ?

**Comment by mattrose** [comment]
Where we have the same features as gnome-terminal, we want to match gnome-terminal as closely as we can, this shouldn't be too hard.

**Comment by mattrose** [comment]
If anyone wants to take a crack at this, it should be just copying and pasting the maximise option in `terminatorlib/optionparse.py`
