### ISSUE TITLE
Fails to run for LDAP user

### ISSUE THREAD

**Issue by agagliardi** [gnome-terminator/terminator#128]
On RHEL 7.6, installed using SNAP. 1.9.1-beta

```
Traceback (most recent call last):
  File "/snap/gnome-terminator/1/bin/terminator", line 58, in <module>
    username = pwd.getpwuid(os.getuid()).pw_name
KeyError: 'getpwuid(): uid not found: xxxxx'

```

https://github.com/gnome-terminator/terminator/blob/a762bb9ff0445558518aabbc30e7bba39100668d/terminator#L59

Maybe should be used getpass.getuser() instead

**Comment by mattrose** [comment]
the python pwd library should just be doing the equivalent of `getent passwd xxxx` and NSS should be taking care of the actual call to LDAP and exposing it to terminator.  I seem to recall that there were problems with this with redhat specifically, and this article title https://access.redhat.com/solutions/3894191 kinda solidifies my suspicions, even though I can't read the full article.  This code is very generic and works across all POSIX platforms and all versions of python and I hesitate to replace it to work around an issue that's specific to redhat, and one that they will likely fix in the future.

**Comment by agagliardi** [comment]
I can read it. It's because SSSD `enumerate` is false by default and there is some trade-off in enabling it, take a look at the man page https://linux.die.net/man/5/sssd.conf .

**Comment by agagliardi** [comment]
I've installed the same version from EPEL repository and it works.
Maybe it was just something about lib deps or permission. 
Sorry to bother you.
