### ISSUE TITLE
PuTTY style paste is pasting from x-selection instead of clipboard

### ISSUE THREAD

**Issue by robertoetcheverryr** [gnome-terminator/terminator#134]
Kali Linux 2020.2
Terminator 1.92-2
After setting PuTTY style paste, the expected behaviour is for the right-click to paste the clipboard content (that is how PuTTY works after all) yet Terminator is pasting the context of the x-selection/PRIMARY instead.
I have selected the option to copy on selection to also mimic PuTTY's copy-on-select.

A quick overview of the code seems to point to terminal.py:
```
if self.config['putty_paste_style']:
            middle_click = [self.popup_menu, (widget, event)]
            right_click = [self.paste_clipboard, (True, )]
        else:
            middle_click = [self.paste_clipboard, (True, )]
            right_click = [self.popup_menu, (widget, event)]
```
If the intent is to replicate PuTTY's behaviour then it should paste the clipboard but the parameter primary=True actually branches to paste the primary instead.
Maybe a selection box to define if the right click will paste the clipboard OR the x-selection?

**Comment by mattrose** [comment]
I'll take a look at this.  You're absolutely right about it not following putty, but I'm hesitant about changing behaviour (however misleadingly named) that's been established for so long.

**Comment by robertoetcheverryr** [comment]
I have done mostly command-line apps and have little experience with GUI (and even less with Linux GUIs) but I forked the code to see if I can familiarize myself with the GUI part and add the relevant toggle.
Maybe to add an option to the config file and the corresponding checkbox or toggle to the pref editor, keeping the current default, could be the no-impact solution?
Something like
putty_paste_style_source_primary, being True the current behaviour...

**Comment by mattrose** [comment]
Funny you should mention that.  None of the other current maintainers have much experience with GUIs and got their start with terminator by forking and poking at the code, much like you have.  See #111 for a stunning example from yours truly 😄   I will take a look at it and see if I can add a checkbox for this, but any help you can offer would be greatly appreciated and will get your name in the credits.

**Comment by robertoetcheverryr** [comment]
Well, done and done. Pull Request #135 ready for review.

**Comment by mattrose** [comment]
Thank you so much for this.  The tests seem to be failing for an unrelated reason, so I'll try to debug that first and there might be a delay in merging, but it will get merged.  Thanks again

**Comment by mattrose** [comment]
Merged.  Thanks so much for contributing.
