### ISSUE TITLE
Errors in prefseditor.py

### ISSUE THREAD

**Issue by robertoetcheverryr** [gnome-terminator/terminator#137]
Loading the Terminator project onto PyCharm for the last issue I raised notified me of a lot of PEP style problems but more importantly, I found a bug:
prefseditor.py:
```
    def on_backspace_binding_combobox_changed(self, widget):
        """Backspace binding setting changed"""
        selected = widget.get_active()
        if selected == 1:
            value = 'control-h'
        elif selected == 2:
            value = 'ascii-del'
        elif selected == 3:
            value == 'escape-sequence'
        else:
            value = 'automatic'
        self.config['backspace_binding'] = value
        self.config.save()
```
If you select Escape Sequence it fails to apply the option and save the config. It's a simple case of fat fingers putting a double = and turning an assignment into an evaluation.
Are there any cleanup/style or other tasks that I could help with? In that same file, there is an apparently superfluous import of GObject, but I'd rather not touch that yet.

**Comment by mattrose** [comment]
There are a **lot** of cleanup items that need to be done.  @lazyfrosch and I just took over the code in March, so, personally, I've just been spelunking into the code and trying to wrap my head around it all.  I've got a pretty good handle on it now, but I haven't really compiled a todo list of cleanup items yet.

I would absolutely love pull requests for any improvements you can see, and I tend to pull in small PRs as quickly as I see them.  You don't even have to open an issue, just a PR is fine.

Thanks again for your contribution

**Comment by robertoetcheverryr** [comment]
Ok, the bug I mentioned is fixed in PR #138. If I see anything else I'll just make a PR. I'm used to a targeted environment, so I do not want to mess with the imports and stuff in case it breaks something back in Python 2.x I'll be wrapping my head around the code (and the tests!) and keep an eye on whatever I can help. Thank you for taking over the code.

**Comment by mattrose** [comment]
The tests run on python 2.7, and they've been good so far at catching import errors.  Unit testing is not my strong suit, but I like them, so any work you can do at writing more tests would be handy.

**Comment by mattrose** [comment]
Fixed. with PR #146
