### ISSUE TITLE
No Text Display on Ubuntu r20.04

### ISSUE THREAD

**Issue by aplatypus** [gnome-terminator/terminator#139]
**PROBLEM**: 

* Running Ubuntu 20.04, upgraded from 19.10
* When I run terminator the display just show a unprintable character glyph (see screenshot, note 1).
    *  No suitabl workaround has been found as yet.
* Next I removed terminator from the system and reinstalled using the `ppa` from the terminator page.
** `apt` reported a security error for `gnome-terminator` repository see: note 2.
** Results is same after complete reinstall -- screenshot, note 1.

**IMPACT**:

* Terminator unusable current **Ubuntu** LTS 20.04

**EXPECTED**:

* Text output shall appear in the appropriate font.
* Repository shall have no errors.

**NOTES**:

1. **Terminator screenshot** --  `ls -l` output

![terminator--2020-06-21_09-01](https://user-images.githubusercontent.com/67028/85213159-f7fcd200-b39d-11ea-90b1-aee5088e794c.png)

2. **Repository error**

Err:6 http://ppa.launchpad.net/gnome-terminator/ppa/ubuntu focal Release                                                                                                                                         
  404  Not Found [IP: 91.189.95.83 80]
Reading package lists... Done                                                                                                                                                                                    
E: The repository 'http://ppa.launchpad.net/gnome-terminator/ppa/ubuntu focal Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.

**Comment by robertoetcheverryr** [comment]
I have tested with a minimal Ubuntu 20.04 LTS install, fully updated, and with the defaults. It works for me:
![image](https://user-images.githubusercontent.com/63941860/85216050-82214800-b356-11ea-9d53-a95a8bc9286e.png)
Are you choosing a different desktop environment?

**Comment by mattrose** [comment]
@aplatypus What window manager/desktop environment are you running?
What language is your computer set to?
Can you paste .config/terminator/config in here?

**Comment by Evernow** [comment]
Note, had a user with this exact issue, deleting the config file fixed it.

**Comment by mattrose** [comment]
Yeah, I have a feeling that it has a text encoding or language setting in the config and the underlying OS doesn't have the proper character set.

**Comment by mattrose** [comment]
closing this issue
