### ISSUE TITLE
Switch to setuptools

### ISSUE THREAD

**Issue by lazyfrosch** [gnome-terminator/terminator#14]
To better handle installation and dependencies we should switch from `distutils` to `setuptools`.

This will help with packaging too.

**Comment by geckon** [comment]
Just curious... Have you considered using poetry? I've recently switched several projects to poetry and I really like it.

**Comment by lazyfrosch** [comment]
If it helps maintaining setup.cfg or setup.py I would agree, not sure how many distros can work with `pyproject.toml`

**Comment by geckon** [comment]
That's actually a good point. I don't know how many distros support poetry either.
