### ISSUE TITLE
Terminator should use XDG_CONFIG_HOME environment variable if it's available.

### ISSUE THREAD

**Issue by mattrose** [gnome-terminator/terminator#152]
Most desktop software has standardised on using the XDG_CONFIG_HOME environment variable for the base directory for configuration files.  Terminator hardcodes `~/.config`.  We should check XDG_CONFIG_HOME and use that before falling back to `~/.config`

**Comment by mattrose** [comment]
https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html

We should also check if any other environment variables in this doc apply.

**Comment by qckzr** [comment]
Hey @mattrose, this seems to be already implemented in file `utils.py`:
``` python
def get_config_dir():
    try:
        configdir = os.environ['XDG_CONFIG_HOME']
    except KeyError:
        configdir = os.path.join(os.path.expanduser('~'), '.config')

    dbg('Found config dir: %s' % configdir)
    return(os.path.join(configdir, 'terminator'))
```

or am I missing something else?

**Comment by mattrose** [comment]
Well I'll be.  Thanks for looking into this.
