### ISSUE TITLE
VirtualBox resizing the window of the VM crashes terminator

### ISSUE THREAD

**Issue by Arnasnn** [gnome-terminator/terminator#153]
VirtualBox resizing the window of the Ubuntu VM crashes terminator.

This only happens, when some of the terminator windows gets too small.

Ubuntu 18.04.3 LTS
terminator --version
terminator 1.91

**Comment by mattrose** [comment]
Wow.  Do you have a traceback for this?  Can you run this under debug mode `terminator -u -d` to see if there are any debug messages when this happens?

**Comment by Arnasnn** [comment]
I can sometimes crash it even just minimizing the window till it crashes, logs of such crash:
`Titlebar::get_desired_visibility: configured visibility: True
ConfigBase::get_item: ConfigBase::get_item: show_titlebar found in profile default: True
ConfigBase::get_item: ConfigBase::get_item: show_titlebar found in profile default: True
Titlebar::get_desired_visibility: configured visibility: True
ConfigBase::get_item: ConfigBase::get_item: show_titlebar found in profile default: True
Titlebar::update_visibility: showing titlebar
ConfigBase::get_item: ConfigBase::get_item: title_hide_sizetext found in globals: False
ConfigBase::get_item: ConfigBase::get_item: title_use_system_font found in globals: True
ConfigBase::get_item: ConfigBase::get_item: putty_paste_style found in globals: False
ConfigBase::get_item: ConfigBase::get_item: focus found in globals: click
ConfigBase::get_item: ConfigBase::get_item: focus found in globals: click
ConfigBase::get_item: ConfigBase::get_item: focus found in globals: click
ConfigBase::get_item: ConfigBase::get_item: focus found in globals: click
ConfigBase::get_item: ConfigBase::get_item: focus found in globals: click
ConfigBase::get_item: ConfigBase::get_item: focus found in globals: click
ConfigBase::get_item: ConfigBase::get_item: focus found in globals: click
ConfigBase::get_item: ConfigBase::get_item: focus found in globals: click
ConfigBase::get_item: ConfigBase::get_item: title_hide_sizetext found in globals: False
ConfigBase::get_item: ConfigBase::get_item: title_use_system_font found in globals: True
ConfigBase::get_item: ConfigBase::get_item: geometry_hinting found in globals: False
ConfigBase::get_item: ConfigBase::get_item: title_hide_sizetext found in globals: False
ConfigBase::get_item: ConfigBase::get_item: title_use_system_font found in globals: True
ConfigBase::get_item: ConfigBase::get_item: geometry_hinting found in globals: False
ConfigBase::get_item: ConfigBase::get_item: title_hide_sizetext found in globals: False
ConfigBase::get_item: ConfigBase::get_item: title_use_system_font found in globals: True
ConfigBase::get_item: ConfigBase::get_item: geometry_hinting found in globals: False
ConfigBase::get_item: ConfigBase::get_item: title_hide_sizetext found in globals: False
ConfigBase::get_item: ConfigBase::get_item: title_use_system_font found in globals: True
ConfigBase::get_item: ConfigBase::get_item: geometry_hinting found in globals: False
ConfigBase::get_item: ConfigBase::get_item: title_hide_sizetext found in globals: False
ConfigBase::get_item: ConfigBase::get_item: title_use_system_font found in globals: True
ConfigBase::get_item: ConfigBase::get_item: geometry_hinting found in globals: False
ConfigBase::get_item: ConfigBase::get_item: title_hide_sizetext found in globals: False
ConfigBase::get_item: ConfigBase::get_item: title_use_system_font found in globals: True
ConfigBase::get_item: ConfigBase::get_item: geometry_hinting found in globals: False
ConfigBase::get_item: ConfigBase::get_item: title_hide_sizetext found in globals: False
ConfigBase::get_item: ConfigBase::get_item: title_use_system_font found in globals: True
ConfigBase::get_item: ConfigBase::get_item: geometry_hinting found in globals: False
ConfigBase::get_item: ConfigBase::get_item: title_hide_sizetext found in globals: False
ConfigBase::get_item: ConfigBase::get_item: title_use_system_font found in globals: True
ConfigBase::get_item: ConfigBase::get_item: geometry_hinting found in globals: False
ConfigBase::get_item: ConfigBase::get_item: title_hide_sizetext found in globals: False
ConfigBase::get_item: ConfigBase::get_item: title_use_system_font found in globals: True
ConfigBase::get_item: ConfigBase::get_item: geometry_hinting found in globals: False
ConfigBase::get_item: ConfigBase::get_item: title_hide_sizetext found in globals: False
ConfigBase::get_item: ConfigBase::get_item: title_use_system_font found in globals: True
ConfigBase::get_item: ConfigBase::get_item: geometry_hinting found in globals: False
ConfigBase::get_item: ConfigBase::get_item: title_hide_sizetext found in globals: False
ConfigBase::get_item: ConfigBase::get_item: title_use_system_font found in globals: True
ConfigBase::get_item: ConfigBase::get_item: geometry_hinting found in globals: False
ConfigBase::get_item: ConfigBase::get_item: title_hide_sizetext found in globals: False
ConfigBase::get_item: ConfigBase::get_item: title_use_system_font found in globals: True
ConfigBase::get_item: ConfigBase::get_item: geometry_hinting found in globals: False
ConfigBase::get_item: ConfigBase::get_item: title_hide_sizetext found in globals: False
ConfigBase::get_item: ConfigBase::get_item: title_use_system_font found in globals: True
ConfigBase::get_item: ConfigBase::get_item: geometry_hinting found in globals: False
ConfigBase::get_item: ConfigBase::get_item: title_hide_sizetext found in globals: False
ConfigBase::get_item: ConfigBase::get_item: title_use_system_font found in globals: True
ConfigBase::get_item: ConfigBase::get_item: geometry_hinting found in globals: False
ConfigBase::get_item: ConfigBase::get_item: title_hide_sizetext found in globals: False
ConfigBase::get_item: ConfigBase::get_item: title_use_system_font found in globals: True
ConfigBase::get_item: ConfigBase::get_item: geometry_hinting found in globals: False
ConfigBase::get_item: ConfigBase::get_item: title_hide_sizetext found in globals: False
ConfigBase::get_item: ConfigBase::get_item: title_use_system_font found in globals: True
ConfigBase::get_item: ConfigBase::get_item: geometry_hinting found in globals: False
ConfigBase::get_item: ConfigBase::get_item: title_hide_sizetext found in globals: False
ConfigBase::get_item: ConfigBase::get_item: title_use_system_font found in globals: True
ConfigBase::get_item: ConfigBase::get_item: geometry_hinting found in globals: False
ConfigBase::get_item: ConfigBase::get_item: title_hide_sizetext found in globals: False
ConfigBase::get_item: ConfigBase::get_item: title_use_system_font found in globals: True
ConfigBase::get_item: ConfigBase::get_item: geometry_hinting found in globals: False
ConfigBase::get_item: ConfigBase::get_item: title_hide_sizetext found in globals: False
ConfigBase::get_item: ConfigBase::get_item: title_use_system_font found in globals: True
ConfigBase::get_item: ConfigBase::get_item: geometry_hinting found in globals: False
ConfigBase::get_item: ConfigBase::get_item: title_hide_sizetext found in globals: False
ConfigBase::get_item: ConfigBase::get_item: title_use_system_font found in globals: True
ConfigBase::get_item: ConfigBase::get_item: geometry_hinting found in globals: False
ConfigBase::get_item: ConfigBase::get_item: title_hide_sizetext found in globals: False
ConfigBase::get_item: ConfigBase::get_item: title_use_system_font found in globals: True
ConfigBase::get_item: ConfigBase::get_item: geometry_hinting found in globals: False
ConfigBase::get_item: ConfigBase::get_item: title_hide_sizetext found in globals: False
ConfigBase::get_item: ConfigBase::get_item: title_use_system_font found in globals: True
ConfigBase::get_item: ConfigBase::get_item: geometry_hinting found in globals: False
ConfigBase::get_item: ConfigBase::get_item: title_hide_sizetext found in globals: False
ConfigBase::get_item: ConfigBase::get_item: title_use_system_font found in globals: True
ConfigBase::get_item: ConfigBase::get_item: geometry_hinting found in globals: False
ConfigBase::get_item: ConfigBase::get_item: title_hide_sizetext found in globals: False
ConfigBase::get_item: ConfigBase::get_item: title_use_system_font found in globals: True
ConfigBase::get_item: ConfigBase::get_item: geometry_hinting found in globals: False
ConfigBase::get_item: ConfigBase::get_item: title_hide_sizetext found in globals: False
ConfigBase::get_item: ConfigBase::get_item: title_use_system_font found in globals: True
ConfigBase::get_item: ConfigBase::get_item: geometry_hinting found in globals: False
ConfigBase::get_item: ConfigBase::get_item: title_hide_sizetext found in globals: False
ConfigBase::get_item: ConfigBase::get_item: title_use_system_font found in globals: True
ConfigBase::get_item: ConfigBase::get_item: geometry_hinting found in globals: False
**
Vte:ERROR:../../src/vteaccess.cc:626:void vte_terminal_accessible_text_scrolled(VteTerminal*, gint, gpointer): assertion failed: (i >= 1)
fish: “terminator -u -d” terminated by signal SIGABRT (Abort)
`

In order for it to crash when resizing VM window it helps to be full screen, but can be reproduced without issues:

`Titlebar::get_desired_visibility: configured visibility: True
ConfigBase::get_item: ConfigBase::get_item: show_titlebar found in profile default: True
ConfigBase::get_item: ConfigBase::get_item: show_titlebar found in profile default: True
Titlebar::get_desired_visibility: configured visibility: True
ConfigBase::get_item: ConfigBase::get_item: show_titlebar found in profile default: True
Titlebar::update_visibility: showing titlebar
ConfigBase::get_item: ConfigBase::get_item: title_hide_sizetext found in globals: False
ConfigBase::get_item: ConfigBase::get_item: title_use_system_font found in globals: True
ConfigBase::get_item: ConfigBase::get_item: putty_paste_style found in globals: False
ConfigBase::get_item: ConfigBase::get_item: title_hide_sizetext found in globals: False
ConfigBase::get_item: ConfigBase::get_item: title_use_system_font found in globals: True
ConfigBase::get_item: ConfigBase::get_item: geometry_hinting found in globals: False
ConfigBase::get_item: ConfigBase::get_item: title_hide_sizetext found in globals: False
ConfigBase::get_item: ConfigBase::get_item: title_use_system_font found in globals: True
ConfigBase::get_item: ConfigBase::get_item: geometry_hinting found in globals: False
ConfigBase::get_item: ConfigBase::get_item: title_hide_sizetext found in globals: False
ConfigBase::get_item: ConfigBase::get_item: title_use_system_font found in globals: True
ConfigBase::get_item: ConfigBase::get_item: geometry_hinting found in globals: False
ConfigBase::get_item: ConfigBase::get_item: title_hide_sizetext found in globals: False
ConfigBase::get_item: ConfigBase::get_item: title_use_system_font found in globals: True
ConfigBase::get_item: ConfigBase::get_item: geometry_hinting found in globals: False
ConfigBase::get_item: ConfigBase::get_item: title_hide_sizetext found in globals: False
ConfigBase::get_item: ConfigBase::get_item: title_use_system_font found in globals: True
ConfigBase::get_item: ConfigBase::get_item: geometry_hinting found in globals: False
ConfigBase::get_item: ConfigBase::get_item: title_hide_sizetext found in globals: False
ConfigBase::get_item: ConfigBase::get_item: title_use_system_font found in globals: True
ConfigBase::get_item: ConfigBase::get_item: geometry_hinting found in globals: False
ConfigBase::get_item: ConfigBase::get_item: title_hide_sizetext found in globals: False
ConfigBase::get_item: ConfigBase::get_item: title_use_system_font found in globals: True
ConfigBase::get_item: ConfigBase::get_item: geometry_hinting found in globals: False
ConfigBase::get_item: ConfigBase::get_item: title_hide_sizetext found in globals: False
ConfigBase::get_item: ConfigBase::get_item: title_use_system_font found in globals: True
ConfigBase::get_item: ConfigBase::get_item: geometry_hinting found in globals: False
ConfigBase::get_item: ConfigBase::get_item: title_hide_sizetext found in globals: False
ConfigBase::get_item: ConfigBase::get_item: title_use_system_font found in globals: True
ConfigBase::get_item: ConfigBase::get_item: geometry_hinting found in globals: False
ConfigBase::get_item: ConfigBase::get_item: title_hide_sizetext found in globals: False
ConfigBase::get_item: ConfigBase::get_item: title_use_system_font found in globals: True
ConfigBase::get_item: ConfigBase::get_item: geometry_hinting found in globals: False
ConfigBase::get_item: ConfigBase::get_item: title_hide_sizetext found in globals: False
ConfigBase::get_item: ConfigBase::get_item: title_use_system_font found in globals: True
ConfigBase::get_item: ConfigBase::get_item: geometry_hinting found in globals: False
ConfigBase::get_item: ConfigBase::get_item: title_hide_sizetext found in globals: False
ConfigBase::get_item: ConfigBase::get_item: title_use_system_font found in globals: True
ConfigBase::get_item: ConfigBase::get_item: geometry_hinting found in globals: False
ConfigBase::get_item: ConfigBase::get_item: title_hide_sizetext found in globals: False
ConfigBase::get_item: ConfigBase::get_item: title_use_system_font found in globals: True
ConfigBase::get_item: ConfigBase::get_item: geometry_hinting found in globals: False
ConfigBase::get_item: ConfigBase::get_item: title_hide_sizetext found in globals: False
ConfigBase::get_item: ConfigBase::get_item: title_use_system_font found in globals: True
ConfigBase::get_item: ConfigBase::get_item: geometry_hinting found in globals: False
ConfigBase::get_item: ConfigBase::get_item: title_hide_sizetext found in globals: False
ConfigBase::get_item: ConfigBase::get_item: title_use_system_font found in globals: True
ConfigBase::get_item: ConfigBase::get_item: geometry_hinting found in globals: False
ConfigBase::get_item: ConfigBase::get_item: title_hide_sizetext found in globals: False
ConfigBase::get_item: ConfigBase::get_item: title_use_system_font found in globals: True
ConfigBase::get_item: ConfigBase::get_item: geometry_hinting found in globals: False
ConfigBase::get_item: ConfigBase::get_item: title_hide_sizetext found in globals: False
ConfigBase::get_item: ConfigBase::get_item: title_use_system_font found in globals: True
ConfigBase::get_item: ConfigBase::get_item: geometry_hinting found in globals: False
ConfigBase::get_item: ConfigBase::get_item: title_hide_sizetext found in globals: False
ConfigBase::get_item: ConfigBase::get_item: title_use_system_font found in globals: True
ConfigBase::get_item: ConfigBase::get_item: geometry_hinting found in globals: False
ConfigBase::get_item: ConfigBase::get_item: title_hide_sizetext found in globals: False
ConfigBase::get_item: ConfigBase::get_item: title_use_system_font found in globals: True
ConfigBase::get_item: ConfigBase::get_item: geometry_hinting found in globals: False
ConfigBase::get_item: ConfigBase::get_item: title_hide_sizetext found in globals: False
ConfigBase::get_item: ConfigBase::get_item: title_use_system_font found in globals: True
ConfigBase::get_item: ConfigBase::get_item: geometry_hinting found in globals: False
ConfigBase::get_item: ConfigBase::get_item: title_hide_sizetext found in globals: False
ConfigBase::get_item: ConfigBase::get_item: title_use_system_font found in globals: True
ConfigBase::get_item: ConfigBase::get_item: geometry_hinting found in globals: False
ConfigBase::get_item: ConfigBase::get_item: title_hide_sizetext found in globals: False
ConfigBase::get_item: ConfigBase::get_item: title_use_system_font found in globals: True
ConfigBase::get_item: ConfigBase::get_item: geometry_hinting found in globals: False
ConfigBase::get_item: ConfigBase::get_item: title_hide_sizetext found in globals: False
ConfigBase::get_item: ConfigBase::get_item: title_use_system_font found in globals: True
ConfigBase::get_item: ConfigBase::get_item: geometry_hinting found in globals: False
ConfigBase::get_item: ConfigBase::get_item: title_hide_sizetext found in globals: False
ConfigBase::get_item: ConfigBase::get_item: title_use_system_font found in globals: True
ConfigBase::get_item: ConfigBase::get_item: geometry_hinting found in globals: False
ConfigBase::get_item: ConfigBase::get_item: title_hide_sizetext found in globals: False
ConfigBase::get_item: ConfigBase::get_item: title_use_system_font found in globals: True
ConfigBase::get_item: ConfigBase::get_item: geometry_hinting found in globals: False
ConfigBase::get_item: ConfigBase::get_item: title_hide_sizetext found in globals: False
ConfigBase::get_item: ConfigBase::get_item: title_use_system_font found in globals: True
ConfigBase::get_item: ConfigBase::get_item: geometry_hinting found in globals: False
ConfigBase::get_item: ConfigBase::get_item: title_hide_sizetext found in globals: False
ConfigBase::get_item: ConfigBase::get_item: title_use_system_font found in globals: True
ConfigBase::get_item: ConfigBase::get_item: geometry_hinting found in globals: False
ConfigBase::get_item: ConfigBase::get_item: title_hide_sizetext found in globals: False
ConfigBase::get_item: ConfigBase::get_item: title_use_system_font found in globals: True
ConfigBase::get_item: ConfigBase::get_item: geometry_hinting found in globals: False
ConfigBase::get_item: ConfigBase::get_item: title_hide_sizetext found in globals: False
ConfigBase::get_item: ConfigBase::get_item: title_use_system_font found in globals: True
ConfigBase::get_item: ConfigBase::get_item: geometry_hinting found in globals: False
ConfigBase::get_item: ConfigBase::get_item: title_hide_sizetext found in globals: False
ConfigBase::get_item: ConfigBase::get_item: title_use_system_font found in globals: True
ConfigBase::get_item: ConfigBase::get_item: geometry_hinting found in globals: False
ConfigBase::get_item: ConfigBase::get_item: title_hide_sizetext found in globals: False
ConfigBase::get_item: ConfigBase::get_item: title_use_system_font found in globals: True
ConfigBase::get_item: ConfigBase::get_item: geometry_hinting found in globals: False
ConfigBase::get_item: ConfigBase::get_item: title_hide_sizetext found in globals: False
ConfigBase::get_item: ConfigBase::get_item: title_use_system_font found in globals: True
ConfigBase::get_item: ConfigBase::get_item: geometry_hinting found in globals: False
ConfigBase::get_item: ConfigBase::get_item: title_hide_sizetext found in globals: False
ConfigBase::get_item: ConfigBase::get_item: title_use_system_font found in globals: True
ConfigBase::get_item: ConfigBase::get_item: geometry_hinting found in globals: False
ConfigBase::get_item: ConfigBase::get_item: title_hide_sizetext found in globals: False
ConfigBase::get_item: ConfigBase::get_item: title_use_system_font found in globals: True
ConfigBase::get_item: ConfigBase::get_item: geometry_hinting found in globals: False
ConfigBase::get_item: ConfigBase::get_item: title_hide_sizetext found in globals: False
ConfigBase::get_item: ConfigBase::get_item: title_use_system_font found in globals: True
ConfigBase::get_item: ConfigBase::get_item: geometry_hinting found in globals: False
ConfigBase::get_item: ConfigBase::get_item: title_hide_sizetext found in globals: False
ConfigBase::get_item: ConfigBase::get_item: title_use_system_font found in globals: True
ConfigBase::get_item: ConfigBase::get_item: geometry_hinting found in globals: False
ConfigBase::get_item: ConfigBase::get_item: title_hide_sizetext found in globals: False
ConfigBase::get_item: ConfigBase::get_item: title_use_system_font found in globals: True
ConfigBase::get_item: ConfigBase::get_item: geometry_hinting found in globals: False
ConfigBase::get_item: ConfigBase::get_item: title_hide_sizetext found in globals: False
ConfigBase::get_item: ConfigBase::get_item: title_use_system_font found in globals: True
ConfigBase::get_item: ConfigBase::get_item: geometry_hinting found in globals: False
ConfigBase::get_item: ConfigBase::get_item: title_hide_sizetext found in globals: False
ConfigBase::get_item: ConfigBase::get_item: title_use_system_font found in globals: True
ConfigBase::get_item: ConfigBase::get_item: geometry_hinting found in globals: False
ConfigBase::get_item: ConfigBase::get_item: title_hide_sizetext found in globals: False
ConfigBase::get_item: ConfigBase::get_item: title_use_system_font found in globals: True
ConfigBase::get_item: ConfigBase::get_item: geometry_hinting found in globals: False
ConfigBase::get_item: ConfigBase::get_item: title_hide_sizetext found in globals: False
ConfigBase::get_item: ConfigBase::get_item: title_use_system_font found in globals: True
ConfigBase::get_item: ConfigBase::get_item: geometry_hinting found in globals: False
ConfigBase::get_item: ConfigBase::get_item: title_hide_sizetext found in globals: False
ConfigBase::get_item: ConfigBase::get_item: title_use_system_font found in globals: True
ConfigBase::get_item: ConfigBase::get_item: geometry_hinting found in globals: False
ConfigBase::get_item: ConfigBase::get_item: title_hide_sizetext found in globals: False
ConfigBase::get_item: ConfigBase::get_item: title_use_system_font found in globals: True
ConfigBase::get_item: ConfigBase::get_item: geometry_hinting found in globals: False
ConfigBase::get_item: ConfigBase::get_item: title_hide_sizetext found in globals: False
ConfigBase::get_item: ConfigBase::get_item: title_use_system_font found in globals: True
ConfigBase::get_item: ConfigBase::get_item: geometry_hinting found in globals: False
ConfigBase::get_item: ConfigBase::get_item: title_hide_sizetext found in globals: False
ConfigBase::get_item: ConfigBase::get_item: title_use_system_font found in globals: True
ConfigBase::get_item: ConfigBase::get_item: geometry_hinting found in globals: False
ConfigBase::get_item: ConfigBase::get_item: title_hide_sizetext found in globals: False
ConfigBase::get_item: ConfigBase::get_item: title_use_system_font found in globals: True
ConfigBase::get_item: ConfigBase::get_item: geometry_hinting found in globals: False
ConfigBase::get_item: ConfigBase::get_item: focus found in globals: click
ConfigBase::get_item: ConfigBase::get_item: focus found in globals: click
ConfigBase::get_item: ConfigBase::get_item: focus found in globals: click
ConfigBase::get_item: ConfigBase::get_item: focus found in globals: click
ConfigBase::get_item: ConfigBase::get_item: title_hide_sizetext found in globals: False
ConfigBase::get_item: ConfigBase::get_item: title_use_system_font found in globals: True
ConfigBase::get_item: ConfigBase::get_item: geometry_hinting found in globals: False
ConfigBase::get_item: ConfigBase::get_item: title_hide_sizetext found in globals: False
ConfigBase::get_item: ConfigBase::get_item: title_use_system_font found in globals: True
ConfigBase::get_item: ConfigBase::get_item: geometry_hinting found in globals: False
ConfigBase::get_item: ConfigBase::get_item: title_hide_sizetext found in globals: False
ConfigBase::get_item: ConfigBase::get_item: title_use_system_font found in globals: True
ConfigBase::get_item: ConfigBase::get_item: geometry_hinting found in globals: False
ConfigBase::get_item: ConfigBase::get_item: title_hide_sizetext found in globals: False
ConfigBase::get_item: ConfigBase::get_item: title_use_system_font found in globals: True
ConfigBase::get_item: ConfigBase::get_item: geometry_hinting found in globals: False
ConfigBase::get_item: ConfigBase::get_item: title_hide_sizetext found in globals: False
ConfigBase::get_item: ConfigBase::get_item: title_use_system_font found in globals: True
ConfigBase::get_item: ConfigBase::get_item: geometry_hinting found in globals: False
ConfigBase::get_item: ConfigBase::get_item: focus found in globals: click
ConfigBase::get_item: ConfigBase::get_item: focus found in globals: click
ConfigBase::get_item: ConfigBase::get_item: focus found in globals: click
ConfigBase::get_item: ConfigBase::get_item: focus found in globals: click
ConfigBase::get_item: ConfigBase::get_item: focus found in globals: click
ConfigBase::get_item: ConfigBase::get_item: focus found in globals: click
ConfigBase::get_item: ConfigBase::get_item: title_hide_sizetext found in globals: False
ConfigBase::get_item: ConfigBase::get_item: title_use_system_font found in globals: True
ConfigBase::get_item: ConfigBase::get_item: geometry_hinting found in globals: False
ConfigBase::get_item: ConfigBase::get_item: title_hide_sizetext found in globals: False
ConfigBase::get_item: ConfigBase::get_item: title_use_system_font found in globals: True
ConfigBase::get_item: ConfigBase::get_item: geometry_hinting found in globals: False
ConfigBase::get_item: ConfigBase::get_item: title_hide_sizetext found in globals: False
ConfigBase::get_item: ConfigBase::get_item: title_use_system_font found in globals: True
ConfigBase::get_item: ConfigBase::get_item: geometry_hinting found in globals: False
ConfigBase::get_item: ConfigBase::get_item: title_hide_sizetext found in globals: False
ConfigBase::get_item: ConfigBase::get_item: title_use_system_font found in globals: True
ConfigBase::get_item: ConfigBase::get_item: geometry_hinting found in globals: False
ConfigBase::get_item: ConfigBase::get_item: title_hide_sizetext found in globals: False
ConfigBase::get_item: ConfigBase::get_item: title_use_system_font found in globals: True
ConfigBase::get_item: ConfigBase::get_item: geometry_hinting found in globals: False
**
Vte:ERROR:../../src/vteaccess.cc:626:void vte_terminal_accessible_text_scrolled(VteTerminal*, gint, gpointer): assertion failed: (i >= 1)
fish: “terminator -u -d” terminated by signal SIGABRT (Abort)
`

**Comment by mattrose** [comment]
Wow, that looks like a problem with the underlying VTE lib.  A little googling suggests that it was hit by everyone that uses that lib (tilix, gnome-terminal) and never formally resolved, but it seems to have been fixed at some point, as it doesn't seem to happen anymore.

Can you try this with latest master, and see if it continues?

**Comment by Arnasnn** [comment]
Ran then install.py on master, 

terminator --version
terminator 1.92

Same issue:
`**
Vte:ERROR:../../src/vteaccess.cc:626:void vte_terminal_accessible_text_scrolled(VteTerminal*, gint, gpointer): assertion failed: (i >= 1)
fish: “terminator -u -d” terminated by signal SIGABRT (Abort)
`

**Comment by mattrose** [comment]
hmm.   What version of vte are you running?  I think the package is called libvte or vte.  can you run `dpkg -l | grep vte` and paste the output?

**Comment by Arnasnn** [comment]
`dpkg -l | grep vte

ii  gir1.2-vte-2.91:amd64                      0.52.2-1ubuntu1~18.04.2                      amd64        GObject introspection data for the VTE library
ii  libvte-2.91-0:amd64                        0.52.2-1ubuntu1~18.04.2                      amd64        Terminal emulator widget for GTK+ 3.0 - runtime files
ii  libvte-2.91-common                         0.52.2-1ubuntu1~18.04.2                      all          Terminal emulator widget for GTK+ 3.0 - common files
`

**Comment by mattrose** [comment]
can you safely upgrade those to the latest version?  I think that's where your problem is.

**Comment by Arnasnn** [comment]
Thanks for the help, I will try that later and will let you know.

**Comment by mattrose** [comment]
no feedback in 21 days, assuming fixed
