### ISSUE TITLE
On toggling visibility terminator moves down the window

### ISSUE THREAD

**Issue by kamilzaharan** [gnome-terminator/terminator#155]
Hello, every time I hide a terminator and then open it again, its window moves several pixels down from its default position all the way until its lower edge touches the menu bar after multiple toggling.

Version: terminator 1.91
System:
Linux Mint 20 Cinnamon
kernel 5.4.0-40-generic

**Comment by mattrose** [comment]
Whoa, I must have missed this issue earlier.  Sorry about that.

1. How are you hiding the window?  Using Ctrl-Alt-A?
2. Can you try reproducing this with the latest master

**Comment by mattrose** [comment]
I can't reproduce this.

**Comment by kamilzaharan** [comment]
Upgraded to 1.92, changed hiding window to ctrl-alt-a and the problem still stands.

**Comment by mattrose** [comment]
Hmm, I can reproduce this on Linux Mint Cinnamon, but not on Ubuntu or Fedora with GNOME.  I'm not sure what we can do, as we rely on the Window Manager / DE to properly position the window after it unmaximise.  We just call the proper GTK.Window.maximize() or unmaximise() method.
