### ISSUE TITLE
Feature Request: "broadcast-only" option in profile preferences

### ISSUE THREAD

**Issue by Sailstone** [gnome-terminator/terminator#157]
It would be useful to have an option - a checkbox in an individual profile's preferences - which allows a terminal to broadcast commands to other terminals, but not inject them into a system itself. A sort of meta command/control terminal, it only broadcasts commands to other ttys.  Not sure how troublesome this would be to implement with actions which need root.  

I believe there may be ways to accomplish this through special commands, not I'm not certain.

**Comment by mattrose** [comment]
This is easily done by creating a heredoc in a shell when setting up the broadcast group.  Just enter something like `cat <<EOF` in the "command" terminal while it's not part of the broadcast group, and then none of the commands will be executed on that server, but will be executed on the other terminals in the broadcast group.  Unfortunately, this is pretty much the only way I can see of doing ths.
