### ISSUE TITLE
Active tab identification

### ISSUE THREAD

**Issue by yash-15** [gnome-terminator/terminator#158]
I am using terminator 1.91 on Ubuntu 18.04
I want to highlight active tab with a distinctive background.

I tried to modify the CSS below:
/usr/share/terminator/terminatorlib/themes/Ambiance/gtk-3.0/apps/terminator_styling.css
```
/* give active tab a background, as it might be dragged across of others when reordering */
.terminator-terminal-window .notebook tab:active {
    /* background-color: @bg_color; */
    background-color: #FCBC8D;
}

.terminator-terminal-window .notebook:focus tab GtkLabel.active-page {
    border-color: @focus_color;
    /*background-color: @focus_bg_color;*/
    background-color: #FCBC8D;
}
```
but this does not seem to work. Can you please help me with the exact change I need to make to highlight the active tab. Happy to share more details. Making this (or a similar) change in many files made it work when I was on 16.04. But after upgrading to 18.04 it got restored.

**Comment by mattrose** [comment]
One thing I've found really helps me with these kinds of problems is the GTK Inspector.  set the env var `GTK_DEBUG=interactive` before running terminator and it will let you inspect all of the CSS properties and modify them.

**Comment by mattrose** [comment]
Instructions [here](http://blog.nabam.net/workstation/2017/09/15/terminator_tabs/) work for me
