### ISSUE TITLE
Search doesn't highlight words.

### ISSUE THREAD

**Issue by MarioMey** [gnome-terminator/terminator#161]
I remember that one day I report this bug... but I really don't remember where and what the workaround was.

When I search for a word, the line that includes the word appears at the top, but the word is not highlighted. It's difficult to know where the word is.

I use Terminator from Debian Buster repo 1.91, but I download 1.92 and it does the same.

Debian Buster 10 x64, Mate desktop 1.20.4.

**Comment by mattrose** [comment]
I'm pretty sure we've fixed that problem, I don't recall off the top of my head whether the fix made it into 1.92 or is just in the master branch

1. Make sure none of the earlier versions of 1.91 are running when testing 1.92, or test 1.92 using `terminator -u`
2. If that doesn't work, try downloading master and running that with the same `terminator -u` command.

**Comment by Fryboyter** [comment]
I can reproduce the problem under Arch Linux with version 1.92. But with the current master from Github the search term is highlighted.

**Comment by mattrose** [comment]
I think we need to cut a new release soon

**Comment by MarioMey** [comment]
Yes, in 1.92 the problem is gone. And maybe was because I had 1.91 running when testing 1.92.... but I just test it again and also 1.91 did highlight words... 🤷

Well, I just removed 1.91. Now it works all the times. Thanks.
