### ISSUE TITLE
ctrl-alt-a activates even when terminal has no focus

### ISSUE THREAD

**Issue by markjfisher** [gnome-terminator/terminator#163]
Hi,

When I'm using emacs (gui) with smartparens (for instance), when I use the ctrl-alt-a binding, it triggers terminator window and doesn't trigger a key response in emacs.

With no terminator running, the keybinding is honoured correctly in the emacs window, but if any terminal session is open (starting before or after starting emacs), it hijacks the keystroke and thus never gets to my editor session.

version: 1.9.1
os: ubuntu 20.04

**Comment by mattrose** [comment]
Probably best to change the keybinding in terminator to something else.  This is intended behaviour.
