### ISSUE TITLE
Feature Request: Add hyperlink support

### ISSUE THREAD

**Issue by pktiuk** [gnome-terminator/terminator#164]
It would be very nice to add supprot for Hyperlinks (a.k.a. HTML-like anchors) in terminator.
They are quite popular in other terminal emulators.

Some examples can be found [here](https://gist.github.com/egmontkob/eb114294efbcd5adb1944c9f3cb5feda)

**Comment by pktiuk** [comment]
It seems that there is already an implementation of hyperliknks, but it seems to work only with printed links.
`echo http://www.google.com` - Working
`echo www.google.com` and `printf '\e]8;;http://example.com\e\\This is a link\e]8;;\e\\\n'` - Not working

**Comment by mattrose** [comment]
Thanks for this, Egmont actually opened this when he introduced the feature.   https://bugs.launchpad.net/terminator/+bug/1686821

I'll take a look at it.

**Comment by mattrose** [comment]
I've started work on this and gotten your second example with the OSC-8 escape sequence working, see https://github.com/mattrose/terminator/tree/new-hyper if you're interested.  I'm still not sure about the first www.google.com example.  I'll see how gnome-terminal does it and if I can easily implement it.

**Comment by mattrose** [comment]
For some reason, the www.google.com example works now.  I'm going to pull this.
