### ISSUE TITLE
broken Close button in Terminator Preferences menu

### ISSUE THREAD

**Issue by br0kenbuild** [gnome-terminator/terminator#167]
steps:
- open Terminator
- right-mouse-click inside terminal
- click Preferences
- attempt to click bottom-right Close button

expected:
- be able to close Preferences menu via Close button

actual:
- Close button clicks but doesn't close the menu
- only top-right X button closes the menu

versions:
- terminator 1.91
- gnome 3.28.2
- py 2.7.17
- ubuntu 64b, 18.04 LTS, 4.15.0-111-generic

**Comment by mattrose** [comment]
Hmm, works for me.  Can you run terminator from the command line and see if there are any tracebacks on stdout or stderr?

**Comment by mattrose** [comment]
Also try upgrading to 1.92 or master.

**Comment by br0kenbuild** [comment]
> Hmm, works for me. Can you run terminator from the command line and see if there are any tracebacks on stdout or stderr?

running now off gnome-terminal as:
/usr/bin/terminator -d -d > term.log 2>&1

regarding 1.92, can you guys push it through Canonical people?
i got 1.9.1 as snap on beta stream and edge one seems to be the same (snap info gnome-terminator).

more observations:
- have another machine with very similar versions - only the kernel seems to be slightly newer 4.17.x - and cannot reproduce
- i have closed that OLD terminator session and now cannot reproduce in the same setup
- in my "buggy" setup i tend to run:
continuous ping, do-while loop for cat of resolv.conf and sometimes also openvpn session and i tend to put machine to sleep without closing Terminator, so perhaps this bug is one that child process overflows after some of these cycles. if you blamed me for nurturing unstable conditions, i wouldn't even be surprised 😊
definitely low priority.
will update as soon as i can reproduce. thanks!

**Comment by mattrose** [comment]
You should be  able to install latest master by just cloning the repo and following the instructions in `INSTALL.md`.  The gnome-terminator snap is entirely unsupported.  I've tried getting in touch with the author and I haven't heard back
