### ISSUE TITLE
new feature: support for term://1.2.3.4/ 'links' that when clicked open a new terminator ssh'ed to 1.2.3.4.

### ISSUE THREAD

**Issue by gigablast** [gnome-terminator/terminator#178]
similar to how terminator hot links http://www.foo.com/ to a browser. this would open up another terminator when clicked.
i'd find this super useful as i'm sure other cmd line junkies would.

**Comment by mattrose** [comment]
This would be really easy to add to the URL Handler plugin: https://github.com/gnome-terminator/terminator/blob/master/terminatorlib/plugins/url_handlers.py  It's got pretty much everything there.

**Comment by mattrose** [comment]
@gigablast I'll do this if you agree with `ssh://1.2.3.4` as described in https://tools.ietf.org/id/draft-salowey-secsh-uri-00.html

**Comment by gigablast** [comment]
that's quite agreeable! :+1:

**Comment by mattrose** [comment]
Wow, this is actually stupidly hard.  I think it should be done, but we can't just piggyback off of `xdg-open` like we would for everything else.
