### ISSUE TITLE
Add vertical spacing between lines

### ISSUE THREAD

**Issue by behnamarbab** [gnome-terminator/terminator#179]
I am trying to use emojis within the text, but I see that the emojis positioned vertically against each other, overlap and it doesn't look good.
To be more specific, I want these two emojis:
```
💻
👎
```
When the above emojis are inserted in consecutive lines, one below the other one, they overlap.
If I can increment the vertical line spacing, my problem would be solved. (Or if the size of the emojis I use are changed, I guess it's on the emoji's vendor side)

**Comment by mattrose** [comment]
I *think* this is a vte bug.  I will poke a bit.

**Comment by mattrose** [comment]
Hmm, seems to work for me:
![Screenshot from 2020-08-18 10-16-34](https://user-images.githubusercontent.com/65013/90524538-31528380-e13c-11ea-9ff0-853dc22c2cca.png)

Few questions:  
 * Is it those specific emojis that are causing the problem?  
 * If it is, can you specify some Unicode codepoints?
 * What version of the VTE lib are you using?
 * What font are you using?

**Comment by mattrose** [comment]
Closing.  Please reopen if you have further problems.
