### ISSUE TITLE
In Uubuntu 20.04 Ctrl + Mosue Scroll Down is NOT zooming out - But with Ctrl + Mouse Scroll Up I can Zoom in

### ISSUE THREAD

**Issue by rohan-paul** [gnome-terminator/terminator#180]
In Uubuntu 20.04 Ctrl+ Mosue Scroll Down is NOT zooming out - But Ctrl + Mouse Scroll Up makes it Zoom in

**Comment by mattrose** [comment]
Umm, I just tried this on ubuntu 20.04 and it works. Can you provide any more information?

**Comment by mattrose** [comment]
closing.  please reopen if you have further problems
