### ISSUE TITLE
Feature request: reenable broadcast keybindings and warn on their first use instead

### ISSUE THREAD

**Issue by JakubVanek** [gnome-terminator/terminator#183]
The intent behind this is to revert https://github.com/gnome-terminator/terminator/pull/41 and use a better mechanism for protecting new users. As per feedback on Gitter, the previous keybindings are still actively used by advanced users. The other proposed solution (showing a warning each time until closed with `do not warn again`) would work for both groups.

**Comment by ohir** [comment]
@JakubVanek 
No it will NOT work for both groups. It would benefit only those users who are happy to ask   developers to make additional code and logic just because someone claiming "advanced" is too lazy to configure a really advanced feature.

This feature (broadcast) while useful for one's who need it is way too dangerous for most casual users. 

I counter with proposal to enable broadcasting not only in keybindings, but also by edit in config file adding a line with 
```
BroadcastEnabled = "I fully and thoroughly understand consequences of broadcasting commands"
```
so only users advanced enough to take a time to **read the docs** may use it.

**Comment by JakubVanek** [comment]
To be fair to the user in question, they did not claim that they are "advanced" or whatnot. I just thought that they felt not happy about us hiding a potentially useful feature and this was my conclusion from it.

I would go for a compromise - the dialog box would be similar to what GitHub shows when deleting a repository.
```
+----------------------------------------------------------+---+---+---+
|                         Terminator warning               | _ | O | X |
+----------------------------------------------------------+---+---+---+
| You have just pressed the keyboard shortcut for 'Broadcast Group'.   |
| This mode can be very dangerous if triggered at a wrong time.        |
| Please review the [terminator documentation](url) before proceeding. |
|                                                                      |
| To enable 'Broadcast Group', please type the following sentence in:  |
|                 "I know what I am doing, I promise"                  |
|                                                                      |
|      [______________________________________________________]        |
|   [ ] do not warn again   [ ] do not require me to write this again  |
|                                                                      |
|              [   cancel   ]           [   (enable)   ]               |
+----------------------------------------------------------------------+
```

A different solution altogether would be to reintroduce the keybindings, but this time requiring a "unlock prefix" keyboard shortcut to be pressed each time before they will activate. This would be similar to how tmux or emacs typically work. However, we would need to pick the right default key combo to not clash with anything and to prevent accidental unlocks.

**Comment by ohir** [comment]
Broadcasts and grouping are available at the titlebar menu. So how an user that have not discovered yet "broadcast off/group/all" there is supposed to decide whether she wants to have a shortcut for it?

>  they did not claim that they are "advanced" or whatnot.

So they certainly are not of group that might demand footcannon's fire button having a default keyboard shortcut.

> about us hiding a still potentially useful feature

Nothing is hidden in terminator code nor in the user interface. Had this user was even briefly accustomed to linux, or any other OS, she would took a tour through "preferences", and menus of a new to her application. Then she would see "broadcast" and would have took a peek into the docs what this "broadcast" does.

As I said - this FR is requesting additional code and logic that afflicts experience of almost all users for the benefit of tiny — if not hypothetical — cohort that believe reading docs is a crime against humanity.
Close it, please.

**Comment by mattrose** [comment]
And, I'm not sure that this is what the user in gitter was complaining about.  I am wary of adding a lot of complexity for this.  We already have a bunch of functions that don't have a default keybinding, and this *is* a particularly dangerous one.

I posted a message to the user in gitter to see if this is indeed a problem for them.  I'm leaning on agreeing with @ohir tho.  It's a fair bit of complexity for an issue that may be entirely hypothetical.

A little bit off-topic for this, but there are many reasons to want a feature or opening an issue.  Opening a github issue should not open you up for insinuations of inexperience or laziness.  Let's all be kind and assume that everyone is intelligent and resourceful, until proven otherwise.

**Comment by JakubVanek** [comment]
> Broadcasts and grouping are available at the titlebar menu.

This does sway my opinion too towards agreeing that this feature would not have much benefit.

**Comment by mattrose** [comment]
Yeah, I'm gonna close this.  I appreciate the thought, but it's a lot of complication for what is, at this time, only a hypothetical problem.  I think your original change should just stand as is.

**Comment by ohir** [comment]
@mattrose 
> Opening a github issue should not open you up for insinuations of inexperience or laziness.

Opening? — no. Whatever feature may come to someone's mind, it has a value. Here we have:
 1) a call to make dangerous existing feature under an obscure to most users, yet default keybinding
 2) an innuendo that terminator devs "hide" something from users

This together **is the proof** of laziness: some gitter user neither read the docs nor took the menu tour (to know "broadcast off/group/all" items and "keybinding" tab in preferences dialog where "broadcast" sits at top) yet she calls devs to make a default keybinding for her. If this is not laziness, what is?

> Let's all be kind and assume that everyone is intelligent and resourceful, until proven otherwise.

I always do assume everyone acts at his or her best, I always assume we all constantly learn, I know that errare humanum est. But I call facts and attitudes by their names.

PS. I am aware that CPCD mandates an not offending __*vital energy saving (person)*__ term instead, but I personally feel offended by the very existence of such euphemisms.

**Comment by JakubVanek** [comment]
I'd like to apologize for this, at least half of this is my fault. Moreover, as @mattrose says, I have likely misunderstood the original comment on Gitter.
