### ISSUE TITLE
Cannot open terminator windows with different configs

### ISSUE THREAD

**Issue by tuukkaanttila** [gnome-terminator/terminator#184]
Opening a terminator window prevents opening another terminator window with a different config using the command line argument --config. It just opens the new window with the same config as the previously opened window uses.

[terminal1] $ terminator
--> terminator opens with default config

[terminal2] $ terminator --config="some_other_config"
--> terminator window opens, still with default config

**Comment by mattrose** [comment]
Took me a second, but you're right.  the `terminator` command will look for a running dbus instance and attach to that, config and all, if you don't tell it not to.  The way to configure 2 different terminals with different configs, you should use profiles.  If there's some configuration that you need to have different that is not supported in profiles, and you have to run with two different configs, you can run `terminator -u -d --config="/tmp/foo"`

**Comment by g3grau** [comment]
I should have seen this many hours ago! I've been getting crazy not being able to spawn multiple windows with multiple environment vars ... Adding -u solved it, thanks!
