### ISSUE TITLE
Htop desktop entry doesn't open in terminator but it works when the command is directly typed

### ISSUE THREAD

**Issue by KavetiRohith** [gnome-terminator/terminator#188]
tested on gnome 3.36 with arch linux

**Comment by mattrose** [comment]
I'm gonna need a lot more details than that.  I am running GNOME 3.36, but not Arch.  What is htop?  What is the htop desktop entry?  Why should it open in terminator?

**Comment by mattrose** [comment]
This is https://gitlab.gnome.org/GNOME/glib/-/issues/338

Go yell at the glib developers.
