### ISSUE TITLE
Selecting first char of a line for copy-paste is impossible

### ISSUE THREAD

**Issue by jwrdegoede** [gnome-terminator/terminator#191]
This is with the Fedora 33 package of terminator: terminator-1.92-5.fc33.noarch

I just tried to copy and paste a bit of text starting in column one from the right terminal of a vertically split terminal, but this is impossible, instead of being able to select the first char I would always get the "resize" cursor for dragging the split between the 2 terminals left/right.

I worked around this be starting the selection at the end of the bit of text which I wanted, still it would be nice if this could be made a bit easier somehow.

**Comment by jwrdegoede** [comment]
I'm trying to switch to terminator as my default terminal emulator and I must say this is quite annoying. I also just noticed that this leads to me accidentally dragging the divider left/right all the time instead of keeping the default 50/50 split.

For me a good fix for this would be to allow disabling dragging on the divider all-together, that would fix both accidentally dragging it and not being able to select text starting in the first column.

**Comment by mattrose** [comment]
Thanks for opening this.  It has bugged me for a while now, and I finally found a fix, thanks to the tilix project. https://github.com/gnunn1/tilix/issues/1838 led me to the weirdly named, wide_handle.  Setting this property on the VPaned Class in `terminatorlib/paned.py` fixes it.

I'll do a PR soon.

**Comment by jwrdegoede** [comment]
I've added the patch to my local terminator version and I can confirm that this fixes this issue, thank you.

**Comment by mattrose** [comment]
Thank you.  I noticed that you added a patch for the fedora rpm.  I'm also a maintainer with @dmaphy

**Comment by jwrdegoede** [comment]
Yes, since the fix works great I asked @dmaphy if he was ok with me adding it to the Fedora pkgs, I did not realize that you were co-maintaining otherwise I would have added you to the Cc.

**Comment by Fonant** [comment]
Thanks for the fix! That was something that has annoyed me, on-and-off, for some time. :+1:

**Comment by mikedlr** [comment]
If stuck on an old version of terminator on an old ("stable") OS version, the workaround is to start selecting at the other end of your selection and go up the way until you reach the start of the line. Thanks all for the great work.
