### ISSUE TITLE
RFE: show 80 char limit

### ISSUE THREAD

**Issue by jwrdegoede** [gnome-terminator/terminator#192]
I use a terminal based editor and many projects have a 80 char line length limit in their coding style.

It would be nice if terminator could show a small vertical line indicating the 80 char (or preferably configurable) limit similar to how some graphical code editors can do this.

**Comment by mattrose** [comment]
Would be nice.  I'll be honest and say that even if there was a way to do this in VTE, I'm not sure I'm up to it.  The way I always deal with this is to set the size of the terminal window to the number of columns allowed.  You can easily see the number of rows and columns in the titlebar.

**Comment by jwrdegoede** [comment]
I use terminator as a tiling WM for just terminals, so I always have it maximized.

With my current hidpi scaling factor + fontsize combo I get 3 83-chars wide terminals horizontally, I guess I could make it 80 + 80 + 89 chars instead.

And I see your point about this needing to be added to VTE first. Shall I file a RFE against upstream VTE ?

**Comment by mattrose** [comment]
That would be great.

**Comment by jwrdegoede** [comment]
Done: https://gitlab.gnome.org/GNOME/vte/-/issues/275

**Comment by mattrose** [comment]
you mind if I close this until it gets implemented by VTE?

**Comment by jwrdegoede** [comment]
Closing this till it gets implemented by VTE is fine with me.

**Comment by mattrose** [comment]
I put a watch on the VTE issue and I'll look at it once that VTE issue gets addressed
