### ISSUE TITLE
Ensure Python 3 support

### ISSUE THREAD

**Issue by lazyfrosch** [gnome-terminator/terminator#2]
Current master doesn't work with Python 3...

We need to merge several community patches:
- [Debian](https://salsa.debian.org/python-team/applications/terminator/-/tree/debian/master/debian%2Fpatches)
  + [#953153](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=953153)
  + [#955383](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=955383)
- Fedora

See PR #6 for details

**Comment by ngosang** [comment]
In ArchLinux we have at least 2 forks with Python3 support working. Maybe they are useful in some manner. 

1. https://aur.archlinux.org/packages/terminator-git/
Source code => https://github.com/JAugusto42/terminator

2. https://aur.archlinux.org/packages/terminator-python3-bzr/
Source code => https://code.launchpad.net/~hellodeargrandma/terminator/python3

@JAugusto42 ping

**Comment by lazyfrosch** [comment]
We will start opening a PR with the changes from Debian and Fedora soon. Would be great when more people review the changes, in case we missed something.

**Comment by ohir** [comment]
At https://github.com/ohir/terminator is my (1.91 based) enhanced version.

Unfortunately debian/arch patches are just rewrites of the old code - with many architectural issues, 
so I published my code as-is (I use it daily). _The stopper (for porting to v3) for me was the config, with borg leaking over crust gathered from many contributors in the past. I started to write new config, but reality called in meantime. So I just use 1.92 with python2._

I will watch here, but I can not commit to work till my current contract ends.
Nonetheless - the config code need to be redone before or along porting to v3.

**Comment by JAugusto42** [comment]
Hello, thanks for the mention, so I have no interest in keeping any version of the terminator, I just did it to get python2 out of my machine, one of the arch developers and maintainer of the terminator in the arch said that he will kill the terminator that depends on python2, I just anticipated it. As soon as a usable version comes up or the terminator maintainer in the arch decides which repo to use, I will kill my project.

cheers

**Comment by lazyfrosch** [comment]
@JAugusto42 thanks for your input :wink:

**Comment by JAugusto42** [comment]
@lazyfrosch 
You're welcome, I already spoke with the package maintainer on the arch and he will look at your repository, me at night (night here in Brazil), I will drop my repository and start contributing to yours, better centralize everything in a repository.

**Comment by ngosang** [comment]
Since 2020-04-22 ArchLinux is using this package with Python3 in the official repositories.
https://www.archlinux.org/packages/community/any/terminator/
:clap:
