### ISSUE TITLE
Tab Char is Truncated when Copying

### ISSUE THREAD

**Issue by JavaScriptDude** [gnome-terminator/terminator#201]
I have just ran into an issue where I was pulling tab delimited data from a tail output in Terminator to pasted into a spreadsheeet and  I noticed that field who's tab delineator was at wrapping point in then console was truncated when I copied the text  by selecting and hitting ctrl-shift-C. 

It appears that when Terminux writes to the screen it truncates extra tabs that begin/end at a line.

I switched to using pipe delineator to get around this.

Is this normal behavior and is there a way to tweak around it?

**Comment by mattrose** [comment]
Can you attach a text file that I can use to attempt to reproduce the problem?

**Comment by JavaScriptDude** [comment]
In the attached zip you will find test.tsv.

- To  verify, open a terminator window and run `% cat test.tsv`
- Resize the window so that the edge of the window hits the end of a field delimiter (tab) and re-run `cat` as need to get positioning right.
- Copy the text on the screen and paste it into a spreadsheet or programmers editor and you will see that some tabs are removed.

[test.zip](https://github.com/gnome-terminator/terminator/files/5314626/test.zip)

**Comment by mattrose** [comment]
Thank you, sorry for leaving this so long, I was in the middle of fixing two other big hairy bugs.   This should help a lot.

**Comment by JavaScriptDude** [comment]
No worries. This definitely is an edge case. I was able to get around the issue by making a proper data extraction API for an ancient roach motel of a database I am working with so I don't have the need to scrape TSV data from tail outputs any more. The pain I went through writing my new extraction API has paid back 100 fold for me so I'm glad I had the issue ;^)

**Comment by mattrose** [comment]
Hmm, not seeing this on Fedora32 with vte291-0.60.3 (wihich, tbh, is probably where the problem lies.  Can you see if latest release fixes this?

**Comment by JavaScriptDude** [comment]
Ok. I'll spin up a Fedora VM and put in lastest to confirm on my end. The version I have going on my Ubuntu is:
% terminator --version
terminator 1.1.9

**Comment by JavaScriptDude** [comment]
I tried on a Fedora VM with Terminator 1.92 and I still see the issue there.

My steps to reproduce:

1. Open Terminator
2. cat tsv sample file
3. Resize Terminator window so that edge of window is at the edge of a column before a tab char (not end of row)
4. Re-run cat of tsv file
5. Copy the range on the screen and paste to a text editor

Result that I see: Tabs that fall at edge of screen are excluded from pasted data

Is there a more recent version of Terminator I can try on my end?

**Comment by mattrose** [comment]
version 2.0.1, you can do `sudo dnf upgrade --enablerepo=updates-testing --advisory=FEDORA-2020-f225727bb7` on Fedora 32 and that should install it.

**Comment by mattrose** [comment]
if it's out of testing you should just be able to do `sudo dnf upgrade terminator`

**Comment by JavaScriptDude** [comment]
Sorry for delay. Had my head in the codes.  I'll take a look at this right now.

**Comment by JavaScriptDude** [comment]
I was able to get 2.01 installed using git. Verified same issue on Fedora with 2.01. Also tested 2.01 on Ubuntu and got the same result.

**Comment by JavaScriptDude** [comment]
Just as a note, I realized that this behavior of truncating tabs that hit the edge of the window is a normal behavior across with Gnome Terminal, Mate Terminal, Konsole and even Window cmd.exe.

As this behavior is the status quo, I think we should seriously consider closing this ticket out as it cannot be considered a bug.

Sorry I did do this baseline check this before :(

**Comment by mattrose** [comment]
All right, thanks for looking into this further.
