### ISSUE TITLE
Gap between windows

### ISSUE THREAD

**Issue by CsatiZoltan** [gnome-terminator/terminator#203]
### Problem
When I resize the windows, either horizontally or vertically, I can see the background. This is due to the fact that there is a few pixel width gap. This is annoying when the background is not homogeneous.

### Version information:
OS: Ubuntu 18.04 LTS
Terminator: [1.91-1](https://launchpad.net/ubuntu/bionic/+source/terminator)

### Demonstration:
![Gap](https://user-images.githubusercontent.com/12742890/91954869-b1631680-ed02-11ea-95ed-c12c8fd96180.gif)

**Comment by mattrose** [comment]
This is fixed in the latest master according to my testing

**Comment by milivoye** [comment]
I'm on 2.1.1 and a wide transparent gap is still there. 
Is there a setting for the gap width, and what would it be?
