### ISSUE TITLE
Terminator overwrite shortcut of console Applications

### ISSUE THREAD

**Issue by Bollos00** [gnome-terminator/terminator#204]
I do not know if it is worthy enough for creating a new issue, sorry if it is not.

I have been using terminator for something like five months now and I love every bit of it. Recently I face myself on a situation when I was running a console applications (vim in that case) on terminator, when I tried to press the help button (`F11`), it redirected me for the [terminator documentation](https://terminator-gtk3.readthedocs.io/en/latest/), instead of showing the help of vim. 

I solved it simply by switching the shortcut of terminator help from `F11 to` `Shift+F11`, but I am not sure if that was supposed to happened. Is there a way to avoid that the shortcuts of terminator conflicts with the shortcuts of other applications?

Thanks in advance.

**Comment by mattrose** [comment]
Not really.  Terminator grabs the keystroke and handles it before any program run from the shell does (It kinda has to, to do it's job)
