### ISSUE TITLE
key sequence to popup context menu ?

### ISSUE THREAD

**Issue by mckellyln** [gnome-terminator/terminator#21]
Hi,
========== Not a problem, just a ques/request ===========
Is there a key sequence (Win+Alt+p etc.) to pop up the context menu ?
I would like to not have it pop on mouse click but only on key sequence.
If not, I can modifiy terminal.py but it would be great if this were configurable.
thx,
-m

**Comment by lazyfrosch** [comment]
Hey there,
actually the context shortcut works for me here.

Not sure how other GTK apps handle this.

**Comment by mckellyln** [comment]
ok, I didn't know, thanks.  I will search how to set this ....

**Comment by lazyfrosch** [comment]
I meant the normal context key on most keyboards: 
![image](https://user-images.githubusercontent.com/121874/79602809-7bbee780-80eb-11ea-87ce-8a8f3a01d658.png)

Alternatively Shift+F10 works, but I can't find any documentation.

I'll assume this should work for you :wink:

**Comment by mckellyln** [comment]
Shift+F10 works great.  I wanted to stop the mouse click for it since I use that for other things.

**Comment by mckellyln** [comment]
So I just wondered if there was a config setting to disable the popup on mouse click ?

**Comment by mckellyln** [comment]
Thanks again so much for carrying on with Terminator!

**Comment by lazyfrosch** [comment]
Since it's the only real menu access in Terminator right now it wouldn't be a good idea to disable it

**Comment by mckellyln** [comment]
ok, I dont mean disable it from all methods - just from a mouse click.
I can edit the the terminal.py in my world :-)
