### ISSUE TITLE
Question - custom command line

### ISSUE THREAD

**Issue by yuriw** [gnome-terminator/terminator#212]
Can someone share an example how to execute a command like below for a profile on start.

`ssh xyz` (and then in the term) `podman exec -it WIP6 /bin/bash` ++

Thx

**Comment by mattrose** [comment]
`ssh xyz -e 'podman exec -it WIP6 /bin/bash'` I think.  I haven't tested that out tho.

**Comment by yuriw** [comment]
@mattrose that does not work :(

**Comment by mattrose** [comment]
the flag for ssh is `-x` not `-e`.  As I said, hadn't tested it :)

**Comment by mattrose** [comment]
I think `ssh xyz -x 'podman exec -it WIP6 /bin/bash' should work, but I don't have podman or docker installed to double-check

**Comment by yuriw** [comment]
odd still no love for me with 'ls -al'

This is my setup:

![image](https://user-images.githubusercontent.com/3876474/93671713-3156e380-fa5a-11ea-8666-0758753dbc81.png)

Like yours?

**Comment by mattrose** [comment]
I think what's going on is that you're exiting the terminal as soon as `ls -al` is done, so it runs the command and immediately exits.  I think I figured it out tho.
I think `ssh -t xyz -x 'podman exec -it WIP6 /bin/bash'` should work.  The -t flag ensures you have a pty, IIRC.  

I do feel obligated to say, this really has nothing to do with terminator and is more of an SSH question...

**Comment by yuriw** [comment]
@mattrose thanks a million for your help!
It does work !

Even thou it's indirectly related to the terminator I am sure it will help lots of its users :)

**Comment by mattrose** [comment]
yr welcome, glad to help!
