### ISSUE TITLE
Feature request: Preference to disable Ctrl + Scroll font size change

### ISSUE THREAD

**Issue by tanc** [gnome-terminator/terminator#219]
Originally posted here: https://bugs.launchpad.net/terminator/+bug/1505292

This feature request is to add a preference to control the behaviour of Ctrl + Mouse (or trackpad) scroll

**Current behaviour**

Ctrl + Scroll increases or decreases font size in Terminator.

**Desired behaviour**

That this feature is behind a preference so it can be disabled. It would be enabled by default in a new installation or upgrade so that behaviour is not changed for current users.

**Rationale**

The problem for many of us is that we use Ctrl for various tasks and if accidentally leaving the control key depressed when switching to terminator and scrolling the mouse the text zooms in or out. This happens to me all the time when I Ctrl + Tab from Terminator to a different window and accidentally scroll at the same time. My touch scroll mouse is very sensitive to movement.

Others [have said](https://bugs.launchpad.net/terminator/+bug/1505292):

> Super annoying for us with trackpads (Accidental ctrl+zoom) or inertia scrolling enabled then fast switching to Terminator.

> An option to completely disable zooming would be nice!

> touchpad inertia issue happens to me several times a day. This is why I would love to see the scroll to zoom to be configurable.

**Comment by gricertg** [comment]
I think this is already fixed with PR https://github.com/gnome-terminator/terminator/pull/46

**Comment by mattrose** [comment]
Can you check out master and close this if this is the case?  I'm planning on releasing this as 2.0 next week.

**Comment by tanc** [comment]
Cloned master branch of the repo and opened `./terminator`. Noted in preferences the new option to disable scrollwheel. Ticked the box and tested Ctrl + Scroll and confirm there is no zoom. THANK YOU!!!

**Comment by gricertg** [comment]
@tanc now you were faster than me ;) 
Just got home and wanted to test it. However i tested it too because i wanted to try a build with manjaro. Works fine!
