### ISSUE TITLE
Create a new release? (and maybe add easier-to-install workflow?)

### ISSUE THREAD

**Issue by awesomebytes** [gnome-terminator/terminator#221]
Hello, I've been using terminator for... as long as I can remember. It's a great tool! First, let me thank you for the effort on keeping this package alive and updated, it is very appreciated.

In this issue I would like to open a conversation about the release model/life cycle/methodology for this great package.

On one hand I would like to request a new release to ease installation as I would very much like to have a few fixes included [1]. I could install from master or tag myself to a commit, but I think it would be nice to have a release with that issue fixed. There are more fixes that I found to work correctly that I'd love to have easily accessible [2].

Currently I cloned the repository and did `pip install --user .` [3] (added --user as I am currently still testing nothing crashes in my usual workflow). This is a bit cumbersome to ask my colleagues to do in order to have the latest version (we are using Ubuntu 18.04 and were installing terminator from apt up until now).
_Edit: I just found out one can do `pip install git+git://github.com/gnome-terminator/terminator.git@a84bed91cfee2fe1e2e4d34e82a465d480ffcaf5` and that works, that's a bit easier!_

Furthermore, and I'd offer myself to help (even though I'm not an expert) maybe uploading terminator to `pip` could help distribute it easier and faster? A [GitHub actions for releases](https://packaging.python.org/guides/publishing-package-distribution-releases-using-github-actions-ci-cd-workflows/) could make this endeavor friendly I believe?

[1] The fix for the search and highlight: https://github.com/gnome-terminator/terminator/issues/4
[2] Opening a config file + layout from command line options works. This did not work in the past (and I'm so happy to see it work!). I.e. `terminator -g MY_CONFIG -l MY_LAYOUT_IN_THAT_CONFIG` correctly opens the layout.
[3] Note that I used python2.7 on that and it seems to work fine, I read in [this comment](https://github.com/gnome-terminator/terminator/issues/1#issuecomment-614753748) that it is not supposed to work, but my experience differs. I wouldn't mind running/installing it in Python3 but our current setup is forced to use Python2.7 for a while.

**Comment by mattrose** [comment]
I definitely agree that we need a new release.  I was planning on having one out at the beginning of this month, but life got in the way and there was always one more bug to fix.  I've discussed it with my co-maintainer and there's a few things we want to work on but we should be ready to release by the end of this week.

For note 3, we've come up with an ad-hoc policy of having terminator be compatible with Python 2.7 as long as we can.   There are a lot of people in a situation where they can't currently upgrade, and we'd like to support them as long as it's feasible.

Any help you could give would be great!

**Comment by clwluvw** [comment]
@mattrose Terminator on ubuntu 20 has lots of bugs, won't you release the new updates on ubuntu ppa?

**Comment by mattrose** [comment]
Unfortunately I don't have any control over the existing ubuntu PPA.  I'll see what I can do about setting up a ppa on my ubuntu account.

**Comment by awesomebytes** [comment]
That's great news! Thanks a lot for the update!

**Comment by mattrose** [comment]
New Release is done.  pypi.org already has a "terminator" project already, but it only has one release from 2016, so I sent an email to the author asking him if.he was still using it.  I think PPA is next

**Comment by freud14** [comment]
Hi @mattrose, I think you should contact the maintainer of the Debian and Ubuntu packages. Here is the links to the respective packages:
* https://packages.debian.org/sid/terminator
* https://packages.ubuntu.com/focal/terminator

**Comment by mattrose** [comment]
@lazyfrosch is one of the debian maintainers and the founder and original impetus behind this fork.  The ubuntu project just picks up his work.  He's busy right now, I know he'll package up 2.0.1 as soon as he gets the chance.

In the meantime I've set up a PPA for 20.04 and 20.10 at https://launchpad.net/~mattrose/+archive/ubuntu/terminator 

you should be able to do 
```
sudo add-apt-repository ppa:mattrose/terminator
sudo apt-get update
```
