### ISSUE TITLE
clusterssh like behaviour via plugin

### ISSUE THREAD

**Issue by gricertg** [gnome-terminator/terminator#222]
I use terminator a lot. 
In some cases i have a list of servers which i pipe to `xargs cssh`. I would love a similar behaviour with `terminator` with multiple panes. 

Before i found this repo i thought about writing a python wrapper which pastes a layout in the configuration file but i think this is not the correct attempt. I can imagine developing a plugin for this functionality which generates a layout and uses it. 
But as far as know plugins support only interactions with the UI, correct? 

A simple solution would be something like `terminator --cssh <server1> <server2> <server3>`, this way lists could be piped to `xargs` to pass it to termiantor. But plugins can't provide new arguments, correct? 

Maybe there are different attempts which I don't see yet. I would be happy to help with this!

**Comment by mattrose** [comment]
One thing that you might be able to use, or maybe just give you some ideas is #213.  The author is working on generating layouts from JSON files.  As a former sysadmin I can definitely see the appeal.  I'm not sure the plugin architecture is up to it, but it can also be extended, if we can come up with a good way.

**Comment by mattrose** [comment]
I'm gonna close this, I think you can do something with generating layouts on the command line and calling them from terminator now.
