### ISSUE TITLE
Some files install to the wrong location

### ISSUE THREAD

**Issue by logix2** [gnome-terminator/terminator#227]
Using the Terminator 2.0 source: On my Ubuntu 20.10 desktop, some files, like the icons, .desktop file, etc. are installed to the wrong location when using `python3 setup.py install`. Example:
```
/usr/local/lib/python3.8/dist-packages/terminator-2.0-py3.8.egg/share/applications/terminator.desktop
/usr/local/lib/python3.8/dist-packages/terminator-2.0-py3.8.egg/share/icons/HighContrast/16x16/actions/terminator_active_broadcast_all.png
...etc.
```

I also tried to install it using `--prefix=/usr`, but then the application doesn't even start.

**Comment by kamermans** [comment]
I had this problem too.  For now you can copy the icons and stuff to `/usr/share` to get Terminator into the applications folder with its icons, etc:

```
sudo cp -R /usr/local/lib/python3.8/dist-packages/terminator-2.0-py3.8.egg/share/* /usr/share/
```
