### ISSUE TITLE
Feature Request: Split window shell based on parent

### ISSUE THREAD

**Issue by ChaoticEvilDM** [gnome-terminator/terminator#229]
I am currently using zsh alongside bash, since I prefer to handle certain tasks in each. Terminator invokes a new shell, based on the users default shell when splitting a window, rather than the shell originally used in the parent window. It would be a great improvement to have the shell based on the parent - as an option e.G.

**Comment by mattrose** [comment]
Figured out how to do this.
Create a profile for each shell you want, and check the `Re-use profiles for new terminals` 

Then you can start a new session with the shell that you're using, and it will always use that shell when splitting or creating a new window.

It's not exactly what you want, but I think it works better for all use cases.
