### ISSUE TITLE
Ubuntu 20 "open in terminal" not replaced by terminator.

### ISSUE THREAD

**Issue by moshenskyDV** [gnome-terminator/terminator#236]
As I get correctly, after installing terminator it replaces all calls of default terminal (Ctrl + Alt + T) for example starts to call terminator instead of terminal.

But there is one scenario when default terminal still opens:
1) open "files" (nautilus if I remember correctly - default file viewer).
2) go to any directory and press right mouse button
3) choose "open in terminal"

Is default terminal expected by this case?
Not really an issue but enchantment. Thanks.

**Comment by mattrose** [comment]
Hmm, I'll have to look at my ubuntu VM and see what's going on there.  I **do** know that Ubuntu has some very specific, and kinda weird patches to GTK that enables the "Open in Terminal" and Ctrl-Alt-T behaviour.

**Comment by mattrose** [comment]
I'm going to have to ask you to open a bug for the ubuntu Files app.  There's nothing I can do about that.

**Comment by timhughes** [comment]
https://github.com/timhughes/nautilus-open-terminator
