### ISSUE TITLE
No tests in tarball

### ISSUE THREAD

**Issue by DarthGandalf** [gnome-terminator/terminator#238]
Hi, tests are missing in the signed release at https://github.com/gnome-terminator/terminator/releases/download/v2.0.1/terminator-2.0.1.tar.gz

They do exist in https://github.com/gnome-terminator/terminator/tree/v2.0.1/tests

**Comment by mattrose** [comment]
Hmm, I'll see if I can fix that for the next release if that's ok with you.

**Comment by DarthGandalf** [comment]
Yeah, for now I'll just have to package for Gentoo from the archive generated by Github instead.

**Comment by mattrose** [comment]
You actually run the tests as part of the install procedure?  Commendable.  Hopefully now that I've got release procedures down, I'll be able to release more often.  I'm hoping for a release every 3 months.

**Comment by DarthGandalf** [comment]
> You actually run the tests as part of the install procedure?

This is an opt-in feature. User can enable tests to run when building/installing the package. And it runs on end user's machine, with user's CXXFLAGS, etc.

As packagers, we support tests in packages where upstream have them.
