### ISSUE TITLE
"s" character always stays in command line

### ISSUE THREAD

**Issue by kimllee** [gnome-terminator/terminator#239]
Hello,

I'm using Ubuntu 20.04LTS, I uninstalled Terminator 1.92 through APT built  and install terminator 2.01 from the sources using python 3.8 but I still have the "s" character displayed in the terminal.

**Comment by mattrose** [comment]
Can you attach a screenshot?  It's not exactly clear from your description where the `s` is appearing.

**Comment by kimllee** [comment]
The issue is related to my VM not from Terminator 2.0.1. I close the issue.
Thank you.
