### ISSUE TITLE
Middle click does not paste selected text

### ISSUE THREAD

**Issue by fonzinc** [gnome-terminator/terminator#24]
Setup: CentOS 8 / Gnome (Wayland)

Steps to reproduce:

1. Open a gnome terminal and highlight some text with the mouse.
2. Middle click within the gnome terminal and observe that the highlighted text is pasted.
3. Middle click within a terminator window and observe that the pasted contents are from a different clipboard (not the highlighted text).

**Comment by JAugusto42** [comment]
yep! confirmed!

**Comment by JAugusto42** [comment]
I couldn't reproduce, which version of the terminator are you using?

**Comment by lazyfrosch** [comment]
Same for me, can you share your config file? `$HOME/.config/terminator/config`

**Comment by fonzinc** [comment]
Sure.

I've reproduced this behavior on multiple CentOS 8 machines using terminator-1.91-15.el8.noarch.
I also reproduced it using 1.92.

I'm suspicious that this issue is specific to Gnome or Wayland because I never saw this issue on CentOS 7 using KDE/X11.

**Config:**
[global_config]
[keybindings]
  split_vert = <Primary><Shift>e
[profiles]
  [[default]]
    background_darkness = 0.83
    background_type = transparent
    cursor_color = "#aaaaaa"
    scrollbar_position = hidden
    scrollback_lines = 50000
[layouts]
  [[default]]
    [[[window0]]]
      type = Window
      parent = ""
    [[[child1]]]
      type = Terminal
      parent = window0
[plugins]

**Comment by alcir** [comment]
I can confirm this behaviour on Fedora 31. GNOME on Wayland.
`terminator-1.92-1.fc31.noarch`

**Comment by fonzinc** [comment]
A few more data points from Fedora 31:

Terminator v1.92:
- Gnome/Wayland - BROKEN
- Gnome/X11 - WORKS
- KDE/Wayland - BROKEN
- KDE/X11 - WORKS
- Weston/Wayland - BROKEN

Terminator v1.91.10.fc31:
- Gnome/Wayland - WORKS
- KDE/Wayland - WORKS
- Weston/Wayland - WORKS

**Comment by fonzinc** [comment]
Disabling the special logic to switch the clipboards on Wayland gives me the expected behavior on CentOS 8 Gnome/Wayland.

    --- terminatorlib/terminal.py.orig  2020-04-24 22:48:07.447809430 -0600
    +++ terminatorlib/terminal.py       2020-04-24 22:48:24.943312461 -0600
    @@ -929,12 +929,11 @@
                 # Suppress double-click behavior
                 return True
   
    -        use_primary = (display_manager() != 'WAYLAND')
             if self.config['putty_paste_style']:
                 middle_click = [self.popup_menu, (widget, event)]
    -            right_click = [self.paste_clipboard, (use_primary, )]
    +            right_click = [self.paste_clipboard, (True, )]
             else:
    -            middle_click = [self.paste_clipboard, (use_primary, )]
    +            middle_click = [self.paste_clipboard, (True, )]
                 right_click = [self.popup_menu, (widget, event)]
   
             if event.button == self.MOUSEBUTTON_LEFT:

**Comment by KrzP** [comment]
I experience the same problem for terminator 1.92 on Gnome 3.36.1/Wayland 1.18.0
@fonzinc thanks for a patch

**Comment by lazyfrosch** [comment]
Interesting problem, thanks for the patch, I will try it out.

**Comment by jehutyy** [comment]
Same problem here on archlinux with terminator 1.91 gnome/wayland. I'm giving a try to the patch.

**Comment by alcir** [comment]
While middle click works on Fedora 31 with terminator-1.92
The same issue is still present on Fedora 32

**Comment by lazyfrosch** [comment]
@alcir The fix is not released yet, please check the milestone and compare to your local version.

**Comment by jjrsylvestre** [comment]
Would you consider making a minor release to push this fix out to distributions? The bug is pretty annoying when you are used to the muscle memory of quickly selecting-then-middle-clicking, but forget about the bug,  then something completely unexpected gets pasted into your terminal...

**Comment by robertoetcheverryr** [comment]
@jjrsylvestre I have an issue with pasting as well and, since this is Python, I modified my own code to suit my needs while the issue is debated and a fix proposed. Unless you are running Terminator on multiple installations, changing 3 lines might be a good solution.

**Comment by jjrsylvestre** [comment]
@robertoetcheverryr Hey thanks! I didn't think of checking the fix commit, you're right it was pretty simple to apply by hand.

**Comment by luisortiz-grit** [comment]
> Disabling the special logic to switch the clipboards on Wayland gives me the expected behavior on CentOS 8 Gnome/Wayland.
> 
> ```
> --- terminatorlib/terminal.py.orig  2020-04-24 22:48:07.447809430 -0600
> +++ terminatorlib/terminal.py       2020-04-24 22:48:24.943312461 -0600
> @@ -929,12 +929,11 @@
>              # Suppress double-click behavior
>              return True
> 
> -        use_primary = (display_manager() != 'WAYLAND')
>          if self.config['putty_paste_style']:
>              middle_click = [self.popup_menu, (widget, event)]
> -            right_click = [self.paste_clipboard, (use_primary, )]
> +            right_click = [self.paste_clipboard, (True, )]
>          else:
> -            middle_click = [self.paste_clipboard, (use_primary, )]
> +            middle_click = [self.paste_clipboard, (True, )]
>              right_click = [self.popup_menu, (widget, event)]
> 
>          if event.button == self.MOUSEBUTTON_LEFT:
> ```

It work like a Charm. Tested on RHEL 8 GNOME 3.32 / Wayland 1.20

**Comment by jwwatts** [comment]
Patch works for me as well.  I updated our internal package, recommend that this be applied to the next release.

**Comment by henricook** [comment]
@lazyfrosch @alcir should we reopen this? I'd also love this fix

**Comment by themanyone** [comment]
No middle-click paste from SciTE into terminal? Fixed by compiling newer version of SciTE and this:
`sudo ln -s /usr/lib64/gtk-3.0/modules/libpk-gtk-module.so /usr/lib64/`
