### ISSUE TITLE
[BUG] Super Zoom of Window Split

### ISSUE THREAD

**Issue by TheCedarPrince** [gnome-terminator/terminator#240]
Hi all,

Thank you so much for revitalizing the terminator project! I have been using it for years and I absolutely love it!

I just tried out the new release off of master (v2.0.1) and it sadly did not fix an issue I have been running into and that is this:

If I have a layout - for example, a vertical split that takes up half my monitor screen and two horizontal splits that halve the remaining half - it creates a strange behavior zooming behavior. The layout is fine but if I try to zoom on one of the splits, it "super zooms" into that split.

Here is a gif explaining what happens:

![terminator_zoom](https://user-images.githubusercontent.com/29561456/95799327-4e31b000-0cc2-11eb-8529-e64e8b149294.gif)

It is odd as this doesn't always happens when a new tab appears. Moreover, the zoom does not super zoom all windows (like I showed, the vim split was unaffected whereas my Julia REPL and zsh splits were). 

I really do not know what to make of this. Any thoughts on what is happening? 

**Notes:**

OS: Fedora 32
WM: KDE Plasma
Terminator version(s) v2.0.1, v1.92

**Comment by mattrose** [comment]
Hmmm, that's not quite clear to me.  Maybe if you could explain it more in steps that I can follow, ie:

I take this sequence of actions and what I expect to see is this.  

Feel free to use screenshots to clarify, but the animated gif doesn't give me quite enough to go on

**Comment by mattrose** [comment]
Closing for lack of feedback, please feel free to re-open.

**Comment by TheCedarPrince** [comment]
Hey @mattrose ! Sorry for the lack of feedback. I ended up finding a different work around -- apologies for cluttering the issue list!
