### ISSUE TITLE
Easy Install?

### ISSUE THREAD

**Issue by JimLynchCodes** [gnome-terminator/terminator#241]
How do I install this for wsl on windows?

Can we can a one-liner install command that works please?

**Comment by mattrose** [comment]
Should be in the WSL distribution repositories.  Running any kind of X11 program under WSL is a chore in my experience, but you should be able to do `apt install terminator` in WSL (if you're running the standard Ubuntu WSL) and it should work.

I haven't touched windows in a couple of years so I'm not very up-to-date on WSL.

**Comment by JimLynchCodes** [comment]
Hey @mattrose!

Sorry for taking so long to follow up on this.

I ran this command and received this output:
```
Reading package lists... Done
Building dependency tree
Reading state information... Done
terminator is already the newest version (1.91-1).
0 upgraded, 0 newly installed, 0 to remove and 132 not upgraded.
```

At this point though, I'm not sure how to open a terminator shell. 🤔
