### ISSUE TITLE
Smart Copy option to clear selection after copy

### ISSUE THREAD

**Issue by 1player** [gnome-terminator/terminator#242]
Smart Copy is a cool feature. But it introduces a small usability problem: if a user inadvertently selects some text (perhaps in the scrollback), pressing Ctrl-C to terminate some foreground program won't do anything, as this will just copy the text in clipboard and do nothing else. The solution is to clear the selection manually (click somewhere on the window so nothing is selected), and press Ctrl-C again.

The Kitty terminal emulator has a feature where Ctrl-C can be set to _copy and clear selection_, which effectively provides a nice solution to the above problem: first Ctrl-C will copy the text in clipboard, also clearing the selection, the second Ctrl-C will terminate the foreground program. 

As people tend to press Ctrl-C multiple times when their intention is to send a SIGINT, it feels very natural, and instead of an option I would argue this behaviour should be enabled by default.

**Comment by mattrose** [comment]
Have no idea how hard this'll be, but I'll take a stab at it.

**Comment by mattrose** [comment]
Hmm, maybe you have copy bound differently?  With the default mapping, Ctrl-C doesn't copy, Ctrl-Shift-C does. and when I select text, and hit Ctrl-C after selecting text in a terminal with  a long-running process, Ctrl-C behaves exactly as I expect, and interrupts the process.

**Comment by 1player** [comment]
I have copy bound to Ctrl-C, which is why I need smart copy. Is smart copy ever useful if copy isn't bound to Ctrl-C?

**Comment by mattrose** [comment]
Ah, ok.  Honestly I've never used the feature, so I wasn't sure what the use case was.

**Comment by mattrose** [comment]
Well, I found an interesting way to get the desired behaviour but boy is it ugly.  I'll keep working at it.

**Comment by mattrose** [comment]
As with most things, it was just a matter of finding the correct Vte.Terminal method
