### ISSUE TITLE
Execute Multiple Custom Commands in One Window?

### ISSUE THREAD

**Issue by TheCedarPrince** [gnome-terminator/terminator#245]
I am trying to chain together multiple commands in a custom command for a window layout and it appears to fail. For example, in custom command, I could write `echo 'Hello World!'` and that works perfectly. However, if I try to chain it with something else like `echo 'Hello World!' && python script.py` it fails.

How do I chain multiple commands for the custom command of one window? Thanks for the help!

**Comment by mattrose** [comment]
Hmm, works for me. I made a profile called cmdtest and this does everything I expect.

```
  [[cmdtest]]
    exit_action = hold
    login_shell = True
    use_custom_command = True
    custom_command = echo "foo" && echo "bar" && python test.py
```

What version are you on?

**Comment by mattrose** [comment]
closing WORKSFORME :)
