### ISSUE TITLE
Ctrl+Shift+e shortcut collision

### ISSUE THREAD

**Issue by fonzinc** [gnome-terminator/terminator#25]
Setup: CentOS 8 / Gnome (Wayland)

The default vertical split shortcut collides with the emoji shortcut. This is quite sad as my muscle memory definitely wants to keep using this key combo...

Consider changing the default v-split shortcut since it no longer works?

See: https://askubuntu.com/questions/1083913/what-does-ctrl-shift-e-do-while-typing-text

**Comment by JAugusto42** [comment]
Hi, actually you can change the default key bindings in preferences > keybindings.

**Comment by lazyfrosch** [comment]
I wasn't even aware of that Emoji combination.

Question: We could change the default, any suggestions?

**Comment by fonzinc** [comment]
I've been re-mapping the vertical split to Ctrl+Shift+L. I realize it's a petty request, but it would be really nice if the first task on a new installation was not to modify the keybindings.

I'll happily retrain my muscle memory to use any new default.

Obviously, the preference would be to avoid any other conflicting key combinations.

Found this: https://en.wikipedia.org/wiki/Table_of_keyboard_shortcuts

**Comment by geckon** [comment]
I wasn't aware of the emoji combination either and I do happily and very often use this key combination for splitting the terminator window in OpenSUSE Tumbleweed. 

Is the emoji combination a new thing? Or something CentOS specific?

**Comment by inoperable** [comment]
@fonzinc you can try to disable global shortcuts on the windows manager level. It's possible in Kwin/Plasma, probably with others as well. 

Add a shortcut that toggles this, you can then swap between priority for conflicted shortcuts, meaning if globals are disabled - terminator gets priority, when enabled the other way around. Simple hack, less headache :-) Can also add some xcape xkbcomp hacks to have a more iTerm2/Karabiner workflow - although Wayland is a different story ...

**Comment by fonzinc** [comment]
@inoperable Yeah. That's a good suggestion.

I have a reasonable work-around. I've been remapping my v-split keybinding since discovering the issue. I guess my point in reporting the bug was to document its existence and propose that it might be worth changing the default since I won't be the only person affected by the collision.

For me, personally, the emoji keybinding is here to stay! I've started using [ctrl][shift]ebeer[space][enter] quite a bit...
