### ISSUE TITLE
Allow the creation of new windows using Ctrl + N

### ISSUE THREAD

**Issue by commadelimited** [gnome-terminator/terminator#260]
I'm a relative Ubuntu newbie, but experienced Mac user. I discovered Terminator while looking for a replacement for iTerm2.

I see in the Keybindings tab that there's an option to set the shortcut for New Window. I'd like to be able to use Ctrl + N like many other applications. However when I try to set this shortcut it forces Shift + Ctrl + N. I looked through the list and didn't see any other options using that shortcut. Why can't I set it to this?

**Comment by mattrose** [comment]
What version of terminator are you using?

**Comment by commadelimited** [comment]
@mattrose I'm using `terminator 1.91` for `Ubuntu 18.04`.

**Comment by mattrose** [comment]
Are you comfortable running following the instructions at https://github.com/gnome-terminator/terminator/blob/master/INSTALL.md to install the latest master?  It works for me in master.

The other thing you could do is edit the terminator config file directly and add the following lines in the `[global_config]` 
 section .config/terminator/config

```
[keybindings]
  new_window = <Control>n
```

**Comment by mattrose** [comment]
Just entirely off-topic, but I'm glad you're checking out terminator as an iterm2 replacement.  I'm also a long-time mac user and iTerm2 is definitely a big inspiration for me.

**Comment by commadelimited** [comment]
> Are you comfortable running following the instructions at https://github.com/gnome-terminator/terminator/blob/master/INSTALL.md to install the latest master? It works for me in master.
> 
> The other thing you could do is edit the terminator config file directly and add the following lines in the `[global_config]`
> section .config/terminator/config
> 
> ```
> [keybindings]
>   new_window = <Control>n
> ```

This worked perfectly, thank you @mattrose!

That's good to hear. I'm not personally a fan of Ubuntu, I'm using it because my company bought Dell laptops for the engineering team. I think it's like an 8 or 9 out of 10 in most areas...just a little worse than Mac OS. But it's that polish that I miss. iTerm2 is a great app...I'm probably not even using 20% of it's capabilities, but it's a wicked combo with ZSH and Oh My ZSH.

**Comment by mattrose** [comment]
> That's good to hear. I'm not personally a fan of Ubuntu, I'm using it because my company bought Dell laptops for the engineering team. I think it's like an 8 or 9 out of 10 in most areas...just a little worse than Mac OS. But it's that polish that I miss. iTerm2 is a great app...I'm probably not even using 20% of it's capabilities, but it's a wicked combo with ZSH and Oh My ZSH.

Though I do use a mac regularly, I actually have been a linux user longer.  I've been using Linux since about 1995 or so, but only switched to mac after they introduced OSX.  I actually used NeXTSTEP before they got bought out, so OSX was pretty familiar.

To get completely off-topic, you know you can install zsh and oh-my-zsh on Ubuntu, and if there's anything you desparately miss form iTerm2 that's not in terminator, and is not already an open issue, please feel free to open one.

I'm going to close this issue as I'm pretty sure it's fixed in the latest release and hopefully ubuntu will pick it up soon.

**Comment by commadelimited** [comment]
> To get completely off-topic, you know you can install zsh and oh-my-zsh on Ubuntu

Yep. Installing my dotfiles are one of the first things I do on any new machine.
