### ISSUE TITLE
Broadcast all is broadcasting to all terminator windows

### ISSUE THREAD

**Issue by clwluvw** [gnome-terminator/terminator#261]
After upgrading to 2.0.1 when I choose broadcast all, it will broadcast to all terminator windows that in previous version it wasn't like this and it was broadcasting to terminals in a that window.
Using Ubuntu 20.04.01

**Comment by mattrose** [comment]
Hmm, that is the intended behaviour.

**Comment by clwluvw** [comment]
@mattrose It's not like this in v1.91
And I think it's so much better to be like this because it has many use case to broadcast command to all terminals in one window not to all of them!

**Comment by mattrose** [comment]
It's always been like this, it's even in the documentation at https://gnome-terminator.readthedocs.io/en/latest/grouping.html

```
In particular, note that when you run Terminator a second time, by default you are not running a completely separate process. It is still connected to the grouping of the initially launched Terminator process. If you need a completely separated window you need to use the -u option or disable the DBus interface in your config file.
```

if you want the behaviour you describe you can always follow the instructions in that doc.
