### ISSUE TITLE
Open terminator [2.0.1] in same working directory

### ISSUE THREAD

**Issue by gkatev** [gnome-terminator/terminator#262]
In 1.92, terminator opens in the same working directory as the "parent", whereas in 2.0.1, it always opens in $HOME.
I believe the functionality should be how it was in 1.92, the same way it is in gnome-terminal (and others?).
How to reproduce:

> From a terminal, cd  to /usr (or any directory other than $HOME).
> Enter 'terminator' command.
> In 1.92, the new window will be started in /usr. In 2.0.1, it will be started in $HOME.

Simple use case: 
When launching a terminal from the file manager, you want it to be started at the current folder.

**Comment by mattrose** [comment]
This is how it works for me.  If I open terminator from another terminal emulator, it opens in the directory I launched it from?

What OS are you using?

**Comment by gkatev** [comment]
Oh, ok! I'm on Arch Linux.
If you can't reproduce this yourself, you could point me to the relevant place in the code and I can look around.

**Comment by napcok** [comment]
Same issue here,
terminator-git from AUR -> https://aur.archlinux.org/packages/terminator-git/
Tested in PCManFM and Thunar file managers, terminator always starts at $HOME, regardless current directory.

**Comment by mattrose** [comment]
I've poked the Arch packager to see if he can reproduce.  

Can you check to see if vte-common is installed?  I don't see a dependency for it, but it does help with this.

**Comment by mattrose** [comment]
The relevant code is here https://github.com/gnome-terminator/terminator/blob/master/terminatorlib/cwd.py if you don't have the OSC-7 escape sequence installed, and is called from https://github.com/gnome-terminator/terminator/blob/master/terminatorlib/terminal.py#L236 if you want to investigate further.

**Comment by napcok** [comment]
> Can you check to see if vte-common is installed? I don't see a dependency for it, but it does help with this.

Yes, vte-common is installed.

**Comment by mattrose** [comment]
If you modify the file manager to run `terminator  -u --working-directory=%s` it should work.  This gives me some ideas as well.

**Comment by mattrose** [comment]
Can you run `terminator -d --debug-methods parse_options --working-directory /tmp/` and paste the output?

**Comment by napcok** [comment]
`napcok@mabox ~ $ terminator -d --debug-methods parse_options --working-directory /tmp/
noclass::parse_options: OptionParse::parse_options: command line options: {'version': None, 'maximise': None, 'fullscreen': None, 'borderless': None, 'hidden': None, 'forcedtitle': None, 'geometry': None, 'command': None, 'config': '/home/napcok/.config/terminator/config', 'configjson': None, 'execute': None, 'working_directory': '/tmp/', 'forcedicon': None, 'role': None, 'layout': 'default', 'select': None, 'profile': None, 'nodbus': None, 'debug': 1, 'debug_classes': None, 'debug_methods': 'parse_options', 'new_tab': None, 'dummy': None}
`
