### ISSUE TITLE
Using terminator natively on Windows 10

### ISSUE THREAD

**Issue by meatware** [gnome-terminator/terminator#263]
Hi,

Is there a way to use terminator natively on windows 10. Perhaps by compiling as an excutable? 

I know there are ways to use it via wsl, but this is slow and a bit of a PITA.

If you could advise me, I would be much obliged! :)

**Comment by mattrose** [comment]
I have no idea.  I have it running on MacOS with some custom vte hacks, but Windows is an entirely different beast.  I don't have any windows machines, so I can't really work on this.

**Comment by meatware** [comment]
oki, thanks for the quick reply. :) 

i'll have a look into it when i get time and let you know if anything comes of it
