### ISSUE TITLE
module 'command_notify' has no attribute 'AVAILABLE'

### ISSUE THREAD

**Issue by planet36** [gnome-terminator/terminator#264]
Upon starting Terminator, these messages are always printed.

> PluginRegistry::load_plugins: Importing plugin command_notify.py failed: module 'command_notify' has no attribute 'AVAILABLE'
> 
> (terminator:13830): VTE-WARNING **: 14:45:14.304: (../vte/src/vtepty.cc:667):bool _vte_pty_spawn_sync(VtePty*, const char*, const char* const*, const char* const*, GSpawnFlags, GSpawnChildSetupFunc, gpointer, GDestroyNotify, GPid*, int, GCancellable*, GError**): runtime check failed: ((spawn_flags & ignored_spawn_flags()) == 0)

I'm running the master branch from this repo.

`terminator --version`
> terminator 2.0.1

Are the messages serious?  Is it possible to prevent them?

**Comment by mattrose** [comment]
The messages aren't serious.  I'll see if I can get rid of them for the next version.  I honestly have no idea why they decided to throw a warning message for the second one you're seeing
