### ISSUE TITLE
Lack of documentation

### ISSUE THREAD

**Issue by wenzler** [gnome-terminator/terminator#268]
Hey,

there's
- no install information
- no information on build/runtime dependencies

I have no idea where to get Vte 2.91 to be satisfied by gi - python-vte does not seem to do the thing

Please add - thanks!

PS: not everyone uses ubuntu latest

**Comment by mattrose** [comment]
https://github.com/gnome-terminator/terminator/blob/master/INSTALL.md

Maybe we should move this into the README.md file?

**Comment by wenzler** [comment]
Damn, that file is just in the repo, but not in the last tagged release tarball - I only looked at that content :D

Yet, would appreciate if you could add some links towards the relevant projects and not only OS specific package names.
