### ISSUE TITLE
Automatically execute plugins without a menu entry

### ISSUE THREAD

**Issue by grg121** [gnome-terminator/terminator#269]
Hello there!

I'm working right now on a project where I want to record user input and console output in a terminal with a certain format.

I've written a plugin for terminator which does the trick! I will upload it to GitHub as soon as I finalise some details. One of them is that I would like to load the plugin automatically and have it being executed without selecting any option on the right-click menu.

I've used the Logger plugin as a base, and now I have something like this:

```
    def callback(self, menuitems, menu, terminal):
        """ Add save menu item to the menu"""
        vte_terminal = terminal.get_vte()
        if vte_terminal not in self.loggers:
            item = Gtk.MenuItem.new_with_mnemonic(_('START'))
            item.connect("activate", self.start, terminal)
        else:
            item = Gtk.MenuItem.new_with_mnemonic(_('STOP'))
            item.connect("activate", self.stop, terminal)
            item.set_has_tooltip(True)
            item.set_tooltip_text("Saving at '" + self.loggers[vte_terminal]["filepath"] + "'")
        menuitems.append(item)
```

I would like to run my `self.start` method when a terminal start and my stop method (is possible) when it ends. Without using the START and STOP buttons.

I've seen that the terminator Plugin class has two main classes: ` URLHandler` and `MenuItem` but none of them seems to be thought to do that, are they?

I'm testing right now and I would really appreciate any help or indication.

Best regards.

**Comment by mattrose** [comment]
I wonder if we can extend the plugin architecture to accept command-line args.  Is this the kind of thing you're looking for?

**Comment by mattrose** [comment]
Sorry for not getting back to you sooner, I fell off my bike on the weekend and wrecked my back pretty bad, I have some ideas, but I need to do a little bit more digging

**Comment by grg121** [comment]
It's okay, I hope you are recovering well. This weekend I've found some issues with my plugin when I entered into another session (for example, through ssh or changing the shell) and when the user is asked for a password. But I'm trying to solve them. I'd be happy to hear those ideas when you're better and have a moment! 

Best regards.

**Comment by mattrose** [comment]
I had a chance to read over your code, and it looks good.  My recommendation to you is to run the main class method in the initializer, like this https://github.com/gnome-terminator/terminator/blob/24a1f912d33ca5c6292ccdf8676d022a1154c59c/terminatorlib/plugins/command_notify.py#L37

That way, as long as the plugin is enabled, it will be running.

**Comment by grg121** [comment]
Allright, I'll check that, thank you very much!

**Comment by mattrose** [comment]
Is it OK if I close this issue?  I look forward to a PR for the plugin.

**Comment by grg121** [comment]
Yeah, sure
