### ISSUE TITLE
Option to make zooming in and out apply to all subterminals instead of just one

### ISSUE THREAD

**Issue by evanbenadler** [gnome-terminator/terminator#271]

**Comment by mattrose** [comment]
Why?  This seems like it would add a lot of complexity for a pretty rare use-case.  Most people only focus on one terminal at a time.

**Comment by evanbenadler** [comment]
This would be helpful for people with high screen resolution displays

**Comment by mattrose** [comment]
Can you not just set the font size larger in the configuration?  That seems like the better way, rather than zooming in after startup all the time...

**Comment by evanbenadler** [comment]
My use case is that I plug my laptop into a monitor. Without the monitor, I need larger font, and every time I plug it into the monitor, I need a smaller font

**Comment by mattrose** [comment]
Maybe use a shift modifier to zoom, so that you could do something like <ctrl><shift>+ zooms all terminals?  Would that be OK?

**Comment by evanbenadler** [comment]
That sounds great

**Comment by mattrose** [comment]
bump
