### ISSUE TITLE
You need to run terminator in an X environment. Make sure $DISPLAY is properly set

### ISSUE THREAD

**Issue by JimLynchCodes** [gnome-terminator/terminator#272]
Hi!

I an using windows 10.0.17134 and a wsl shell with `Ubuntu 18.04.4 LTS`.

I installed terminator with `apt install terminator`

Now I am trying to start terminator: `terminator`

I am getting this error, but I am not really sure what it means and what it wants me to do...
```
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused
You need to run terminator in an X environment. Make sure $DISPLAY is properly set
```

**Comment by JimLynchCodes** [comment]
bump! 🙃

**Comment by mattrose** [comment]
Github is not a good support mechanism.  Helped on gitter, as much as I could.

**Comment by oljisfcy** [comment]
There are two solutions:
1. upgrate to wsl2
2. install an X-server

may be this can help you: 
https://superuser.com/questions/1580610/how-to-run-gui-apps-with-windows-subsystem-for-linux
