### ISSUE TITLE
Better to use OS package system or setup.py for Ubuntu 20.04

### ISSUE THREAD

**Issue by merceskoba** [gnome-terminator/terminator#274]
In [this link](https://github.com/gnome-terminator/terminator/blob/master/INSTALL.md) it said, It's strongly recommended to install Terminator using your OS's package system rather than using setup.py yourself.

I just finished my college and installed Ubuntu 20.04 :heart: 
And my coworker suggests me to use Terminator terminal

Now, i am confused how exactly installed Terminator in Ubuntu 20.04 based [INSTALL.md](https://github.com/gnome-terminator/terminator/blob/master/INSTALL.md)

Do i have to run this `apt install python3-gi python3-gi-cairo python3-psutil python3-configobj gir1.2-keybinder-3.0 gir1.2-vte-2.91 gettext intltool dbus-x11` first ? and then `python3 setup.py build`

And what is exactly "strongly recommended to install Terminator using OS's package ?"
I scroll-down and It brings me to [here](https://repology.org/project/terminator/versions) and then i looked for [Ubuntu 20.04 focal](https://packages.ubuntu.com/source/focal/terminator)
And what should i do ? 

Sorry for this dumb question, i am trying to understand the instruction :hear_no_evil: 
Should i install it by running these steps
`python3 setup.py build`
`python3 setup.py install --single-version-externally-managed --record=install-files.txt`

**Comment by Nigma1337** [comment]
you can just do `sudo apt install terminator`

**Comment by mattrose** [comment]
there are now three ways of installing terminator on ubuntu on 20.04

1.  Install the latest release packaged by ubuntu: `sudo apt install terminator`
2.  Install the 2.0.1 release: 
```
sudo add-apt-repository ppa:mattrose/terminator
sudo apt-get update
sudo apt install terminator
```
3. Install it from the git repository: 
```
python3 setup.py build
python3 setup.py install --single-version-externally-managed --record=install-files.txt
```
I've got to update the README I think
