### ISSUE TITLE
Terminator crashes 1-10 seconds after opening

### ISSUE THREAD

**Issue by RoelVdP** [gnome-terminator/terminator#281]
```
$ cat /etc/*release* | grep -E 'DESC|VER.*ID'
DISTRIB_DESCRIPTION="Ubuntu 20.04.1 LTS"
VERSION_ID="20.04"
```

Already tried:
1) `sudo apt -y purge terminator && sudo apt -y install terminator`  -> Same result
2) `sudo apt -y purge terminator && git clone https://github.com/gnome-terminator/terminator.git &&` {install deps}` &&` {compile & install}
3) Tried running with another older Python version (normally it uses 3.8), but that produced symbol missing.

Same result after all attempts to fix

Issue started happening today with no real clear change in the setup other then perhaps creating some groups and then closing/re-opening terminator. 

Grabbing the window by the title bar (mouse left-click + drag) seems to make the issue produce immediately.

Also, when it crashes, the process keeps running though the terminal window itself is gone. No output in `dmesg` and not sure where else to look for logs. Killing the process (-9) and re-opening has no effect, issues reproduces again and again after a few seconds.

Please assist, I use terminator very often for work.

**Comment by RoelVdP** [comment]
It seems to be related to a particular configuration. i.e. have a particular config in place (4 windows, auto-start a script), then open config, don't save anything (though `config` file seems to get date/time update), and from that moment the crashes happen. Removing the config also stops the crashes.

**Comment by RoelVdP** [comment]
Completely re-configured the environment, and it continues to work without issues. In conclusion, it must be something in the config file which is updated when the configuration window opens and closes, or when terminal groups are updated, and then perhaps in combination with some backword compatibility or similar. I can perhaps upload the crashing config file.

**Comment by RoelVdP** [comment]
Steps to reproduce:
1. close all terminator windows, check with `ps -ef | grep terminator` there are no live processes
2. `cd ~/.config && mv terminator terminator.OLD`
3. `mkdir terminator && cp ~/Downloads/config ./terminator/config` 
     The config file is @ https://gist.github.com/RoelVdP/26d59a27bbf2809819b608902dd23f43
4. open terminator, click on titlebar, keep in left mouse, drag down
5. terminator should crash  < # The [bug]
6. check with `ps -ef | grep terminator` and note process is still there
7. `kill -9 pid` where pid is the pid from the command in #6
8. `cd ~/.config && mv terminator terminator.BROKE && mv terminator.OLD terminator`
9. restart your own terminator
Also, the ~/s script mentioned in the config file is simply a ssh to google cloud I use for work.

**Comment by mattrose** [comment]
I'll take a look at this when I get the chance, but if you could run terminator at another command prompt by opening up gnome-terminal and running `terminator -d` and attaching the output here that would make things go quicker.

Also, can you run `terminator -v` to tell us what version you're on?

**Comment by derenv** [comment]
also had this problem (with terminator 2.0.1 on Ubuntu 20.10), renaming my config file and creating a new one (setting new preferences) seemed to solve. These are my config files:

deren > ~ > cat .config/terminator/config 

[global_config]
  suppress_multiple_term_dialog = True
[keybindings]
[profiles]
  [[default]]
    audible_bell = True
    background_color = "#002b36"
    background_darkness = 0.8
    background_type = transparent
    cursor_shape = ibeam
    cursor_color = "#aaaaaa"
    foreground_color = "#839496"
    scroll_on_output = True
    scrollback_infinite = True
    palette = "#073642:#dc322f:#859900:#b58900:#268bd2:#d33682:#2aa198:#eee8d5:#002b36:#cb4b16:#586e75:#657b83:#839496:#6c71c4:#93a1a1:#fdf6e3"
    login_shell = True
[layouts]
  [[default]]
    [[[window0]]]
      type = Window
      parent = ""
    [[[child1]]]
      type = Terminal
      parent = window0
[plugins]


 deren > ~ > cat .config/terminator/config.old 


[global_config]
  geometry_hinting = True
  title_inactive_bg_color = "#f57900"
  enabled_plugins = LaunchpadBugURLHandler, LaunchpadCodeURLHandler, APTURLHandler, Logger
  suppress_multiple_term_dialog = True
[keybindings]
  switch_to_tab_1 = <Primary><Shift>exclam
  switch_to_tab_2 = <Primary><Shift>quotedbl
  switch_to_tab_3 = <Primary><Shift>sterling
  switch_to_tab_4 = <Primary><Shift>dollar
  switch_to_tab_5 = <Primary><Shift>percent
  switch_to_tab_6 = <Primary><Shift>asciicircum
  switch_to_tab_7 = <Primary><Shift>ampersand
  switch_to_tab_8 = <Primary><Shift>asterisk
  switch_to_tab_9 = <Primary><Shift>parenleft
  switch_to_tab_10 = <Primary><Shift>parenright
[profiles]
  [[default]]
    audible_bell = True
    background_color = "#aa00aa"
    background_darkness = 0.7
    background_type = transparent
    cursor_shape = ibeam
    cursor_color = "#aaaaaa"
    foreground_color = "#ffffff"
    scroll_on_output = True
    scrollback_infinite = True
    palette = "#000000:#cd0000:#00cd00:#cdcd00:#0000ee:#cd00cd:#00cdcd:#e5e5e5:#7f7f7f:#ff0000:#00ff00:#ffff00:#5c5cff:#ff00ff:#00ffff:#ffffff"
    login_shell = True
[layouts]
  [[default]]
    [[[child0]]]
      type = Window
      parent = ""
      order = 0
      position = 0:27
      maximised = True
      fullscreen = False
      size = 1920, 948
      title = deren@ubuntu-d2: ~
      last_active_term = 9294f53d-597b-4f2b-a424-80208ba719c9
      last_active_window = True
    [[[terminal1]]]
      type = Terminal
      parent = child0
      order = 0
      profile = default
      uuid = 9294f53d-597b-4f2b-a424-80208ba719c9
[plugins]

I recently upgraded the terminator version, could that be affecting it?

**Comment by mattrose** [comment]
Tried it with both config files and they both worked fine on my 20.04.1 VM.  @RoelVdP's config had a `~/s` command that may be causing the problem, as it is set to restart when it fails, so on my VM it just constantly restarts without doing anything.  If this command can cause CPU usage on start it might be causing the issue.  Anyways, attache `terminator -d` output and that should tell us if anything is going wrong within terminator

**Comment by derenv** [comment]
https://gist.github.com/derenv/5df2c1b13455e0cd1b88c7d194f06e20

**Comment by mattrose** [comment]
Hmm, I don't see anything unusual in that debug output.  Did you close it yourself, or did it close through some other method?

**Comment by derenv** [comment]
once it crashes terminator restarts (with the 1-10 second delay) and a new window spawns then works normally, at which point i closed it myself.

**Comment by mattrose** [comment]
Hmm, I don't see it crashing at all.  When the new window spawns, is there new debug output in the window that you originally launched it from?  I wish I could reproduce.

**Comment by derenv** [comment]
nah, it seems to maintain the debug output of the initial window (the quit proccess part at the end of that gist is me closing the new window).

this has been bugging me (ha) for a while im just glad a new config file fixes it.

**Comment by mattrose** [comment]
The only thing I can think of doing from here is going through the old config file line-by-line and seeing which line causes the problem.

**Comment by derenv** [comment]
Found the culprit!

`maximised = True`

**Comment by mattrose** [comment]
Thank you so much for this!

**Comment by RoelVdP** [comment]
No, still crashes when I remove the 3x 'maximised = True'. It also has nothing to do with the '~/s', that is just a script and it does not loop. I removed 'use_custom_command' as well as 'custom_command` from the config file completely, to be sure and indeed: **it still crashes** all the same.

**Comment by RoelVdP** [comment]
```
$ terminator -v
terminator 2.0.1
```

And end of log:

```
Config::set_profile: Config::set_profile: Changing profile to default
Config::connect_gsetting_callbacks: GSetting connects for system changes
noclass::parse_options: OptionParse::parse_options: command line options: {'version': None, 'maximise': None, 'fullscreen': None, 'borderless': None, 'hidden': None, 'forcedtitle': None, 'geometry': None, 'command': None, 'config': '/home/me/.config/terminator/config', 'configjson': None, 'execute': None, 'working_directory': None, 'forcedicon': None, 'role': None, 'layout': 'default', 'select': None, 'profile': None, 'nodbus': None, 'debug': 1, 'debug_classes': None, 'debug_methods': None, 'new_tab': None, 'dummy': None}
Terminator::__init__: Borg::__init__: Preparing borg state for Terminator
ConfigBase::load: ConfigBase::load: config already loaded
Config::set_profile: Config::set_profile: Changing profile to default
Config::connect_gsetting_callbacks: GSetting connects for system changes
ConfigBase::get_item: ConfigBase::get_item: broadcast_default found in globals: group
ConfigBase::load: ConfigBase::load: config already loaded
Config::set_profile: Config::set_profile: Changing profile to default
Config::connect_gsetting_callbacks: GSetting connects for system changes
ConfigBase::get_item: ConfigBase::get_item: dbus found in globals: True
function::with_proxy: dbus client call: new_window_cmdline
function::with_proxy: dbus client call: new_tab_cmdline
function::with_proxy: dbus client call: new_window
function::with_proxy: dbus client call: new_tab
function::with_proxy: dbus client call: hsplit
function::with_proxy: dbus client call: vsplit
function::with_proxy: dbus client call: get_terminals
function::with_proxy: dbus client call: get_window
function::with_proxy: dbus client call: get_window_title
function::with_proxy: dbus client call: get_tab
function::with_proxy: dbus client call: get_tab_title
DBusService::__init__: Borg::__init__: Preparing borg state for DBusService
DBusService::prepare_attributes: Checking for bus name availability: net.tenshu.Terminator21a9d5db22c73a993ff0b42f64b396873
DBusService::prepare_attributes: bus name unavailable: net.tenshu.Terminator21a9d5db22c73a993ff0b42f64b396873
noclass::<module>: Unable to become master process, operating via DBus
noclass::<module>: Requesting a new window
```

**Comment by mattrose** [comment]
can you make sure you're passing -u, so `terminator -d -u` just so that you're getting debug output from the command.

**Comment by mattrose** [comment]
Closing
