### ISSUE TITLE
Laggy performance after upgrade to ubuntu 20.10

### ISSUE THREAD

**Issue by dimisjim** [gnome-terminator/terminator#284]
Hey.

I have a T590, terminator v1.92 (via apt: terminator/groovy,groovy,now 1.92-2 all [installed]) and after recently upgrading to ubuntu 20.10 from 20.04 I am experiencing some really laggy behavior from terminator. I have a 2-3 split windows open, and when I type something, the thing that I have types will appear after I move the mouse for some reason. This happens a lot but not all the time.

Is this a known bug? I am not experiencing this behavior from other terminal emulators like the one used in Visual Studio Code for example.

**Comment by mattrose** [comment]
Can you try my PPA and see if that fixes it?
```
sudo add-apt-repository ppa:mattrose/terminator
sudo apt-get update
sudo apt install terminator
```

**Comment by dimisjim** [comment]
Same result.

**Comment by mattrose** [comment]
Can you see if you get the same hiccups with gnome-terminal?

**Comment by dimisjim** [comment]
seems to be the case, but the effect is more pronounced as I so multiple windows in terminator

**Comment by dimisjim** [comment]
Groovy gorilla ubuntu 20.10 contained some faulty graphics driver I suppose...

Thanks Canonical :+1:

**Comment by mattrose** [comment]
If you're interested in pursuing this further, you can open an issue in the ubuntu project against vte.  The problem is most likely with that component, as both terminator and gnome-terminal, but I don't think it's with the stock version of vte, as I haven't seen that with Fedora.

**Comment by jchillerup** [comment]
It happens to me, too, on Archlinux. I'll try to do a screen grab the next time I can reproduce. I can type in commands etc. and they will get executed, but won't see the result until I move focus to another window. Maybe it has to do with the infinite scroll buffer?

**Comment by dimisjim** [comment]
@jchillerup I don't have infinite scroll buffer enabled.

It seems to be linked with gnome terminal. I am not seeing this behavior with visual studio code's terminal.

@mattrose Could you look into this issue again, i.e reopen this issue?

**Comment by mattrose** [comment]
This seems to be an issue with the underlying vte or gtk library.  I saw someone report the same kind of thing on IRC in #vte on the GNOME network. To test this out you could see if you get the same behaviour in xfce4-terminal, or gnome-terminal, or tilix.  If this is something in vte, unfortunately, there's nothing I can do in the terminator code to fix this.  I will ask you to open a bug here https://gitlab.gnome.org/GNOME/vte/-/issues and help the vte authors track down the issue.

**Comment by mattrose** [comment]
@dimisjim @jchillerup can you try running glxgears on the same display or run terminator in fullscreen to see if this recurs when you're running with glxgears or in fullscreen mode?

**Comment by jchillerup** [comment]
Kicking off a day at work under constant supervision by xeyes 😂

**Comment by dimisjim** [comment]
@mattrose seeing normal numbers and performance while running glxgears and at the same time multiple terminator windows:
```
Running synchronized to the vertical refresh.  The framerate should be
approximately the same as the monitor refresh rate.
322 frames in 5.0 seconds = 64.280 FPS
301 frames in 5.0 seconds = 60.161 FPS
301 frames in 5.0 seconds = 60.163 FPS
301 frames in 5.0 seconds = 60.168 FPS
301 frames in 5.0 seconds = 60.157 FPS
301 frames in 5.0 seconds = 60.169 FPS
301 frames in 5.0 seconds = 60.166 FPS
301 frames in 5.0 seconds = 60.153 FPS
```

**Comment by jchillerup** [comment]
Me too. No change running xeyes, but running glxgears seemed to work.

**Comment by jchillerup** [comment]
Oh, forgot to say, my glxgears is not synced to the monitor refresh rate, although it _says_ it is...

```Running synchronized to the vertical refresh.  The framerate should be
approximately the same as the monitor refresh rate.
16549 frames in 5.0 seconds = 3309.727 FPS
17021 frames in 5.0 seconds = 3404.040 FPS
17873 frames in 5.0 seconds = 3574.456 FPS
19135 frames in 5.0 seconds = 3826.897 FPS
17230 frames in 5.0 seconds = 3445.801 FPS
17448 frames in 5.0 seconds = 3489.540 FPS
17919 frames in 5.0 seconds = 3583.740 FPS
18173 frames in 5.0 seconds = 3634.371 FPS
17713 frames in 5.0 seconds = 3542.475 FPS```

This is my graphics card, for what it's worth.

```01:00.0 VGA compatible controller: NVIDIA Corporation TU117M [GeForce GTX 1650 Mobile / Max-Q] (rev a1)```

Using the latest proprietary Nvidia driver.

**Comment by dimisjim** [comment]
@mattrose I am also using the proprietary nvidia driver on a different machine, on 20.10 and I am still experiencing these lag issues.

I must say though that I believe this is a graphics issue for ubuntu 20.10 in general, as I was getting laggy performance while using two monitors + having a google meet call.
