### ISSUE TITLE
Unable to Set "Image" as Background

### ISSUE THREAD

**Issue by fray6c** [gnome-terminator/terminator#285]
I've got a PDF document that I'd like to set up as a background. I've selected it but even after restarting it's not showing. I've also tried modifying the transparency setting without much success.

**Comment by mattrose** [comment]
Background images don't work with PDFs (I don't think, honestly I've never tried).  They do work with PNG and jpeg files.

**Comment by fray6c** [comment]
Thanks @mattrose I've also tried with both jpeg/jpg but none seem to work. What I am missing here?

**Comment by mattrose** [comment]
Hmm.  In that case, I must humbly ask for forgiveness for my sheer idiocy when writing this code because ... I do absolutely nothing when the picture fails to load, which is probably what's going on in this.  Would you be comfortable running code from a test branch we set up to debug this?

**Comment by fray6c** [comment]
I realized that the picture only loads when I use the "default" profile, this was just a lucky try. This whole time I was using a different profile that I had created because I didn't want to modify the "out-of-box" profile.

**Comment by mattrose** [comment]
Yeah, you can set it per profile, along with the rest of the background options.
I'm going to keep this bug open as a reminder to put in more debug information when the image fails to load.

**Comment by fray6c** [comment]
Please do, because as of now background image does not work with any other profile than "default". Also once the image is set there is no option to 'deselect' it. It appears that the only option to revert to a "blank" background is to set the transparency to "opaque", I am not sure if this is intentional or not or I am misunderstand how to use this feature. Thanks for coming back so quickly.

**Comment by mattrose** [comment]
You can also reset it by going into the config file and removing the `background_image` line.  This is not intentional and will be fixed as well

**Comment by mattrose** [comment]
Not my best implementation of that feature, tbh.  It took me so long to figure out the mechanics of how to add in background images that I really rushed the implementation, unfortunately.   I just wanted it behind me, I think.

**Comment by mattrose** [comment]
I cleaned up the preferences UI and tried to make sure everything works switching back and forth between background types
