### ISSUE TITLE
Help/suggestion: proc title.

### ISSUE THREAD

**Issue by MarioMey** [gnome-terminator/terminator#289]
I would like to change proc title to terminator. I would like to name it "terminator" :D. So I add:

    from setproctitle import setproctitle
    setproctitle('terminator')

... to terminator file and it doesn't work. Why? Does Terminator has a fixed name?

I would like to read "terminator" in `ps` list, to kill it with `killall`, for example.

**Comment by mattrose** [comment]
This works for me see the code in gitter, that I added.

**Comment by mattrose** [comment]
I don't want to add this because I'd like to keep the python modules that we use to a minimum to make sure it's as cross-platform as possible.
