### ISSUE TITLE
Alt+ScrollWheel ?

### ISSUE THREAD

**Issue by mckellyln** [gnome-terminator/terminator#29]
Hi,
In my very old terminator I used alt+mouse scrollwheel.
But I cannot seem to get any esc sequences out of terminator with alt+scrollwheel.
scrollwheel by itself works fine.  Does anyone know if this is configurable ?
thx
-m

**Comment by JAugusto42** [comment]
hi
i will check here, Sorry for the late answer.

**Comment by mattrose** [comment]
Going through old issues and I saw this and I think I was getting confused between this issue and some of the commits in #46 that actually, as far as I can tell, enable the alt-scrollwheel behaviour you're looking for.  Would you be comfortable putting those together into a pull request and link it against this issue?  I would do it myself, but I think that you would be able to get the behaviour you want better if you do the pull request yourself.  I am definitely available to help if you want, you can reach out to me here or on gitter if you need help.

**Comment by mckellyln** [comment]
Thanks.  I have not (yet) been able to find where in gtk/vte/gnome the alt+wheel is configured - in order to change/disable it - but we can, as shown before, at least scroll as tho alt was not pressed with some small changes.  I can issue that PR.  We can also close this as its sort of understood its not a terminator specific issue.
thx,
-m

**Comment by mattrose** [comment]
I feel your pain.  I'm running terminator on a mac most of the time and the quartz backend support with vte and GTK is ... a little bit spotty and tracking down keypress behaviours is super-painful.  I'll close the issue, but would still welcome a PR.

**Comment by mckellyln** [comment]
ok, cool
