### ISSUE TITLE
Groups in config file

### ISSUE THREAD

**Issue by domix75** [gnome-terminator/terminator#290]
hi
I was wondering if it would be possible to add a group in layouts, in the configuration file
so it would be possible to open a preset layout with 2 terms in group phi and 2 other terms in group beta

Or maybe there is already a way that I did not catch in the doc/FAQ
thanks for the software any way !
cheers

**Comment by mattrose** [comment]
you can do this in layouts.  Follow instructions at: https://gnome-terminator.readthedocs.io/en/latest/layouts.html

**Comment by domix75** [comment]
oh thanks a lot for your reply
sorry that I missed it
br
