### ISSUE TITLE
Unwanted transparent pane separators

### ISSUE THREAD

**Issue by santisoler** [gnome-terminator/terminator#293]
When opening more than one tab, the tab separators look transparent using Matcha Dark-Sea theme on Manjaro XFCE.

![image](https://user-images.githubusercontent.com/11541317/99543132-957e2100-2991-11eb-96a4-a640f87c6b75.png)

I don't know if this is caused by a bug on terminator or a problem with the theme itself (I don't have the problem using another theme, like Adwaita). If the problem is theme-related, is there a way to set the color of the separators on `gtk.css`?

For the record, I had to set the color of the terminal separators (when tiling), otherwise they also look transparent using the same theme:

```css
/* Fix terminator separator color */
separator {
  background-color: #222b2e;
  min-height: 1px;
  min-width: 1px;
}
```

**Comment by mattrose** [comment]
What version is this?  I think I fixed this in a PR a month or so ago

**Comment by santisoler** [comment]
Sorry for my shitty and uninformative issue :man_facepalming: .
I'm running `1.92`, the one on Manjaro repos.

I'll build the latest release and notify if the problem is still present.
Thanks for the quick response.

**Comment by santisoler** [comment]
I'm getting the same transparent borders on `2.0.1`:

![image](https://user-images.githubusercontent.com/11541317/99546560-4afea380-2995-11eb-9442-d260b4522be1.png)

**Comment by pedroflor** [comment]
Here the same issue:
Terminator 2.0.1
Linux Mint 20

![image](https://user-images.githubusercontent.com/3332674/100176136-1bc0c880-2ea6-11eb-911b-94735223c88d.png)

**Comment by deathtrip** [comment]
On Arch Linux I also have the same transparent separator between vertical panes, as in the above picture.
It started happening on 1.92 and the split got bigger in 2.0.1

**Comment by AcidRain123456** [comment]
I also have this issue. I upgraded 1.92 to 2.0.1 where the problem occurred (from repository) then downloaded and installed 2.10. Problem still there. I noted terminal separator size was "-1" which according to the documentation makes it default to the system theme. The separators where also quite big as in the picture from pedroflor above.

I set a size of 1 (which overwrites the system setting) and the size of the separate is no 1 pixel (what I want) but they are still transparent. I have spent few hours researching gtk.css /usr/share/themes/Mint-Y/gtk-3.0 nd /usr/share/terminator/gtk.css (which did not exist) and nothing I found helps.

I have thinking it is a theme issue with Linux Mint. I am running Linux Mint 20 Cinnamon, Cinnamon version 4.6.7 with the Mint-> theme. No idea really what I need to change to get rid of these awful transparent separators...

**Comment by mattrose** [comment]
Whatever theme you're using is not setting the CSS property for the pane separator.  you can set this yourself if you add or edit  `~/.config/gtk-3.0/gtk.css` and add the following:
```
separator {
background-color: rgb(0,0,0) /* set separator to black */
}
``` 
Or whatever colour you prefer.  Ideally, your GTK theme should be setting this.

**Comment by santisoler** [comment]
Thanks @mattrose for the comment.

As I showed before, that CSS solution (set the `background-color` for the `separator`) works only for the separators of tiled terminals, although it doesn't solve the original problem of this issue, which are the transparent borders of tabs.

Let me know if I haven't explained myself well or if I'm missing something here.

**Comment by mattrose** [comment]
ah, there should be a CSS property that determines that.  I'll see if I can dig that up for you.

**Comment by santisoler** [comment]
> ah, there should be a CSS property that determines that. I'll see if I can dig that up for you.

I though the same, but didn't know where to look for CSS properties of gtk (is there something as the browser inspector but for gtk applications?)

Thanks again for the help!

**Comment by santisoler** [comment]
Wow! That's amazing! I was able to run GtkInspector (you're right that it's kind of confusing at first) and find the CSS code needed to remove the border of the tabs. The problem was with the border of `notebook` and `notebook header`.

So, if you want to remove the borders, you need to add the following to your `gtk.css` file, which is usually located in `~/.config/gtk-3.0/gtk.css`:

```css
notebook {
  border: 0px;
}

notebook header {
  border-bottom: 0px;
}
```

Alternatively, you can change the color of the border through CSS.

```css
notebook {
  border-color: white;
}

notebook header {
  border-color: white;
}
```

Thanks again @mattrose for the guidelines! Now I think this issue is closed and solved.

**Comment by mattrose** [comment]
Glad to have helped.  That GTK inspector is a gem once you get used to it.

**Comment by d6bels** [comment]
> Here the same issue: Terminator 2.0.1 Linux Mint 20
> 
> ![image](https://user-images.githubusercontent.com/3332674/100176365-8a9e2180-2ea6-11eb-87dc-c624d9ac6e02.png)

Hi, so I just updated to Mint 21.1 from 20.3 and this issue is back.
I tried to write the gtk.css with the separator but it does nothing.

Is there something else that can be done to fix this?
