### ISSUE TITLE
Geometry ignored

### ISSUE THREAD

**Issue by mrtimdog** [gnome-terminator/terminator#297]
Starting terminator with --geometry isn't working for me:

commit 40bd5948 (HEAD -> master, origin/master, origin/HEAD)

$ terminator --geometry 30x30

(terminator:245224): Gtk-WARNING **: 08:35:44.317: gtk_window_parse_geometry() called on a window with no visible children; the window should be set up before gtk_window_parse_geometry() is called.

**Comment by mattrose** [comment]
I think you're confusing the units to give to geometry.  The units to give to geometry are pixels, so you would use `terminator --geometry 800x600`  

`terminator --geometry 30x30` gives you an unusably small window

![Screenshot from 2020-11-20 11-55-30](https://user-images.githubusercontent.com/65013/99827191-5550a700-2b27-11eb-8fe8-c677f533d6c9.png)

**Comment by mrtimdog** [comment]
Hi, that was just an random example. I can't get geometry set to anything other than what the default profile defines.

**Comment by mattrose** [comment]
Hmm, same commit works for me?  Are you on X11 or Wayland for your display?

**Comment by mrtimdog** [comment]
I'm on Fedora 33 using Xfce, so it'll still be X11 I'm using.
