### ISSUE TITLE
text rewrapping on last line is weird

### ISSUE THREAD

**Issue by eubnara** [gnome-terminator/terminator#300]
I appreciate text rewrapping feature.

But, I found some weird behavior.

![simplescreenrecorder-2020-11-23_13 42 52](https://user-images.githubusercontent.com/12639125/99929863-2722cf80-2d92-11eb-8dd3-24398b8ce784.gif)

Is there some work around to stop producing duplicate text on last line?

**Comment by mattrose** [comment]
I have a strong suspicion that this is a vte behaviour.  Can you reproduce this with gnome-terminal or xfce4-terminal?

**Comment by eubnara** [comment]
@mattrose 
Thanks for reply.
I don't know what `vte` is.
Anyway I reproduced this with gnome-terminal.

![Peek 2020-11-24 03-14](https://user-images.githubusercontent.com/12639125/99999446-84a33480-2e03-11eb-9001-0145bd2c2f40.gif)

**Comment by eubnara** [comment]
I found that if I use `sh` instead of `bash`, it doesn't happen.

Maybe this issue(https://unix.stackexchange.com/questions/343875/resizing-the-terminal-causes-it-to-mix-previous-lines-and-duplicate-pieces-of-te) is some kind of related.

**Comment by mattrose** [comment]
vte is a basic terminal emulator library that is used by a lot of different terminal emulators, including terminator and gnome-terminal.  It takes care of a lot of the lower-level details.  I'm going to close this as there doesn't seem to be any way for me to fix this in terminator
