### ISSUE TITLE
Feature Request: detach tab

### ISSUE THREAD

**Issue by boyska** [gnome-terminator/terminator#302]
Sometimes I want to detach a tab, similarly to what I can easily do on Firefox. I can't find a way to do that easily on Terminator, but I can do that in a boring way:

- `ctrl+shift+N` will open a new window for me.
- Then I can drag-n-drop all the panes I need from the old window to the new
- then I can remove the original pane created in the new window

which works! But, well, something more intuitive would be very good to have.

**Comment by mattrose** [comment]
https://lazka.github.io/pgi-docs/Gtk-3.0/classes/Notebook.html#Gtk.Notebook.set_tab_detachable is the call we want to use, but there's some work on top, I think

**Comment by boyska** [comment]
> can you actually drag tabs from one window to another? doesn't work for me on Xubuntu 20.04.

I can, if I create the second window with `ctrl+shift+N`. Doesn't work if I run `terminator` twice.

**Comment by mattrose** [comment]
relevant python sample code: https://stackoverflow.com/a/56377756
