### ISSUE TITLE
Command-line option to unhide previously hidden Terminator

### ISSUE THREAD

**Issue by UnsolvedCypher** [gnome-terminator/terminator#304]
In Wayland, applications cannot register global hotkeys, so once the Terminator window gets hidden with the "hide window" hotkey, it cannot be unhidden with a hotkey. For Guake, I can bind a shortcut to `guake -t` in my desktop environment which will unhide a previously hidden window, and I would like to do something similar in Terminator. Otherwise, the hiding functionality is unusable on Wayland.

**Comment by mattrose** [comment]
That is a great idea.  I knew that this was a problem on Wayland and I've been desparately trying to think of a way to fix that, and this is just the idea I needed.

**Comment by mattrose** [comment]
@UnsolvedCypher would you mind trying out the PR attached to this issue?

**Comment by UnsolvedCypher** [comment]
@mattrose The hiding functionality does not seem to be working for me in the first place (I set the hide keybinding and it does not hide, and I have tried a number of different keybindings). Is there some additional information I can provide? Logs or something?

**Comment by mattrose** [comment]
If you have a fresh config it should be Ctrl-Alt-A, there's some weirdness in that code to do with stripping the shift key that I don't understand.  If you run `terminator` on the command line it should be able to tell you if it was able to bind the key or not.

**Comment by UnsolvedCypher** [comment]
Hmm when I run terminator on the command line I don't see any output on startup (this is with a clean config).

**Comment by mattrose** [comment]
Does it hide now when you hit Ctrl-Alt-A?

When it's unable to bind it usually spits out `Unable to bind hide_window key, another instance/window has it.`

Did you bind the same key combo to your window manager for unhiding?

**Comment by mattrose** [comment]
This works for me, I'm just gonna merge
