### ISSUE TITLE
terminator-2.0.1: vertical separator too big

### ISSUE THREAD

**Issue by Massimo-B** [gnome-terminator/terminator#305]
On Gentoo I updated from
x11-terms/terminator-1.92-r2
to
x11-terms/terminator-2.0.1

After that the vertical splitter is bigger than the horizontal splitter eventhouth the "separator size" is -1. Both should be a thin 1 or 2 px line. The horizontal line looks fine just as before the update.

**Comment by mattrose** [comment]
This should be fixed as of #247.
