### ISSUE TITLE
Add a 'clear terminal' function

### ISSUE THREAD

**Issue by pwujek** [gnome-terminator/terminator#306]
Add an affordance to clear all of the output in a terminal panel. 

Why? When a command is streaming output to the terminal it is sometimes helpful to be able to clear out old output so that new output will be easily apparent, but at those times it is not possible to enter a bash `clear` or equivalent command.

This function could be provided via a key sequence or right-click menu option or some other affordance.

**Comment by mattrose** [comment]
Hook this Vte.Terminal method to a keypress https://lazka.github.io/pgi-docs/Vte-2.91/classes/Terminal.html#Vte.Terminal.reset

**Comment by mattrose** [comment]
I just went to add this to the list of keybindings, and discovered it was already there.
