### ISSUE TITLE
Terminator does not read config file from /etc/xdg directory 

### ISSUE THREAD

**Issue by daniruiz** [gnome-terminator/terminator#308]
Hi!
I'm a Kali Linux developer. In our OS We see lots of people using this amazing terminal, thus I'd like to include by default a basic config file for terminator, in order to provide our color-scheme for the users that opt to install this terminal. Adding config files inside the user's directory is something we want to highly prevent so it'd be nice terminator could use `/etc/xdg/terminator/config` as the fallback settings file.

Following the "XDG Base Directory Specification":
> If $XDG_CONFIG_DIRS is either not set or empty, a value equal to /etc/xdg should be used
https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html

**Comment by mattrose** [comment]
Good idea.

**Comment by daniruiz** [comment]
Awesome! thank you :wink:
