### ISSUE TITLE
how to change colour of the tabs?

### ISSUE THREAD

**Issue by alevikpes** [gnome-terminator/terminator#313]
Hi! I am trying to change the colour of the tabs, particularly the contrast between the active and the passive tabs, since they look the same in my case. I do not see any option in the config for this. Is it possible to do at all? I use Ubuntu 18.04.

**Comment by mattrose** [comment]
The color of the tabs is controlled by the GTK theme.  There is a strip at the base which changes color to try and hilight the active tab.

**Comment by alevikpes** [comment]
Thank you. I was able to change via the theme.

**Comment by pedroflor** [comment]
> Thank you. I was able to change via the theme.

Hey @alevikpes ...
could you please show how you changed the colour of the tabs?
Thanks in advance.

**Comment by pedroflor** [comment]
@mattrose : could you please elaborate how to achieve the tab highlight?
Thanks a lot!

**Comment by lsem** [comment]
I think changing colors of the tabs in straightforward way would be great feature.
I used in iTerm and that is probably the only feature I miss from it in Terminator.

What do you think? Is there any reason why it should be in Terminator?

**Comment by pedroflor** [comment]
Not an issue, just a little help to anyone looking to change the visual of their TABs
Borrowed from: 
https://www.preining.info/blog/2020/03/de-uglify-gtk3-tabs-of-terminals/
http://blog.nabam.net/workstation/2017/09/15/terminator_tabs/

@mattrose: Could you add an entry in Documentation?

Here is my config:
`~/.config/gtk-3.0/gtk.css`
```

/* Color of inactive TAB */
notebook tab {
    padding: 0.4em;
    border: 0;
    border-color: #444;
    border-style: solid;
    border-width: 1px;
}

/* Color of active TAB */
notebook tab:checked {
    border-color: #76C802;
    border-width: 1px;
}

/* Color of text's TAB */
notebook tab:checked label {
    color: #ffffff;
    font-weight: 500;
}

/* Color of "x" close button */
notebook tab button {
    padding: 0;
    background-color: transparent;
    color: #ffffff
    border-width: 1px;
}

/* Color of "x" border's close button */
notebook tab button:hover {
  padding: 0;
  background-image: none;
  border-color: #00b0ff;
  border-style: solid;
  border-width: 1px;
}
```

Here is the resutl:
![image](https://user-images.githubusercontent.com/3332674/122074748-79c3e780-cdc7-11eb-8405-3295ed1ad36a.png)

**Comment by mattrose** [comment]
Thanks so much for figuring this out. @pedroflor

**Comment by alevikpes** [comment]
> > Thank you. I was able to change via the theme.
> 
> Hey @alevikpes ...
> could you please show how you changed the colour of the tabs?
> Thanks in advance.

Hi! I installed the gnome tweaks, where they have a few extra themes for windows. It is not very detailed, but was good enough for me.

![Screenshot from 2021-07-04 23-02-38](https://user-images.githubusercontent.com/3097359/124399472-06edc280-dd1c-11eb-9871-85b1deba2c83.png)
