### ISSUE TITLE
Shortcuts don't work in non-default keyboard layout

### ISSUE THREAD

**Issue by dnohales** [gnome-terminator/terminator#315]
I noticed this strange issue where on a multi keyboard layout setup (Spanish and English for my case), Terminator shortcuts don't work if you have the non-default keyboard layout selected. That is, for clarity:

If you have in GNOME Control Center the following layouts:

1. Spanish (Spain)
2. English (US)

Shortcuts only works if you have "Spanish (Spain)" selected.

But if you have the following layouts (that is, with different order):

1. English (US)
2. Spanish (Spain)

Shortcuts only works if you have "English (US)" selected.

Also tried with different configurations (like 3 or more layouts) with the same result. Shortcuts in `gnome-terminal` work just fine in any selected layout.

I'm running Terminator 2.0.1 in Fedora 32 on X11.

**Comment by dantuin** [comment]
same problem - running 2.0.1 Fedora 33 X11

**Comment by avma** [comment]
Same with Linux Mint 20.1 English Hebrew...

**Comment by mattrose** [comment]
Hmm, I can't seem to reproduce this without an alternate keyboard I think.

can you run `terminator -d -u --debug-class=Terminal --debug-method=on_keypress` and try the failing shortcuts again, and see what is output to the terminal?

**Comment by dantuin** [comment]
For me it's fixed in 2.1.0

**Comment by dnohales** [comment]
True! Just updated the 2.1.0 in Fedora 33 and the problem is gone. Thanks.

**Comment by lam015** [comment]
not working in terminator 2.1.1
after running in debug mode with; `terminator -d -u --debug-class=Terminal --debug-method=on_keypress`
there is messages like `Terminal::on_keypress: Terminal::on_keypress: lookup found: 'split_vert'` when in default (englush) layout, and nothing when hotkeys are pressed in another layout
what can i do to fix it
thanks

**Comment by Heesz** [comment]
@lam015 Same problem

**Comment by mukhumaev** [comment]
@lam015 Same problem
