### ISSUE TITLE
How to get some kind pane id (on a bash shell) for each terminator pane?

### ISSUE THREAD

**Issue by evandrocoan** [gnome-terminator/terminator#316]
For example, I can:
1. Split my `terminator` window into multiple panes horizontally or vertically
1. Open several tabs or windows

I would like to get an unique id for each terminator `pane`, so I can use it on my ssh script to connect to a remote tmux session over ssh. For example,
```
File: ~/.config/terminator/config
[profiles]
  [[default]]
    exit_action = restart
    login_shell = True
    use_custom_command = True
    custom_command = ''' ssh -t root@machine 'tmux attach -t $TERMINATOR_ID || tmux new $TERMINATOR_ID' '''
```

I would use this combined with a saved layout of 10 tabs. Then, I am always connected to my remote server, even when the connection fails or I open a new window with the same layout.

The problem is that I need a variable like `"$TERMINATOR_ID"` which identify my terminator `pane`. So each `pane` connects to the correct `tmux` session when I open a new terminator window using a saved layout or just when my remote ssh connection disconnect/reconnect.

Is there some environment variable each terminator `pane` get associated? I could use it in my script as my `"$TERMINATOR_ID"` to create/connect with the remote tmux session.

**Comment by evandrocoan** [comment]
I think I found that `$TERMINATOR_UUID` works for this. This is my full command for my `tmux` remote thing:  
```shell
File: ~/.config/terminator/config
[profiles]
  [[default]]
    exit_action = restart
    login_shell = True
    use_custom_command = True
    custom_command = '''set +x; \
      export TERMINATOR_TMUX_UUID="$(printf '%s' "$TERMINATOR_UUID" | cut -c10-20)"; \
      sshlogin="root@10.0.0.1"; \
      runterminatorthingslocal() { \
        local counter=0; \
        while [[ true ]]; \
        do counter=$(( (counter+1) % 30 + 1 )); \
          sleeptime=$(( (RANDOM % 30 + 1) * counter )); \
          if (( counter < 2  )); \
          then \
            printf '%s - Connecting ssh "%s" (press something and enter to exit to the local machine %s)... \n' "$(date)" "$sshlogin" "$TERMINATOR_TMUX_UUID"; \
            ssh -C -o ConnectTimeout=10 -t "$sshlogin" "tmux a -t 'username-$TERMINATOR_TMUX_UUID' || tmux new -s 'evandro-$TERMINATOR_TMUX_UUID'; bash"; \
          else \
            ssh -q -o ConnectTimeout=10 -t "$sshlogin" "tmux a -t 'username-$TERMINATOR_TMUX_UUID' || tmux new -s 'evandro-$TERMINATOR_TMUX_UUID'; bash" 2> /dev/null; \
          fi; \
          printf '%s/%s seconds. ' "$counter" "$sleeptime"; \
          answer=""; \
          read -t "$sleeptime" answer; \
          if [[ "w$answer" != "w" ]]; \
          then \
            break; \
          fi; \
        done; \
      }; \
      runterminatorthingslocal; \
      bash;'''
```

**Comment by mattrose** [comment]
Does this mean I can close this one?

**Comment by evandrocoan** [comment]
Sure. Just do not remove the `$TERMINATOR_UUID` on future versions of `terminator`, as it was really useful and solved this problem easily. After experimenting, each terminator's `pane` has its own `$TERMINATOR_UUID`. And when a layout is saved, each `$TERMINATOR_UUID` is also saved. This is quite useful because even after closing terminator, I can come back to the same old `tmux` sessions as the `$TERMINATOR_UUID` did not changed.
