### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'get_toplevel'

### ISSUE THREAD

**Issue by evandrocoan** [gnome-terminator/terminator#318]
I am trying to run `remotinator`, from inside terminator shell, but it keeps failing with:
```
$ python3 --version
Python 3.8.2

$ /usr/share/terminator/remotinator --version
remotinator 1.91

$ echo $TERMINATOR_UUID; /usr/share/terminator/remotinator get_tab_title
urn:uuid:e70a4348-5bda-47e0-998f-a4f058924c4f

Traceback (most recent call last):
  File "/usr/share/terminator/remotinator", line 82, in <module>
    func(uuid, options)
  File "/usr/share/terminator/terminatorlib/ipc.py", line 195, in _exec
    func(proxy, *args, **argd)
  File "/usr/share/terminator/terminatorlib/ipc.py", line 251, in get_tab_title
    print(session.get_tab_title(uuid))
  File "/usr/lib/python3/dist-packages/dbus/proxies.py", line 72, in __call__
    return self._proxy_method(*args, **keywords)
  File "/usr/lib/python3/dist-packages/dbus/proxies.py", line 141, in __call__
    return self._connection.call_blocking(self._named_service,
  File "/usr/lib/python3/dist-packages/dbus/connection.py", line 652, in call_blocking
    reply_message = self.send_message_with_reply_and_block(
dbus.exceptions.DBusException: org.freedesktop.DBus.Python.AttributeError: Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/dbus/service.py", line 711, in _message_cb
    retval = candidate_method(self, *args, **keywords)
  File "/usr/share/terminator/terminatorlib/ipc.py", line 179, in get_tab_title
    window = terminal.get_toplevel()
AttributeError: 'NoneType' object has no attribute 'get_toplevel'
```

**Comment by mattrose** [comment]
Hmm, is dbus enabled on the parent terminator window?  I'll take a look at this in a bit.

**Comment by evandrocoan** [comment]
I think dbus is enabled. How can I check this?

I only have this problem with my terminator window's I loaded for saved layout (Alt+L). If I open a new fresh window, it works fine:
```
$ echo $TERMINATOR_UUID; /usr/share/terminator/remotinator get_tab_title                                                                       
urn:uuid:f3c669b6-fdd9-4ff3-aa57-9d6689e8a60b
evandro@Pc: ~
```

**Comment by mattrose** [comment]
Oh, interesting.  I'm going to have to look at the code on my linux machine.  (My mac doesn't have dbus enabled), so I'm not going to be able to look at this right now, but I will try and figure it out as soon as I can.

**Comment by evandrocoan** [comment]
I was trying to use this feature for my other issue https://github.com/gnome-terminator/terminator/issues/316 - How to get some kind pane id (on a bash shell) for each terminator pane?

But, I as managed to fix that by using `$TERMINATOR_UUID`, I have no use for `remotinator` right now.

I just tried creating a new fresh layout and opening it with Alt+L but the problem did not happened. 

So I think my uuid of my current saved layout could be broken?

If you are interested, these are my layouts I am using now: https://github.com/evandrocoan/dotfiles/blob/b2a706b96310f47fa58657a58ef4f8131f771b50/.config/terminator/config#L1

I tested this problem with the RootLayout and Ubuntu19 layout.

**Comment by mattrose** [comment]
Root layout will not work, because it cannot connect to the user dbus session.

Ubuntu19Layout works fine for me.  (Well, it doesn't connect to your IP, but once it fails the command works fine).  Are you running remotinator on the remote IP?  If so, that's probably where your problem lies, as it's connecting to the dbus server on the remote machine, which has no idea about the terminator session running on your desktop

**Comment by evandrocoan** [comment]
I just tried again with Ubuntu19Layout (which did not connected to the remote machine because it is shutdown, so if fallback to running on my own computer).

But when I tried to call remotinator the problem was the same.
```
qua 30 dez 2020 20:38:07 -03 - Connecting ssh "root@10.3.50.192" (press something and enter to exit to the local machine 66fda826-dc)... 


ssh: connect to host 10.3.50.192 port 22: No route to host
3/52 seconds. d
365 20:38:29 User@LocalPc:(master)~$ echo $TERMINATOR_UUID; /usr/share/terminator/remotinator get_tab_title
urn:uuid:66fda826-dc0e-4e9c-99da-8af599e01370
Traceback (most recent call last):
  File "/usr/share/terminator/remotinator", line 82, in <module>
    func(uuid, options)
  File "/usr/share/terminator/terminatorlib/ipc.py", line 195, in _exec
    func(proxy, *args, **argd)
  File "/usr/share/terminator/terminatorlib/ipc.py", line 251, in get_tab_title
    print(session.get_tab_title(uuid))
  File "/usr/lib/python3/dist-packages/dbus/proxies.py", line 72, in __call__
    return self._proxy_method(*args, **keywords)
  File "/usr/lib/python3/dist-packages/dbus/proxies.py", line 141, in __call__
    return self._connection.call_blocking(self._named_service,
  File "/usr/lib/python3/dist-packages/dbus/connection.py", line 652, in call_blocking
    reply_message = self.send_message_with_reply_and_block(
dbus.exceptions.DBusException: org.freedesktop.DBus.Python.AttributeError: Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/dbus/service.py", line 711, in _message_cb
    retval = candidate_method(self, *args, **keywords)
  File "/usr/share/terminator/terminatorlib/ipc.py", line 179, in get_tab_title
    window = terminal.get_toplevel()
AttributeError: 'NoneType' object has no attribute 'get_toplevel'

365 20:38:33 User@LocalPc:(master)~$ 
```

I do not have remotinator installed on the remote machine. The Ubuntu19 I was trying to connect is the server version of Ubuntu, so it does not have a user interface (neither I installed one). I just started it up to confirm it:
```
365 23:47:55 root@ubuntu-server-19:(master)~# dpkg -l | grep terminator
365 23:48:00 root@ubuntu-server-19:(master)~# dpkg -l | grep minator                            
365 23:48:03 root@ubuntu-server-19:(master)~# dpkg -l | grep nator                              
365 23:48:06 root@ubuntu-server-19:(master)~# 
```

**Comment by mattrose** [comment]
Weird, the exact same thing works on my desktop just fine.  What OS/Linux distro are you running?

**Comment by evandrocoan** [comment]
I am using `20.04.1 LTS` with XFCE 4.14:
```
$ cat /etc/os-release 
NAME="Ubuntu"
VERSION="20.04.1 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.1 LTS"
VERSION_ID="20.04"
```

If you are using the same `~/.config/terminator/config` as I am, them, may be there is something somewhere else causing this.

How to restart the terminator dbus after editing this?
```python
File: terminatorlib/terminator.py
212:     def find_terminal_by_uuid(self, uuid):
213:         """Search our terminals for one matching the supplied UUID"""
214:         print('searching self.terminals for: %s, %s' % (uuid, self.terminals))
215:         for terminal in self.terminals:
216:             dbg('checking: %s (%s)' % (terminal.uuid.urn, terminal))
217:             if terminal.uuid.urn == uuid:
218:                 return terminal
219:         return None
```

I tried adding some debug code, but the changes are not reloaded when terminator is restarted.

**Comment by mattrose** [comment]
You need to make sure that all running instances of terminator are killed.  If there is a running instance, if you run terminator from the WM or the terminal, it will just launch a new window on the running instance.

Make sure by running `ps auxw | grep terminator` or your favourite equivalent.

It got me too, when I first started working on terminator

**Comment by evandrocoan** [comment]
Thanks. Now I got it working. The only problem is that the messages which are printed on the `dbus` side as:
```
File: terminatorlib/terminator.py
212:     def find_terminal_by_uuid(self, uuid):
213:         """Search our terminals for one matching the supplied UUID"""
214:         dbg('searching self.terminals for: %s, %s' % (uuid, self.terminals))
215:         raise
216:         for terminal in self.terminals:=
```

Are not show on the stderr/stdout of my terminal (which run the commando `echo $TERMINATOR_UUID; /usr/share/terminator/remotinator get_tab_title`).

Only the messages not on the `dbus` side as the following are printed:
```
function::with_proxy: dbus client call: get_window_title (/usr/share/terminator/terminatorlib/ipc.py:194)
function::with_proxy: dbus client call: get_tab (/usr/share/terminator/terminatorlib/ipc.py:194)
function::with_proxy: dbus client call: get_tab_title (/usr/share/terminator/terminatorlib/ipc.py:194)
noclass::<module>: remotinator starting up, version 1.91 (/usr/share/terminator/remotinator:50)
bus <dbus._dbus.SessionBus (session) at 0x7f8d4a9755e0>
```

**Comment by mattrose** [comment]
tbh, I'm not quite sure.  I've never actually looked into this.  Just as a guess, you would grab the bus name and use something like https://dbus.freedesktop.org/doc/dbus-monitor.1.html to see what messages are passing back and forth over that bus.

**Comment by evandrocoan** [comment]
I managed to fix it by replacing `file=sys.stderr` by `file=open("/tmp/output.txt", "a")` on the debug function:
```python
File: terminatorlib/util.py
44: def dbg(log = ""):
45:     """Print a message if debugging is enabled"""
46:     if DEBUG:
...
67:             print("%s::%s: %s%s" % (classname, method, log, extra), file=open("/tmp/output.txt", "a"))
...File: terminatorlib/util.py
71: def err(log = ""):
72:     """Print an error message"""
73:     try:
74:         print(log, file=open("/tmp/output.txt", "a"))
```

Then, I just open the file `/tmp/output.txt` to see the contents of everything `dbus` or not, as the are all put togheter.

**Comment by mattrose** [comment]
nice.  What exactly are you trying to accomplish?

**Comment by evandrocoan** [comment]
There is this debug code:
```python
File: terminatorlib/terminator.py
212:     def find_terminal_by_uuid(self, uuid):
213:         """Search our terminals for one matching the supplied UUID"""
214:         print('searching self.terminals for: %s, %s' % (uuid, self.terminals))
215:         for terminal in self.terminals:
216:             dbg('checking: %s (%s)' % (terminal.uuid.urn, terminal))
```

I was trying to check why is is not finding my terminator window by its uuid.

After comparing the output from a window which works:
```
$ echo $TERMINATOR_UUID; /usr/share/terminator/remotinator get_tab_title                                                                        
urn:uuid:a3d1864b-0407-4a2a-8c5f-bc1bdbe4df87
bus <dbus._dbus.SessionBus (session) at 0x7fc5b6e16770>
None

Terminator::find_terminal_by_uuid: searching self.terminals for: urn:uuid:a3d1864b-0407-4a2a-8c5f-bc1bdbe4df87 (/usr/share/terminator/terminatorlib/terminator.py:214)
Terminator::find_terminal_by_uuid: checking: urn:uuid:a3d1864b-0407-4a2a-8c5f-bc1bdbe4df87 (<terminal.Terminal object at 0x7f282d900b40 (terminatorlib+terminal+Terminal at 0x10dd160)>) (/usr/share/terminator/terminatorlib/terminator.py:217)
```

Against the one which did not worked:
```
$ echo $TERMINATOR_UUID; /usr/share/terminator/remotinator get_tab_title                                                                        
urn:uuid:b7574b1f-a495-461b-96fb-118567954651
bus <dbus._dbus.SessionBus (session) at 0x7fe9ae606630>
Traceback (most recent call last):
  File "/usr/share/terminator/remotinator", line 82, in <module>
    func(uuid, options)
  File "/usr/share/terminator/terminatorlib/ipc.py", line 199, in _exec
    func(proxy, *args, **argd)
  File "/usr/share/terminator/terminatorlib/ipc.py", line 255, in get_tab_title
    print(session.get_tab_title(uuid))
  File "/usr/lib/python3/dist-packages/dbus/proxies.py", line 72, in __call__
    return self._proxy_method(*args, **keywords)
  File "/usr/lib/python3/dist-packages/dbus/proxies.py", line 141, in __call__
    return self._connection.call_blocking(self._named_service,
  File "/usr/lib/python3/dist-packages/dbus/connection.py", line 652, in call_blocking
    reply_message = self.send_message_with_reply_and_block(
dbus.exceptions.DBusException: org.freedesktop.DBus.Python.AttributeError: Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/dbus/service.py", line 711, in _message_cb
    retval = candidate_method(self, *args, **keywords)
  File "/usr/share/terminator/terminatorlib/ipc.py", line 182, in get_tab_title
    window = terminal.get_toplevel()
AttributeError: 'NoneType' object has no attribute 'get_toplevel'

Terminator::find_terminal_by_uuid: searching self.terminals for: urn:uuid:b7574b1f-a495-461b-96fb-118567954651 (/usr/share/terminator/terminatorlib/terminator.py:214)
Terminator::find_terminal_by_uuid: checking: urn:uuid:a3d1864b-0407-4a2a-8c5f-bc1bdbe4df87 (<terminal.Terminal object at 0x7f282d900b40 (terminatorlib+terminal+Terminal at 0x10dd160)>) (/usr/share/terminator/terminatorlib/terminator.py:217)
```

Their difference is their UUID.

On this examples, I used tmux. The one which worked, was outside tmux, but when I am inside tmux, it does not work.

I think that using tmux is easier than using my `Ubuntu19Layout` because they both reproduce the problem and the tmux one uses only 1 tab instead of 10.

It looks like that just by the fact that I am inside tmux, the terminator uuid changes from `uuid:a3d1864b-0407-4a2a-8c5f-bc1bdbe4df87` to `urn:uuid:b7574b1f-a495-461b-96fb-118567954651`.

When tmux is looking for an uuid, it is looking for `urn:uuid:b7574b1f-a495-461b-96fb-118567954651` when inside tmux. But is only finds `urn:uuid:a3d1864b-0407-4a2a-8c5f-bc1bdbe4df87`.

When it is outside tmux, it does look for `urn:uuid:a3d1864b-0407-4a2a-8c5f-bc1bdbe4df87` and it finds it.

The question would be why the uuid is changing when inside tmux.

**Comment by mattrose** [comment]
Wow, that was a good find.  There might be something within your tmux configuration which is resetting the $TERMINATOR_UUID env var? Or tmux itself might clear out some env variables?  I don't use tmux very much, so I'm not too clear on how tmux spawns new sessions.  btw, going to bed now.

**Comment by evandrocoan** [comment]
I am going to bed too. For now, I will leave this as it is because I am not using `remotinator` for now.
