### ISSUE TITLE
Saving a layout after changing it, it correctly updates the config file but does not update the UI

### ISSUE THREAD

**Issue by evandrocoan** [gnome-terminator/terminator#319]
If I:
1. Add some new split in a existing and already saved layout
1. Go to Preferences -> Layout
1. Select the correct layout
1. And hit the save button

The new layout changes are correctly saved to the config file `~/.config/teminator/config`, but the UI is not updated with those changes. This leads me to think they were not saved, while they were.

![image](https://user-images.githubusercontent.com/5332158/101299020-48160680-380f-11eb-8cd9-d2d9f5160771.png)

**Comment by mattrose** [comment]
I hate UI code.  I probably need to reload the Layouts pane after save.

**Comment by mattrose** [comment]
While spelunking through the code, I realized that you can refresh the layout pane by switching to another layout, and then back again.

**Comment by evandrocoan** [comment]
Thanks for fixing it!
