### ISSUE TITLE
terminator version 1.92-1 won't launch from whisker menu (arch XFCE)

### ISSUE THREAD

**Issue by MortalGoddess** [gnome-terminator/terminator#32]
When using the Open terminal here option in the xfce whisker menu, and with Terminator as my preferred terminal it fails to open the terminal. This works as intended and fine as 1.91-1, and downgrading does result in the intended result.
![image](https://user-images.githubusercontent.com/43297317/79824560-83d58c00-8364-11ea-9627-2f8ab21cf470.png)
![image](https://user-images.githubusercontent.com/43297317/79824592-9bad1000-8364-11ea-8d90-efa9625e8896.png)

**Comment by hirowatari** [comment]
Also an arch user.  After upgrading from 1.91-6 to 1.92-1, I got the following error:
```bash
$ terminator
Traceback (most recent call last):
  File "/usr/bin/terminator", line 48, in <module>
    import terminatorlib.optionparse
  File "/usr/lib/python3.8/site-packages/terminatorlib/optionparse.py", line 24, in <module>
    from . import config
  File "/usr/lib/python3.8/site-packages/terminatorlib/config.py", line 75, in <module>
    from configobj import ConfigObj, flatten_errors
ModuleNotFoundError: No module named 'configobj'

```

Thanks for your work on Terminator and please let me know if I can do anything else to help debug the issue.  Downgrading fixed it for now.

**Comment by ErwinJunge** [comment]
This might very well be an Arch Linux packaging issue. The dependency on configobj is specified in https://github.com/gnome-terminator/terminator/blob/master/setup.py#L237, however `pacman -Si terminator` returns this: 

`Depends On      : gsettings-desktop-schemas  libkeybinder3  libnotify  python-cairo  python-dbus  python-psutil  python-gobject  vte3  xdg-utils`

I've fixed it locally by installing configobj using `pacman -S python-configobj`

**Comment by ErwinJunge** [comment]
A bug in the Arch tracker has apparently already been filed: https://bugs.archlinux.org/task/66332?project=5&string=terminator

**Comment by MortalGoddess** [comment]
> This might very well be an Arch Linux packaging issue. The dependency on configobj is specified in https://github.com/gnome-terminator/terminator/blob/master/setup.py#L237, however `pacman -Si terminator` returns this:
> 
> `Depends On : gsettings-desktop-schemas libkeybinder3 libnotify python-cairo python-dbus python-psutil python-gobject vte3 xdg-utils`
> 
> I've fixed it locally by installing configobj using `pacman -S python-configobj`

This fix also fixed the initial issue, but introduced a bug with the transparency no longer working.

**Comment by lazyfrosch** [comment]
Dependencies might have to be fixed in some distributions, but that is not some change we did with 1.92...

**Comment by lazyfrosch** [comment]
Also see #31 

@MortalGoddess regarding transparency, this could be an issue with XFCE, but I haven't tested it yet.

Can you open a separate issue and describe your environment?
