### ISSUE TITLE
Middle click does not paste selected text

### ISSUE THREAD

**Issue by jehutyy** [gnome-terminator/terminator#320]
On archlinux with `terminator 1.92` middle mouse doesn't paste selected string but primary clipboard (*i.e.* string copied with ctrl+shift+c).

It seems to be a regression since, if I remember correctly, this has already been fixed in previous PR.

**Comment by mattrose** [comment]
It's configurable now.  I'm not sure whether it was merged in before or after 1.92, but there's a radio button in prefs for it now.

**Comment by mattrose** [comment]
It was fixed by #135 but that is not in 1.92, only 2.0.1.

**Comment by jehutyy** [comment]
Ok I see that Putty paste option thank you very much.

Nonetheless how can I get back old behavior which is middle mouse click paste primary buffer ?

**Comment by mattrose** [comment]
Sorry, misunderstood your problem.  I think this is the commit you're looking for 

https://github.com/gnome-terminator/terminator/commit/fe9e041b6178d89b8272d07476f288d703a9509f

Again, I think this was fixed in 2.0 not 1.92

**Comment by jehutyy** [comment]
Allright thank you very much ! I'll have a look ;)
