### ISSUE TITLE
add "switch profile" command to remotinator

### ISSUE THREAD

**Issue by Codeberg-AsGithubAlternative-buhtz** [gnome-terminator/terminator#321]
I would like to have different profiles (fore- and background colors) for different users and different locations depending on the bash promt `PS1`.
e.g

- "user"
- "admin@serverA"
- "user@serverA"
- "root"

etc

Is there such a way with terminator?

**Comment by mattrose** [comment]
Nope.  I was hoping there would be a remotinator command that could switch profiles, but not as it stands.
