### ISSUE TITLE
A bug with prefrences

### ISSUE THREAD

**Issue by Bipul-Harsh** [gnome-terminator/terminator#327]
# A bug and a problem too

I open the preference menu in terminator and there I checked "paste-like PuTTY", but after that, it starts disappearing whenever I click on tap panel and even I reinstall it with

- sudo apt remove terminator
- sudo apt-get install terminator 

the problem is still there. Please help.

**Comment by mattrose** [comment]
What version? what OS? What distro?

**Comment by Bipul-Harsh** [comment]
Actually, the mistake was mine, as in preferences in <i><b>Behaviour</b></i> section I checked <I><b>Hide on loose focus</b></i> which was actually causing that problem.
