### ISSUE TITLE
No (visible) context menu in sway

### ISSUE THREAD

**Issue by dd23** [gnome-terminator/terminator#330]
I'm using sway as a wayland compositor and I have trouble opening the (right-click) context menu in terminator.
I'm on an up-to-date arch linux with kernel 5.9.14 using terminator 2.0.1 and sway 1.5.1. I remember that this has been an issue for a while, so nothing that was recently introduced.

I tried a right-click in the terminator window, the little icon next to the terminator groups, and a dedicated hardware key, but neither opens a visible context menu. The context menu seems to open, though, but it's either "behind" terminator, not rendered correctly/at all, or outside of the screen and I cannot click it. It seems as if I can interact with it though.

I have found a seemingly related sway issue, which might be of interest here:
https://github.com/swaywm/wlroots/issues/1678

I'd be happy to supply more (debug) information, if needed. If this is a configuration issue with terminator and/or sway, I'd be happy if someone could point me to it.

Thanks in advance for your help.

**Comment by mattrose** [comment]
Could be https://bugzilla.gnome.org/show_bug.cgi?id=772096#c10 to do with [Gtk.Menu.popup()](https://lazka.github.io/pgi-docs/#Gtk-3.0/classes/Menu.html#Gtk.Menu.popup)

After a little bit of research it looks very likely.  I'll likely need you to test it out once I can get a PR complete.

**Comment by mattrose** [comment]
Can you try latest master to see if that fixes it?  I did PR #341

**Comment by mattrose** [comment]
Please re-open if #341 didn't fix it

**Comment by dd23** [comment]
Thanks a lot!

I pulled the current master (by now also released as v2.1.0) and can confirm that right-clicking and using the keyboard key now opens the context menu as expected.

Minor issue: If I remember correctly, the tiny button/icon left of the group name / in the top left corner of a terminal was also used to open the context menu. This does currently not work. I'm not sure if I remember this correctly, though. Anyhow, not a big deal.

**Comment by mattrose** [comment]
That opened a different menu (the Broadcast menu).  Can you open a new bug if that one has the same problem?
