### ISSUE TITLE
The Alt+L layout chooser is too small

### ISSUE THREAD

**Issue by evandrocoan** [gnome-terminator/terminator#345]
When I press `Alt+L` on terminator, I get this window:
![image](https://user-images.githubusercontent.com/5332158/103391277-64981c80-4af7-11eb-95b0-94721ceda41b.png)

But it is too small and I can barely see my layouts.

I tried resizing it, but the new size is forgotten on the next time I open it.

**Desktop (terminator 1.91)**
 - OS or Linux Distribution: Ubuntu
 - Version 20.04.1

**Comment by mattrose** [comment]
Weird, this is what I get 
![image](https://user-images.githubusercontent.com/65013/103418895-a9a36980-4b5e-11eb-9631-dc10f6f277e1.png)

**Comment by evandrocoan** [comment]
@mattrose which one is your Desktop Manager? I use XFCE4.
