### ISSUE TITLE
in create_layout, if layout[obj]['type'].lower() == 'window': TypeError: string indices must be integers

### ISSUE THREAD

**Issue by tsat-psv** [gnome-terminator/terminator#356]
Please try moving the terminator config out of the way to see if that solves the
problem.  If it does, and you still want to open the bug, then please attach the
config file to the issue

Fill out as many of these fields as you can

**Describe the bug**
Starting terminator on Ubuntu 18 cases this error:

```bash
$ terminator
Traceback (most recent call last):
  File "/usr/bin/terminator", line 122, in <module>
    TERMINATOR.create_layout(OPTIONS.layout)
  File "/usr/share/terminator/terminatorlib/terminator.py", line 271, in create_layout
    if layout[obj]['type'].lower() == 'window':
```

The same behavior is seen when cloning this repo and manually building, installing and running:

```bash
$ python3 terminator 
Traceback (most recent call last):
  File "terminator", line 129, in <module>
    TERMINATOR.create_layout(OPTIONS.layout)
  File "/opt/terminator/terminatorlib/terminator.py", line 245, in create_layout
    if layout[obj]['type'].lower() == 'window':
TypeError: string indices must be integers
```

**To Reproduce**
Update Ubuntu with apt to latest packages, try to launch terminator. Alt. build from source.

**Expected behavior**
Terminator should start.

**Desktop (please complete the following information):**
 - Ubuntu
 - 18.04.5  (bionic)

**Additional context**
Not sure if this is the config you are asking to include in the description, but it's the one I found that made the least nonsense.

```
cat ./.tx/config
[main]
host = https://www.transifex.com

[terminator.po-terminator-pot--master]
file_filter = po/<lang>.po
minimum_perc = 0
source_file = po/terminator.pot
source_lang = en
type = PO
```

**Comment by mattrose** [comment]
Can you try the command `python3 terminator -d --debug-class=noclass --debug-method='<module>'` and paste the result please?

**Comment by tsat-psv** [comment]
Sure @mattrose, here you go:

```bash
$ python3 terminator -d --debug-class=noclass --debug-method='<module>'
noclass::<module>: Creating a terminal with layout: default
Traceback (most recent call last):
  File "terminator", line 129, in <module>
    TERMINATOR.create_layout(OPTIONS.layout)
  File "/opt/terminator/terminatorlib/terminator.py", line 245, in create_layout
    if layout[obj]['type'].lower() == 'window':
TypeError: string indices must be integers
```

**Comment by mattrose** [comment]
is there a file `$HOME/.config/terminator/config` that exists?

**Comment by tsat-psv** [comment]
@mattrose 
```bash
$ cat $HOME/.config/terminator/config
[global_config]
[keybindings]
[layouts]
  [[default]]
    scrollback_lines = 5000
    [[[child1]]]
      parent = window0
      type = Terminal
    [[[window0]]]
      parent = ""
      type = Window
[plugins]
[profiles]
  [[default]]
    cursor_color = "#aaaaaa"
    scrollback_infinite = True
```

**Comment by mattrose** [comment]
can you remove `$HOME/.config/terminator/config` (or move it to config.old if you want to preserve it), and try launching with that file removed?

**Comment by mattrose** [comment]
alternately, you could try `terminator -g /dev/null` to see if you get the error then.

**Comment by tsat-psv** [comment]
Thanks, I tried that, and it now launches. 🙂
________________________________

**Comment by tsat-psv** [comment]
I'm not sure what caused it, but I did change the history to "unlimited" not too long ago, so I have a feeling the bug is related to that.

**Comment by mattrose** [comment]
Maybe, but that config says your scrollback history is 5000.  I think it may be that there was an error writing out your config file and it got corrupted somehow.

**Comment by tsat-psv** [comment]
Thanks. Maybe check to the config parsing is useful, to have a more graceful fail?
