### ISSUE TITLE
No broadcast menu in sway

### ISSUE THREAD

**Issue by dd23** [gnome-terminator/terminator#357]
I'm using sway as a wayland compositor and I have trouble opening the broadcast menu (the menu that lets you select the terminal group and more on the top left, when clicking the tiny icon).

I'm on an up-to-date arch linux with kernel 5.10.4 using terminator 2.0.1 and sway 1.5.1. This also happens when using the  terminator 2.1.0 release from here (the arch package is not updated yet).
I remember that this has been an issue for a while, so nothing that was recently introduced.

When I click the icon on the top left, I get the following error in the terminal from which I had called terminator and nothing happens.
```
Gdk-Message: 13:28:56.834: Window 0x563b9cd68940 is a temporary window without parent, application will not be able to position it on screen.

(terminator:1093): Gdk-CRITICAL **: 13:28:56.837: gdk_wayland_window_handle_configure_popup: assertion 'impl->transient_for' failed
```

This is probably related to #330 and #341, which covered the right-click context menu.

**Comment by mattrose** [comment]
Can you test out and make sure this works?

**Comment by dd23** [comment]
Works like a charm. 

Thanks a lot for fixing this so quickly! :)

**Comment by mattrose** [comment]
No Problem, Glad you brought this to our attention.
