### ISSUE TITLE
[FR] Option to elide terminal title from the left

### ISSUE THREAD

**Issue by protist** [gnome-terminator/terminator#362]
**Is your feature request related to a problem? Please describe.**
My terminal titles are set to the current working directory. When this is long, or there are many tabs, it is elided from the right. For example, `/usr/lib/python3.9/site-packages/terminatorlib` becomes `/usr/lib/python3.9...`.

**Describe the solution you'd like**
Instead, it would often be more informative to elide from the left, i.e. `...ages/terminatorlib`

**Describe alternatives you've considered**
Alternatively, I could restrict my terminal title to the shallowest directory, e.g. in zsh `%1~`. However, this would frequently remove information unnecessarily.

**Additional suggestions**
Also, I find the ellipsis to take up a fair amount of space

![Screenshot_20210114_174049](https://user-images.githubusercontent.com/646668/104554162-f3786d80-568f-11eb-95d8-ecaca09b4a77.png)

Perhaps there might be a smaller glyph? In addition, is there a way to remove the close button? I always use the keyboard shortcut.

**Comment by mattrose** [comment]
Hmm, we just send the text to the tab, I'm not sure if there's a way for us to tell the tab which text to display when we send it up there.  I'll do some hunting around the API.

**Comment by mattrose** [comment]
If you could find another VTE app that does this it would help me greatly :)

**Comment by mattrose** [comment]
Yeah, this is what we use to set the text https://lazka.github.io/pgi-docs/Gtk-3.0/classes/Notebook.html#Gtk.Notebook.set_tab_label and it doesn't really allow us to specify this.  There's good parts and bad parts to highly leveraging GTK calls, and this is one of the downsides.

**Comment by protist** [comment]
Thanks for the quick reply @mattrose. My random searching brought up [Gtk.Label.props.ellipsize](https://lazka.github.io/pgi-docs/index.html#Gtk-3.0/classes/Label.html#Gtk.Label.props.ellipsize). Is that relevant?

Also, from the link, it doesn't seem like the ellipsis glyph itself is configurable. Do you know if it is possible to hide the close button?

**Comment by mattrose** [comment]
props.ellipsize doesn't seem to be what we want, but I'll poke around a bit.  Thanks for looking that up.  

Holy crap, there's a config variable named `close_button_on_tab` that is not in the preference UI at all, but if you set that to false in your `.config/terminator/config` it will get rid of the close buttons on tabs.  So that'll work for you.

**Comment by mattrose** [comment]
I didn't see anything in the label properties that would do what you want.  I can ask around on IRC, but other than that I'm out of ideas.

**Comment by protist** [comment]
> props.ellipsize doesn't seem to be what we want, but I'll poke around a bit. Thanks for looking that up.
>
> I didn't see anything in the label properties that would do what you want. I can ask around on IRC, but other than that I'm out of ideas.

No worries. I don't really know anything about it; I was just searching for synonyms. Thanks for checking anyway.

> Holy crap, there's a config variable named `close_button_on_tab`

Awesome! That works well!
