### ISSUE TITLE
Background image not showing up on Xubuntu 20.04

### ISSUE THREAD

**Issue by hupmake** [gnome-terminator/terminator#364]
**Describe the bug**
Background image not showing up on Xubuntu 20.04 (terminator v2.1.0), even though one with an acceptable file-type has been selected.

**To Reproduce**
Using Xubuntu 20.04, install terminator v2.1.0, set background image via Preferences.

**Expected behavior**
For the background image to be visible.

**Screenshots**
![image](https://user-images.githubusercontent.com/53275084/104643364-519a5600-567a-11eb-9415-778c754846ef.png)

**Terminator config file**
```
[global_config]
  focus = mouse
[keybindings]
[profiles]
  [[default]]
    background_darkness = 1.0
    background_type = image
    cursor_color = "#aaaaaa"
    scrollback_infinite = True
    background_image = /home/bhupman/Pictures/symbolonly.png
[layouts]
  [[default]]
    [[[window0]]]
      type = Window
      parent = ""
    [[[child1]]]
      type = Terminal
      parent = window0
[plugins]
```

**Desktop (please complete the following information):**
 - OS or Linux Distribution: Xubuntu
 - Version: 20.04.1 LTS

**Comment by mattrose** [comment]
You've set shading to 100% so that you won't see the picture because it's entirely darkened.  Move the slider to something closer to 50% or lower to see the picture

**Comment by hupmake** [comment]
Gotcha. Thanks!
