### ISSUE TITLE
Visual aids

### ISSUE THREAD

**Issue by pedroflor** [gnome-terminator/terminator#367]
**Feature request: Visual Aids**
A picture is worth a thousand words.

Please refer to the image for a more "graphical" description of the request.
![image](https://user-images.githubusercontent.com/3332674/104866290-93dec400-5914-11eb-8bd4-fe40eccb6b8a.png)

Does anybody know how can I achieve that?
I know it's about .css, but some guide will be wonderful.

Thanks for the help!

**Comment by pedroflor** [comment]
Thanks Matt !!!

**Comment by mattrose** [comment]
I'm gonna write a little bit more documentation on this, but I found this page that works well
http://blog.nabam.net/workstation/2017/09/15/terminator_tabs/

**Comment by mattrose** [comment]
added a few gtk css pointers to the FAQ https://github.com/gnome-terminator/docs/blob/master/source/faq.rst
