### ISSUE TITLE
Open in terminal

### ISSUE THREAD

**Issue by fily1212** [gnome-terminator/terminator#368]
Hello, 
A good feature could be implement the possibility to add a voice in the context menu in nautilus file manager called "Open in terminal" or replace the existent.

**Comment by mattrose** [comment]
To add something in the Nautilus File Manager would need access to Nautilus and the wider desktop environment.  Many distros have this functionality (Ubuntu and it's derivatives mainly), but this is not something that is within the scope of Terminator, sorry.

**Comment by fily1212** [comment]
Ok, I understand. Maybe a short workaround in the readme or in the manual could be helpful

**Comment by timhughes** [comment]
@fily1212  I had the same thought https://github.com/timhughes/nautilus-open-terminator
