### ISSUE TITLE
broken profile transparency with 1.92 and XFCE

### ISSUE THREAD

**Issue by MortalGoddess** [gnome-terminator/terminator#37]
Before the 1.92 update I had no issues with transparency, however after 1.92 I no longer have transparency, even if I downgrade to 1.91-6 on arch. 

I have tested that the profile is being loaded, and I can load another profile using the -p flag with no issues, but irregardless of profile, transparency doesn't work.

I don't know what sort of logs I could be able to find, but let me know what more I can do to help narrow down this issue.

**Comment by JAugusto42** [comment]
i try to reproduce here, but heres works fine, how to reproduce?

**Comment by MortalGoddess** [comment]
I don't know more then
Arch XFCE
have transparency working in 1.92-6
Upgrade
No transparency. 

I have done full reinstall of terminator, I have removed the config file and reinstalled terminator, I have even checked that the config file is set to transparent (it is) 

I figured that it is a system issue, but I have no idea what it could be, the toggle is checked on the profile. I checked the toggle on a new profile and that still didn't fix it.

**Comment by JAugusto42** [comment]
i have arch wth xfce too, and transparency here works fine.

**Comment by MortalGoddess** [comment]
Are there config files other then ~/.config/terminator/config I should be looking at or into?
Would sharing my config file here help any as well?

**Comment by mattrose** [comment]
try "terminator -ud" and see if you can find any tracebacks in the debug output.

**Comment by MortalGoddess** [comment]
I don't see anything using that that looks like a problem. using grep to go through the logs gets only 3 hits for background 
`ConfigBase::get_item: ConfigBase::get_item: background_color found in profile default: #300a24
ConfigBase::get_item: ConfigBase::get_item: background_type found in profile default: transparent
ConfigBase::get_item: ConfigBase::get_item: background_darkness found in profile default: 0.7
`
profile doesn't have anything that looks like an error, and trying to find traceback has 0 hits. 

I have attached a log from running, terminator -ud > log 2>&1

[Terminator.log](https://github.com/gnome-terminator/terminator/files/4569640/Terminator.log)

**Comment by lazyfrosch** [comment]
Just to verify, can you use transparency in gnome or xfce terminal? Which both should use VTE as well in the backend

**Comment by MortalGoddess** [comment]
That was it, compositing was disable in my XFCE settings. Thank you for the help.
