### ISSUE TITLE
Update PPA to 2.1.0

### ISSUE THREAD

**Issue by qx-775** [gnome-terminator/terminator#374]
First off I want to **thank you** for terminator. It's an amazing tool that helps me a lot. I find it much more easier to use than tmux because terminator has great documentation.

It has been 20 days since 2.1.0 was released and the ubuntu ppa:mattrose/terminator is still on 2.0.1. I'm just wondering if this ppa will get updated or if I have to build from source to get updates.

Thank you!

**Comment by mattrose** [comment]
Sorry, that's my bad, I'll update it in the next day or so.

**Comment by qx-775** [comment]
Thanks, once updated feel free to close this issue.

**Comment by pktiuk** [comment]
According to Debian freeze [timeline](https://release.debian.org/bullseye/freeze_policy.html) this package even updated won't get into the next stable release.    
That's a shame

**Comment by mattrose** [comment]
The package is already in Debian unstable, so it should go into the next stable release just fine.  @lazyfrosch put it there as soon as it was released.  I'm actually running the package from buster-backports (I think that was the stream) on Ubuntu 20.10.  It installed flawlessly.

**Comment by dkebler** [comment]
https://launchpad.net/~mattrose/+archive/ubuntu/terminator
ppa still does not have 2.1

alternatively
what is the universe package name?   `terminator` in ubuntu focal/20.04 is the old terminator 1.91-4 ,  `gnome-terminator` is not listed.  Do you have to load unstable or backports to get 2.1?

**Comment by qx-775** [comment]
Closing due to no response. Best way to the the latest terminator version on your platform is to compile from python using the instructions. It's actually not a hassle and it compiles fast. Just make sure you use the exact commands to compile from the docs.

**Comment by pacharanero** [comment]
Hi, sorry to bump this issue, but is there any chance that the PPA could be updated to 2.1.0?
Building from Python is certainly possible, but seems pointless having PPAs if that's the recommended route to obtain?
