### ISSUE TITLE
Allow hide title bar as global option

### ISSUE THREAD

**Issue by PietroPate** [gnome-terminator/terminator#377]
**Is your feature request related to a problem? Please describe.**
I am trying to launch a fullscreen terminal together with xtrlock to show cmatrix as background of the lockscreen, however the titlebar shows (respecting the configuration top/bottom) despite the profile being set to hide the title bar.

**Describe the solution you'd like**
A global option to hide the title bar

**Describe alternatives you've considered**
a command line option to hide the title bar would also work

**Comment by mattrose** [comment]
Under Preferences->Profiles in the General Tab there is a "Show Titlebar" checkbox.
You can also set it directly in the config file by setting `show_titlebar` to False
