### ISSUE TITLE
Feature request: move titlebar colors config to profiles, rather than global settings

### ISSUE THREAD

**Issue by tronorama** [gnome-terminator/terminator#379]
When I use completely different color scheme profiles for day and night, one titlebar color scheme ends up looking jarringly out of place with one of these profiles

**Comment by mattrose** [comment]
This *should* be fairly easy, but it might be trickier than just moving the titlebar config in the interface.  Very good idea, thank you!

**Comment by Vulcalien** [comment]
Working on this, a PR should be there tomorrow. All the settings can be moved, except 'Titlebar at bottom'.
