### ISSUE TITLE
Natural Scrolling

### ISSUE THREAD

**Issue by tdrusk** [gnome-terminator/terminator#380]
How would one enable natural scrolling or reverse scrolling?
I currently have this in my .Xmodmap and it works for all applications except Terminator.
`
pointer = 1 2 3 5 4 7 6 8 9 10 11 12`

**Comment by mattrose** [comment]
Hmm, that may be an artifact of the way that we've implemented scrolling.  Can you try installing the vte development packages and see if you can reproduce it in the vte-2.91 app that comes in those packages?

**Comment by mattrose** [comment]
closing for lack of response
