### ISSUE TITLE
regexp/command hyperlink handler

### ISSUE THREAD

**Issue by nojhan** [gnome-terminator/terminator#381]
When debugging code, I find it useful to be able to click on a file path to immediately jump to it _at the indicated line number_.
While there is an easy way in Terminator to capture arbitrary text, it rely on URL plugins, they are only able to capture and handle the file name, but not an additional _line_ argument.

Ideally, it would be easy to add any capturing regexp and connect it to a generic command, with multiple arguments.
For instance, in Rxvt, you can configure a regexp which capture the two arguments which are necessary to open a file at a given line:
```
URxvt.matcher.pattern.2: \\B(/\\S+?\\.py)\\S{2}\\sline\\s(\\d+)
URxvt.matcher.launcher.2: gvim --servername IDE --remote +$2 $1
```
Which enable links such as:
![urxvt_regexp_link_example](https://user-images.githubusercontent.com/285009/107856779-cce25980-6e2a-11eb-83f5-7cd9c61ef450.png)

Of course, it is possible to add several regexp/command pairs, to handle different situations.

Using URL handler plugins is not possible, as the callback is supposed to return an URL without any additional information.
To the best of my knowledge, URIs do not allow for an explicit line number in `file://`.
Additionally, as far I know, programs such as xdg-open cannot process more than one argument, hence rendering the filename/line pair impossible to process that way.

I guess a plugin allowing for configuring many regexp/command pairs would do the job, but I'm unsure how to do that without colliding with the existing URL handling API.

**Comment by mattrose** [comment]
I think this is possible without conflicting with the existing URL handling API, because it doesn't really follow the URL format.

You should be able to write a plugin that just matches the string you're interested in and add an entry to the context menu that will open the file at the specified line.

**Comment by nojhan** [comment]
And would it be possible that way to add visual clue about the underlying link? Just like with regular URLs?

**Comment by nojhan** [comment]
I made a first attempt at making a URL handler plugin (see [my feat+RunCmdOnMatch](https://github.com/nojhan/terminator/tree/feat+RunCmdOnMatch) branch).

However, I faced the following problems:

- The `match` member is a class member, which render impractical the management of several used-defined regexps.
- There is no legit way to return a no-op URL, as `None` will trigger the default URL manager.
- I failed to find doc/examples about how to add a configuration interface in the Preference window (the `custom_commands` plugin even seems to use its own window, triggered from within the contextual menu).

**Comment by mattrose** [comment]
I'm gonna be embarassingly honest here and say I have no idea how to add a configuration interface in the Preference window, and I'm wondering if that was just a feature that was never completed.

I'll take a look at the rest of it soon.  You might just want to create your own popup window to configure the regexes like the custom commands plugin does.  

It looks like a good start, just from a first look at the code.

**Comment by mattrose** [comment]
Thanks so much for doing this, it's always appreciated when people take the initiative and get their hands dirty 😄

**Comment by mattrose** [comment]
This is fixed as part of your commits.  Thank you so much for contributing.
