### ISSUE TITLE
CTRL+A behaviour abnormal

### ISSUE THREAD

**Issue by avsdev-cw** [gnome-terminator/terminator#384]
When pressing CTRL+A, regardless of if terminator is in focus or not, it either hides the primary (ie, first opened) terminator window or displays it if it is already hidden.  If that window is closed the behaviour returns to normal - until the next time you open a new terminator window which then exhibits the same behaviour. Any windows opened between opening the buggy one and closing it perform as expected.

This is a bug that has been around for a number of years, it has a launchpad report here: https://bugs.launchpad.net/terminator/+bug/1703530

I'm surprised it is still in existence in the current version (2.1.0) of terminator given how critical this to a functioning system and since this is the new place to report bugs, I'm opening a ticket here. I'd entirely forgotten about it until I upgraded my system and upgraded terminator (I had it pinned to an earlier version which did not display the bug and it is no longer suitable to do so).

Let me emphasize, this steals the CTRL+A EVERY time it is used REGARDLESS of if terminator is in focus and WITHOUT it being set as a shortcut key (I see CTRL+SHIFT+A is a shortcut by default for hiding/showing the current terminator window, changing or disabling this shortcut has no effect).

**Comment by avsdev-cw** [comment]
Further information on my system:
Debian 11 (Bullseye) [modified BunsenLabs flavor]
Terminator 2.1.0
Openbox 3.6.1 / lightdm 1.26.0

**Comment by avsdev-cw** [comment]
Further investigation, because I never actually checked it, if you change the "hide_window" shortcut to something else (e.g. CTRL+`), it doesn't work

**Comment by mattrose** [comment]
I'll take a look at this soon.  The show/hide on Ctrl-A is actually supposed to work as you describe.  IE, no matter what window has focus, the terminator window is supposed to toggle when you hit Ctrl-A, but there should be a way to disable it if you don't want that behaviour, and I don't see any way of doing that in preferences.

**Comment by mattrose** [comment]
It's supposed to be able to emulate "Quake mode" that other terminals have.

**Comment by avsdev-cw** [comment]
Ah ok, it is very unfortunate that the shortcut chosen is a universally common shortcut for "Select all".

**Comment by mattrose** [comment]
Looking at this further, the default keybinding is actually Ctrl-Alt-A, not Ctrl-A.  And it is configurable in the keybindings preferences.  Can you re-open if this is still a problem for you.

**Comment by avsdev-cw** [comment]
@mattrose Are you sure? Unless I'm wrong, that would conflict with the default keybinding for edit_tab_title keybinding. I can't find a keybinding setting for "quake mode"? The default for hide_window is <Shift><Control><Alt>a and changing that setting seems to fix the issue for me
