### ISSUE TITLE
unremovable background image

### ISSUE THREAD

**Issue by atommaki** [gnome-terminator/terminator#387]
**Describe the bug**
There is no way (on the GUI) to remove the background image once you set it up.

**To Reproduce**

Go to Preferences -> Profiles -> your profile (probably "default") -> Background
choose a background image. As soon as you start a new terminator instance you see the background image, all works fine till this point. Now try to remove this background image in the Preferences. There is no way. You can choose another image, but no option to remove your chosen picture from the setup. 

**Expected behavior**

Should be an option to remove the image from the setup (clear).

BTW: this part of the preferences anyway looks quite confusing, asking for a refactoring. You can choose between "solid color" and "transparent", but you can not choose the color because it's on another tab (colors) and there is no radio button to choose the "background image" option. As soon as you setup a background image even choosing the "solid color" option doesn't remove the background image

**Workaround**
Set the "shade the background image" to 1.0, it makes the image invisible.

**Screenshots**

**Desktop (please complete the following information):**
 - Ubuntu 20.04, teminator 2.1.0

![Screenshot from 2021-02-19 00-16-24](https://user-images.githubusercontent.com/14099928/108434557-24782f00-7248-11eb-90c1-4b5c51b1e648.png)

**Comment by mattrose** [comment]
Are you sure you're using 2.1.0?  I see an entirely different preferences pane in 2.1.0.  The one you see is from 2.0, IIRC.  Here's mine

<img width="745" alt="Screen Shot 2021-02-18 at 6 21 58 PM" src="https://user-images.githubusercontent.com/65013/108434843-4eb0f900-7216-11eb-8ed0-bf69e94cdac5.png">

**Comment by mattrose** [comment]
As you can see, that one makes much more sense, and works as you want it to.

**Comment by atommaki** [comment]
Sorry, my fault. Indeed I was using 2.0.1. It works fine now.
