### ISSUE TITLE
Terminal title-bars are transparent on first start

### ISSUE THREAD

**Issue by jwrdegoede** [gnome-terminator/terminator#392]
**Describe the bug**
I use terminator without window-decorations with terminals in a 2x2 grid. At startup the title-bars for the 4 terminals are transparent, without any text showing in them. Rather then grey or red with the usual title-bar text in them.

**To Reproduce**
I've put a symlink to `/usr/share/applications/terminator.desktop` in `~/.config/autostart/`. I'm also autostarting the "audacious" media-player when I log in.

What I believe is happening is that terminator is relying on a focus-in (or out) event to trigger the first drawing of the title-bars. Since in my case audacious ends up with the initial focus, terminator never gets the focus, so no focus in/out events and thus never draws the title-bars, causing them to appear transparent.

If I manually start terminator instead of having it autostart, this problem does not happen.

**Expected behavior**
Terminator renders the per-terminal title-bars at startu

**Screenshots**
https://fedorapeople.org/~jwrdegoede/Screenshot%20from%202021-02-08%2016-52-39.png

**Desktop (please complete the following information):**
 I'm seeing this on 2 x86_64 machines, One with Fedora 33 + all the latest updates and another which is running Fedora 34 (pre-release) with all the latest updates. I'm using the terminator package provided by the distro in both cases.

**Comment by jwrdegoede** [comment]
I forgot to mention that I can interact with and even start other apps and the title bars stay transparent, they get drawn as soon as I switch focus to terminator once, further strengthening my believe that this is causes by terminator solely relying on focus events to draw the title-bars, without doing an initial draw at startup.

**Comment by mattrose** [comment]
might need an explicit .show, or .queue_draw call.  I'll look into this.

**Comment by jwrdegoede** [comment]
Thanks, let me know if you have a patch which you would like me to test.

For me this is 100% reproducable, but I dunno if you will be able to reproduce it yourself.
