### ISSUE TITLE
Losing focus on a tabbed window will grey out the window

### ISSUE THREAD

**Issue by grazzolini** [gnome-terminator/terminator#393]
**Describe the bug**
When losing focus on a tabbed terminator window, the terminator window will be grayed out. This doesn't happen on a non-tabbed window

**To Reproduce**
Open terminator, create a tab, leave the windows focus

**Expected behavior**
The dimming should work on both regular windows and tabbed ones

**Screenshots**
https://user-images.githubusercontent.com/4093184/108853832-f0916680-75c5-11eb-9d4e-92b20d2bcc74.mp4
![terminator-issue](https://user-images.githubusercontent.com/4093184/108854100-3b12e300-75c6-11eb-8a89-a0ca5f9967f3.png)

**Desktop (please complete the following information):**
 - Arch Linux
 - terminator 2.1.0-1

**Additional context**
No compositor is running, this is plain i3 on Xorg.

**Comment by mattrose** [comment]
fixed in #372

**Comment by grazzolini** [comment]
I'm applying the patch to the Arch package for now.

**Comment by mattrose** [comment]
Thank you!  I'll probably do the same for Fedora.

**Comment by grazzolini** [comment]
Do you have it handy? I'm trying to create it using format-patch, but no luck yet.

**Comment by mattrose** [comment]
it was an ugly patch to try and revert.  It was all in `terminatorlib/terminal.py` so if you just do a diff of the 2.1.0 version of that file and the current master, it *should* just contain that change.  I'll double check

**Comment by mattrose** [comment]
Nope.  The attached patch should do the trick, I generated it by: `git diff 4a91585d3bd2cf2e0c2eb29d55cf7204ee4c581b..01bb33eebc44d8967550236db9883ba798f38440 terminatorlib/terminal.py`

[terminator-patch.txt](https://github.com/gnome-terminator/terminator/files/6029818/terminator-patch.txt)

**Comment by mattrose** [comment]
apparently I've been more productive than I thought :neutral_face:
