### ISSUE TITLE
Clicking on terminator title bars does not focus the terminal belonging to the title-bar

### ISSUE THREAD

**Issue by jwrdegoede** [gnome-terminator/terminator#394]
**Describe the bug**
I use terminator without window-decorations with terminals in a 2x2 grid. So I have 4 terminator managed per-terminal title-bars.

If I'm running a mouse-sensitive app inside the terminal I'm used to clicking on the terminal-title-bar to give that terminal focus to avoid sending a click to the app running in the terminal.

This does not work, I must click inside the terminal to give it focus.

**To Reproduce**
Start terminator with at least 2 terminals in a single tab. Try to switch the focus between the  2 by clicking on their  terminal-title-bars.

**Expected behavior**
Clicking on the terminal-title-bar gives the terminal it belongs to focus.

**Desktop**
I'm seeing this on 2 x86_64 machines, One with Fedora 33 + all the latest updates and another which is running Fedora 34 (pre-release) with all the latest updates. I'm using the terminator package provided by the distro in both cases.

**Comment by mattrose** [comment]
fixed in #372, sorry about that.  I'll see if I can put out a release on it soon as it's causing a lot of bug churn

**Comment by gulshangit** [comment]
Hi Matt

Using terminator with Multiple Tabs, while working on current tab, then remaining tabs gets greyout. So i have espciallt click on other tab, This make me difficult to capra logs parellely. SS below

![Screenshot from 2022-08-01 19-13-49](https://user-images.githubusercontent.com/85386813/182161537-9e000961-e01a-4781-b2cf-84db68e91760.png)
