### ISSUE TITLE
cannot import name 'Validator' from 'validate' | arch community/terminator 2.1.0-2

### ISSUE THREAD

**Issue by DO1JLR** [gnome-terminator/terminator#395]
Hello together

After I just updated my Archlinux, terminator *(``community/terminator 2.1.0-2``)* stopped working and spit out the following message:

```bash
Traceback (most recent call last):
  File "/usr/bin/terminator", line 48, in <module>
    import terminatorlib.optionparse
  File "/usr/lib/python3.9/site-packages/terminatorlib/optionparse.py", line 24, in <module>
    from . import config
  File "/usr/lib/python3.9/site-packages/terminatorlib/config.py", line 77, in <module>
    from validate import Validator
ImportError: cannot import name 'Validator' from 'validate' (/usr/lib/python3.9/site-packages/validate/__init__.py)
```
Something similar happened to me before and I solved it locally with the fix from https://github.com/gnome-terminator/terminator/pull/325

Now I took a closer look and found out that the following line causes the problem for me. *For your information: I have installed Python 3.9.1 and updated arch to the current state via the standard arch package sources.*

https://github.com/gnome-terminator/terminator/blob/23a15ea9e1b2eb355ea5b5e937b7814acea95e7b/terminatorlib/config.py#L77

based on the README at https://pypi.org/project/validator/ I changed line 77 locally to ``from validator import validate`` and since then terminator works clean again.

It seems strange to me that such an error has not been noticed and I could imagine that this is a local or archlinux specific problem. Nevertheless I wanted to inform you about it.

If you like I can also submit this as a pull request similar to https://github.com/gnome-terminator/terminator/pull/325.

Stay healthy! And thanks for terminator. I like to use it very much. :kissing_heart:

**Comment by mattrose** [comment]
This was a problem caused by the packaging of one version of the python-configobj package in Arch Linux, specifically in version 5.0.6-10.  Both the previous version (5.0.6-9), and the subsequent version (5.0.6.r110.g3e2f4cc-1) do not have this problem.  Please make sure you're not running 5.0.6-10 of the arch package.
