### ISSUE TITLE
Terminal loses focus versus tab title

### ISSUE THREAD

**Issue by aplopez** [gnome-terminator/terminator#400]
**Describe the bug**
When clicking on the current tab's title, the terminal loses the focus which is transferred to the title. It is no longer possible to type on the terminal.
Running `terminator -g /dev/null` still behaves as described.

**To Reproduce**
1 - Open at least 2 tabs.

2 - Select a tab by clicking on it and you can type your commands on that terminal.
![Step-2](https://user-images.githubusercontent.com/17848382/110122155-89429600-7dbf-11eb-9aa8-45fe23037246.png)

3 - Click (again) on current tab's title as you just did on step 2.

4 - The terminal loses the focus (it is slightly greyed and the red bar become grey), which is transferred to the tab's title (see the dotted-line box around the title) and you can no longer type on the terminal.
![Step-4](https://user-images.githubusercontent.com/17848382/110122176-9069a400-7dbf-11eb-9175-c38d6bdd026a.png)

5 - Click on the terminal itself, and the focus is transferred from the tab's title back to the terminal. You can again type your commands.

**Expected behavior**
When clicking for a second time (not a double-click) on the tab, the focus should remain on the terminal. This is what seems most logical and what Gnome Terminal does.

**Desktop (please complete the following information):**
 - RHEL7

**Additional context**
Seems to be this same [old bug on Launchpad](https://bugs.launchpad.net/terminator/+bug/1520692) which was never fixed.

**Comment by mattrose** [comment]
So, I think that when you click on the same tab that's associated with the terminal, it transfers focus to the tab itself, not the associated terminal.  I wonder if there's a way to associate just a double-click to the associated tab, and not a single-click.   I may see how gnome-terminal does this.

**Comment by mattrose** [comment]
This is the gnome-terminal fix, apparently:
https://bug746665.bugzilla-attachments.gnome.org/attachment.cgi?id=300270

Not sure how to translate that to python.

**Comment by marktimarev** [comment]
> This is the gnome-terminal fix, apparently:
> https://bug746665.bugzilla-attachments.gnome.org/attachment.cgi?id=300270
> 
> Not sure how to translate that to python.

Thanks, I will try to figure out how implement it

**Comment by marktimarev** [comment]
Yeah, I got it, they hook the event when a tag grabs focus and then push the focus back to the inner terminal back manually.
Going to push a MR soon.

**Comment by mattrose** [comment]
Wow, that's great!  Thanks and looking forward to the PR.

**Comment by marktimarev** [comment]
It was apparently easier than the fix in the gnome-terminal.
It solves the issue for me, please check.
