### ISSUE TITLE
Question - overlaid multiple lines 

### ISSUE THREAD

**Issue by yuriw** [gnome-terminator/terminator#403]
Hello

I started seeing lately overlaid multiple lines in my terms, e.g. multi lines command is very hard to see.
Tried `reset` with not much success.

Wonder if this is a new bug and if there is a terminator specific way how to fix it?

Thx

**Comment by mattrose** [comment]
Hmm, there's been no changes in terminator recently.  Vte is mostly in charge of the actual terminal interactions, so this sounds like a vte problem.  Do you have `vte-2.91`?  Seeing if you can reproduce the problem in that, or gnome-terminal will give you an idea of if there's anything you can do in terminator specifically.

**Comment by mattrose** [comment]
closing for lack of response
