### ISSUE TITLE
Feature request: expose the window and terminal title setting features in context menu

### ISSUE THREAD

**Issue by tronorama** [gnome-terminator/terminator#405]
**Is your feature request related to a problem? Please describe.**
The only "problem" per se is that I never knew that keyboard shortcuts even existed for setting the title of the window ( <kbd>Ctrl + Alt + w</kbd> ) as well as the individual terminal within the window ( <kbd>Ctrl + Alt + x</kbd> ); I only stumbled upon these today via StackExchange. These are very useful shortcuts, and perhaps I'm not the only person completely unaware of them.

**Describe the solution you'd like**
Just to expose the underlying mechanisms with two new entries in the context menu that appears when secondary-clicking inside a Terminator window with one's pointing device. I believe this would immensely help _discoverability_ of these two existing title-setting features.

**Additional context**
I'm including a screenshot of the effects of the keyboard shortcuts and the opened context menu. Alas, when the window is not maximized, the title is not passed to the GNOME Unite extension's title in the top bar, but that's a separate issue (at least Unite picks up the window title of a _maximized_ window).
![terminator-title-options](https://user-images.githubusercontent.com/7062385/111873859-c767ba00-8968-11eb-8fb6-ab39da1f6441.png)

**Comment by mattrose** [comment]
That's an interesting idea.  I'm a little loathe to add too much to the context menu.  If we put every option there that we expose through keyboard shortcuts it would be a really long menu, or a forest of sub-menus.  I'll think on it.

**Comment by mattrose** [comment]
Did a little investigation with a thought to discoverability, and decided on the following.  You can discover that you can set the titlebar title and the tab title by double-clicking on it, and I think that's pretty instinctive.  However there's no way to edit the window title itself without knowing that keystroke, so I just wrote up a patch that adds a "Set window title"  to the context menu.

**Comment by tronorama** [comment]
I didn't know about double-clicking the title within individual panes, but that you for your consideration regarding the main app window title.
