### ISSUE TITLE
Unable to Install from Source

### ISSUE THREAD

**Issue by fray6c** [gnome-terminator/terminator#412]
Hello,
I am running Ubuntu 20.04 and I got python 3.8.3
I've already got Terminator 2.0.1 installed via package manager. 
I wanted to installed/upgrade to v2.1.0 which I understand is only possible to do so via source.

- I've downloaded to code (zip) extracted it. 

- I made sure I had the dependency installed by running
`sudo apt install python3-gi python3-gi-cairo python3-psutil python3-configobj gir1.2-keybinder-3.0 gir1.2-vte-2.91 gettext intltool dbus-x11` 
for which I got the following output 
`Reading package lists... Done
Building dependency tree       
Reading state information... Done
gettext is already the newest version (0.19.8.1-10build1).
python3-configobj is already the newest version (5.0.6-4).
python3-gi is already the newest version (3.36.0-1).
python3-gi-cairo is already the newest version (3.36.0-1).
python3-psutil is already the newest version (5.5.1-1ubuntu4).
gir1.2-keybinder-3.0 is already the newest version (0.3.2-1ubuntu1).
intltool is already the newest version (0.51.0-5ubuntu1).
dbus-x11 is already the newest version (1.12.16-2ubuntu2.1).
gir1.2-vte-2.91 is already the newest version (0.60.3-0ubuntu1~20.04).
0 to upgrade, 0 to newly install, 0 to remove and 0 not to upgrade.`

- But when I run the following 
`python3 terminator --help`  I get:  `You need to install the python bindings for gobject, gtk and pango to run Terminator.`

Am I suppose to run `python3 setup.py build` and `python3 setup.py install --single-version-externally-managed --record=install-files.txt` first??

Thanks

**Comment by mattrose** [comment]
Hmm, if you already have terminator 2.0.1 installed, the dependencies are exactly the same and it should run fine.  Without knowing more about the system it's hard to say why it's not working.

**Comment by fray6c** [comment]
Hi Matt, thanks for the feedback, any suggest on how I go about troubleshooting this?

**Comment by fray6c** [comment]
I will close this. I  realized that `python3` command was pointing at the the Anaconda version of python instead of the default. So by doing `/bin/python3 `I was able to build and install the package.
