### ISSUE TITLE
How to deactivate the middle mouse button paste?

### ISSUE THREAD

**Issue by viertelb** [gnome-terminator/terminator#415]
Not sure if this should be working already. I use Ubuntu 18 and 20 and deactivated paste upon middle mouse button via Gnome Tweaks. This works. But still, in Terminator 2.0.1 the middle button does a paste of the clipboard content. 

I want to deactivate this paste option but cannot find anything in the settings .

**Comment by mattrose** [comment]
This is the first time I've ever heard of somebody asking for this. 

I'll take a look when I get the chance.

**Comment by bvrulez** [comment]
I had a lot of content from a personal email in the clipboard from my second virtual machine, changed to the virtual machine of my bosses where I was on the server via SSH. I scrolled through the terminal. While scrolling, I accidentally touched the scroll button too hard and pasted all of my email into my terminal which generated a lot of entries in the history. Until logging out history is only saved in my memory and not written to a file for everyone. But it was a funny experience. Just sharing for the laughs and the background. Thanks for your awesome work!
