### ISSUE TITLE
Project based layout

### ISSUE THREAD

**Issue by huseyinkozan** [gnome-terminator/terminator#418]
**Is your feature request related to a problem? Please describe.**
Not really a problem, maybe an enhancement.

**Describe the solution you'd like**
Loading layout file from current/given directory.

**Describe alternatives you've considered**
Defining a layout for each project as globally.

**Additional context**
Some example projects:
* https://github.com/kamranahmedse/itomate
* https://github.com/tmux-python/tmuxp

**Comment by mattrose** [comment]
You should look into the new --layout-json option.  You could have a JSON file that describes your layout in the project directory and load it from there.

**Comment by huseyinkozan** [comment]
> You should look into the new --layout-json option. You could have a JSON file that describes your layout in the project directory and load it from there.

There is a `--layout` doc at man, but not `--layout-json`.  Tried with below file like `terminator --layout 4-4-grid.json`, but not worked.

https://raw.githubusercontent.com/gnome-terminator/terminator/master/data/layout-files-examples/4-4-grid.json

`terminator --help` shows there is `-j CONFIGJSON` option, but it does not works, too. Tried `terminator -j 4-4-grid.json`, and `terminator --config-json=4-4-grid.json`

I am using version 2.1.1.

**Comment by mattrose** [comment]
I haven't actually written the documentation for that, and need to refresh my memory, but you should be able to be able to call the layout json by calling the full path to the JSON file
ie: terminator -j /home/user/terminator/data/layout-files-examples/4-4-grid.json, assuming that file exists.

**Comment by huseyinkozan** [comment]
No luck. Tried : 
```bash
terminator -j /home/hk/Downloads/4-4-grid.json
terminator --layout /home/hk/Downloads/4-4-grid.json
terminator --layout-json /home/hk/Downloads/4-4-grid.json    # error: no such option: --layout-json
terminator --config-json=/home/hk/Downloads/4-4-grid.json
```
