### ISSUE TITLE
Hole between title bar and terminal

### ISSUE THREAD

**Issue by janp20** [gnome-terminator/terminator#419]
![terminator_cropped](https://user-images.githubusercontent.com/63359862/114364959-3efcc380-9b7a-11eb-9dd0-889f62fc2775.png)

If I open multiple tabs the effect is as in the picture above. Please don't go ahead with CSD, it's ruining everything.
Thanks.

**Comment by janp20** [comment]
Between the title bar and the tabs there is a thin transparent window (the black rectangle in the picture) and you can see the desktop background through it.
Moreover there is a similar, very thin, "hole" also below the tab bar and the terminal.  To me it looks as  a bug. 
I thought that this was due to the use of CSD (client side decorations) but maybe I was wrong.
Thank you.

**Comment by mattrose** [comment]
Nope, we don't use Client Side Decorations, and I've seen terminator running in a bunch of different environments and I've ... never seen this.

What Linux Distribution are you using?
What Desktop Environment or Window Manager are you using?
What version of Terminator are you running?

Problems like this are usually caused by window manager or desktop themes.

**Comment by janp20** [comment]
I am using Arch with Xfce, and the 2.1.1 terminator version .. I checked with Enlightenment, Cinnamon and OpenBox.. no problem. Only with Xfce there is the anomaly I described and it does not depend on the terminator version . I downgraded it to ..uh .. 1.9.x (maybe) and the problem is there anyway. I tried to turn off the compositor but the (not transparent) "hole" remains. So the problem is definitely the interaction between Xfce (Xfwm) and the terminator.
Thank you for the attention and for your good work.

**Comment by pedroflor** [comment]
> ![terminator_cropped](https://user-images.githubusercontent.com/63359862/114364959-3efcc380-9b7a-11eb-9dd0-889f62fc2775.png)
> 
> If I open multiple tabs the effect is as in the picture above. Please don't go ahead with CSD, it's ruining everything.
> Thanks.

Hey @janp20 ...
maybe this could help?
[](https://github.com/gnome-terminator/terminator/issues/293)

**Comment by mattrose** [comment]
Yep, the problem is with the css that is used by the XFCE theme that you're using.
