### ISSUE TITLE
Open layout in new tab from inside Terminator. 

### ISSUE THREAD

**Issue by TonisPiip** [gnome-terminator/terminator#420]
**Is your feature request related to a problem? Please describe.**
I use terminator guake style, single key for show/hide, and use tabs / splits when needing more workspace. 

I tried to use the layout features, however the scope of the layout for the whole terminal.   
What I would like to be able to do is run a command from inside the terminal to open a layout inside a tab. So it will split and start whatever commands are discribed in the layout.
What happe

**Describe alternatives you've considered**
As I'm not seeing any way to trigger terminator layout on the current terminal the only way I've though of resoving it is using `xdotool` to create a macro for setting up the layout and inital commands. 

`xdotool key ctrl+shift+o; xdotool type "htop"; xdotool key Return; ` 

Binding the comand to an alias/bashfile and then running it. But it's not ideal... time consuming to write and maintain.

**Comment by mattrose** [comment]
In #472 I implemented a remotinator command that would do exactly that. 
`remotinator vsplit -x htop` will do the same thing.

Would this be a better solution?

The other thing we could do is write a plugin if this isn't acceptable.

**Comment by TonisPiip** [comment]
That's great! Thanks.  What's the easiest way to update to get the new command? 

IIRC I just installed using apt. I guess it'll take some time for the newest version to get to the standard package lists...

**Comment by mattrose** [comment]
I'll see if I can update the PPA in INSTALL.  I haven't done it yet, but I'll let you know when it's done

**Comment by timur-g** [comment]
Excuse me, can you explain how to use `remotinator vsplit -x ls` ? 
For me that windows stays stuck with cursor waiting, I cannot Ctrl+C or interrupt that.
