### ISSUE TITLE
Intermittent bracketed paste mode bug?

### ISSUE THREAD

**Issue by drigiln** [gnome-terminator/terminator#422]
**Describe the bug**
This does not always happen, but sometimes I copy text from various sources, then paste it into Terminator, and my desired text string has garbage characters prepended and appended to the beginning and end (see screenshots). When it happened again just now, I opened GNOME Terminal and pasted the same clipboard content without any extra garbage characters. Then I closed Terminator, started it as advised in the bug filing instructions, and the clipboard content pasted normally. It then also pasted normally after I closed Terminator and restarted with my normal config file.

**To Reproduce**
Since it seems intermittent, I'm not sure how you'd reproduce. Terminator and GNOME Terminal are both using the same zsh theme (powerlevel10k). I do tend to leave a Terminator window open 24/7/365, I don't know if that would introduce a problem.

**Expected behavior**
Just to paste the clipboard content without adding extra cruft characters before and after the desired text string.

**Screenshots**

what I copied (in this case, from Visual Studio Code; I was going to `grep` this string to find which file it was in):
![paste-source](https://user-images.githubusercontent.com/7062385/114876156-0c4a0980-9dcc-11eb-9eb5-6100d270b621.png)

how it pasted in Terminator:
![paste-terminator-bracketed-bug](https://user-images.githubusercontent.com/7062385/114876198-17049e80-9dcc-11eb-943b-454a03b4748a.png)

how it pasted in GNOME Terminal at the same time:
![paste-gnome-terminal-no-bug](https://user-images.githubusercontent.com/7062385/114876275-2ab00500-9dcc-11eb-9489-3e81cce5a4eb.png)

**Desktop (please complete the following information):**
Manjaro Linux

So I just wondered if there is any way I can permanently prevent the cruft being added to pastes?

I'm attaching my config file with a .txt extension added since GitHub won't seem to allow the bare file; it doesn't differ substantially from the default / no config file scenario:
[config.txt](https://github.com/gnome-terminator/terminator/files/6318332/config.txt)

**Comment by mattrose** [comment]
I've noticed the same problem, but it seems to happen inconsistently on my F34 beta machine, but never on my Ubuntu 20.10 server, even when running the exact same terminator code, which leads me to believe that it is likely in the vte code.

**Comment by mattrose** [comment]
This went away when I upgraded from F34 beta to full release. Can you upgrade to the latest version of vte and see if that fixes it?

**Comment by drigiln** [comment]
On Manjaro I seem to be using version `0.64.1-1` (packaged as `vte3`), which I _think_ is the [latest version](https://gitlab.gnome.org/GNOME/vte/-/tags) (?). I just opened Terminator and GNOME Terminal side by side, so far I didn't reproduce the bug in Terminator but it happened twice in GNOME Terminal. I guess it's not truly fixed yet, but there's no reason to keep it open as a _Terminator-specific_ bug. Thanks for pointing out `vte` as a likely culprit :)
