### ISSUE TITLE
Add more fundamental "editor-ish" feature

### ISSUE THREAD

**Issue by tomty89** [gnome-terminator/terminator#424]
Namely "Select All" to highlighting the whole (remaining) buffer for copying. Would be even better if "Find"/"Search" can be implemented.

Hence a preference to adjust maximum lines to retain in a buffer would be great as well. (Perhaps it's already possible and I just missed it?)

**Comment by mattrose** [comment]
We have a search function: https://terminator-gtk3.readthedocs.io/en/latest/gettingstarted.html#search-the-buffer

**Comment by tomty89** [comment]
Thanks, but what about "Select All"?

**Comment by wwwd4ta** [comment]
@mattrose , I came to request features related to both these things as well, a Ctrl+A select all, and not actually requesting search - but the ability to auto-scroll to matches without pressing enter. The scroll to matches seems to be default behavior for a lot of apps, would be nice to have that same feel in terminator. 

Currently the only way I've seen to select all is:
```
Shift + Home
Select the first line
Shift + End
Shift + click on the last character
```

If the feature exist and I just don't see it, please let me know. Thanks
