### ISSUE TITLE
Does this tool support macOS Big Sur?

### ISSUE THREAD

**Issue by cityvigil** [gnome-terminator/terminator#430]
**Describe the solution you'd like**
support for horizontal scrolling;

I found from this URL https://www.youtube.com/watch?v=tC81PMO7ODw&t=1812s at 27:35 that the terminator terminal tool can support horizontal scrollbars for windows.

I would like to ask if gnome-terminator/terminator is supported?

If so, I would like to know how to install it under macOS Big Sur.
Thanks!

**Comment by mattrose** [comment]
This tool is not related to the Java Terminator tool and does not support MacOS at this time

**Comment by cityvigil** [comment]
thanks
