### ISSUE TITLE
Doubled input from keyboard when broadcasting in tabs

### ISSUE THREAD

**Issue by abrams21** [gnome-terminator/terminator#432]
**Describe the bug**
Fresh installation of terminator on RHEL 8.3. When i have 2 or more tabs opened and i use option "Broadcast all" or "Broadcast group" -   charactes i type in active tab are doubled in other tabs. Example - when i type "a" in active tab, i got "aa" in other tabs. 
This is fresh installation of terminator on this system, no options changed in default config
I have tried to remove and install again, reinstall and run with fresh config. 

**To Reproduce**
Tried same versrion 1.92 from EPEL on Rocky Linux VM and i don't have this issue

**Desktop (please complete the following information):**
RHEL 8.3 Workstation

**Additional context**
Screenshot has been taken after typing single letter "a" in active window:
![WhatsApp Image 2021-05-03 at 15 03 35](https://user-images.githubusercontent.com/74722705/116879409-ea041880-ac20-11eb-8a69-dd65d1232677.jpeg)

Screenshot has been taken after typing "top" in active window:
![WhatsApp Image 2021-05-03 at 15 06 41](https://user-images.githubusercontent.com/74722705/116879734-4bc48280-ac21-11eb-9fcb-daead1c8d49b.jpeg)

**Comment by mattrose** [comment]
This was fixed a long time ago, and I don't have access to build new RPMS for RHEL.  Use a version from EPEL or file a bug with  Redhat if you want the RHEL version fixed.

**Comment by elfazzz** [comment]
I built from source today on RHEL 8.3, and I have the same issue - characters are echoed twice on non-focused terminals, while the focused terminal is OK (as seen in the original submission screenshot).
@mattrose do you have some reference to the fix that was done for this in the past? Could be helpful to troubleshoot further.

Thanks!

**Comment by mattrose** [comment]
Could be: https://github.com/gnome-terminator/terminator/pull/265/commits/736e88aa4606f8a2ea4a8d82fc63e6a9d34e51db

Also could be something to do with https://github.com/gnome-terminator/terminator/commit/6738199e0fa27618207f9095eecc1e3208e09fc3

Depends on what you're environment is.

**Comment by elfazzz** [comment]
Thanks a lot for pointing these out.

Indeed reinstating the removed workaround https://github.com/gnome-terminator/terminator/commit/736e88aa4606f8a2ea4a8d82fc63e6a9d34e51db does fix the issue for me - keypresses are not doubled
anymore in grouped terminals.

Would it be possible to put this workaround back, assuming it doesn't break anything else?

Thank you!
