### ISSUE TITLE
Ratio and/or position on a config file's layout ignored

### ISSUE THREAD

**Issue by facundofc** [gnome-terminator/terminator#433]
Ratio and/or position properties on a VPaned type node on a layout are not obeyed when starting up.

To reproduce, open a terminator window. Split it horizontally or vertically. Resize one pane to fill the entire window. Left-click on the window and Preferences. Go to Layout tab and click on the Add button. Then close the preferences dialog. Run a terminator session recalling the just saved layout (say it's named A):

```
terminator -l A
```

Note that there is a new window with two panes, but equally sized.

The expected behavior is, I believe, to have the exact same layout as the saved one. This is, one pane occupying the entire window.

I'm running Ubuntu Focal:

```
$ uname -a
Linux kathy 5.4.0-72-generic #80-Ubuntu SMP Mon Apr 12 17:35:00 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.1 LTS
Release:	20.04
Codename:	focal
```

**Comment by mattrose** [comment]
fixed by PR #442
