### ISSUE TITLE
Option to open URLs with just a click

### ISSUE THREAD

**Issue by ifohancroft** [gnome-terminator/terminator#434]
I'd like the ability to disable the need to hold Ctrl while clicking a URL, in-order to open it. In other words, I'd like to be able to open a URL by just clicking it, without having to hold the Ctrl key.

**Comment by mattrose** [comment]
Fixed in master.  https://github.com/gnome-terminator/terminator/pull/398

**Comment by ifohancroft** [comment]
That's awesome! Thank you!
