### ISSUE TITLE
Border->Shell Prompt Spacing In Right Pane Of Vertical Split

### ISSUE THREAD

**Issue by tundratim** [gnome-terminator/terminator#439]
If I vertically split a terminator window,  the right pane positions the output so close to the left border than I cannot highlight the leftmost text character.

Is the spacing between the split border and the output user configurable?

**Comment by mattrose** [comment]
What version are you running?  I fixed this problem sometime in v2.0 or 2.1.

**Comment by tundratim** [comment]
Ah, ok that explains it.  I am running Linux Mint 20 and they are still at terminator 1.91
