### ISSUE TITLE
Intermittent crashes on paste

### ISSUE THREAD

**Issue by Varun-garg** [gnome-terminator/terminator#440]
Before opening an issue, please try starting terminator with an empty config
file, by issuing `terminator -g /dev/null` and see if it starts normally.

If it does, and you still want to open the bug, then please attach the
config file, usually found at `$HOME/.config/terminator/config` to the issue

Fill out as many of these fields as you can

**Describe the bug**
On arch Terminator 2.1.1 seems to be crashing intermittently on paste

**To Reproduce**
This is intermittent. Once in a few days, terminator crashes for me, even if I am copy-pasting something from terminator itself.

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS or Linux Distribution: [e.g. FreeBSD or Ubuntu]
 - Version [e.g. 20.04]
 I am using Arch Linux (updated every 2-3 days) with Gnome 40.1 

**Additional context**

If there is a way to enable logging, I will be happy to share crash logs.

**Comment by mattrose** [comment]
If you can find stdout and stderr of the process that launched the process there should be a traceback that will help.
if you're using systemd, you can try `journalctl -f _COMM=terminator` to see if there's anything there.  That's where it logs on my ubuntu desktop.  Also, if it's actually crashing, you can usually enable some kind of automated crash reporting system, depending on what distribution you're using.

**Comment by Varun-garg** [comment]
Thanks for helping out. I am seeing these
```
May 27 23:09:35 zangetsu gsd-media-keys[88403]: Traceback (most recent call last):
May 27 23:09:35 zangetsu gsd-media-keys[88403]:   File "/usr/lib/python3.9/site-packages/terminatorlib/terminal.py", line 924, in on_keypress
May 27 23:09:35 zangetsu gsd-media-keys[88403]:     window_focussed = self.vte.get_toplevel().get_property('has-toplevel-focus')
May 27 23:09:35 zangetsu gsd-media-keys[88403]: TypeError: object of type `terminatorlib+notebook+Notebook' does not have property `has-toplevel-focus'
May 27 23:09:35 zangetsu gsd-media-keys[88403]: Traceback (most recent call last):
May 27 23:09:35 zangetsu gsd-media-keys[88403]:   File "/usr/lib/python3.9/site-packages/terminatorlib/terminal.py", line 924, in on_keypress
May 27 23:09:35 zangetsu gsd-media-keys[88403]:     window_focussed = self.vte.get_toplevel().get_property('has-toplevel-focus')
May 27 23:09:35 zangetsu gsd-media-keys[88403]: TypeError: object of type `terminatorlib+notebook+Notebook' does not have property `has-toplevel-focus'
May 27 23:09:35 zangetsu gsd-media-keys[88403]: Traceback (most recent call last):
May 27 23:09:35 zangetsu gsd-media-keys[88403]:   File "/usr/lib/python3.9/site-packages/terminatorlib/terminal.py", line 924, in on_keypress
May 27 23:09:35 zangetsu gsd-media-keys[88403]:     window_focussed = self.vte.get_toplevel().get_property('has-toplevel-focus')
May 27 23:09:35 zangetsu gsd-media-keys[88403]: TypeError: object of type `terminatorlib+notebook+Notebook' does not have property `has-toplevel-focus'
May 27 23:09:45 zangetsu gsd-media-keys[88403]: Traceback (most recent call last):
May 27 23:09:45 zangetsu gsd-media-keys[88403]:   File "/usr/lib/python3.9/site-packages/terminatorlib/terminal.py", line 924, in on_keypress
May 27 23:09:45 zangetsu gsd-media-keys[88403]:     window_focussed = self.vte.get_toplevel().get_property('has-toplevel-focus')
May 27 23:09:45 zangetsu gsd-media-keys[88403]: TypeError: object of type `terminatorlib+notebook+Notebook' does not have property `has-toplevel-focus'
May 27 23:09:46 zangetsu audit[88403]: ANOM_ABEND auid=1000 uid=1000 gid=1000 ses=5 pid=88403 comm="terminator" exe="/usr/bin/python3.9" sig=11 res=1
```

**Comment by Varun-garg** [comment]
Note: I observe this mostly in split screen

**Comment by mattrose** [comment]
How are you pasting?  Are you using the keybindings within terminator?  Terminator seems to be dying with Signal11 which means that something is causing memory corruption, but the whole thing is written in python, which has memory management, so corruption is theoretically impossible.

It looks like gsd-media-keys is sending a keypress to terminator that it doesn't know what to do with.  Which is really weird because according to a quick scan of the docs, it shouldn't send a signal to anything which hasn't registered to receive those signals.

**Comment by mattrose** [comment]
Closing after two weeks of no response
