### ISSUE TITLE
Can't disable transparency on separators

### ISSUE THREAD

**Issue by awvalenti** [gnome-terminator/terminator#441]
**Describe the bug**
Terminator uses transparency behind separator lines. Not sure if this behaviour is expected, but I would like to disable it.

**To Reproduce**
1. Ctrl Shift E to divide vertically 

**Expected behavior**
Not using transparency or offering an option to disable it

**Screenshots**
![image](https://user-images.githubusercontent.com/834921/120123171-bebf0b80-c183-11eb-8f65-051c0df747df.png)

If we increase separator size and remove scrollbar, it is more visible:
![image](https://user-images.githubusercontent.com/834921/120123212-edd57d00-c183-11eb-970c-d8339deb5e74.png)

**Desktop (please complete the following information):**
 - OS or Linux Distribution: Linux Mint Cinammon
 - Version 20.1

**Comment by mattrose** [comment]
What version  of terminator are you running.  I think I've fixed this in 2.0 or 2.1.

**Comment by awvalenti** [comment]
2.0.1. By the way, this is currently the newest version on [PPA](https://launchpad.net/~mattrose/+archive/ubuntu/terminator), do you plan on updating it to 2.1.1?

**Comment by awvalenti** [comment]
Any news? Can I help in some way?

**Comment by mattrose** [comment]
Sorry, can you try pulling down master and testing to see if the problem still exists in master.  As I said, I'm pretty sure I fixed this, but it may not be in the release you're running.  It could also be in the GTK theme that you're using.  Can you see if it happens with the default "Adwaita" themes?

**Comment by mattrose** [comment]
Closing issue after three weeks of no response

**Comment by Massimo-B** [comment]
Same issue here with terminator 2.1.1 compiled on Gentoo. The separators are always transparent with any separator size. Please make the separator color and transparency a configuration setting.

**Comment by Massimo-B** [comment]
I noticed, the issue does not happen with Theme Adwaita, but for instance with my local Mint-X-Red or Radiance. I'm happy with those themes, the separator transparency of Terminator is the only issue.

**Comment by mattrose** [comment]
This is a problem with those themes not specifying the color of the separators, therefore, GTK renders the separators as transparent.  I'm loathe to add more complexity to the preference pane to fix an issue with incomplete GTK themes.  There are good instructions in https://github.com/gnome-terminator/terminator/issues/293 for fixing the CSS for this property manually, and you could push the changes to your favourite theme so that it would fix this problem for everyone who uses that theme.
