### ISSUE TITLE
Multiple Terminator instances randomly crash on Ubuntu 20.04

### ISSUE THREAD

**Issue by metaturso** [gnome-terminator/terminator#444]
**Describe the bug**
I have been using two terminator windows, one per virtual desktop, for years without issue. Recently my terminator instances have started disappearing at random times.

The problem started happening a few days ago, most likely after a series of Ubuntu non-security patches were sneakily installed on my system.

**To Reproduce**
1. Open terminator a window on virtual desktop 1 (Ctrl-Alt-T)
2. Open another terminator window on virtual desktop 2 (Ctrl-Alt-Down, Ctrl-Alt-T)
3. Run a never-ending program that rarely outputs stuff in this second terminal
4. Switch back to virtual desktop 1 (Ctrl-Alt-Up)
5. Open other programs and do stuff, e.g. Firefox and wait a random amount of time
6. Terminator application crashes and all terminal windows disappear

I'm not sure if the following procedure triggers the same failure mode that I've been getting during regular operation, but you can quickly crash terminator by spawning the process in another terminal and sending it to the background:

1. open gnome-terminal
2. run `terminator -g /dev/null`
3. press Ctrl-z

Although sending a GUI application to the background is a questionable practice, I've never seen programs like GNU/Emacs crashing when doing this. 

I think I've seen this same error happens when running two instances of `terminator` in separate terminals.

**Expected behavior**
Terminator keeps working.

**Desktop (please complete the following information):**
```
terminator --version
terminator 1.91

cat /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=20.04
DISTRIB_CODENAME=focal
DISTRIB_DESCRIPTION="Ubuntu 20.04.2 LTS"

uname -r
5.8.0-53-generic
```

**Additional context**
Everything was working fine until the last batch of updates installed by Ubuntu.

Original crash dump:
```
ERROR:dbus.proxies:Introspect error on :1.94:/net/tenshu/Terminator2: dbus.exceptions.DBusException: org.freedesktop.DBus.Error.NoReply: Message recipient disconnected from message bus without replying
Traceback (most recent call last):
  File "/usr/bin/terminator", line 86, in <module>
    dbus_service = ipc.DBusService()
  File "/usr/share/terminator/terminatorlib/ipc.py", line 43, in __init__
    self.prepare_attributes()
  File "/usr/share/terminator/terminatorlib/ipc.py", line 56, in prepare_attributes
    raise dbus.exceptions.DBusException(
dbus.exceptions.DBusException: Couldn't get DBus name net.tenshu.Terminator23558193cd9818af7fe4d2c2f5bd9d00f: Name exists

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/terminator", line 107, in <module>
    ipc.new_window_cmdline(optionslist)
  File "/usr/share/terminator/terminatorlib/ipc.py", line 195, in _exec
    func(proxy, *args, **argd)
  File "/usr/share/terminator/terminatorlib/ipc.py", line 201, in new_window_cmdline
    session.new_window_cmdline(options)
  File "/usr/lib/python3/dist-packages/dbus/proxies.py", line 72, in __call__
    return self._proxy_method(*args, **keywords)
  File "/usr/lib/python3/dist-packages/dbus/proxies.py", line 141, in __call__
    return self._connection.call_blocking(self._named_service,
  File "/usr/lib/python3/dist-packages/dbus/connection.py", line 652, in call_blocking
    reply_message = self.send_message_with_reply_and_block(
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.ServiceUnknown: The name :1.94 was not provided by any .service files
```

Crash dump after running `terminator -g /dev/null`

```
ERROR:dbus.proxies:Introspect error on :1.127:/net/tenshu/Terminator2: dbus.exceptions.DBusException: org.freedesktop.DBus.Error.NoReply: Message recipient disconnected from message bus without replying
Traceback (most recent call last):
  File "/usr/bin/terminator", line 86, in <module>
    dbus_service = ipc.DBusService()
  File "/usr/share/terminator/terminatorlib/ipc.py", line 43, in __init__
    self.prepare_attributes()
  File "/usr/share/terminator/terminatorlib/ipc.py", line 56, in prepare_attributes
    raise dbus.exceptions.DBusException(
dbus.exceptions.DBusException: Couldn't get DBus name net.tenshu.Terminator23558193cd9818af7fe4d2c2f5bd9d00f: Name exists

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/terminator", line 107, in <module>
    ipc.new_window_cmdline(optionslist)
  File "/usr/share/terminator/terminatorlib/ipc.py", line 195, in _exec
    func(proxy, *args, **argd)
  File "/usr/share/terminator/terminatorlib/ipc.py", line 201, in new_window_cmdline
    session.new_window_cmdline(options)
  File "/usr/lib/python3/dist-packages/dbus/proxies.py", line 72, in __call__
    return self._proxy_method(*args, **keywords)
  File "/usr/lib/python3/dist-packages/dbus/proxies.py", line 141, in __call__
    return self._connection.call_blocking(self._named_service,
  File "/usr/lib/python3/dist-packages/dbus/connection.py", line 652, in call_blocking
    reply_message = self.send_message_with_reply_and_block(
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.ServiceUnknown: The name :1.127 was not provided by any .service files
```

**Comment by mattrose** [comment]
So, the first reproduction (basically send SIGTSTP to the process), does exactly what I expect it to do on my ubuntu 20.10 desktop.  It stops the process, but the process doesn't crash.
I'm trying your original reproduction steps now with this loop running my 2nd virtual desktop
`i=0 ; while [ $i -lt 1000 ] ; do echo $i ; i=$(($i+1)) ; sleep 30 ; done` and it's chugging along nicely.  It certainly sounds like dbus on your system is really unstable and when terminator tries to contact it, it gets no reply occasionally, see

`ERROR:dbus.proxies:Introspect error on :1.94:/net/tenshu/Terminator2: dbus.exceptions.DBusException: org.freedesktop.DBus.Error.NoReply: Message recipient disconnected from message bus without replying'

from the original crash dump.

2 suggestions.

1.  Reboot, or restart your dbus session.  If the desktop has gone through a bunch of updates and hasn't been rebooted, this will likely fix your issue.

and if that doesn't work.

2. Go into Terminator preferences and uncheck 'DBus Server' under the Global Tab.
