### ISSUE TITLE
Separators is wider after upgrading to ubuntu 21.04

### ISSUE THREAD

**Issue by nikolaik** [gnome-terminator/terminator#445]
When upgrading to Ubuntu 21.04 with terminator version 2.1.0 the separators are much wider than before.

After a bit of digging I found these two lines could be commented out to revert to the old appearance:
https://github.com/gnome-terminator/terminator/blob/013336191ebddb19b53422e73468fafa9d03a089/terminatorlib/paned.py#L514

https://github.com/gnome-terminator/terminator/blob/013336191ebddb19b53422e73468fafa9d03a089/terminatorlib/paned.py#L532

* Is there another way of disabling the wide borders?
* Is the default GTK theme in Ubuntu making the resize handlers too big or something like that?

**Comment by mattrose** [comment]
My guess would be that the default GTK theme is making the resize handlers bigger.  The problem is, is that if that property is not set to True, then you lose the ability to select the first character in a vertical pane with your mouse. (Makes no sense, I know, but ... GTK).  Also, I think it causes the handles to be transparent.  I'll play with this a bit.

**Comment by mattrose** [comment]
I just checked it out and ... it's not abnormally chunky.  Honestly I think it's fine but if somebody wants to have a go at some custom CSS for it, I wouldn't object.

**Comment by nikolaik** [comment]
> I just checked it out and ... it's not abnormally chunky. Honestly I think it's fine but if somebody wants to have a go at some custom CSS for it, I wouldn't object.

chunky indeed! Do you have any pointers on how to find the relevant CSS selectors and where it should belong?

**Comment by mattrose** [comment]
Off the top of my head, you can find the relevant CSS by useing the GTK Inspector https://wiki.gnome.org/Projects/GTK/Inspector 

Basically, you can use the GTK Debug interface to play with CSS properties.  
`GTK_DEBUG=interactive terminator`

**Comment by mattrose** [comment]
So, I've decided not to fix this feature, as the lines you point out actually fix a bug where you cannot select the first character of a vertically-split pane.
