### ISSUE TITLE
Window vanishes

### ISSUE THREAD

**Issue by pierre-imbaud** [gnome-terminator/terminator#447]
**Desktop (please complete the following information):**

Linux zebu 5.8.0-48-generic #54~20.04.1-Ubuntu SMP Sat Mar 20 13:40:25 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

working with xfce.

**Describe the bug**

terminator is not my definite choice, I am experimenting with it.

I keep loooong sessions, suspending the machine at night rather than closing.
I have one terminator window, with 3 to 4 tabs.

What happens is: every week or so, the window where terminator leaves vanishes: I just cant find it in the virtual desk where it lived, or elsewhere.

I use xfdesktop -W to try to locate it, its nowhere.

But the process is still alive: 

~ 21:35:38 > ps -ef|grep terminator
pierre   1012287    3943  0 May24 pts/1    00:01:02 /usr/bin/python3 /usr/bin/terminator
pierre   1131367    4011  0 21:36 pts/2    00:00:00 grep terminator

I looked for open files, hoping to find some log file:
ls -l /proc/1012287/fd
total 0
lrwx------ 1 pierre pierre 64 juin   4 10:19 0 -> /dev/pts/1
lrwx------ 1 pierre pierre 64 juin   4 10:19 1 -> /dev/pts/1
lrwx------ 1 pierre pierre 64 juin   4 10:19 10 -> 'anon_inode:[eventfd]'
lrwx------ 1 pierre pierre 64 juin   4 10:19 11 -> 'socket:[14915725]'
lrwx------ 1 pierre pierre 64 juin   4 10:19 12 -> 'socket:[14915726]'
lr-x------ 1 pierre pierre 64 juin   4 10:19 13 -> anon_inode:inotify
lrwx------ 1 pierre pierre 64 juin   4 10:19 14 -> /dev/ptmx
lrwx------ 1 pierre pierre 64 juin   4 10:19 15 -> 'socket:[14913838]'
lrwx------ 1 pierre pierre 64 juin   4 10:19 16 -> 'socket:[14913839]'
lrwx------ 1 pierre pierre 64 juin   4 10:19 17 -> /dev/ptmx
lrwx------ 1 pierre pierre 64 juin   4 10:19 18 -> /dev/ptmx
lrwx------ 1 pierre pierre 64 juin   4 10:19 19 -> /dev/ptmx
lrwx------ 1 pierre pierre 64 juin   4 10:19 2 -> /dev/pts/1
lrwx------ 1 pierre pierre 64 juin   4 10:19 20 -> '/tmp/#131078 (deleted)'
lrwx------ 1 pierre pierre 64 juin   4 10:19 21 -> '/tmp/#131088 (deleted)'
lrwx------ 1 pierre pierre 64 juin   4 10:19 3 -> 'socket:[14914740]'
lrwx------ 1 pierre pierre 64 juin   4 10:19 4 -> 'anon_inode:[eventfd]'
lrwx------ 1 pierre pierre 64 juin   4 10:19 5 -> 'socket:[14915708]'
lrwx------ 1 pierre pierre 64 juin   4 10:19 6 -> 'anon_inode:[eventfd]'
lrwx------ 1 pierre pierre 64 juin   4 10:19 7 -> 'anon_inode:[eventfd]'
lrwx------ 1 pierre pierre 64 juin   4 10:19 8 -> 'anon_inode:[eventfd]'
lrwx------ 1 pierre pierre 64 juin   4 10:19 9 -> 'socket:[14910165]'
~ 20:00:07 > 

Could the /tmp deleted files be meaningful?
I went thru logs, looking for some event that could explain, found none.
I read the bug list, and found nothing similar.
I feel motivated to further dig, like run with debug options, but with guidance of someone.

**To Reproduce**
No recipe, seems to occur at random; Well, at least, I didnt spot any significant event suite that would explain. Well, thinking of it, it newer occured while operating with terminator, rather when acting on something else.

**config**
[global_config]
  borderless = True
  title_receive_bg_color = "#73d216"
[keybindings]
[profiles]
  [[default]]
    cursor_color = "#aaaaaa"
    palette = "#000000:#aa0000:#00aa00:#aa5500:#0000aa:#aa00aa:#00aaaa:#aaaaaa:#555555:#ff5555:#55ff55:#ffff55:#5555ff:#ff55ff:#55ffff:#ffffff"
  [[attempt]]
    cursor_color = "#aaaaaa"
[layouts]
  [[default]]
    [[[window0]]]
      type = Window
      parent = ""
    [[[child1]]]
      type = Terminal
      parent = window0
[plugins]

Before opening an issue, ....

**Comment by mattrose** [comment]
terminator logs to stdout and stderr, so it would be captured by whatever captures stdout and stderr on your system.  If you use systemd for your logins, it would be captured by journalctl, if not there might be something in your X11 logs.

to debug this further you can run `terminator -d` and redirect stderr and stdout to a log file by hand.  

JADP, I actually run terminator for weeks on end on my work desktop and it's rock solid.  

I would also look to see if you can easily upgrade to a newer version of terminator.  I found this one works well on 20.10
https://packages.debian.org/buster-backports/terminator

**Comment by mattrose** [comment]
closing with no response
