### ISSUE TITLE
Option to disable system notifications

### ISSUE THREAD

**Issue by baelter** [gnome-terminator/terminator#448]
There does not seem to be any way to disable system notifications? I get like a million notifications a day sent to gnome notifications. 

Fedora 34
Terminator 2.1.1

**Comment by mattrose** [comment]
There are three plugins that use notifications
ActivityWatch
InActivityWatch
and CommandNotify

These plugins should be disabled.

**Comment by baelter** [comment]
All those are disabled. Still getting notifications.

**Comment by mattrose** [comment]
What kind of notifications are you getting?  I'm very confused as the notification system is only loaded by those plugins.  Can you paste the text of some of the notifications in here?

**Comment by baelter** [comment]
Sorry, not related to terminator at all.
