### ISSUE TITLE
Coloring Tabs / Tabs Appearance

### ISSUE THREAD

**Issue by pedroflor** [gnome-terminator/terminator#449]
**Not a bug**, just a little help to anyone looking to change the visual of their TABs
Borrowed from: 
https://www.preining.info/blog/2020/03/de-uglify-gtk3-tabs-of-terminals/
http://blog.nabam.net/workstation/2017/09/15/terminator_tabs/

@mattrose: Could you add an entry in Documentation?

Here is my config:
`~/.config/gtk-3.0/gtk.css`
```

/* Color of inactive TAB */
notebook tab {
    padding: 0.4em;
    border: 0;
    border-color: #444;
    border-style: solid;
    border-width: 1px;
}

/* Color of active TAB */
notebook tab:checked {
    border-color: #76C802;
    border-width: 1px;
}

/* Color of text's TAB */
notebook tab:checked label {
    color: #ffffff;
    font-weight: 500;
}

/* Color of "x" close button */
notebook tab button {
    padding: 0;
    background-color: transparent;
    color: #ffffff
    border-width: 1px;
}

/* Color of "x" border's close button */
notebook tab button:hover {
  padding: 0;
  background-image: none;
  border-color: #00b0ff;
  border-style: solid;
  border-width: 1px;
}
```

Here is the resutl:
![image](https://user-images.githubusercontent.com/3332674/122074748-79c3e780-cdc7-11eb-8405-3295ed1ad36a.png)

**Comment by mattrose** [comment]
Thank you so much for this! I was looking at this last night trying to figure out the correct css selectors.  Do you mind if I edit this and turn it into an enhancement request to incorporate it into the Preferences?

**Comment by pedroflor** [comment]
Hi @mattrose ... please, go ahead!

**Comment by mattrose** [comment]
Changed my mind on adding this to Preferences.  After giving it a little thought, I would much rather stick with the GTK colors for all of the window decorations.  I will add this stuff to the documentation.  I also found this: http://blog.nabam.net/workstation/2017/09/15/terminator_tabs/

**Comment by mattrose** [comment]
I added the gtk.css to the faq https://github.com/gnome-terminator/docs/blob/master/source/faq.rst
