### ISSUE TITLE
Terminal deletes lines when fullscreened and unfullscreened

### ISSUE THREAD

**Issue by LinuxFTW** [gnome-terminator/terminator#452]
**Describe the bug**

**To Reproduce**
1. Open Terminator under i3
2. Have a few other windows open on the same workspace side-by-side
3. Fullscreen and unfullscreen
4. One line should be deleted per full-unfullscreen cycle

**Expected behavior**
Lines not being deleted

**Screenshots**

**Desktop (please complete the following information):**
 - Arch Linux

**Additional context**

**Comment by mattrose** [comment]
Where is the line being deleted from?  The top?  The bottom?  Are there any lines that wrap to the edge of the screen in non fullscreen mode?

Also, can you reproduce this with gnome-terminator?

**Comment by mattrose** [comment]
Closing issue after 2 weeks of no response.
