### ISSUE TITLE
Incorrect layout sorting in notebook

### ISSUE THREAD

**Issue by AsadJivani** [gnome-terminator/terminator#453]
## Description
Layouts are in incorrect order inside the notebook if the layout count is above 9 in the notebook.

## Steps to Reproduce
1- Create a layout, add a window in it. 
2- Add a notebook inside the window.
3- Add more than 9 child layouts ( preferably of type terminal ) inside it. 
4- Give a title to each terminal layout in order to differentiate between them.

## Expected behavior
All the layouts should be in the specified order.

## Reason
After going through the code, the problem is the compare child function inside the notebook

**Comment by mattrose** [comment]
I haven't looked at this but I am willing to bet that it's because the layouts are launched in alphabetical order, and not numeric order.

ie: 1,10,11,12,2,3,4,5,6,7,8,9 and not in the order you were expecting.

**Comment by AsadJivani** [comment]
exactly, because in the sorting function order should be converted to integer type, I have created pull request against this ticket
