### ISSUE TITLE
Active page not working in notebook

### ISSUE THREAD

**Issue by AsadJivani** [gnome-terminator/terminator#455]
## Description
Notebook not selecting the active page after opening.

## Steps to Reproduce
1- Create a layout, add a window in it. 
2- Add a notebook inside the window, then add few terminal layouts.
3- Add ```active_page``` attribute, specify your desired page.

## Expected behavior
The value provided in ```active_page``` should be the active terminal

**Comment by mattrose** [comment]
That active_page call is done by `GObject.idle_add()` which doesn't appear in the GTK3 documentation anymore.  It *might* be `GLib.idle_add()` but I'm not sure.  Can you pass me a simple config that reproduces this?

**Comment by mattrose** [comment]
closing due to lack of response.
