### ISSUE TITLE
Mouse scrolling on openbsd 6.9 does not work

### ISSUE THREAD

**Issue by suletm** [gnome-terminator/terminator#463]
**Describe the bug**
Scrolling with mouse scrolls only about 4 lines back. Though I can scroll back using shift + page up shortcut.

**To Reproduce**
Install on OpenBSD 6.9 with latest xfce-4.16 and terminator-1.92p0. Start a new terminator window. Generate a bunch of text in the shell. Attempt to scroll using mouse: you will be able to scroll back only for roughly 4 lines of text. This bug is reproducible under "terminator -g /dev/null"

**Expected behavior**
Scrolling with mouse should be able to scroll for more than 4 lines back. 

**Desktop (please complete the following information):**

OS: OpenBSD 6.9
Window Manager: xfce-4.16

**Additional context**

Contents of ~/.config/terminator/config
```
[global_config]
  title_font = System-ui 9
[keybindings]
  zoom_in = <Super>equal
  zoom_out = <Super>minus
  zoom_normal = <Super>0
  new_tab = <Super>t
  split_horiz = <Super>bracketleft
  split_vert = <Super>bracketright
  search = <Super>f
  scaled_zoom = <Shift><Super>Return
  next_tab = <Shift><Super>braceright
  prev_tab = <Shift><Super>braceleft
  full_screen = <Super>Return
  new_window = <Super>n
[profiles]
  [[default]]
    allow_bold = False
    visible_bell = True
    cursor_color = "#aaaaaa"
    font = Monospace 15
    scroll_on_output = True
    use_system_font = False
    copy_on_selection = True
  [[mefs profile]]
    cursor_color = "#aaaaaa"
    font = Monospace 10
    use_system_font = False
[layouts]
  [[default]]
    [[[window0]]]
      type = Window
      parent = ""
    [[[child1]]]
      type = Terminal
      parent = window0
[plugins]
```

**Comment by mattrose** [comment]
Honestly I don't have the time right now to set up an entire OpenBSD VM with xfce4 to test this out.  Needless to say, this seems to be an OpenBSD thing as I cannot reproduce on Linux, FreeBSD or MacOS.  Can you try upgrading to the latest version?

**Comment by suletm** [comment]
> Can you try upgrading to the latest version?
The issue is reproducible in terminator from the repository head.

> Honestly I don't have the time right now to set up an entire OpenBSD VM with xfce4 to test this out
No worries. Maybe you can give some pointers to how to debug this issue ?

**Comment by mattrose** [comment]
I would start with `terminator -d -u` to see if there's any debug messages.  I would also see if xfce4-terminal has the same problem.  If it does, it might be a vte issue as terminator and xfce4-terminal both use that lib.

**Comment by suletm** [comment]
Thanks for the troubleshooting hints. I did not find anything interesting in the debug output. But, it turns out xfce native terminal has the same issue. But xterm does not. I tend to think this is xfce related issue now.

**Comment by mattrose** [comment]
It's probably an issue in vte, which is the library that both terminator and xfce4-terminal use to do basic terminal operations, including scrolling.  If you would like, you should open a bug against vte here https://gitlab.gnome.org/GNOME/vte/-/issues
