### ISSUE TITLE
New layout with npm commands not working

### ISSUE THREAD

**Issue by andreescocard** [gnome-terminator/terminator#464]
**Describe the bug**
Layout with nvm/npm commands say command not found

**To Reproduce**
Create new layout, use 1 or more terminal windows, add any nvm or npm commands

**Expected behavior**
Commands should run, after terminator opens if i type the same command, it works (example npm run build)

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Version: 1.9.1

**Additional context**
Tried adding source .bashrc command to refresh, checked on preferences > layouts > run custom command instead default shell, created ./sh file and added the command on it, nothing works.

Thanks

**Comment by mattrose** [comment]
This looks like a path problem:  try to determine the full path to npm (or whatever utility) by issuing `which npm` then adding the full path to the command, ex: `/path/to/npm run build`

**Comment by andreescocard** [comment]
I tried to add full path for npm but won't work, always give me another error. I am curently using nvm, what i don't get is that the command don't work on terminator startup but if i run it after, it works.

**Comment by mattrose** [comment]
What is the error message?

**Comment by andreescocard** [comment]
> What is the error message?

command - /home/aescocard/.nvm/versions/node/v14.17.1/bin/npm run build; bash
error - /usr/bin/env: “node”: No such file or directory

**Comment by mattrose** [comment]
Do you have login shell enabled in the command preferences?

**Comment by andreescocard** [comment]
> Do you have login shell enabled in the command preferences?

yes

**Comment by mattrose** [comment]
It's definitely a path problem.  Can you paste in a simplified config that displays the problem?

**Comment by andreescocard** [comment]
`[[project]]
    [[[child0]]]
      fullscreen = False
      last_active_term = 753d550b-8b48-4afe-8490-32cae99169d3
      last_active_window = False
      maximised = True
      order = 0
      parent = ""
      position = 0:0
      size = 1366, 731
      title = aescocard@NOTE: /HYBRIS/PROJECT/hybris/bin/platform
      type = Window
    [[[child1]]]
      order = 0
      parent = child0
      position = 681
      ratio = 0.500367376929
      type = HPaned
    [[[terminal2]]]
      command = cd /HYBRIS/PROJECT/hybris/bin/platform && ant clean all && ./hybrisserver.sh debug; bash
      order = 0
      parent = child1
      profile = default
      type = Terminal
      uuid = 753d550b-8b48-4afe-8490-32cae99169d3
    [[[terminal3]]]
      command = cd /HYBRIS/PROJECT/hybris/bin/custom/projectfront && /home/aescocard/.nvm/versions/node/v14.17.1/bin/npm run build; bash
      order = 1
      parent = child1
      profile = default
      type = Terminal
      uuid = 0c7e2bf2-f011-44c5-9731-2aa359c60cd8`

**Comment by andreescocard** [comment]
The most strange problem is that if i run npm run build after terminator opens, it works.
Somehow bash isn't being loaded before the command execution.

**Comment by mattrose** [comment]
I can't read that config file, there's no newlines. Maybe attach it?

**Comment by andreescocard** [comment]
> I can't read that config file, there's no newlines. Maybe attach it?

You mean not showing the config inline? I edited the config answer

**Comment by mattrose** [comment]
Thanks I'll see if I can come up with a reproduction scenario

**Comment by andreescocard** [comment]
Fixed adding a symlink:
`sudo ln -s "$(which node)" /usr/bin/node`

More info: https://stackoverflow.com/questions/26320901/cannot-install-nodejs-usr-bin-env-node-no-such-file-or-directory/62850005#62850005

Thanks
