### ISSUE TITLE
Wallpaper configuration option from terminal

### ISSUE THREAD

**Issue by ghost** [gnome-terminator/terminator#466]
**Feature request for background wallpaper**
I've been trying to figure out a way that I could run a command from the terminal to change the backgroun wallpaper instead of having to use the config options tab. Also because I think it would come in handy if I wanted to make a script change the wallpaper every 5 minutes or so, of course, the terminal won't be updated until I open a new tab or close then reopen.

I don't know, just thought it could be another cool thing to add.

**Comment by mattrose** [comment]
good idea!
