### ISSUE TITLE
Changing cursor foreground color

### ISSUE THREAD

**Issue by kraftwerk28** [gnome-terminator/terminator#467]
In gnome-terminal it is possible to set both cursor background/foreground colors independently, but in terminator there's only one option.

![](https://user-images.githubusercontent.com/31807671/125505627-75af7915-5711-484e-8f72-19953b14c63f.png)
*gnome-terminal settings*

![](https://user-images.githubusercontent.com/31807671/125505753-0c862b98-03aa-47e4-808c-f3917206c7d1.png)
*terminator settings*

Could it made so that terminator also has options for cursor fg/bg?

**Comment by mattrose** [comment]
yes.

**Comment by mattrose** [comment]
fixed by #486
