### ISSUE TITLE
Terminator hangs when I split it into 4 terminals and broadcast into them

### ISSUE THREAD

**Issue by adbidwai** [gnome-terminator/terminator#468]
Hello, community,

**System Configuration**: Ubuntu 18.04 dual-booted alongside Windows

**Issue** :
When I split my terminal into 4 parts, something like this : 

![image](https://user-images.githubusercontent.com/46625413/125547426-2c86960a-456b-4263-be95-4d76fcb8152c.png)

and then I try to broadcast into all of them, my entire terminal windows hangs and I am forced to shut it down forcefully. I noticed this problem is arising only recently and I was able to use this feature smoothly some days ago.

TIA

**Comment by marktimarev** [comment]
Could you provide more details on how I can reproduce it on my system?
Otherwise, it may be an issue with the specific setup you have.

**Comment by mattrose** [comment]
Yep, can't repro here either.  Can you run it under `terminator -d ` to see if there's any exceptions or errors?

**Comment by mattrose** [comment]
What version of terminator are you running?

**Comment by adbidwai** [comment]
@mattrose My terminator version is `terminator 1.91`

![image](https://user-images.githubusercontent.com/46625413/127294155-4ac47586-048b-4007-bd69-5c163a81335d.png)

**Comment by mattrose** [comment]
Hmm, that version is about 4 years old, and has a lot of big bugs fixed, as well as porting from python2 to python3.  Can you try reproducing this on the latest release?

**Comment by adbidwai** [comment]
OMG, 4 years!
How do I update it though, just doing `sudo apt-get update` and `sudo apt-get upgrade` should work right?
I daily do it, still it's the same version

**Comment by mattrose** [comment]
Well, you're running a distro that was released three years ago, so it kinda makes sense that the version is from slightly before that.  What you could do is download [the latest release](https://github.com/gnome-terminator/terminator/releases/tag/v2.1.1), and test out the latest release by following the instructions in [INSTALL.md](https://github.com/gnome-terminator/terminator/blob/master/INSTALL.md)

**Comment by mattrose** [comment]
Closing
