### ISSUE TITLE
Expose Buffer size on the UI 

### ISSUE THREAD

**Issue by yuriw** [gnome-terminator/terminator#47]
Currently buffer size can be set vi `.config/terminator/config` editing, e.g. adding `scrollback_infinite = True` (unsure BTW if it works), but it should be available via the UI

**Comment by JakubVanek** [comment]
Hi @yuriw,

there is some configuration entry that looks similar, wouldn't it work?
![scrollback](https://user-images.githubusercontent.com/6003171/80624986-caa24080-8a4c-11ea-97f0-987633964dc2.png)

Best regards,
Jakub

**Comment by yuriw** [comment]
@JakubVanek of cause it will, thx !
withdrawing ...
