### ISSUE TITLE
Support OpenType font features

### ISSUE THREAD

**Issue by clsn** [gnome-terminator/terminator#473]
A few other terminal-emulators (kitty, pterm, qterminal...?) have some support for OpenType font features like contextual substitution, etc.  It might not sound useful in a monospace environment but it is (having fonts that automatically place no-width commas between groups of three digits makes reading the output of `ls -l` a lot easier.)  It would be nifty if terminator could provide this as well.  Ideally, something like kitty's ability to actually specify features in the configuration (or command-line) would be good, but that's pretty rare.  At least use the features that fontconfig provides.

I don't really know how hard this is; haven't looked into terminator's rendering much.  Many modern rendering engines support these features.  Just putting it out there.

**Comment by mattrose** [comment]
Font rendering is way out of scope for terminator.  We rely on the Gnome vte library, which depends on the pango and harfbuzz for font rendering.  

If you're fairly specific you could open an issue with vte, but be warned there's been a lot of requests for additional font features, and a lot of pushback from the VTE developers.
