### ISSUE TITLE
It is impossible to select text further than the one that one sees in the current Terminator screen

### ISSUE THREAD

**Issue by tommasosansone91** [gnome-terminator/terminator#477]
When left clicking on the text in Terminator window and moving the mouse, the window does not scroll, so that it is impossible to  select text further than the one that one sees in the current Terminator screen.

This does not happens in the custom Linux (I'm using Ubuntu) Terminal, can you please fix this bug? Thanks in advance

**Comment by Vulcalien** [comment]
Hi! Thanks for reporting the bug, could you give us some more information?

The version of Terminator (`terminator --version`)

Also, does the bug occur if you open Terminator using default settings?
To try this, all instances of Terminator must be closed. From a different terminal (the Ubuntu default is fine) type
`terminator -g /dev/null`.

**Comment by tommasosansone91** [comment]
Hi,
I'm using Terminator 2.1.0.
I've run `terminator -g /dev/null` , then I deselected all the plugins and... it works! 
As I hold down right click and move the mouse over the edges of Terminator window, the text scrolls, allowing me to select the entire text log.

I also tryed to re-tick all the plugins one by one in order to find out the one generating the bug but the bug did not show up anymore. weird...

**Comment by Vulcalien** [comment]
It has to be something about the config file I guess. Could you send the config file? It's located here:
`~/.config/terminator/config`.
Let's see if I can reproduce it.

**Comment by tommasosansone91** [comment]
> It has to be something about the config file I guess. Could you send the config file? It's located here:
> `~/.config/terminator/config`.
> Let's see if I can reproduce it.

here it is, i just turned it to txt only to get it allowed for upload on Github
[config.txt](https://github.com/gnome-terminator/terminator/files/6939307/config.txt)

**Comment by mattrose** [comment]
Hmm, cannot reproduce from here with latest `master` code

**Comment by mattrose** [comment]
It might be being caused by TerminalShot.  The SelectAll plugin looks fine, but I have no idea what that TerminalShot plugin does.

**Comment by tommasosansone91** [comment]
I have the same problem again, but this time I have noticed this happens only when I am trying to select and scroll text inside a txt file that I "opened" with Terminator with `command less <filename.txt>`.

I kindly ask to reopen the issue.

**Comment by mattrose** [comment]
That's because less takes over the scrolling functions.  You'll find that other terminals have the same problem.
