### ISSUE TITLE
Select all functionality

### ISSUE THREAD

**Issue by tommasosansone91** [gnome-terminator/terminator#478]
It would be nice to have a way to select all the text in the current Terminator window at once, even better if callable via the shortcut CTRL+A, identically to what possible in lots of text editors.
I'd find it useful because sometimes you just need to copy all the thins you did on the terminal and save it somewhere as log of how you found/fixed bugs, etc.
Someone already implemented a [similar functionaly as plugin](https://github.com/egroeper/terminator-plugins/blob/master/selectall.py), but unfortunately it looks like the method `select_all()` in `selectall` function

```
def selectall(self, _widget, terminal):
    """Select all text """
    terminal.vte.select_all()
```

cannot really select all the text in the terminal, but only

"the latest (at the most bottom of the window) x lines of text, where x is a number of lines corresponding to those appearing in the window at its current size"

would it be possible to implement such functionality? Thanks in advance

**Comment by mattrose** [comment]
According to the api doc, select_all() selects all text including that in the scrollback buffer

https://lazka.github.io/pgi-docs/#Vte-2.91/classes/Terminal.html#Vte.Terminal.select_all

So that should do exactly as asked.  Does it not?

**Comment by tommasosansone91** [comment]
> According to the api doc, select_all() selects all text including that in the scrollback buffer
> 
> https://lazka.github.io/pgi-docs/#Vte-2.91/classes/Terminal.html#Vte.Terminal.select_all
> 
> So that should do exactly as asked. Does it not?

No, in my case it copies only

"the latest (at the most bottom of the window) x lines of text, where x is a number of lines corresponding to those appearing in the window at its current size"

and not the one in the scrollback buffer
