### ISSUE TITLE
Terminator ignors system proxy

### ISSUE THREAD

**Issue by sylar-my** [gnome-terminator/terminator#479]
Terminator doesn't working with system proxy even while gnome terminal is working. It might not be bug and I might not know how to . Please suggest me.  
If I run " **env | grep proxy** " in gnome termianl , it outputs as below,
all_proxy=socks://127.0.0.1:1089/
http_proxy=http://127.0.0.1:8889/
ftp_proxy=http://127.0.0.1:8889/
no_proxy=localhost,127.0.0.0/8,::1
https_proxy=http://127.0.0.1:8889/

but nothing happend in Terminator.

**Comment by mattrose** [comment]
You probably need to set "Run command as a login shell" in the Preferences https://terminator-gtk3.readthedocs.io/en/latest/preferences.html#command

**Comment by sylar-my** [comment]
> You probably need to set "Run command as a login shell" in the Preferences https://terminator-gtk3.readthedocs.io/en/latest/preferences.html#command

I have searched on net long time and tried this already. But It's really not working.

**Comment by mattrose** [comment]
This is more to do with what shell you're using and what env returns.  Terminator (or gnome-terminal for that matter) have no effect on this.

What does `terminator -d --debug-classes=Terminal --debug-methods=spawn_child` say about what shell it's launching?

**Comment by sylar-my** [comment]
> This is more to do with what shell you're using and what env returns. Terminator (or gnome-terminal for that matter) have no effect on this.
> 
> What does `terminator -u -d --debug-classes=Terminal --debug-methods=spawn_child` say about what shell it's launching?

"Terminator" was launching when I run this. The one thing I made is that " I have made default terminal to _Terminator_ instand of "gnone-terminal" . However I have switched it back and tested . I remains same problem.

**Comment by sylar-my** [comment]
> This is more to do with what shell you're using and what env returns. Terminator (or gnome-terminal for that matter) have no effect on this.
> 
> What does `terminator -u -d --debug-classes=Terminal --debug-methods=spawn_child` say about what shell it's launching?

"Terminator" was launching. The one thing is I made is that I did default terminal to "Terminator" in stand of " gnome-terminal". However I have switched it back and tested. It remains same problem..

PS: when I run  `terminator -u -d --debug-classes=Terminal --debug-methods=spawn_child` in "gnone-terminal" . Terminator runs and working with proxy . But if I run in "Terminator" , same problem.

**Comment by sylar-my** [comment]
@mattrose Sorry for my comment is not completed. My default shell is `/usr/bin/zsh` and zsh shell was launching . I am so excited for your reply please!

**Comment by mattrose** [comment]
Umm, Can you explain:

What Linux Distro you're using
What display layer are you using (Wayland or X11)
What window manager or Desktop Environment you're using

Basically, there should be no difference between what you're doing normally to start terminator, and the command line I gave you, so the fact that these differ is that whatever you're doing is not starting terminator correctly.  I'm tempted to just tell you that if terminator starts correctly from the command line, we've proven it works.  But I won't, yet...

If you had filled out the issue template properly we would have known this much sooner.

**Comment by mattrose** [comment]
closed for non-response

**Comment by haozhou-wong** [comment]
same error, using zsh in ubuntu24.04

**Comment by shuangmuaigwu** [comment]
1. ubuntu20.04 
2. x11
3. gnome
Similarly, there is no reuse of system proxy.
