### ISSUE TITLE
Question - key bindings for Search

### ISSUE THREAD

**Issue by yuriw** [gnome-terminator/terminator#48]
Is it possible to assign key bindings to perform `Next` ad `Prev` search ?

**Comment by lazyfrosch** [comment]
Currently <Enter> will jump to the next search, I would expect <Shift+Enter> to go in reverse.

I don't think there are other bindings right now, it requires focus in the search bar

**Comment by yuriw** [comment]
it'd be nice to have !

**Comment by mattrose** [comment]
fixed in #903
