### ISSUE TITLE
Terminator unable to start on freh debian 11 (Bullseye)

### ISSUE THREAD

**Issue by Naik-NLZ** [gnome-terminator/terminator#489]
When I try to launch Terminator on fresh debian 11 I get following error:

`(terminator:67932): Gtk-WARNING **: 09:10:22.504: Theme parsing error: gtk.css:5:24: The style property GtkRange:stepper-size is deprecated and shouldn't be used anymore. It will be removed in a future version

** (terminator:67932): WARNING **: 09:10:22.571: Binding '<Control><Alt>a' failed!
Unable to bind hide_window key, another instance/window has it.
Traceback (most recent call last):
  File "/usr/bin/terminator", line 129, in <module>
    TERMINATOR.create_layout(OPTIONS.layout)
  File "/usr/lib/python3/dist-packages/terminatorlib/terminator.py", line 285, in create_layout
    window, terminal = self.new_window()
  File "/usr/lib/python3/dist-packages/terminatorlib/terminator.py", line 208, in new_window
    terminal = maker.make('Terminal')
  File "/usr/lib/python3/dist-packages/terminatorlib/factory.py", line 93, in make
    output = func(**kwargs)
  File "/usr/lib/python3/dist-packages/terminatorlib/factory.py", line 105, in make_terminal
    return(terminal.Terminal())
  File "/usr/lib/python3/dist-packages/terminatorlib/terminal.py", line 199, in __init__
    self.reconfigure()
  File "/usr/lib/python3/dist-packages/terminatorlib/terminal.py", line 723, in reconfigure
    self.vte.set_cell_height_scale(self.config['line_height'])
gi.repository.GLib.Error: g-invoke-error-quark: Could not locate vte_terminal_set_cell_height_scale: 'vte_terminal_set_cell_height_scale': /usr/local/lib/libvte-2.91.so.0: undefined symbol: vte_terminal_set_cell_height_scale (1)`

The same happens when launched with empty config as suggested.
The version is 2.1.0

Thanks!

**Comment by mattrose** [comment]
Can you confirm what version of vte you have?  is it 0.52 or greater?

**Comment by mattrose** [comment]
Something in the traceback leads me to believe that something is wonky with this install:

```
gi.repository.GLib.Error: g-invoke-error-quark: Could not locate vte_terminal_set_cell_height_scale: 'vte_terminal_set_cell_height_scale': /usr/local/lib/libvte-2.91.so.0: undefined symbol: vte_terminal_set_cell_height_scale (1)`
```

libvte should NOT be installed in /usr/local/lib unless you really know what you're doing.

**Comment by mattrose** [comment]
It looks to me like there is an old version of libvte installed in /usr/local but this does not equate with the statement that this is a fresh install of debian 11.  Need more info to help further

**Comment by Naik-NLZ** [comment]
sorry for not making this clear enough. I dist-upgraded from buster to bullseye and both terminator and vte had been installed before. I will trie to get rid of vte and install it from the repos again to see what happens.

**Comment by mattrose** [comment]
Unless you have a **really** good reason for that vte lib to be in /usr/local I would remove it, as it is likely a really old version that does not support newer api calls that terminator depends upon.  I'm going to close this, as, on a stock debian 11 install it works fine.  If you need more help you can ask in https://gitter.im/gnome-terminator/community but I'm not going to promise to be able to resolve it there.
