### ISSUE TITLE
suppor for sixel graphics

### ISSUE THREAD

**Issue by cesarpachon** [gnome-terminator/terminator#492]
Hello, I tried to use the lsix project  (https://github.com/hackerb9/lsix) to be able to see thumbnails of pictures right in Terminator (Ubuntu) ,
but I get this error:

Error: Your terminal does not report having sixel graphics support.

It is possible to add support for sixel graphics to Terminator?

**Comment by mattrose** [comment]
Sixel support is being worked on as part of the GNOME vte library project.  I think they were hoping to release it as part of 0.66, but  I see now it's not quite ready.  If you want to see how this is progressing you can follow https://gitlab.gnome.org/GNOME/vte/-/tree/master

**Comment by Tyler-Hardin** [comment]
@mattrose, it's implemented and working in master but they keep refusing to release it without extensive tests. Currently I'm building and installing it manually from git and doing the same with terminator, plus a 2 line patch to terminator. All it requires is vte.set_enable_sixel(True) on each vte instantiation (I count two places in the code where that happens).

Would you see an issue with preemptively changing Terminator to enable sixel when it's available? I could submit a merge request, but you wouldn't be able to easily test that it works on your end (only that it doesn't break anything, is a np-op).

https://lazka.github.io/pgi-docs/Vte-2.91/classes/Terminal.html
