### ISSUE TITLE
Bash completion

### ISSUE THREAD

**Issue by abrzozowski** [gnome-terminator/terminator#495]
Is available a bash completion for the gnome-terminator? If not, what do you think about adding a bash completion to the gnome-terminator?

**Comment by mattrose** [comment]
Closed for lack of response

**Comment by abrzozowski** [comment]
@mattrose Sorry for the lack of response, I have been on the holiday.

> What kind of completions are you looking for? 

It will be nice if completion works, in my case for 

`terminator -p <TAB>`

suggesting available profiles or even available options
