### ISSUE TITLE
Terminator slow to close if xclip was invoked

### ISSUE THREAD

**Issue by boltronics** [gnome-terminator/terminator#503]
**Describe the bug**
I use the pass password manager in terminator, which in turn uses xclip. In terminator/pass/xclip that shipped with Debian Buster would allow me to run `pass -c somepassword`, hit `Ctrl+d` (or type `exit`), and terminator would exit instantly and I'd have the password temporarily pasted to the clipboard.

Since upgrading to Debian bullseye (which includes terminator 2.1.0), terminator will now hang for about 3 seconds before terminating. Just like the movie, terminator seems unable to self-terminate - at least not immediately. :smile: 

I have tried running `python3 ./terminator` directly from the git master branch as of `d57314ca6ca567ade21e5b6c65e9af2e13997bee` which also has the problem.

**To Reproduce**
Inside terminator, run `echo test | xclip ; exit`

Compare how long it takes to terminate compared to just running `exit` by itself.

**Expected behavior**
Instant termination of terminator, just as it used to. Other terminal emulators I've tried (including the classic [xterm](https://invisible-island.net/xterm/xterm.html)) don't seem to have the problem.

**Desktop (please complete the following information):**
Debian GNU/Linux 11, Bullseye, amd64.

**Comment by mattrose** [comment]
Ugh, this seems to be a vte bug, as it also happens in Tilix and gnome-terminal, but not in xterm.  You could try downgrading to vte-0.62 or so to see if that fixes the problem. 

I'm going to open a bug against vte and update this issue with that link

**Comment by mattrose** [comment]
opened https://gitlab.gnome.org/GNOME/vte/-/issues/2510  

There's not much else I can do in this issue, though I will work through the issue with the vte folks as best I can.  I'm going to close this, but that doesn't mean that I won't try and help the vte folks.
