### ISSUE TITLE
hide_window mapped with Shift+Control+Alt+$an_alphabet catches Control+Alt+$an_alphabet instead

### ISSUE THREAD

**Issue by tomty89** [gnome-terminator/terminator#509]
**Describe the bug**
If the keymapping of `hide_window` is set to `Shift+Control+Alt+$an_alphabet`, the keystroke will be ignored and`Control+Alt+$an_alphabet` will be made to trigger hide_window instead. This occurs with (but most likely not limited to) the default `Shift+Control+Alt+A` and `Shift+Control+Alt+H`.

The problem appears to be `hide_window` specific. It does not occur with e.g. `layout_launcher`.

For the record, changing `edit_tab_title` away from `Control+Alt+A` (its default) does not make the problem go away.

**Desktop (please complete the following information):**
 - OS or Linux Distribution: Arch Linux
 - Terminator Version 2.1.1

**Comment by Vulcalien** [comment]
Relevant code: (window.py, line 135)

```py
self.hidebound = Keybinder.bind(
    self.config['keybindings']['hide_window'].replace('<Shift>',''),
    self.on_hide_window)
```

**Comment by tomty89** [comment]
@sboddy Could you provide any details about the commit?

**Comment by Vulcalien** [comment]
I don't think they work on Terminator anymore, that commit is 5 years old. It's supposed to fix the shift keys, I guess. However, if I remove the `replace`, it won't work at all. It might be an outdated library, or something has changed in these years.

**Comment by tomty89** [comment]
It's odd that it's only a problem with `hide_window` though. Anyway, I guess we can/should at least changes the default of `hide_window` to something else (e.g. Ctrl+Alt+H?) unless someone has a better fix. To be honest, this replace fix hardly makes senses anyway (it's literally worse than a FIXME comment...).

**Comment by Vulcalien** [comment]
I agree, the default should be different if we don't manage to fix this. hide_window is binded in an different way than all the other keybindings: it's a system-wide bind, because when the window is hidden, it must catch the keys even without focus. I'm reading the documentation, maybe I can see what we are doing wrong.

**Comment by Vulcalien** [comment]
The best documentation I found is the comments in the code. They are pretty good.

From [this](https://github.com/kupferlauncher/keybinder/blob/master/libkeybinder/bind.c):
> "Cooked" accelerators use symbols produced by using modifiers such as shift or altgr, for example if "!" is produced by "Shift+1".

```py
keybinder_set_use_cooked_accelerators
```

This seems connected to our problem.

**Comment by Vulcalien** [comment]
I made a patch to fix the issue. It should work as expected now, thanks for reporting the problem!

**Comment by awvalenti** [comment]
Hello. I just experienced this issue again:

Terminator was capturing my Ctrl Alt A usage from another app and executing `hide_window`, which was by default mapped to Ctrl Shift Alt A.

Ctrl Alt A was mapped by default to `edit_tab_title`.

I simply disabled both shortcuts for now.
