### ISSUE TITLE
Find functionality does not show matches on same line

### ISSUE THREAD

**Issue by fenilgmehta** [gnome-terminator/terminator#511]
**Config file**
[config.txt](https://github.com/gnome-terminator/terminator/files/7152490/config.txt)

**Describe the bug**
When terminator is fullscreen, and multiple matches of the same string fall on the same line, terminator does not find all. It only highlights/finds the first match and then moves to the next line.

**To Reproduce**
```bash
var='/home/student/miniconda3/envs/dev/bin:/home/student/miniconda3/condabin:/home/student/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/usr/local/go/bin:/home/student/golib/bin:/home/student/bin:/home/student/Desktop/myapps/cling/bin'
echo $var

# Make the terminator window occupy full screen
# Now, search for "bin", it will only search for first occurrence of the word "bin" on each line visible (irrespective of where \n character is)

# Now make the terminator window occupy only 1/3 or 1/2 part of the screen, and search for "bin"
```

**Expected behavior**
The search functionality should be able to match multiple occurrence of the search string on the same line as well.

**Desktop**
 - Linux Mint 20 Cinnamon
 - Version 4.6.7

**Comment by Vulcalien** [comment]
This seems to be a bug (?) on `vte`. Gnome Terminal and Tilix have this problem as well.

Reference:
https://gitlab.gnome.org/GNOME/vte/-/issues/220

**Comment by mattrose** [comment]
Ugh. I'm going to label this as "Upstream" and close it.  Even if I hunt through VTE code and try to find the source of it, and in the even less likely case that I find a fix (it being open for so long), there's no guarantee they'll merge.  I'll keep an ongoing monitor on upstream bugs in case they ever get resolved.
