### ISSUE TITLE
Auto-scroll to the cursor position when typing

### ISSUE THREAD

**Issue by marktimarev** [gnome-terminator/terminator#513]
In the Terminal, if you scroll up and then start typing, then the terminal automatically scrolls down to the cursor position. It's really convenient since I do not need to scroll down myself every time I checked some long output and want to issue another command.
Since I started to use Terminal I miss that feature and trying to keep in mind I need to scroll down before typing.

**Comment by mattrose** [comment]
Interesting, I went to look at your PR and this works as described, even before applying your PR.  Can you be a little bit more specific about the environment you find yourself having this problem?

**Comment by marktimarev** [comment]
Hmm

Well, I just checked out to the current HEAD (before my commits). Then I run the app with `python3 terminator`.
As the window appear, I hold the enter key for a while to make many lines. Then, I scroll up so that the last line is not visible. And here is the problem: if type something, then nothing happens at all, and if I manually scroll down to the last line I will see characters appeared as the result of my typing. So, what I want is that if I type and the last line is not visible, it should scroll down automatically.

Does it really work as expected for you? Maybe it's something about the version VTE or some another package on my machine then..

**Comment by marktimarev** [comment]
![example](https://user-images.githubusercontent.com/86591723/133657384-fd9196cd-fb6a-4a96-aa53-852181abfb1a.gif)

**Comment by mattrose** [comment]
Sorry to say it really does work as expected for me.  It could be VTE, or window manager, or something else I haven't thought of.

**Comment by marktimarev** [comment]
Ok, let's close it then, seems I just got unlucky.
