### ISSUE TITLE
keybinding <Shift><alt>braceright/braceleft not work

### ISSUE THREAD

**Issue by shaofeng66** [gnome-terminator/terminator#521]
also tried 
  next_tab = <Shift><Alt>bracketright
  prev_tab = <Shift><Alt>bracketleft

Below is my config

[global_config]
  window_state = maximise
  borderless = True
  inactive_color_offset = 0.7083333333333334
[keybindings]
  new_tab = <Primary>t
  cycle_next = None
  cycle_prev = None
  copy = <Alt>c
  paste = <Alt>v
  next_tab = <Shift><Alt>braceright
  prev_tab = <Shift><Alt>braceleft
[profiles]
  [[default]]
    cursor_color = "#aaaaaa"
    scrollback_infinite = True
[layouts]
  [[default]]
    [[[window0]]]
      type = Window
      parent = ""
    [[[child1]]]
      type = Terminal
      parent = window0
[plugins]

**Comment by mattrose** [comment]
Hi, When I push the Shift+Alt+{ keys in the keybindings window, I get the following:
![image](https://user-images.githubusercontent.com/65013/145094964-a972a4a1-0342-44eb-9a2d-bb29989e2e30.png)

Which ... makes sense to me.  The Shift modifier is superfluous there, I think.

**Comment by mattrose** [comment]
Ah, see also #549 as it might be causing your problem as well.
