### ISSUE TITLE
Change the color of the current tab to highlight it better

### ISSUE THREAD

**Issue by qqlovekerry** [gnome-terminator/terminator#522]
**Is your feature request related to a problem? Please describe.**

I have been using Terminator for many years. Thanks very much for providing the excellent tool!
The problem is that I found that the current tab is slightly highlighted by the current tab is slightly more bright. But I feel it is still not very clear to distinguish between the current working tab and the others. And I did not find an option in `Preferences` to configure it.

**Describe the solution you'd like**

If there would be an option to change the color of the current working tab or some other ways can make the current working tab more distinguishable, that would be very helpful.

**Describe alternatives you've considered**

**Additional context**

**Comment by mattrose** [comment]
Unfortunately the color of focused and unfocused tabs is a property of your GTK theme,  We put a small blue bar on the bottom to help better differentiate, but I don't want to go any further than this for a number of reasons (ask me on gitter if you're curious)

However, having said that, I have made fairly easy-to-follow instructions on how to make the tabs more distinctive at https://gnome-terminator.readthedocs.io/en/latest/faq.html#make-the-active-tab-more-distinctive

**Comment by qqlovekerry** [comment]
@mattrose Hello, thank you very much for the reply! That really helps a lot.
Could you please help me with one more question? How do I know whether gtk-2.0 or gtk-3.0 is used for my current version Terminator? I am currently using Ubuntu 18.04 LTS.
Thanks in advance!

**Comment by qqlovekerry** [comment]
@mattrose Hello, I found that the instruction works very well for me. Please ignore my previous comment. Thank you very much!
