### ISSUE TITLE
altgr keybinds do not work. 

### ISSUE THREAD

**Issue by benibilme** [gnome-terminator/terminator#526]
Hello,

Any keybind with alt-gr do not work in my system. I am using manjaro.

I specifically want to change Alt+arrow combinations to AltGr + Arrow since I have switched the Alt and AltGr in my keyboard layout which let me use two hand with mostly used programming characters such as {},[] etc. 

I am not sure if this is a bug or not.

**Comment by mattrose** [comment]
None of my keyboards have an AltGr key, so ... PRs are welcome :)

**Comment by mattrose** [comment]
Closing.  if this is still a problem please re-open with the requested info.
