### ISSUE TITLE
Crash everytime after encoding is changed to TCVN

### ISSUE THREAD

**Issue by santiagofn** [gnome-terminator/terminator#529]
**Describe the bug**

After character encoding is changed to Vietnamese TCVN and Terminator is closed, it will crash whenever you try to open it again.

**To Reproduce**

1. Go to Preferences > Profiles > Compatibility
1. Change "Encoding" to Vietnamese TCVN
1. Close Terminator
1. Open terminator again

Terminator won't open

**Expected behavior**

Terminator will open using the new encoding.

**Desktop (please complete the following information):**
 - Linux Distribution: Ubuntu
 - Version: 21.10

**Additional context**

Terminator version: 2.1.0

[debug info.txt](https://github.com/gnome-terminator/terminator/files/7423276/debug.info.txt)
[config.txt](https://github.com/gnome-terminator/terminator/files/7423285/config.txt)

**Comment by mattrose** [comment]
This is way out of my expertise, but I've opened https://gitlab.gnome.org/GNOME/vte/-/issues/2522 and hopefully somebody there can help point the way

**Comment by mattrose** [comment]
Did a little bit more digging and it appears that you should just use UTF-8, which can render Vietnamese properly given  the right locale

**Comment by santiagofn** [comment]
Thanks for the investigation, Matt! 
Yeah, it was in a completely random way that I ended up with that TCVN encoding, I always use UTF-8. But after discovering it was making Terminator crash I thought it was worth opening a bug.
