### ISSUE TITLE
group broadcasting switched on/off for all groups

### ISSUE THREAD

**Issue by atommaki** [gnome-terminator/terminator#532]
**Describe the bug**
When you have different windows with different groups and you turn on group broadcasting (Alt-g) it turns on the group broadcasting for all groups, not only for the one you currently using.

**To Reproduce**
Open 4 terminals in terminator (eg: with split window). Put them to 2 groups (2-2), like "Alpha" and "Gamma". Now activate one of the terminal in the Alpha group, press Alt-g for group broadcasting. That works fine, both of the terminals in the Alpha group has the same input.
Now activate one of the terminal in the Gamma group, start typing and you see the broadcasting is on for this group as well.

**Expected behavior**
When I turn on group broadcasting that should activate group broadcasting only for the currently active group. I am not sure if it is a bug or a design issue, but I believe it is an issue. The current behaviour is confusing and I don't really see the usecase when it would be helpful this way.

**Comment by mattrose** [comment]
You want to change this setting in Preferences to None.  
![image](https://user-images.githubusercontent.com/65013/139966575-584ac7af-b4e5-46a7-bddc-cd97e9149837.png)

**Comment by atommaki** [comment]
I am not sure what is this settings for, but doesn't change the behaviour what I described above.

**Comment by mattrose** [comment]
If it's not that, I can't reproduce your issue.  Everything works as I expect it, and my keystrokes are only broadcast to the group that I specify.

**Comment by atommaki** [comment]
That is not the problem. The broadcasting works fine, when I start the group broadcasting keystrokes only broadcasted to the other terminals of the current group. This is OK.

My problem is when I turn on the broadcasting for one group, I not necessarily want to switch it on for all the groups (honestly I don't see the real usecase when I would like that).  With other words: when I use broadcasting for one group, then I click into other terminal window where I have another group I don't want active broadcasting there.

I believe now it is not a bug, but a design failure.
