### ISSUE TITLE
Vte.Terminal().set_encoding deprecated

### ISSUE THREAD

**Issue by mattrose** [gnome-terminator/terminator#534]
We should remove the encoding section from the context menu and the "Profiles->Compatibility" tab, as support for different encodings has been deprecated, and only UTF-8 is supported

**Comment by pkreuzt** [comment]
Sorry to necrobump this issue, but I'm confused about it. Gnome-terminal, Xfce4-terminal and other terminals using VTE (2.91 in my distro) still support multiple encodings. They don't support fast change via context menu as in Terminator, but they never did. I've been reading VTE's Gitlab and didn't find references to this. Am I missing something ¿!?

**Comment by mattrose** [comment]
According to docs this has been deprecated for years now.  https://lazka.github.io/pgi-docs/#Vte-3.91/classes/Terminal.html#Vte.Terminal.set_encoding

**Comment by pkreuzt** [comment]
It hasn't been removed from VTE' master (yet). Then, everyone else is relying on a doomed function? The recommended luit workaround doesn't allow to change encoding on a running shell on the fly. This seems to be important for a number of users, according to issues and comments here.
