### ISSUE TITLE
Split vertical keyboard don't work on debian 11

### ISSUE THREAD

**Issue by lucieb31** [gnome-terminator/terminator#535]
**Describe the bug**
I updated my debian version to debian 11 and the keyboard to split vertically the terminal on terminator doesn't work anymore. It's write a 'e' on the line.

**To Reproduce**
Use Ctlr+Shift+e on terminator command line

**Expected behavior**
Terminal splitted vertically

**Screenshots**
![2021-11-05 15_00_56-Debian 10  Running  - Oracle VM VirtualBox _ 1](https://user-images.githubusercontent.com/34625336/140522610-b5462698-b2c5-4570-8384-244d81f93012.png)

**Desktop (please complete the following information):**
 - OS or Linux Distribution: Debian
 - Version 11.1

**Comment by Vulcalien** [comment]
Hi! It might be a problem with the keybindings, could you share the config file with us?
It's located in `~/.config/terminator/config`.

**Comment by Vulcalien** [comment]
I think it might be the emoji shortcut. You could check by running the `ibus-setup` command > Emoji menu > Emoji annotation.
This might be the same issue as #25

**Comment by lucieb31** [comment]
Yes it's work. Thanks :)
