### ISSUE TITLE
remotinator split and execute command — cannot determine uuid

### ISSUE THREAD

**Issue by caprinux** [gnome-terminator/terminator#537]
Essentially I was interested in the split and execute a command feature from #446, I installed from the source with instructions given.

Here's the error:

![image](https://user-images.githubusercontent.com/76640319/141089370-845da012-b5e8-439d-abfa-f47407500502.png)

**Desktop (please complete the following information):**
 - Ubuntu 20.04

Do you have any idea how I could fix this?

Here's a successful vsplit output if it helps:

![image](https://user-images.githubusercontent.com/76640319/141090088-26ceb66a-e8ff-4122-b5bc-149fc53a1884.png)

**Comment by mattrose** [comment]
Hmm, does it work if you give it a Title?  `remotinator vsplit -T test -x ls`

**Comment by caprinux** [comment]
Nope :/ 
![image](https://user-images.githubusercontent.com/76640319/141234461-ba4c1e55-6a5c-4aae-9ae2-ef1d017ef75c.png)

**Comment by caprinux** [comment]
I see the problem now, it seems that after the split terminal executes the command, it immediately closes as soon as it's done.

If I split and execute a program like GDB, the split-screen is successful and closes as soon as I exit GDB.

Perhaps like other terminals, we could introduce a -hold flag which runs a splits a terminal, executes a command, and keep the terminal open even after the command is complete.

**Comment by mattrose** [comment]
Cool, can I close this in the meantime or do you want me to keep it open for you to refer to in your PR.

**Comment by caprinux** [comment]
We can close it for now :) Thanks!
