### ISSUE TITLE
Change separator color

### ISSUE THREAD

**Issue by dshibanov** [gnome-terminator/terminator#538]
Can anybody explain how to change separator color? 

![image](https://user-images.githubusercontent.com/5215047/141650093-6982f84f-efc6-4951-867b-deb82a7572d0.png)

 - Fedora Linux 32
 - X11

**Comment by mattrose** [comment]
Color is GTK Theme dependent, and size is configurable in Preferences.  NB: 1 is the smallest size: 0 and -1 are the default separator size and usually wider.
