### ISSUE TITLE
CommandNotify plugin doesn't work on zsh

### ISSUE THREAD

**Issue by pogossian** [gnome-terminator/terminator#541]
Problem: see the title

fedora 35 / wayland

**Comment by mattrose** [comment]
Do you have your precmd_function set properly in zsh?

**Comment by pogossian** [comment]
Noo, how can I do that in zsh?

**Comment by mattrose** [comment]
Read the comments in the plugin.  https://github.com/gnome-terminator/terminator/blob/a21575b0aba1babfeac7bb306d5634a0cc414404/terminatorlib/plugins/command_notify.py#L2
