### ISSUE TITLE
Will terminator ever consider picking up ligature support?

### ISSUE THREAD

**Issue by caprinux** [gnome-terminator/terminator#543]
Ligatures are essential and a game-changing feature for many people who use the terminal especially developers.

We could look into using the Harfbuzz library to implement ligatures for Terminator. 

What do you think?

**Comment by mattrose** [comment]
Font support is provided by vte, which doesn't support ligatures, and, I'm gonna say, is not likely to in the near future.  See https://gitlab.gnome.org/GNOME/vte/-/issues/192 for more ugly details.

**Comment by mattrose** [comment]
Not saying I'm particularly happy about this, but I don't have time to fork my own vte (as tempting as that is) and start adding features as tricky as ligatures.

**Comment by Felixoid** [comment]
Hey. Just wanted to say that the issue https://gitlab.gnome.org/GNOME/vte/-/issues/1661 looks a bit more relative
