### ISSUE TITLE
None isn't a valid value of keybindings config anymore

### ISSUE THREAD

**Issue by Felixoid** [gnome-terminator/terminator#548]
Fill out as many of these fields as you can

**Describe the bug**
`None` value in `[keybindings]` settings breaks the ability to set the keys.

**To Reproduce**
1. Set `cycle_next = ""` - and launch terminator, try to change the key binding for anything. It works as expected  of shows a dialogue `X already in use to trigger Y`
2. Set `cycle_next = None`, now it's broken. I have config from an ancient version 2 years ago, back there it was a valid value

**Expected behavior**
I'd like to have the config backward compatible.

**Desktop (please complete the following information):**
 - OS or Linux Distribution: Arch Linux
 - Version terminator 2.1.1-2
 - Display Technology: X11

**Additional context**
```
# logs for "" value
> terminator -u -g /tmp/term.config 

** (terminator:17429): WARNING **: 11:53:19.939: Binding '<Control><Alt>a' failed!
Unable to bind hide_window key, another instance/window has it.
<window.Window object at 0x7fe96198c540 (terminatorlib+window+Window at 0x55aeffa66280)> is not in registered window list
# logs for None value
> terminator -u -g /tmp/term.config   

** (terminator:17261): WARNING **: 11:52:54.237: Binding '<Control><Alt>a' failed!
Unable to bind hide_window key, another instance/window has it.
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/terminatorlib/prefseditor.py", line 1719, in on_cellrenderer_accel_edited
    parsed_conf_accel = Gtk.accelerator_parse(conf_accel)
TypeError: Argument 0 does not allow None as a value
```

**Comment by Vulcalien** [comment]
Hi! Thanks for bringing this up.
I could reproduce the bug, it shouldn't be hard to fix.
