### ISSUE TITLE
Switch focus and splits don't work when terminal is zoomed

### ISSUE THREAD

**Issue by Felixoid** [gnome-terminator/terminator#550]
**Is your feature request related to a problem? Please describe.**
When a tab has few terminals and one is zoomed, switching to any direction doesn't work. There are different approaches in different emulators:

- tmux cancels zoom and switch to another pane
- kitty remains zoomed, but switch the pane to the next/previous one

**Describe the solution you'd like**
I'd prefer tmux approach, when focus change is triggered, it's better to zoom out the current terminal and then switch

**Describe alternatives you've considered**
Kitty's approach would work as well. The zoom can be preserved during a terminal focus switch

**update**: the same case is for splits. It seems logical to me to exit zoom mode and split terminal. And the same for tab switching.

**Comment by Vulcalien** [comment]
I'm working on this. I've implemented a surprisingly clean solution for splits and new tabs. Still working on the 'switch to tab' thing.

As a side note: un-zooming a terminal when there are tabs, makes the background opaque.
