### ISSUE TITLE
Enabling "putty style paste" causes context menu to be unreachable with 2-button mouse

### ISSUE THREAD

**Issue by rcedgar** [gnome-terminator/terminator#565]
The bug title should be self-explanatory. I installed terminator on Ubuntu 20.04.3 because I want copy-on-select. This did not work in the initial installation, so I tried selecting "putty style paste". (Strictly, I could copy-on-select and paste back into a terminator window, but paste into other apps did not work). After "putty style paste" was enabled, I could not reach the context menu because right-click is paste and I have no middle button. From reading the documentation, best I can tell there is no other way to reach the context menu, so terminator is hosed. Removing and re-installing terminator did not fix the problem, presumably because uninstalling fails to remove the config file and/or re-installing fails to reset defaults. This seems to be a fatal design flaw for people with 2-button mouses, apologies if I missed the workaround -- if so, please consider this post a feature request for alternative shortcuts to access the context menu.

**Comment by Vulcalien** [comment]
Hi! There is a quick solution: go to `~/.config/terminator/config` and delete the line `putty_paste_style = True`.

The Copy on Selection feature already exists, it's in the Profile>General menu. I think it's what you are looking for.

That's an interesting problem however, the fact that enabling putty might lock some users out of the preferences menu.

**Comment by rcedgar** [comment]
:+1: thanks!
