### ISSUE TITLE
Middle click paste in 1.92

### ISSUE THREAD

**Issue by nierdz** [gnome-terminator/terminator#57]
Since I updated to last release (1.92) from 1.91 the middle click paste is not acting the same way.
Before, I could select text from another window and middle click in terminator pastes this selected text.

This is related to this very commit 42fecfd5c626b964aefb8b08fc18335e9110e36a as when I remove it, it works as usual.

Is this working as intended or is it a regression ?

**Comment by mattrose** [comment]
Hmm, looks like this code was committed to be able to pass through middle mouse clicks to tmux or other TUIs that did stuff with the middle mouse-click.  It might not be detecting the mouse settings in the TUI application correctly.  I'll take a look

**Comment by mattrose** [comment]
This is the bug where this was fixed https://bugs.launchpad.net/terminator/+bug/1647507

**Comment by mattrose** [comment]
Nierdz Can you see if the latest master code fixes the issue.  @lazyfrosch just pulled in a patch from @fonzinc that fixes this issue on wayland.

**Comment by nierdz** [comment]
Thanks @mattrose I didn't see that commit in master.
It perfectly works ! :thumbsup:

**Comment by lazyfrosch** [comment]
duplicates #24
