### ISSUE TITLE
Can't add/remove terminal panes from layout editor

### ISSUE THREAD

**Issue by 0xnullb** [gnome-terminator/terminator#572]
I'm trying to create a custom layout, but unless I'm missing something, there doesn't seem to be a way to add terminal panes to the layout in terminator. See the screenshot below:

![image](https://user-images.githubusercontent.com/98149467/150545831-09adbabb-a6f0-4414-82c3-7c971eb6a1fa.png)

I have a layout called `Layout 1`, and I would like terminator to open up with 4 terminals when I choose this layout.

At the moment, there is only 1 terminal and there doesn't seem to be a way to add a new one. I am aware that I can edit the layout in `~/.config/terminator/config`, but it would be much easier if I could use the layout builder within Terminator, since it is a lot easier to work with than editing the config file, and that is what it was created for.

I'm currently using Terminator 1.91 on Ubuntu 20.04, which comes from the software repository for Ubuntu, which I install with `apt install terminator`. I tried downloading the latest version of terminator, but there still appears to be no way of adding terminals in the layout.

There is also supposed to be the ability to load the layout from a JSON file in the latest version, but there didn't seem to be any command line option for this. I also tried loading a layout from a JSON file using `terminator --layout layout.json`, but it doesn't seem to be able to recongize the JSON file.

I would preferably like to use the built in layout editor within the GUI if possible, but if there is another another option, that's fine.

Below is the layout that I am trying to achieve:

![image](https://user-images.githubusercontent.com/98149467/150736066-5d8cdf3f-670e-47c9-b471-7a33d3e5e429.png)

**Comment by Vulcalien** [comment]
I think what you are referring to is already implemented.

The `Add` button adds the "current" layout to the list of layouts.
The `Save` button instead overwrites the selected layout, saving the "current" layout.

To change the default, do this:
- open a fresh terminator window
- build the layout, splitting terminals and/or adding tabs
- go to preferences>layouts
- select `default`
- press `Save`

**Comment by 0xnullb** [comment]
I just tried this now and it works perfectly, thank you so much.

I think it just wasn't clear enough to someone whose new to terminator, so it would be awesome if it could be documented :)
