### ISSUE TITLE
Terminator need to highlight search string

### ISSUE THREAD

**Issue by mathiasbarreto** [gnome-terminator/terminator#575]
**Is your feature request related to a problem? Please describe.**
When I search for code, there is no visual indication of where it is. 

It indicates the row,  but its' hard to locate the row, because there is no numbered rows in it either.

**Describe the solution you'd like**

Wrap and highlight my search so I can see it, like the native ubuntu terminal.

**Describe alternatives you've considered**

Use the native one

**Additional context**
![image](https://user-images.githubusercontent.com/61096828/151565928-735fa087-75b0-419a-9f98-d053d4d0ed12.png)

**Comment by Vulcalien** [comment]
Hi! Could you tell us the version of Terminator? `terminator -v`. That might be an older version.

My interface is different, and I think what you want is already implemented (I searched the word, and pressed "enter" and it got highlighted).

![image](https://user-images.githubusercontent.com/47713809/151590392-5950a62d-ee89-4a82-b17d-1ff7dc6f6488.png)

**Comment by mathiasbarreto** [comment]
Great! right on the spot. I've updated it, and it worked. Many thanks!!
