### ISSUE TITLE
UTF-8 character breaks terminator config file

### ISSUE THREAD

**Issue by brean** [gnome-terminator/terminator#577]
**Describe the bug**
After adding an UTF-8 character to the config file (e.g. in a custom command) terminator is not able to save the config file anymore and instead empties it.

[terminator.txt](https://github.com/gnome-terminator/terminator/files/7979721/terminator.txt)

**To Reproduce**
1. load the attached terminator.txt-file, e.g. `terminator -g terminator.txt`.
2. Right click -> Preferences
3. change anything (e.g. save the layout)
4. take a look at the terminator.txt-file. It is empty now.

**Expected behavior**
The terminator.txt file should not be empty, instead the configuration should be saved correctly

**Screenshots**
(not applicable)

**Desktop (please complete the following information):**
 - Distros: Ubuntu
 - Versions: 20.04
 - Display Technology: X11
 - Terminator Version: 1.91

**Additional context**
I am getting this error message:
ConfigBase::save: Unable to save config: 'ascii' codec can't encode character '\u2757' in position 165: ordinal not in range(128)

(I have not tried any other UTF-8 characters beside the heavy exclamation mark)

**Comment by Vulcalien** [comment]
Hi! I can confirm that in version 1.91 the problem occurs in Ubuntu 20.04 (haven't tested anywhere else).
But in the latest version (git repository) it seems to be fixed (tested Ubuntu 20.04 and Debian).

Unfortunately, some distros ship old versions (1.91 is 5 years old).
If the error causes you troubles, I suggest you clone the repository and use the newest version instead.

**Comment by brean** [comment]
Thanks for the update. My Workaround for now is to not use UTF-8 when calling a program. Because it works on the git master I close this issue now.

**Comment by mattrose** [comment]
There's also a PPA I maintain that you can use to get more recent versions.  Instructions are in INSTALL.md
