### ISSUE TITLE
terminator for MacOS user

### ISSUE THREAD

**Issue by merceskoba** [gnome-terminator/terminator#578]
**Describe alternatives you've considered**
I would like to request terminator terminal be available for MacOS. I love this terminal and really appreciate your hard work guys for developing it.

If you have recommendation for macOS user to replace its basic terminal, kindly tell me what that is.

Thank you

**Comment by mattrose** [comment]
If you have homebrew (https://brew.sh) you can install terminator on macOS by just doing `brew install terminator`.  It's very rough right now as I haven't had time to wrap a nice gui around it, but you can use terminal.app to fire it up, or use platypus (https://sveinbjorn.org/platypus) to make a semi-nice gui for it.  I'd love PRs to help me polish it up as well.
