### ISSUE TITLE
Unable to load Keybinder module

### ISSUE THREAD

**Issue by crimson-med** [gnome-terminator/terminator#580]
Before opening an issue, please try starting terminator with an empty config
file, by issuing `terminator -u -g /dev/null` and see if it starts normally.

If it does, and you still want to open the bug, then please attach the
config file, usually found at `$HOME/.config/terminator/config` to the issue

Fill out as many of these fields as you can

**Describe the bug**

I installed terminator on mac and it doesn't launch

**To Reproduce**

- `brew install terminator`
- in terminal launch terminator with command: `terminator`

Following error appears:

```
kuhaku@s-MacBook-Air ~ % terminator
ConfigBase::load: Unable to open /etc/xdg/terminator/config ([Errno 2] No such file or directory: '/etc/xdg/terminator/config')
Unable to load Keybinder module. This means the hide_window shortcut will be unavailable
Unable to bind hide_window key, another instance/window has it.

(terminator:19114): Gtk-WARNING **: 10:52:20.771: Error loading theme icon 'dialog-information' for stock: Icon 'dialog-information' not present in theme Adwaita
PluginRegistry::load_plugins: Importing plugin command_notify.py failed: Namespace Notify not available
ActivityWatch plugin unavailable as we cannot import Notify
PluginRegistry::load_plugins: Importing plugin activitywatch.py failed: module 'activitywatch' has no attribute 'AVAILABLE'
```

**Expected behavior**

terminator should launch

**Screenshots**

<img width="1214" alt="Screenshot 2022-02-14 at 10 52 11 AM" src="https://user-images.githubusercontent.com/28290546/153792113-2a7b8c4a-0883-4698-b207-e2b48e43f443.png">
<img width="834" alt="Screenshot 2022-02-14 at 10 52 33 AM" src="https://user-images.githubusercontent.com/28290546/153792132-15604ff4-a9c4-4349-9853-c81aeecd6eca.png">

**Desktop (please complete the following information):**
 - OS or Linux Distribution: MacOS Monterey
 - Version [e.g. 20.04] 12.2.1
 - Display Technology: unsure

**Comment by mattrose** [comment]
It is launching.  I can see it in the screenshot.  The default font on Mac is terrible, but you can fix it easily in the preferences.

**Comment by dorian-marchal** [comment]
Sorry for the bump, but it is launching indeed, but the `hide_window` doesn't work, like stated in the error message:
> Unable to load Keybinder module. This means the hide_window shortcut will be unavailable

Do you know how I could fix this? I use this shortcut to hide & bring up the terminal.
