### ISSUE TITLE
TERMINAL , Text visibility  issue

### ISSUE THREAD

**Issue by anurag-mehra** [gnome-terminator/terminator#584]
I am facing a problem where the terminal output text , gets hidden not all but between some values , i have checked color schemes its not the problem Also I have updated still nothing goes.. i Have linked a video down you can see here ^ i am using kali linux 2022 with xfce and fully upgraded

https://user-images.githubusercontent.com/72686000/158354769-06b6bca9-1135-4ba8-8932-802b5ffd7813.mp4

_Originally posted by @anurag-mehra in https://github.com/gnome-terminator/terminator/issues/372#issuecomment-1067795543_

**Comment by mattrose** [comment]
Can you reproduce this using xfce4-terminal?

**Comment by mattrose** [comment]
Closed for non-responsiiveness.  Please re-open with a response.
