### ISSUE TITLE
Update the authorship in README

### ISSUE THREAD

**Issue by cmsj** [gnome-terminator/terminator#586]
Hello Terminator maintainers!

I noticed recently that I'm still listed at the top of the README and it struck me that I haven't been involved in Terminator for *many* years at this point, and so it feels a bit unfair to everyone else who has carried the project since I moved on.

Personally I would suggest putting the name of the current maintainer there, but I leave that choice up to you - I'm just here to say that there's no need for my name to still be there :)

**Comment by mattrose** [comment]
So many years, but you're still number one in number of commits and neither Markus and I would have this wonderful program but for your original contribution.  We could modify it to say something like, Originally by cmsj@tenshu, maintained from 2014 to 2020 by Stephen Boddy, currently maintained by Markus Frosch and Matt Rose and many others.  That seems a little wordy, but we could do it if you think that's good.

**Comment by mattrose** [comment]
Btw, good to hear from you!  I've been using terminator since 0.1 and it's made my life as a sysadmin and developer much better, so thank you for starting this.  Apparently I couldn't live without it enough that I offered to take over maintainership of it rather than go without 😄

**Comment by maximstewart** [comment]
@mattrose  I like your wording even though you think it's long. You could also just do a core maintainer list in order of stewardship, their time of service, and of course marking the originator(s) of the project.

**Comment by lazyfrosch** [comment]
Thanks @cmsj for your input, I think we should mention @mattrose as the main maintainer there, all other are mentioned in the AUTHORS file either way.

Or just leave names out there and mention the full list.

**Comment by cmsj** [comment]
I'm fine with any option you choose, whether it mentions me or not.

Thanks for keeping the project alive!
