### ISSUE TITLE
Feature Request: set initial window size in preferences

### ISSUE THREAD

**Issue by w3333** [gnome-terminator/terminator#593]
Hello,

the only thing I miss in Terminator is the possibility to simply set a certain height/width (in characters) of the main window at startup in the preferences. There is only the choice between full screen, which is usually too much, and "normal", which is a tiny window that, for me, is almost always too small. Even the simple Gnome terminal has this option, please add! Thanks.

**Comment by mattrose** [comment]
Just create the layout that you want to start with, and then go to Preferences->Layouts, and click save, and it will save the current layout as the default layout and use it every time you open terminator.
