### ISSUE TITLE
The repository 'https://ppa.launchpadcontent.net/mattrose/terminator/ubuntu jammy Release' does not have a Release file.

### ISSUE THREAD

**Issue by SeeYangZhi** [gnome-terminator/terminator#594]
**To reproduce:**
```
sudo add-apt-repository ppa:mattrose/terminator
sudo apt-get update
sudo apt install terminator
sudo apt-get upgrade
```

**Expected bahavior:**
```
Ign:6 https://ppa.launchpadcontent.net/mattrose/terminator/ubuntu jammy InRelease
Err:7 https://ppa.launchpadcontent.net/mattrose/terminator/ubuntu jammy Release 404  Not Found
Reading package lists... Done
E: The repository 'https://ppa.launchpadcontent.net/mattrose/terminator/ubuntu jammy Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.

```

**Desktop (please complete the following information):**
 - Linux Distribution: Ubuntu 22.04 LTS
 - Codename:	jammy

**Comment by mattrose** [comment]
Whoops, I haven't updated the release for 22.04 yet.  I'll see if I can do that this weekend, but...

22.04 has the most recent version anyways, so you should be able to remove my PPA.

**Comment by nyg** [comment]
I have the same error. It would be really great to have this PPA for Ubuntu 22.04 as well, as the latest version in the main package archive is from 2021 (2.1.1).

https://packages.ubuntu.com/search?keywords=terminator&searchon=names&suite=all&section=all

**Comment by mattrose** [comment]
fixed now.
