### ISSUE TITLE
background images only  displaying on default profile

### ISSUE THREAD

**Issue by JamesB-byte** [gnome-terminator/terminator#595]
If two different profiles both have the option for background image, the image is only displayed for the default profile.  Even if `background_type = image` is listed on a non-default profile, it still only renders the background image of the default. 

**To Reproduce**
on default profile, set background option to background image and select image_1.jpg
on non_default, set background option to background image and select image_2.jpg
Once saved, right click, choose either of the profiles. 

**Expected behavior**
Each profile should have a different image rendering

**Screenshots**
default - 

![z](https://user-images.githubusercontent.com/19785696/165380524-eef0759d-d078-40d7-81ab-33ccd0d3b570.png)
![d](https://user-images.githubusercontent.com/19785696/165381500-a463b88c-b75d-494a-a23b-9ddb340a59bf.png)

non_default -

![a](https://user-images.githubusercontent.com/19785696/165380650-254ea6ef-82b6-4091-ba8d-63f58ea8ecbe.png)
![a](https://user-images.githubusercontent.com/19785696/165381381-67fa7bb2-e36c-428f-981d-4276333910f3.png)

**Desktop:**
 - Ubuntu
 - 20.04.2 LTS
 - X11

**Comment by Vulcalien** [comment]
Hey there! Just checked, and I'm glad to say I fixed that bug in #551.

I could reproduce the bug, but it seems to work fine now.
Since the change hasn't been put in a version yet, you could install from source if you want to use it. (See `INSTALL.md`)
