### ISSUE TITLE
Clickable filepath:rownumber

### ISSUE THREAD

**Issue by dunderrrrrr** [gnome-terminator/terminator#598]
**Is your feature request related to a problem? Please describe.**
File paths printed in the terminal are not clickable.

**Describe the solution you'd like**
Let's say a script outputs the following. Left click the path (or maybe ctrl+left click) and default editor (vscode) would open on correct row number.
```
this/is/a/path/file.py:69
```

**Describe alternatives you've considered**
Preferably this would be a plugin of some sort.

**Comment by mattrose** [comment]
Somebody has already written a plugin https://github.com/mchelem/terminator-editor-plugin

**Comment by dunderrrrrr** [comment]
Awesome, thank you!
