### ISSUE TITLE
Keybinding with digits do not seem to work

### ISSUE THREAD

**Issue by lejeczek** [gnome-terminator/terminator#602]
**Describe the bug**

If I set in 'preferences' keybindings to switch_to_tab_X say: Alt+1 Alt+2 and so on, these do not seem to work.
The same with Ctrl+X

**Desktop (please complete the following information):**

Fedora 36 with default vanilla Gnome
terminator-2.1.1-5.fc36.noarch

thanks, L.

**Comment by Vulcalien** [comment]
Strange enough, I use Alt+1, Alt+2 etc.. to do exactly that.
That might be something specific to your config file, could you send the file `~/.config/terminator/config`?

I'm also thinking it could be something related to alt being caught by the OS instead.

Does Alt+number work on other applications, like firefox, or gnome-terminal...?

**Comment by lejeczek** [comment]
Yes, Alt+a_digit works in gnome-terminal.
Here:

-> $ cat ~/.config/terminator/config
[global_config]
  title_inactive_bg_color = "#f6f5f4"
  always_split_with_profile = True
  title_font = Nimbus Mono PS 6.5
  smart_copy = False
[keybindings]
  switch_to_tab_1 = <Primary><Alt>1
[profiles]
  [[default]]
    cursor_color = "#aaaaaa"
  [[Local Purpleish]]
    allow_bold = False
    background_color = "#f9f5fa"
    cursor_color = "#aaaaaa"
    font = Noto Sans Mono Medium 5.9599609375
    foreground_color = "#000000"
    scrollbar_position = hidden
    scrollback_lines = 5000
    exit_action = hold
    login_shell = True
    use_system_font = False
  [[Local Whiteish]]
    background_color = "#ffffff"
    cursor_color = "#aaaaaa"
    font = Noto Sans Mono 5.8994140625
    foreground_color = "#000000"
    scrollbar_position = hidden
    exit_action = hold
    login_shell = True
    use_system_font = False
  [[CCNR vpn CTRL]]
    background_color = "#f4ebf5"
    cursor_color = "#aaaaaa"
    font = Noto Sans Mono 5.94921875
    foreground_color = "#000000"
    scrollbar_position = hidden
    exit_action = hold
    login_shell = True
    use_custom_command = True
    custom_command = ssh appmgr@ctrl.stack -YC
    use_system_font = False
[layouts]
  [[default]]
    [[[window0]]]
      type = Window
      parent = ""
    [[[child1]]]
      type = Terminal
      parent = window0
      profile = default
  [[Multi]]
    [[[child0]]]
      type = Window
      parent = ""
      order = 0
      position = 56:50
      maximised = False
      fullscreen = False
      size = 772, 612
      title = pe243@fedora:~
      last_active_term = 4949ca3e-dfcd-4d4b-8bca-66b77e4afec2
      last_active_window = True
    [[[terminal1]]]
      type = Terminal
      parent = child0
      order = 0
      profile = Local Purpleish
      uuid = 4949ca3e-dfcd-4d4b-8bca-66b77e4afec2
[plugins]

**Comment by lejeczek** [comment]
Aha.. a month later still with terminator-2.1.1-5.fc36.noarch with most likely plethora of updates Alt+a_digit works!

**Comment by mattrose** [comment]
Modifier keys are a pretty tricky thing to handle, and they go through three layers of library before they get to terminator.  I'm glad this is working for you now!
