### ISSUE TITLE
Set Terminator tab title via command line

### ISSUE THREAD

**Issue by sinister3vil** [gnome-terminator/terminator#603]
Hello, I'm trying to find a way to set up the Terminator tab title, not the tile set by the current terminal a la `\e]0;TEXT\a`, in a scriptable manner.

i.e.
I have a tab and I ssh into various hosts. The title changes based on the remote host, say root@host.
If I split the tab into views then the tab title will change depending on the active view.
If I use the kb shortcut CTRL+ALT+A I can set the tab title myself, and this does not get overwritten when changing hosts, active views etc.

I want to be able to set the title, as it's set with CTRL+ALT+A, in a scriptable manner.

i.e. do something like this

```sh
function tssh {
terminator --magictitlecommand $1
ssh ${@:2}
}
```

**Comment by mattrose** [comment]
`python3 remotinator set_tab_title -t foo` works on master, but hasn't been released yet.

I really need to make a new release.
