### ISSUE TITLE
Ctrl+Shift+Mouse-Scroll triggers Ctrl+Mouse Scroll

### ISSUE THREAD

**Issue by nonZero** [gnome-terminator/terminator#606]
**Describe the bug**
1. While holding Ctrl+Shift+Mouse wheel/Scroll up the font size increases (it shouldn't change, as Shift is pressed)
1. While holding Ctrl+Shift+Mouse wheel/Scroll **DOWN** the font size also **increases** (it shouldn't change, as Shift is pressed)

**To Reproduce**
Use Ctrl+Shift+Mouse wheel/Scroll up/down

**Expected behavior**
Font size should not change.
(It should change when Ctrl+Mouse wheel/Scroll up/down is used, without Shift)

**Desktop (please complete the following information):**
 - Arch Linux
 - Terminator 2.1.1
 - X11

It happens on google chrome too: https://bugs.chromium.org/p/chromium/issues/detail?id=1335654 (but not with firefox or other apps)

**Comment by Vulcalien** [comment]
I can replicate what you say for the shift key, but `Ctrl+Shift+Mouse Down` does not increase the size for me, instead it decreases it as expected.

I think the shift key is being completely ignored. Shouldn't be too hard to fix.
