### ISSUE TITLE
Question about persisting pane ratios

### ISSUE THREAD

**Issue by tronorama** [gnome-terminator/terminator#607]
I've Googling without much luck, and I don't think I really under the `ratio` or `position` keys (whether in a `child` or `terminal` block) in the normal config file. For example in this excerpt from a layout in my config file, this tab is split into a top and bottom pane, but no matter what I try, both panes always take up half of the tab.

What I want though is for the top pane to take up, say, _only_ 20% of the tab, and the bottom pane (the "psql" pane) to take up 80% of the tab, on startup, without me dragging anything manually (and ideally without this layout ever being overwritten by terminator if I _do_ drag the separator manually on occasion).

```ini
    [[[child9]]]
      type = VPaned
      parent = child1
      order = 7
      position = 168 # changing this does not seem to do anything
      ratio = 0.16666666666666666  # changing this does not seem to do anything
    [[[terminal10]]]
      type = Terminal
      parent = child9
      # ratio = 0.2 # does not seem to do anything
      order = 0
      profile = default
      title = createdb/dropdb
      uuid = 6766e864-2a49-4fc4-a66a-5254418a044a
    [[[terminal11]]]
      type = Terminal
      parent = child9
      # ratio = 0.8 # does not seem to do anything
      order = 1
      profile = default
      title = psql
      command = psql
      uuid = fcaac26a-e2ca-4b28-bd66-ac21cab47ebf
```

Is there a way to do what I want? Adding a `ratio` key to both terminal panes does not seem to do anything for instance.

**Comment by mattrose** [comment]
This is a bug that should be fixed by #433 Please let me know if this does fix the issue for you.
