### ISSUE TITLE
Split terminal vertically/horizontally from command line

### ISSUE THREAD

**Issue by nicolaipre** [gnome-terminator/terminator#610]
It would be nice to be able to "Split Horizontally" and "Split Vertically" directly from the command line, similar to how one can open a new tab with `terminator --new-tab`. 

Essentially it would be the equivalent of the following in tmux: `tmux splitw -h` and `tmux splitw -v`.

I could not find anything in the command line options or documentation on this other than creating a layout and starting that.

**Comment by mattrose** [comment]
`remotinator hsplit` and `remotinator vsplit` should do what you want. `remotinator -h` for more.

**Comment by nicolaipre** [comment]
Perfect! Thank you @mattrose !
