### ISSUE TITLE
Shortcut for autosplit h/v depending on active terminal size

### ISSUE THREAD

**Issue by crondrift** [gnome-terminator/terminator#613]
I could not find something like that in the manual.

Maybe Ctrl+Shift-A?

![autosplit2](https://user-images.githubusercontent.com/75867848/174874356-56da5288-31ea-4bab-9a86-b432168d4305.png)

**Comment by mattrose** [comment]
Am I correct in assuming this is an enhancement request?

**Comment by crondrift** [comment]
Yes.
