### ISSUE TITLE
[Question] is there a way to prevent Terminator from dereferencing symbolic links?

### ISSUE THREAD

**Issue by venteto** [gnome-terminator/terminator#617]
For instance, when I have have a pane opened in a directory that is based on a symbolic link, when I split the pane, the new pane makes my working directory the same as the parent pane (which _is_ what I expect), but since in this specific case the parent was also a _symbolic link_, the new pane instead uses the path that the link _pointed_ to, and I'd prefer to keep using the link in the new pane instead.

**Comment by mattrose** [comment]
That should be the only behaviour IMO.  I'm not sure whether it's possible, but I'll look at the code and see if I can fix it so that it always starts in the same path you were in before.

**Comment by mattrose** [comment]
God, what a rat's nest.  Time for some fixes.

**Comment by venteto** [comment]
I'm sorry, it's not a huge deal, I was just curious if there was already some existing configuration option or something.

**Comment by mattrose** [comment]
Ah-ha!  Figured it out.  This feature requires some heavy lifting from your shell, and various distros either set this or don't.  Long story short:

1.  alter your default profile and check off "Run command as a login shell" checkbox.
2. alter your .bashrc to call `source /etc/profile.d/vte-2.91.sh` 

this should allow your shell to tell terminator what the current working directory is without calling getcwd()

**Comment by venteto** [comment]
Thank you! I didn't find that file on Manjaro but I had vte.sh and sourcing that worked, I don't seem to need to change Terminator to run as a login shell.
