### ISSUE TITLE
[Question] what might cause the desktop background to bleed through the Terminator window when I'm not using transparency in the config?

### ISSUE THREAD

**Issue by venteto** [gnome-terminator/terminator#619]
It's not enough to bother me at all, but I am just _curious_ why my desktop wallpaper always seems to bleed in e.g., between the top of the tab bar and the window title bar (when not maximized, since I use the Unite extension to hide the window title bar when maxmized) ... and around all sides of the maximized Terminator window, including between the Terminator window and the dock.

![terminator-one-pane-cannot-max](https://user-images.githubusercontent.com/7062385/178035858-1a6c3736-9637-4077-88ba-02f0b080f96e.png)

![Screenshot from 2022-07-08 13-03-05](https://user-images.githubusercontent.com/7062385/178037985-afac9d59-f381-431f-abc4-7810b042fd1c.png)

![Screenshot from 2022-07-08 13-02-21](https://user-images.githubusercontent.com/7062385/178037987-21388648-f573-4a9e-98a9-28705b05e9d7.png)

I'm using GNOME 42.2 with X11 on Manjaro Linux, but I've noticed this since probably at least GNOME 3.38, with Wayland or X11.

**Comment by mattrose** [comment]
I'm going to say your gtk theme.  If there are gtk widgets that don't have a specific style and color attached to them the widgets just don't render, and appear transparent

**Comment by mattrose** [comment]
Can you try it with the default Adwaita theme, and see if it still happens

**Comment by venteto** [comment]
Ah, that seems to add a white border to the parts where the background bleeds through in one Manjaro's themes (but only when I add more than one tab):

![Screenshot from 2022-07-12 12-10-17](https://user-images.githubusercontent.com/7062385/178541771-5c7fa295-5aff-48bd-95ca-9d614e6993d6.png)

![Screenshot from 2022-07-12 12-16-27](https://user-images.githubusercontent.com/7062385/178543159-cbb2258d-6c66-4db6-bf2c-81dd8cafea20.png)

It only seems to happen when using more than one tab, with the specific Manjare theme I was using as well:

![Screenshot from 2022-07-12 12-15-37](https://user-images.githubusercontent.com/7062385/178543440-b354bca3-0422-49c3-9560-e2bccec22723.png)

Thanks for clearing that up for me.
