### ISSUE TITLE
Starting Terminator with the --layout parameter opens up 2 Windows instead of 1 

### ISSUE THREAD

**Issue by bedaberner** [gnome-terminator/terminator#621]
**Describe the bug**
Opening Terminator with the layout option opens a second window with the default layout.
**To Reproduce**
execute 
terminator -l "notDefaultLayout"
you will find that 2 Terminator Windows will open, one with the asked for layout, the other one with default layout

**Expected behavior**
only open the Window with the asked for layout

**Desktop (please complete the following information):**
 - ubuntu 20.04 LTS

**Additional context**
The select layout option (-s) behaves the same

**Comment by mattrose** [comment]
Can't reproduce this with the latest release.  The default terminator pkg on ubuntu 20.04 LTS is pretty old.  There should be a newer one in my PPA mentioned in INSTALL

**Comment by bedaberner** [comment]
Still happens to me in version 2.1.1
small Screenrecording of the Issue:

https://user-images.githubusercontent.com/49646807/180155026-344066b8-1aca-4164-b49a-cb4577854d6f.mp4

**Comment by mattrose** [comment]
Hmm, can you attach a copy of your config from `~/.config/terminator/config`

**Comment by bedaberner** [comment]
I had to make it into a .txt so github lets me attach it.
[config.txt](https://github.com/gnome-terminator/terminator/files/9165910/config.txt)

**Comment by mattrose** [comment]
both of your non-default layouts have 2 windows in them, one that is customized, and one that just uses the default window config.  That is why they are opening two windows

**Comment by flippedcracker** [comment]
I think this is happening when you save the layout. It's also happened to me and I had to manually edit the config file to remove the extra window. I'm wondering if it's saving the preferences window as part of the layout, but then just opening it as a default window.
