### ISSUE TITLE
No left gutter or margin for maximized windows

### ISSUE THREAD

**Issue by morenathan** [gnome-terminator/terminator#622]
**Describe the bug**
When Terminator window is maximized the left side of text is cutoff. It's as if there is a rendering issue and they're being drawn with a negative pixel value. 

The issue happens with an empty config, my own config, with our without window borders. If using the window manager "fullscreen" window option it does not appear.

This only happens on a maximized window with or without borders.

**To Reproduce**
Start Terminator. Maximize window. Cat file with text along first column.

**Expected behavior**
There should be some kind of margin or padding for the left gutter before text is drawn. This does appear to be the case for windowed terminals just not for maximized ones.

**Desktop (please complete the following information):**
 - ArchLinux (Linux 5.18.10-zen1-1-zen)
 - X11 (xorg-server 21.1.4)
 - Terminator 2.1.1

**Additional context**
~/.config/termnator/config
[global_config]
  handle_size = 3
  geometry_hinting = True
  window_state = maximise
  borderless = True
  tab_position = hidden
  use_custom_url_handler = True
  custom_url_handler = xdg-open
  title_hide_sizetext = True
  inactive_color_offset = 0.9578947368421052
  enabled_plugins = ActivityWatch, InactivityWatch, LaunchpadBugURLHandler, LaunchpadCodeURLHandler
  title_font = Fira Code 11
  putty_paste_style_source_clipboard = True
[keybindings]
[profiles]
  [[default]]
    icon_bell = False
    backspace_binding = automatic
    delete_binding = automatic
    cursor_blink = False
    cursor_color = "#aaaaaa"
    font = Fira Code 11
    foreground_color = "#eeeeec"
    scrollbar_position = hidden
    scrollback_lines = 2000
    disable_mousewheel_zoom = True
    palette = "#000000:#cc0000:#4e9a06:#c4a000:#3465a4:#75507b:#06989a:#d3d7cf:#555753:#ef2929:#8ae234:#fce94f:#729fcf:#ad7fa8:#34e2e2:#eeeeec"
    word_chars = "-,.?%&#_"
    login_shell = True
    bold_is_bright = True
    copy_on_selection = True
[layouts]
  [[default]]
    [[[window0]]]
      type = Window
      parent = ""
    [[[child1]]]
      type = Terminal
      parent = window0
      profile = default
[plugins]

**Comment by mattrose** [comment]
I cannot reproduce this problem even with your configuration.  Can you see if this happens when the window is not maximised?

**Comment by morenathan** [comment]
I've seen this a couple of times but now on a different machine am not also seeing it. It must be specific to a font setting. Unfortunately that original configuration is lost. Right now, both of my regular configurations are running fine.

The problematic settings did have far more unique font settings. I'll dig around and see at some point if I can reproduce it again in the future. As it stands apparently this was never an issue for the average :)

Sorry for the late reply. Life.
