### ISSUE TITLE
Resets the tab title on rotation

### ISSUE THREAD

**Issue by WhiteBlackGoose** [gnome-terminator/terminator#624]
- [x] Reproduces on `terminator -u -g /dev/null`

**Describe the bug**
Rotation of terminals resets the title of the current tab

**To Reproduce**
1. Create more than one tab
2. Rename it to something
3. Rotate terminals
4. It's back to the default one (it's `/bin/bash` in my case)

**Expected behavior**
Should keep the title

**Desktop (please complete the following information):**
 - Xubuntu
 - 22.04
 - X11

**Additional context**
terminator 2.1.1

**Comment by mattrose** [comment]
Able to reproduce

**Comment by Vulcalien** [comment]
In #589 I dealt with what seems to be the same issue. That code should be easily adapted to fix this as well.

**Comment by Vulcalien** [comment]
Ok should be working! I put the fix in #589 since it uses similar code

**Comment by Vulcalien** [comment]
I tested it, and after #589 it doesn't happen anymore.
