### ISSUE TITLE
Make a submenu of Layouts in the popup menu.

### ISSUE THREAD

**Issue by mattrose** [gnome-terminator/terminator#63]
nbeaver opened up PR #42  and I really like the idea, because layouts are a feature of Terminator that I rarely use and would like to use more, but the feature is not obvious on how to launch new layouts easily.  PR #42 adds a link to the layout launcher in the popup menu, but I think we can go one further, and just have the entry in the popup menu that brings up a submenu of available layouts directly, without bringing up the layout launcher.

**Comment by lazyfrosch** [comment]
Just a quick note aside, there is no need to open issues when there is a PR.

Basically a PR is also an issue, you would open an issue when there is no code changed yet.

**Comment by mattrose** [comment]
This code was pulled in #132
