### ISSUE TITLE
Layout settings get lost or shifted.

### ISSUE THREAD

**Issue by dandudikof** [gnome-terminator/terminator#630]
Inconsistent editing of layout settings, saves and deletes and profiles also. 

sometimes  settings get lost , or shifted to another profile.  

maybe it is just me not understanding of how things are supposed to work.  

But i am having to resort to backing up the config and edits by hand as an alternative.

**Comment by mattrose** [comment]
I'm on vacation right now til the end of the month, and unfortunately there's not much here for me to go on. Can you find a way to reliably reproduce this?

**Comment by winksaville** [comment]
@mattrose, this may not be the exact problem @dandudikof is seeing but I think my problem might be related.

First I on Arch Linux with terminator version:
```
$ terminator --version
terminator 2.1.1
```
I've noticed that when I have multiple layouts the last one is the one that is used, not the one I actually selected. For example, I have config with two layouts "default" and "Robert-5wins":
```
$ cat .config/terminator/config
[global_config]
  suppress_multiple_term_dialog = True
[keybindings]
[profiles]
  [[default]]
    cursor_color = "#aaaaaa"
    font = Source Code Pro 11
    scrollback_infinite = True
    use_system_font = False
  [[Black on white]]
    background_color = "#ffffff"
    cursor_color = "#aaaaaa"
    foreground_color = "#000000"
  [[White on black]]
    cursor_color = "#aaaaaa"
    foreground_color = "#ffffff"
  [[Black on yellow]]
    background_color = "#ffffdd"
    cursor_color = "#aaaaaa"
    foreground_color = "#000000"
    palette = "#000000:#aa0000:#00aa00:#aa5500:#0000aa:#aa00aa:#00aaaa:#aaaaaa:#555555:#ff5555:#55ff55:#ffff55:#5555ff:#ff55ff:#55ffff:#ffffff"
  [[system theme]]
    cursor_color = "#aaaaaa"
    use_theme_colors = True
[layouts]
  [[default]]
    [[[window0]]]
      type = Window
      parent = ""
    [[[child1]]]
      type = Terminal
      parent = window0
      command = ""
      profile = default
  [[Robert-5wins]]
    [[[child0]]]
      type = Window
      parent = ""
      order = 0
      position = 588:894
      maximised = False
      fullscreen = False
      size = 2818, 1366
      title = kendall@robert: ~
      last_active_term = 375d0cef-6f80-4dd0-a25e-eb8a485ca0a5
      last_active_window = True
    [[[child1]]]
      type = VPaned
      parent = child0
      order = 0
      position = 440
      ratio = 0.3232916972814107
    [[[child2]]]
      type = HPaned
      parent = child1
      order = 0
      position = 1407
      ratio = 0.5001777461784571
    [[[terminal3]]]
      type = Terminal
      parent = child2
      order = 0
      profile = default
      uuid = 375d0cef-6f80-4dd0-a25e-eb8a485ca0a5
      command = ssh kendall@robert
    [[[terminal4]]]
      type = Terminal
      parent = child2
      order = 1
      profile = default
      uuid = 5c2d197e-65db-438f-a17c-855fc0abd838
      command = ssh kendall@robert
    [[[child5]]]
      type = VPaned
      parent = child1
      order = 1
      position = 239
      ratio = 0.2609170305676856
    [[[terminal6]]]
      type = Terminal
      parent = child5
      order = 0
      profile = default
      uuid = bff12c33-d167-4ae9-955e-a535ec312cb1
      command = ssh kendall@robert
    [[[child7]]]
      type = VPaned
      parent = child5
      order = 1
      position = 344
      ratio = 0.5119047619047619
    [[[terminal8]]]
      type = Terminal
      parent = child7
      order = 0
      profile = default
      uuid = 9c0028b1-6fab-4073-b320-5a0abff21218
      command = ssh kendall@robert
    [[[terminal9]]]
      type = Terminal
      parent = child7
      order = 1
      profile = default
      uuid = f3fc4476-2714-4447-88e8-09fc8c2e1057
      command = ssh kendall@robert
[plugins]
```
If I select "default":
![terminator-default-cropped](https://user-images.githubusercontent.com/1024284/186273711-f2e2c347-6a4c-4904-b51d-2341d4abd5c2.png)

I end up with the "Robert-5wins" layout and NOT the "default" layout:
![Robert-5wins](https://user-images.githubusercontent.com/1024284/186273987-4ea8f241-d780-46f5-883b-25467a3e8c57.png)

Hopefully you can reproduce the problem.

**Comment by dandudikof** [comment]
What would be the proper procedure in dealing with multiple layouts , that include multiple profiles.
After the initial save. how would you bring up each one individually, modify and save again later.

I have found this is the part that gets me .

And thank you for you work(not complaining about anything). Terminator does , what no other emulator can for my needs.

But bash/sh scripting as a sysadmin is as far as i go.

If there is a particular test in a clean env you would want me to perform i would try and report back.

thanx.

**Comment by antonioprates** [comment]
I can confirm same issue happens to me as described by @winksaville - terminator uses the last config from the list, when selecting from the context menu, regardless of how many you have saved.

**Comment by winksaville** [comment]
> I can confirm same issue happens to me as described by @winksaville - terminator uses the last config from the list, when selecting from the context menu, regardless of how many you have saved.
> 
> (on manjaro linux, terminator 2.1.1, shell: zsh 5.

Glad it was reproducible!

**Comment by vssdeo** [comment]
Can anyone corss check if this fix https://github.com/gnome-terminator/terminator/issues/652 has fixed the issue. It seems the same.

**Comment by winksaville** [comment]
> Can anyone corss check if this fix #652 has fixed the issue. It seems the same.

I cloned the repo and then ran `python3 terminator` from my system install terminator:
```
wink@3900x 22-10-31T20:12:51.057Z:~
$ terminator --version
terminator 2.1.2
wink@3900x 22-10-31T20:12:57.970Z:~
$ cd prgs/clones/terminator/
wink@3900x 22-10-31T20:14:08.169Z:~/prgs/clones/terminator (master)
$ python3 terminator
wink@3900x 22-10-31T20:14:18.600Z:~/prgs/clones/terminator (master)
```
That did **NOT** work the behavior was the same as before, the "last" profile was always used.

But then I guessed that the even though I requested to run the new version with `python3 terminator` I might be running the system installed version. So then I started an `xterm` window it worked:

So I agree, the master branch #653 resolves this problem, TXS!
```
wink@3900x 22-10-31T20:34:36.005Z:~/prgs/clones/terminator (master)
$ git log -1
commit 1aa437d6e3f2492b698fb80c50f75d42d95f5653 (HEAD -> master, origin/master, origin/HEAD)
Merge: f289b4df 548a51c6
Author: Matt Rose <mattrose@folkwolf.net>
Date:   Mon Oct 31 12:50:11 2022 -0400

    Merge pull request #663 from vssdeo/662-In-the-Context-Menu-right-click-show-keyboard-shortcuts
    
    [bug 662] [Feature Request] - In the Context Menu(Right-Click) show k…
wink@3900x 22-10-31T20:34:45.506Z:~/prgs/clones/terminator (master)
```

**Comment by winksaville** [comment]
Can we get a new release soon?

**Comment by vssdeo** [comment]
great, I saw this bug and was kind of confident that my fix should have settled related issue with selection. Thanks for confirming. Cheers !

**Comment by winksaville** [comment]
> Unfortunately, we just put out a release a week or two ago, but I'm hoping to institute quarterly releases so there should be one in January that incorporates this fix.

Bummer, but for me an any fellow Arch Linux distribution users you can install using aur [terminator-git](https://aur.archlinux.org/packages/terminator-git).

**Comment by mattrose** [comment]
I just keep a copy of master checked out and run terminator from that :)

**Comment by vssdeo** [comment]
My only comment here to @winksaville would be, that we are pushing quite a lot of changes recently which we all will like and I guess some testing and time be given before freezing things. May be that will give us more time to push more features :)
