### ISSUE TITLE
Terminator can't start launcher properly

### ISSUE THREAD

**Issue by arne-fuchs** [gnome-terminator/terminator#634]
**Describe the bug**
I want to start Elite Dangerous with the [MinEdLauncher](https://github.com/Rfvgyhn/min-ed-launcher) through steam.
Before terminator I started it with gnome-terminal:
`MANGOHUD=1 gnome-terminal -- ./MinEdLauncher %command% /autoquit`
Everything works fine.
I've tried to open it with terminator with the following command:
`MANGOHUD=1 terminator -x ./MinEdLauncher %command% /autoquit`
and had following problems:

1. In the %command% part is a path leading to the elite dangerous. In this path there is a space between Elite and Dangerous. Suddenly the MinEdLauncher thought it would be two arguments instead of one. I could fix that in the program but it didn't happened in gnome-terminal.
2. Steam provides the wineprefix through a environmental variable called STEAM_COMPAT_DATA_PATH. Somehow this variable gets lost in terminator. Defining it in the launch options didn't helped.

**To Reproduce**
1. Install Elite Dangerous through steam
2. Install [MinEdLauncher](https://github.com/Rfvgyhn/min-ed-launcher)
3. Change the launch options to open the [MinEdLauncher](https://github.com/Rfvgyhn/min-ed-launcher)
4. Start game through
5. If it failes, read logs at ~/.local/state/min-ed-launcher

**Expected behavior**
parsing the arguments through without messing it up and providing environmental variables.

**Desktop (please complete the following information):**
 - Ubuntu 
 - 22.04
 - X11

**Config**
[global_config]
  title_hide_sizetext = True
  title_transmit_fg_color = "#000000"
  title_transmit_bg_color = "#992500"
  title_receive_fg_color = "#ff7800"
  title_receive_bg_color = "#c64600"
  title_inactive_fg_color = "#c64600"
  title_inactive_bg_color = "#000000"
  title_use_system_font = False
  title_font = Tlwg Mono Bold 13
[keybindings]
[profiles]
  [[default]]
    background_darkness = 1.0
    cursor_shape = ibeam
    cursor_color = "#c64600"
    cursor_color_fg = False
    foreground_color = "#e66100"
    scrollback_lines = 1000
    palette = "#000000:#cc0000:#4e9a06:#c4a000:#3465a4:#75507b:#06989a:#d3d7cf:#555753:#ef2929:#8ae234:#fce94f:#729fcf:#ad7fa8:#34e2e2:#eeeeec"
    split_to_group = True
    background_image = /home/arne/Pictures/Screenshots/Screenshot from 2022-08-13 03-05-41.png
[layouts]
  [[default]]
    [[[window0]]]
      type = Window
      parent = ""
    [[[child1]]]
      type = Terminal
      parent = window0
[plugins]

**Comment by mattrose** [comment]
you could try `MANGOHUD=1 terminator -x 'STEAM_COMPAT_DATA_PATH=foo ./MinEdLauncher %command% /autoquit'`

**Comment by arne-fuchs** [comment]
I am in vacation now. Will test it next week

**Comment by arne-fuchs** [comment]
It worked. But it failed to start steam now for unknown reason.

**Comment by arne-fuchs** [comment]
Tried it in urxvt terminal. No problems.

**Comment by mattrose** [comment]
There's been some fixing of how we handle command line arguments.  Can you check master to see if it's fixed?

**Comment by arne-fuchs** [comment]
Cloned the repo from master and did a setup build and install.
I pasted the arguments mentioned in the issue above but resulted in instant crashing from the launcher. Launcher was not able to write any logs

**Comment by arne-fuchs** [comment]
I noticed by the way, that the setup.py is only to able to install the program, but not removing it, which is missing.

**Comment by mattrose** [comment]
Is there any errors from terminator?  Possibly terminator is still doing something weird.

**Comment by mattrose** [comment]
> I noticed by the way, that the setup.py is only to able to install the program, but not removing it, which is missing.

It does if you follow the [Installation Instructions](https://github.com/gnome-terminator/terminator/blob/master/INSTALL.md)

**Comment by mattrose** [comment]
I'm not sure what more I can do to help you in this case.

**Comment by arne-fuchs** [comment]
For now I am using Rxvt so I am closing the issue.
Thanks for helping though!
