### ISSUE TITLE
Pasting Primary Clipboard Pastes Mouse Clipboard

### ISSUE THREAD

**Issue by imbezol** [gnome-terminator/terminator#636]
Mouse clipboard:
- Highlighting text enters the text into the Mouse clipboard properly.
- Middle paste / Right paste (depending on PuTTy option) pastes the mouse clipboard properly.

Primary clipboard:
- Ctrl-Insert / Ctrl-C inserts the text into Primary clipboard properly.
- Shift-Insert / Ctrl-V pastes the **Mouse** clipboard rather than the Primary clipboard.

To demonstrate:
Highlight some text, which will insert it into the mouse clipboard. Hit ctrl-insert to also copy it to the primary clipboard.
Middle click to paste, and shift-insert to paste. Both will paste the same content.
Highlight some other text, which will insert it into the mouse clipboard.
Middle click to paste, and shift-insert to paste. Both will paste the same content. They shouldn't because the primary still holds the first content.
Go to a different application and hit shift-insert. You'll see the first content that is still in the primary clipboard.

You can also see this behaviour by copying something from another app with ctrl-insert, then highlight something else. Terminator will pastes the Mouse clipboard for both middle click or shift-insert.

**Comment by Vulcalien** [comment]
I think it might be working as intended. I tried this on other terminals (gnome-terminal and st) and `Shift+Insert` is the same as `Middle Click`.

**Comment by imbezol** [comment]
I tired a few as well.

Ones that paste the mouse clipboard with shift-insert:
terminator - has ctrl-shift-v to paste primary clipboard
gnome-terminal - has ctrl-shift-v to paste primary clipboard
roxterm - has ctrl-shift-v to paste primary clipboard
xterm
xfce4-term - has ctrl-shift-v to paste primary clipboard
terminus - has ctrl-shift-v to paste primary clipboard
eterm
terminology - has ctrl-shift-v to paste primary clipboard
tilda - has ctrl-shift-v to paste primary clipboard
zutty - has ctrl-shift-v to paste primary clipboard

Ones that paste the primary clipboard with shift-insert:
konsole - plus ctrl-shift-insert to paste mouse clipboard and ctrl-shift-v as additional to paste primary clipboard
yakuake - plus ctrl-shift-insert to paste mouse clipboard and ctrl-shift-v as additional to paste primary clipboard

I thought maybe this is a KDE vs Gnome behaviour difference but I tested a number of Gnome apps. Some paste the mouse and some paste the primary clipboard. It seems like this is an area that needs to be cleaned up and standardized.

**Comment by mattrose** [comment]
Given that you can tell Terminator where you want the selected text to go to, I'm going to call this intended behaviour and close
