### ISSUE TITLE
Split terminal tabs

### ISSUE THREAD

**Issue by k3rn3Lp4n1cK** [gnome-terminator/terminator#638]
Please add tabs to split terminals

**Comment by Vulcalien** [comment]
Do you mean something like this?

![example-split-term-tab](https://user-images.githubusercontent.com/47713809/188270338-75d871e6-7be9-4ced-8a61-c1a65596889c.png)

**Comment by mattrose** [comment]
Closed for ... lack of feedback?  Already done?  Not sure.  @Vulcalien if you disagree lemme know and we can reopen
