### ISSUE TITLE
Profiles for different Shells - is it possible? how does it work?

### ISSUE THREAD

**Issue by jrich523** [gnome-terminator/terminator#640]
My typical shell is ZSH and i use oh-my-zsh for customization and such. However i occasionally use bash or even sh to test stuff. From my zsh shell i can simply type `sh` or `bash` to get in to those shells, but they tend to get env vars and such from the parent shell.

I've noticed that with Profiles i can set a custom command, however because i cant do new tab (or even split) to a new profile type, im not exactly sure how to use these. I've been able to do `terminator --new-tab --profile bash`  but it then will do all new tabs/windows as the bash profile.

Is there something im missing? is there a better way to start a new pane as a different shell?

Using v2.1.1

**Comment by mattrose** [comment]
Yeah, --profile doesn't do what you're expecting.  

I'm not sure how to do what you want, tbh.

**Comment by jrich523** [comment]
@mattrose thank you for the response. Unfortunately I've moved over to tabby.sh

**Comment by mattrose** [comment]
Nothing unfortunate about that.  No program can do everything that everybody wants.  If you've found something that works better for you, that's a win.  I'm gonna  close this issue.  Thanks!
