### ISSUE TITLE
Changing the default profile?

### ISSUE THREAD

**Issue by JOJ0** [gnome-terminator/terminator#646]
Hi, it might be a stupid question. I did search through existing issues but not too thoroughly: Is there any quick and  simple way to change the profile that is used as a default.

As far as I understand the default being used is bound to the name "default". Is that an hardcoded problem? It would be nice if simply I could select any profile and set a checkbox named "use as default" 

I often change my work atmospheres and there is times where the default should be a light theme a few days and there is other phases were it should default to a dark theme. 

I find it pretty time consuming and annoying to having to change single settings in my profile named "default". 

Also a workaround of trying to just rename a profile to "default" fails because the one named "default" already can't be changed!

Maybe this issue is solved already in newer Terminator versions? Please point me to it! Thanks so muche for your time and a great terminal emulator over all! Appreciated!

I'm currently using the original terminator package from Ubuntu 20.04 repos:
```
ii  terminator                             1.91-4ubuntu1                         all          multiple GNOME terminal
```

Would I get a fixed version if i use the ppa?

```
http://ppa.launchpad.net/gnome-terminator/ppa/ubuntu
```

**Comment by FernandoBasso** [comment]
I open different profiles through a command line like his:

```
$ terminator --profile GreenOnBlack --working-directory ~/work/myproj --title 'My Project'
```

Then I add it as a shortcut on my window manager.

But perhaps there are other solutions that I'm not aware of.

**Comment by JOJ0** [comment]
- Thanks so much for the hint but it's not going well with my workflows. Often I have several tabs and tiled windows open. I'd like to open new tabs with a new default setting. I dont really use several windows! everything is tabs and tiled windows. there is no way to quickly change the default for new terminals created with eg. ctrl-shift-n, that I find rather odd and like to ask if this is fixed in newer versions?

**Comment by mattrose** [comment]
Hmm, lemme think on this.  Could you do it by updating the config file directly?  Honestly I'm not sure this will work.

Also, if you uncheck, "Re-use profiles for new terminals" does it behave more as you would wish?

**Comment by nyg** [comment]
> Would I get a fixed version if i use the ppa?
> http://ppa.launchpad.net/gnome-terminator/ppa/ubuntu

@JOJ0 This is the PPA of the old Gnome Terminator, which this current repository forked. The last version was uploaded in 2016: https://launchpad.net/~gnome-terminator/+archive/ubuntu/ppa.

You could use Matt Rose's PPA to get version 2.1.1 (September 2021), see: https://launchpad.net/~mattrose/+archive/ubuntu/terminator?field.series_filter=focal and https://github.com/gnome-terminator/terminator/blob/master/INSTALL.md.

**Comment by JOJ0** [comment]
Sorry for not getting back here. I moved away from using Terminator entirely. Konsole has all the features I need.
