### ISSUE TITLE
Add option to set given terminal to "read only"

### ISSUE THREAD

**Issue by zaskokus** [gnome-terminator/terminator#649]
Simple feature request: please add option to set given terminal to "read only" just like Gnome Terminal has this context menu option.

**Comment by mattrose** [comment]
Should be fairly easy.

Wire up a "Read-Only" checkmark entry in "terminal-popup-menu.py to this VTE.Terminal() class method https://lazka.github.io/pgi-docs/Vte-2.91/classes/Terminal.html#Vte.Terminal.set_input_enabled

For UI hints, run GNOME-Terminal
