### ISSUE TITLE
When can we expect a new release?

### ISSUE THREAD

**Issue by pktiuk** [gnome-terminator/terminator#650]
According to a release site https://github.com/gnome-terminator/terminator/releases/tag/v2.1.1  
More than a full year passes since last release.  
There are more than **150** commits implementing tons of new functionalities and fixes to terminator. All of this code is waiting mainly unused (for people using regular packages from repositories).

It would be great to create a new release and ship these improvements and bugfixes to the public :)

**Comment by Vulcalien** [comment]
Well, 2.1.2 is here!

**Comment by pktiuk** [comment]
Thank you :D
