### ISSUE TITLE
Loading layout loads only the last added layout from context menu (right click)

### ISSUE THREAD

**Issue by vssdeo** [gnome-terminator/terminator#652]
Loading Added layout (from Preferences->Layout)  loads only the last added layout from context menu (right click)->Layouts even if you select any layout item.

1. launch ./terminator
2. Right Click, Open New Tab (Repeat 2 times to open 2 tabs)
3. Go to Preferences->Layout->Add  Layout
4. Close
5. launch ./terminator 
6. Right Click Open New Tab (Repeat 3 times to open 3 tabs)
7. Go to Preferences->Layout->Add  Layout
8. Close
9. Now to Test launch ./terminator
10. Now Right Click->Layout-> (Try to open the Saved Layouts)

Try to open saved layout with 2 tabs. Context Menu (Right  Click) -> Layouts->(Select) 
Result: It will still open the last saved Layout with 3 tabs.

In my 
[config.txt](https://github.com/gnome-terminator/terminator/files/9793080/config.txt)
attached config the layout "New Layout" is always loaded since its last saved.

Expected Behavior
-------------------------
After launching terminator and using context menu (right click) the correct Layout should open the selected layout
Right Click->Layouts->(Select)

-I am submitting a patch also.

Linux kali 5.18.0-kali5-amd64 #1 SMP PREEMPT_DYNAMIC Debian 5.18.5-1kali6 (2022-07-07) x86_64 GNU/Linux
 - X11

**Comment by vssdeo** [comment]
I forgot to mention the pull request with the fix. Here Ref: https://github.com/gnome-terminator/terminator/pull/653

**Comment by mattrose** [comment]
fixed by #653
