### ISSUE TITLE
terminator: error: unrecognized arguments

### ISSUE THREAD

**Issue by planet36** [gnome-terminator/terminator#660]
**Describe the bug**
When the `-x` option is used and the EXECUTE parameter has options, terminator tries to parse them as its own options.

**To Reproduce**
`terminator -u -g /dev/null -x bash -l`

**Expected behavior**
Terminator starts.

**Desktop (please complete the following information):**
 - Arch Linux
 - Display Technology: X11

**Additional context**
The help message says:
>  -x EXECUTE, --execute EXECUTE
>                        Use the rest of the command line as a command to execute inside the terminal, and its arguments

**Comment by planet36** [comment]
`terminator --version`
> terminator 2.1.2

**Comment by ncmprhnsbl** [comment]
just saying: 
`terminator -u -g /dev/null -x 'bash -l'`
seems to avoid this..

**Comment by planet36** [comment]
> just saying: `terminator -u -g /dev/null -x 'bash -l'` seems to avoid this..

In a previous version that wasn't necessary.

**Comment by Vulcalien** [comment]
About 1 year ago I made a major rewrite of the option parser in #506.

But how do we distinguish between -l being an option for terminator or for bash?
I've seen some program use a `;` to close the command.

I suspect this could be fixed with a one-line change.

**Comment by mattrose** [comment]
The way it's documented is that anything after --execute is the command you're supposed to run, so assume --execute is the last terminator arg.

**Comment by shawn-ogg** [comment]
I ran into this issue because I wanted to use terminator together with ranger integrated in firefox :smile:

**Comment by mattrose** [comment]
Thanks for your code @shawn-ogg.  I merged it into master.

**Comment by ManuelSchneid3r** [comment]
This is still an issue in the recent versions.

**Comment by AdamPS** [comment]
> This is still an issue in the recent versions.

This is expected. The patch was merged in Nov 2022, and the most recent release was Oct 2022. It would be great to have a new release😃.
