### ISSUE TITLE
What happened to the change terminal titlebar under preferences?

### ISSUE THREAD

**Issue by blue-devil** [gnome-terminator/terminator#664]
Hello
I am so appreciated you have released a new release. Thank you for your effort folks.

I have updated my terminator to 2.1.2 . I am using latest updated arch linux.(Yes I use arch btw)

Before the latest release I can set terminal titlebar colors via `Right Click on the Terminator > Preferences > Terminal Titlebar`. On version 2.1.1 I can set titlebar background colors and font colors: `Focused - Inactive - Receiving`

I cannot find this function on preferences window! Is it possible to bring this functionality back?

Thank you very much.

**Comment by mattrose** [comment]
It was moved to it's own tab underneath the profiles tab.  Sorry about that, but now you can set different titlebar colors per-profile!

**Comment by mattrose** [comment]
This was done under #481
