### ISSUE TITLE
Is there a official page to maintain a offical/third-part plugin list?

### ISSUE THREAD

**Issue by yurenchen000** [gnome-terminator/terminator#668]
It's not easy to scour the Internet here and there.
Probably everyone will have duplicate work.
And is not conducive to ecological accumulation.

How about maintain one page here,
 list plugins categorized and some summary, accept record/edit like the wiki does.

<br>

I just found one page here, I'm not sure is offical maintained and up to date.
https://terminator-gtk3.readthedocs.io/en/latest/plugins.html#third-party-plugins

**Comment by mattrose** [comment]
That is the official plugins page. If you wish to add to it you can raise an issue or PR here https://github.com/gnome-terminator/docs
