### ISSUE TITLE
GTK_IM_MODULE=cedilla doesn't work to get "ç"

### ISSUE THREAD

**Issue by edersondisouza** [gnome-terminator/terminator#670]
**Describe the bug**
Can't type <dead_acute>\<c> to get "ç" on us intl keyboard. I use `GTK_IM_MODULE=cedilla` to achieve that (otherwise I'd get a "ć").

**To Reproduce**
Have a US intl keyboard configured. Use `GTK_IM_MODULE=cedilla` to get "ç" instead of "ć" when typing <dead_acute>\<c>. Type <dead_acute>\<c>.

**Expected behavior**
Get a "ç".

**Desktop (please complete the following information):**
 - OS or Linux Distribution: Arch Linux
 - Display Technology: X11

**Additional context**
It seems https://github.com/gnome-terminator/terminator/commit/1e8940039a75b5a6fb32e59b4a2130da4777065f (fix for https://github.com/gnome-terminator/terminator/issues/78) causes this. There's also another aspect for this: if I start any application from terminator (such as a browser with some command line parameters), it also won't get the `GTK_IM_MODULE` env var and cedilla will be broken. For this reason, I'm not sure if terminator can go removing env vars like in this fix.

**Comment by mattrose** [comment]
If I created a test branch for you would you feel comfortable pulling down code and running it?

I could try and reproduce your situation, but I think it's better if I fix what I think is the problem, and have you run a few tests to make sure it works.

**Comment by edersondisouza** [comment]
>If I created a test branch for you would you feel comfortable pulling down code and running it?

Yes, it shouldn't be a problem.

**Comment by mattrose** [comment]
Can you look at the code in #674 and test out to see if it fixes the problem?

**Comment by edersondisouza** [comment]
I confirm that the code in #674 works for me.

**Comment by mattrose** [comment]
good, code is merged into master now.  If I don't put out 2.1.3 by January poke me.
