### ISSUE TITLE
drag the border and it will be messy

### ISSUE THREAD

**Issue by zilong-ding** [gnome-terminator/terminator#677]
Before opening an issue, please try starting terminator with an empty config
file, by issuing `terminator -u -g /dev/null` and see if it starts normally.

If it does, and you still want to open the bug, then please attach the
config file, usually found at `$HOME/.config/terminator/config` to the issue

Fill out as many of these fields as you can

**Describe the bug**

**Screenshots**
![image](https://user-images.githubusercontent.com/71497754/202591694-0f9aef1e-a23d-4468-a7a6-babf3fd8e532.png)
when i try to drag the border of the terminator,it will be like this,is this a bug?or is there anything to solve this problem

**Desktop (please complete the following information):**
 - OS or Linux Distribution: [ Ubuntu]
 - Version [ubuntu 20.04]

**Comment by Vulcalien** [comment]
I've seen this happen before. Does it happen when making the terminal bounds very small in one direction?

If that's what I think, it might be just a behavior of the shell. If so, this should also happen on othef terminals.

**Comment by mattrose** [comment]
Yeah, I think your PS1 is too long to fit inside the window, so bash gets very confused when you resize.
