### ISSUE TITLE
Focus loss when renaming a tab

### ISSUE THREAD

**Issue by the-shank** [gnome-terminator/terminator#696]
**Is your feature request related to a problem? Please describe.**
When I rename a tab (edit_tab_title in key bindings), the focus is lost and I need to use the mouse to refocus the terminal.

**Describe the solution you'd like**
I expect the renamed tab to be focused after a renaming (this would avoid using the mouse to refocus it).

**Describe alternatives you've considered**
I dont know of any alternative other than to use the mouse to re-focus the terminal

**Additional context**
os - ArchLinux
terminator version - 2.1.2

**Comment by FernandoBasso** [comment]
Same here (also on Arch).

I do `CTRL-SHIFT-a` to rename a tab. When I hit Enter, the focus is NOT on the terminal prompt.

What I then do is to press `SHIFT-TAB` to move the focus back to the prompt. Not ideal but much better than having to reach for the mouse.

**Comment by the-shank** [comment]
> What I then do is to press `SHIFT-TAB` to move the focus back to the prompt. Not ideal but much better than having to reach for the mouse.

Thank you. This is sufficient for me as this doesn't require me to use the mouse.

Out of curiosity, what action does `Shift+Tab` stand for? I cannot find it in the list of keybindings.

**Comment by FernandoBasso** [comment]
I think `Shift+Tab` is not mapped to anything (which I could find in the menu) for Terminator. Maybe it is a window manager thing or more or less standard way GUI toolkits (like GTK) handle focus. Even typing this message on Github I can do `TAB` and `SHIFT+TAB` to move focus to other UI elements.
