### ISSUE TITLE
Failed to execute default Terminal Emulator on Kali Linux.

### ISSUE THREAD

**Issue by Stroichik** [gnome-terminator/terminator#700]
Before opening an issue, please try starting terminator with an empty config
file, by issuing `terminator -u -g /dev/null` and see if it starts normally.

If it does, and you still want to open the bug, then please attach the
config file, usually found at `$HOME/.config/terminator/config` to the issue

There was no config file, until i made a new profile in Preferences.
This is all that is inside that file now.

`[global_config]
[keybindings]
[profiles]
  [[default]]
    background_darkness = 0.95
    background_type = transparent
    palette = "#1f2229:#d41919:#5ebdab:#fea44c:#367bf0:#9755b3:#49aee6:#e6e6e6:#198388:#ec0101:#47d4b9:#ff8a18:#277fff:#962ac3:#05a1f7:#ffffff"
    use_theme_colors = True
  [[New Profile]]
[layouts]
  [[default]]
    [[[window0]]]
      type = Window
      parent = ""
    [[[child1]]]
      type = Terminal
      parent = window0
[plugins]
`

Fill out as many of these fields as you can

**Describe the bug**
Whenever i install Terminator and choose it as Default Application for terminal on Kali Linux i cannot start any program from Startup Menu. I get this error:

![image](https://user-images.githubusercontent.com/12185977/212550769-9159b203-b435-4a86-80b2-e8e0dd944e8a.png)

**To Reproduce**

Install Terminator through `sudo apt install terminator` and choose it as default application
![image](https://user-images.githubusercontent.com/12185977/212550918-0aec3afb-6480-49c2-94bc-164420c63764.png)
![image](https://user-images.githubusercontent.com/12185977/212550933-49ce971b-fe4e-4c78-a6e3-c3bf51606ae0.png)

Then try to start any program for terminal from menu

![image](https://user-images.githubusercontent.com/12185977/212550717-6ad95b8d-58d2-41ca-a28f-862c33ff4378.png)
For example - press menu button and choose any program - i chose Nikto as example for screenshot.

![image](https://user-images.githubusercontent.com/12185977/212550675-73f247da-e9a6-4fba-ba4d-7f968d185b5b.png)
and u get error like that

**Expected behavior**
A new terminal window should start and chosen program must launch in it, like this with QTerminal

![image](https://user-images.githubusercontent.com/12185977/212550870-d975f267-31a3-4520-9d1c-8d51dccdf804.png)

**Screenshots**
I posted screens above

**Desktop (please complete the following information):**
 - OS or Linux Distribution: Kali Linux for VirtualBox for official Kali.org website
 - Version 2022.4
 - Display Technology: X11 

**Additional context**

**Comment by mattrose** [comment]
This may be fixed in master.  There was a bug with option parsing.  I hope to have a new release out soon.

**Comment by Stroichik** [comment]
It would be nice, yeah.

**Comment by Vulcalien** [comment]
@Stroichik Is this fixed in the latest version (2.1.3)?

**Comment by Stroichik** [comment]
@Vulcalien I just tried it on Nikto and Sqlmap after upgrading Kali yesterday. Seems to be fixed now, yay!

![image](https://github.com/gnome-terminator/terminator/assets/12185977/ab161148-fa73-49af-9bef-bc9829543764)

**Comment by Vulcalien** [comment]
Great! I'm closing the issue, thanks for reporting the problem!
