### ISSUE TITLE
terminator launch issue--- lacking GUI

### ISSUE THREAD

**Issue by GuShaocheng** [gnome-terminator/terminator#701]
Hi,

I am running the terminator on the Ubuntu system. I noticed that if I open it from gnome Applications or Alt+F2, I won't see its GUI. It only existed in the background. I saw "/usr/bin/python3 /usr/bin/terminator" when typing "ps -ef".
Besides, if I repeatedly open it from gnome Applications twice or more, the GUI will appear.
However, if I type terminator in the Ubuntu origin terminal, it will appear normal.
is there a tiny bug?

Best wishes!

**Comment by mattrose** [comment]
I'm running ubuntu as well and I'm not seeing this at all.  Can you say which version of ubuntu?

**Comment by GuShaocheng** [comment]
> I'm running ubuntu as well and I'm not seeing this at all. Can you say which version of ubuntu?

It is Ubuntu 22.04. It seems that it happens randomly.

**Comment by mattrose** [comment]
Can you attach a copy of your config file?

**Comment by mattrose** [comment]
Closing, please re-open with the requested info if there is still a problem.
