### ISSUE TITLE
`-x`/`--execute` still broken

### ISSUE THREAD

**Issue by ManuelSchneid3r** [gnome-terminator/terminator#702]
**Describe the bug**
I use terminals to run commands from albertlauncher. Terminator as the only exception [fails to do so](https://github.com/albertlauncher/albert/issues/1177). As some of the comments in the linked issue show, terminator _does not_ interpret the args after `-x` as commandline, but rather interprets them as its own args. E.g.

    terminator -x /bin/bash -ic "ssh somehost;  exec /bin/bash"

results in 

    terminator: error: unrecognized arguments: ssh github.com; exec /bin/bash

but I expect it to run a terminal _without_ a shell and the following commandline

```
arg[0]: /bin/bash
arg[1]: -ic
arg[2]: "ssh somehost;  exec /bin/bash"
```

Finally, in the above example, terminator should open and run a shell runnig ssh.

**Desktop (please complete the following information):**
 - Archlinux

(_Still_ broken because there is #660)

**Comment by mattrose** [comment]
Are you sure you're running the master version of terminator?  That command works fine for me with master.  Try `terminator -u -x /bin/bash -ic "ssh somehost;  exec /bin/bash"` to make sure you're not attaching to an older running terminator

**Comment by ManuelSchneid3r** [comment]
https://software.manjaro.org/package/terminator

**Comment by mattrose** [comment]
Ah, well that explains it.  #660 isn't released yet, so it won't have been picked up by manjaro.  
Bad News: If you want this change immediately you'll have to [install master](https://github.com/gnome-terminator/terminator/blob/master/INSTALL.md)
Good News: I plan a release within the next couple of weeks, as soon as I get some free time

**Comment by vmath3us** [comment]
what are the plans for supporting the emerging xdg-terminal-exec?
https://gitlab.gnome.org/GNOME/glib/-/merge_requests/2839
https://github.com/Vladimir-csp/xdg-terminal-exec#limitations
terminator actually needs quotes to exec (like in terminator -x or terminator -e)
xdg-terminal-exec vim file not works ; but
xdg-terminal-exec "vim file" yes.
