### ISSUE TITLE
Release file

### ISSUE THREAD

**Issue by amirtadayon** [gnome-terminator/terminator#705]
I installed `terminator` as explained [here](https://github.com/gnome-terminator/terminator/blob/master/INSTALL.md) on my Ubuntu 18.04 LTS machine. However, when I execute the command `sudo apt update`, the message error below pops up
```
E: The repository 'http://ppa.launchpad.net/mattrose/terminator/ubuntu bionic Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
```
Please advise. 

I can change the distribution from `bionic` to `xenial` on `Software & Update`. But is this something recommended? If so, please add it to the `INSTALL.md` file.

**Comment by nyg** [comment]
Hello @amirtadayon, as you can see here: https://launchpad.net/~mattrose/+archive/ubuntu/terminator/+packages there is no release of Terminator (in Matt Rose's PPA) for any version of Ubuntu before Focal (20.04).

If you want to install Terminator on Ubuntu 18.04 Bionic (Xenial is version 16.04) you need to **not** use Matt Rose's PPA. The downside is that you'll get version 1.91 which is from 2017 if I'm not mistaken. See: https://packages.ubuntu.com/bionic/terminator.

If you want a newer version, you can either update your Ubuntu, or try to build Terminator from source, or ask @mattrose to publish a recent version in his PPA :). I think there are still a lot of people using Ubuntu 18.04 LTS, at least at my workplace there are. It would be nice to have a more recent release for this Ubuntu version.

**Comment by mattrose** [comment]
I added 2.1.2-3 to 18.04, so you should be able to use it to install the latesst version now.
