### ISSUE TITLE
Favorites/Bookmarks ???

### ISSUE THREAD

**Issue by Foul** [gnome-terminator/terminator#706]
Hello, would it be possible to add Favorites/Bookmarks in this terminal ?

I'm using Konsole by default and i swould like this feature in Terminator plz.

Thx.

**Comment by vssdeo** [comment]
Putting in some code to check things via Plugin.

**DEPENDENCIES:** KeyBind Util https://github.com/gnome-terminator/terminator/pull/806
**Known Issues:** 

-keyboard short cuts have issue on new windows, #681 puts in a solution to reload but that needs to be verified by others also. -GUI works.
-if two windows are opened, sometimes the second one while loading bookmark does not load the directory for the first time.

**Usage:** 

```
<Alt>b to add 
<Alt>r to remove
or right click and use via menu
```

- sub-menu via right click->bookmarks->urls->(act menu)

- bookmark plugin, basic features 
- Requires support of KeyBindUtil from Plugin which assists short cuts
- may be edit option  can be added via Preferences Plugin window 
- config has = so rhs can be used for tags
- TODO: config changes if can be brought to plugin code
```
-       support in Preferences window
-       limit on number of urls via Preferences ?
-       display shortcuts in menu
-       selection of urls from keyboard and tag support

```


![bookmark_plugin](https://github.com/gnome-terminator/terminator/assets/19357612/d6acd814-007b-4033-a355-31ebcc0beba3)

**Comment by vssdeo** [comment]
Have changes in my branch Ref: https://github.com/vssdeo/terminator/tree/706-Favorites-Bookmarks-Plugin for testing and trying out.
- basic plugin
- tags feature
- UI support via prefs

![bookmark-plugin-2-tags](https://github.com/gnome-terminator/terminator/assets/19357612/3b8c5133-1933-4e86-8551-9f3173d4f017)
![bookmark-plugin-prefs-menu](https://github.com/gnome-terminator/terminator/assets/19357612/516d6023-0576-476b-bea5-4456d97f9e26)

**Comment by vssdeo** [comment]
Hi. Have removed my old separate bookmark plugin and have added the functionality to custom command plugin. Would be great if anyone can test / try Ref: https://github.com/vssdeo/terminator/tree/706-Favorites-Bookmarks-Plugin 

Changes rest on my branch not putting up a pull request now. 

To test, just merge my changes or use branch. enable custom command plugin. Default keybindings are <Alt>b or direct adding <Shift><Aft>b to launch custom command pref window.

Current changes:     
    - modified custom command plugin to have bookmarks
    - added keybindings for directly adding or launch the custom command menu
    - made name parsing of the custom command optional

I made parsing of custom command name optional keeping old behavior default. As I find, most of the times people would want to command name to be same as command and not parse it to submenus every time.

Once things seem ok I can merge tags functionality also.

[GitHub - vssdeo/terminator at 706-Favorites-Bookmarks-Plugin](https://github.com/vssdeo/terminator/tree/706-Favorites-Bookmarks-Plugin) - GitHub
multiple GNOME terminals in one window. Contribute to vssdeo/terminator development by creating an account on GitHub.
![bookmark-add-1](https://github.com/gnome-terminator/terminator/assets/19357612/f9851a02-caae-48c3-931f-528b51a82c52)
![bookmark-add-2](https://github.com/gnome-terminator/terminator/assets/19357612/7efc69af-dc45-4e74-88c7-be2324009b93)
![bookmark-add-3](https://github.com/gnome-terminator/terminator/assets/19357612/a8554403-8940-4544-a2ba-0fb8a40107ae)
