### ISSUE TITLE
Terminator crashing Gnome when using multiple SSH-commands in config 

### ISSUE THREAD

**Issue by dotbanana** [gnome-terminator/terminator#707]
Starting with empty/default config works.

**Describe the bug**
When using Terminator with SSH in "command", to automatically connect to a remote server at start,it is crashing gnome going back to login-screen. 
When you login there is nothing. I have to go to ALT+F3 and reboot the PC that way. 
I found out that when just using a single command for a terminal-tile/window it loads it up even tho there is a tiny moment after starting up that freezes whole Desktop but then works. But when using two commands in two different tiles it locks up completely. I tried using a "sleep X && [Command]" in the config but that does not help. 

I use for example such commands:  ssh -L 8000:localhost:8000 root@123.123.123.123 -p 1111; bash
  
It feels like something is locking up while it tries to process the SSH-connection. It would be maybe nice to have something like a "try" option, so that not the whole program (or even the whole Desktop) crashes when a subthread locks up, but should just throw an error.   
For me Terminator is unfortunately unusable that way - since i need it to connect fast to multiple remotes at once without having to rearrange terminals every morning. 

**Expected behavior**
Terminator opening without crashing Gnome.

**Desktop (please complete the following information):**
 - OS or Linux Distribution: Fedora
 - Version 37
 - Display Technology: Wayland

**Comment by mattrose** [comment]
Can you attach a copy of a config file that causes this behaviour?

**Comment by mattrose** [comment]
Closing.  If this is still a problem, please re-open and supply the requested info.

**Comment by dotbanana** [comment]
In the config is nothing but the ssh-commands. 
Default. 
Take a default two pane config and enter two ssh tunnel as pictured above in each of them in the command field and that's it.  
I think that it must have something to do with the SSH-Agent, the program that offers the SSH-keys, stalling the Startup of Terminator.   
By now i switched to Tilix which doesn't have this behaviour no matter how many ssh-sessions i open at startup, so for me this is basically solved and can be kept closed.
