### ISSUE TITLE
Option to set split ratio of terminals

### ISSUE THREAD

**Issue by EmnichtdaYT** [gnome-terminator/terminator#708]
**Is your feature request related to a problem? Please describe.**
When I start terminator I have it set to open one window with two terminals split horizontally, on the left terminal I have it configured to show a welcome screen and on the right terminal a fancy 80-columns wide ASCII art. I usually manually adjust the right terminal to 80 columns every time right after I open terminator.
It would be nice to be able to save the split ratio as part of the layout config, so you don't have to adjust it every time.

**Describe the solution you'd like**
I took a look at the config, HPaned does already have a setting called "ratio", but (for me) it doesn't change the split ratio, idk what its for. (Maybe this is actually a bug?) Adding a option called similarly that gives the ability to set the split ratio would be great.

**Describe alternatives you've considered**
Well, I could not think about anything else I could do.

**Additional context**
How it is right now at startup:
![image](https://user-images.githubusercontent.com/55759123/215604784-43dde40b-87e4-4980-ab0a-2f66dbc99577.png)

How I'd like it to be at startup:
![image](https://user-images.githubusercontent.com/55759123/215605171-347fc52f-9388-4f6c-8242-a3ef20fa41cc.png)

Thankies! :3

**Comment by EmnichtdaYT** [comment]
Update: This is actually a bug! A really weird one tho. When I open terminator via the search (GNOME, X.org on Ubuntu 22.04), the ratio setting works, unless there is already a window of terminator open. When I open terminator via a key bind or typing terminator in a terminal it also doesn't work.

**Comment by Vulcalien** [comment]
What version of terminator are you using? I remember fixing a bug like that some time ago, where the terminal ratio would not be properly loaded when reading a layout.

**Comment by EmnichtdaYT** [comment]
> What version of terminator are you using? 
Oh I just noticed I haven't added the terminator repo, I had 2.1.1 installed, it got fixed in 2.1.2 thanks!
