### ISSUE TITLE
Text Slection doesn't work under wayland.

### ISSUE THREAD

**Issue by music-cat-bread** [gnome-terminator/terminator#710]
Issue:
When selecting text using mouse, after releasing mouse button any selected text instantly de-selects itself.
This issue is only happening under Wayland, under X11 everything works fine.

Tested on:
KVM/QEMU virtual machine.
Void BASE image + KDE/SDDM installed.
Newest kernel (6.1) and all packages up to date.

Config:
No changes were made to default terminal install except disabled: "Settings -> Global -> Smart Copy".

Also those settings:
"Global -> Clear selection on copy"
"Profiles -> default -> General -> Copy on selection"
are off.

**Comment by mattrose** [comment]
Closing after non-response
