### ISSUE TITLE
How to enable fast encoding change?

### ISSUE THREAD

**Issue by IMR3ON** [gnome-terminator/terminator#712]
Dear developers, thanks for a very good terminal, a question arose, earlier it was possible to change the encoding in version 2.1.1, how can you enable this feature in version 2.1.2, so that when you right-click, you can change it to cp866 and etc, thanks

**Comment by Vulcalien** [comment]
I'm afraid the feature was removed in #536, as it was deprecated by vte (the terminal widget that Terminator is based on).
