### ISSUE TITLE
Layouts menu not working

### ISSUE THREAD

**Issue by Massimo-B** [gnome-terminator/terminator#717]
I have created 3 layouts that work fine when calling with -l like this:
```
$ terminator --list-layouts
default
4l6r
2l2r
4l4r
```
`$ terminator -l "2l2r" -m`

But when calling the context-menu Layouts->4l4r or one of the other entries, it's always started a new terminator with the wrong profile, always the same profile, not the selected one.

For instance: I start a terminator like 

`$ terminator -l "2l2r" -m`

I call Layouts->4l6r, a new terminator with 4l4r is started.
I call Layouts->2l2r, a new terminator with 4l4r is started.
I call Layouts->4l4r, a new terminator with 4l4r is started.
I call Layouts->defaults, a new terminator with 4l4r is started.

**Desktop:**
 - OS or Linux Distribution: Gentoo
 - terminator 2.1.2
 - Display Technology: X11

**Comment by palumbamboo** [comment]
Hello! I have the same problem also using the right-click menu and selecting layouts. It always opens the last layout added.

Desktop:
- OS or Linux Distribution: Ubuntu 22.10
- terminator 2.1.1
- Display Technology: Wayland

**Comment by mattrose** [comment]
Fixed in 2.1.3
