### ISSUE TITLE
2.1.3 release for Ubuntu 22.04 LTS

### ISSUE THREAD

**Issue by nyg** [gnome-terminator/terminator#718]
Hello!

This new release looks really really nice, congrats!

@mattrose I know the release if only a few days old, but would you have some time to publish this release in your PPA?

Many thanks,
nyg

PS: any feedback on #699?

**Comment by mattrose** [comment]
Ugh.  I hate building .deb packages, but I'll see what I can do.

**Comment by mattrose** [comment]
I did it.  I beat launchpad into submission.  The package is pending, and I'll close this when it's published, as for #699 I'll leave a comment there.

**Comment by nyg** [comment]
Thanks a lot! I'm closing as I was able to upgrade on my machine.
