### ISSUE TITLE
Font size change unexpectedly when maximizing a splitted windows.

### ISSUE THREAD

**Issue by letsgologan** [gnome-terminator/terminator#721]
**Describe the bug**
I use the split feature everyday and found it very useful when i have to work with multiple server at the same time or need different views to debug.
Often when i split a terminal vertically into 2 windows (or more ) and full screen one of them the font size stay the same, but when split windows horizontally the font size increasing so i have to scroll to resize them and that's inconvenient.

**To Reproduce**
i mapped:
ctrl-z to maximize a windows.
shift-pgup : split horizontally
shift-pgdn : split vertically

when split vertically and press ctrl-z the font size stay the same
when split horizontally and press ctrl-z the font size change unexpectedly

**Expected behavior**
when split horizontally and press ctrl-z the font size should stay the same.

**Screenshots**

**Desktop (please complete the following information):**
 - OS or Linux Distribution: Ubuntu 20
 - Version : 20.04.4
 - Display Technology: X11
![terminator](https://user-images.githubusercontent.com/67781194/223318065-66a44632-95e3-4adc-95ce-37d210873956.png)
![before_maximize](https://user-images.githubusercontent.com/67781194/223318079-a6eb84dd-1ff5-4b4c-ab95-2937e917e1fb.png) 
![after_maximize](https://user-images.githubusercontent.com/67781194/223318085-765823bf-8eb2-4f0c-9ee5-33f02cdd053c.png)

**Comment by Vulcalien** [comment]
In Terminator there are a "zoom" feature and a "maximize" feature.
Are you sure that ctrl+z is mapped to maximize, and not zoom?

That's the first thing that comes to my mind. The default to "maximize" without changing the font should be ctrl+shift+x.

**Comment by letsgologan** [comment]
> In Terminator there are a "zoom" feature and a "maximize" feature. Are you sure that ctrl+z is mapped to maximize, and not zoom?
> 
> That's the first thing that comes to my mind. The default to "maximize" without changing the font should be ctrl+shift+x.

Yes, you're right, i end up with zoom instead on maximize. How dump i was :( .
Sorry and thank you for let me know this. Even with maximize we can use Ctrl+0 to change the font to default size.
Glad i found the trick, have a nice day man.
