### ISSUE TITLE
Buffer issue when deleting text

### ISSUE THREAD

**Issue by youngunix** [gnome-terminator/terminator#729]
_Before opening an issue, please try starting terminator with an empty config
file, by issuing `terminator -u -g /dev/null` and see if it starts normally.

If it does, and you still want to open the bug, then please attach the
config file, usually found at `$HOME/.config/terminator/config` to the issue

Fill out as many of these fields as you can_

**Describe the bug**
I have no idea how to word this issue but I'll try. 
If I type a command and run it, things are fine. Now, when I press the arrow up key to get the said command and want to modify it by deleting some parameters or arguments, somehow some letters move into the preceding text and when I try to delete the whole line, the cursor stops before those jumbled up letters.  

**To Reproduce**
Steps to reproduce the behavior: see above.

**Expected behavior**
Accessing command history and/or deleting text without the experiencing the issue described above.

**Screenshots**

**Desktop (please complete the following information):**
 - OS or Linux Distribution: Gentoo (Kernel 6.1.19)
 - Version 17.1
 - Display Technology:  X11

**Additional context**
Running `terminator -u -g /dev/null` does not solve the problem.

Terminator version: 2.1.2
xfce4/xfwm: 4.18
Python: 3.10.10_p3

**Comment by mattrose** [comment]
Hmm, this kinda sounds like a problem with vte or the shell to me.  Can you see if you can reproduce the problem in xfce4-terminal?

**Comment by youngunix** [comment]
I think I might have found the culprit. 

I hope I'm not jumping into conclusions here, but it seems that this issue only happens in `bash`. I switched to `zsh` and I cannot reproduce the problem.
