### ISSUE TITLE
Terminator 2.1.3 opens with bad window size (tiny 2x1 char)  based on config

### ISSUE THREAD

**Issue by steveja** [gnome-terminator/terminator#730]
It seems that if I save a default layout with a size & position, enable geometry hints, and use a non-system-default font in the default profile, the resulting config cause terminator to open with a tiny/useless window size.
Details here:  https://bugzilla.redhat.com/show_bug.cgi?id=2180854#c2

**Comment by mattrose** [comment]
Appreciate the instructions, and I tried to follow them to the letter, but I still couldn't reproduce your problem.  This is the config I generated:


```
[global_config]
  geometry_hinting = True
[keybindings]
[profiles]
  [[default]]
    font = Liberation Mono 10
    use_system_font = False
[layouts]
  [[default]]
    [[[child0]]]
      type = Window
      parent = ""
      order = 0
      position = 150:182
      maximised = False
      fullscreen = False
      size = 1040, 548
      title = mattrose@fedora:~/Code/terminator
      last_active_term = 8d89779c-35b8-47bf-863d-3b9a1e2ea84a
      last_active_window = True
    [[[terminal1]]]
      type = Terminal
      parent = child0
      order = 0
      profile = default
      uuid = 8d89779c-35b8-47bf-863d-3b9a1e2ea84a
[plugins]

```

**Comment by mattrose** [comment]
Can you attach a copy of the config that reproduces the problem?

You can generate a new temporary config file by executing `terminator -u -g /tmp/config` and that will run a new copy of terminator with /tmp/config as it's config file

**Comment by steveja** [comment]
This config (w 10pt font) opens as a 120x1 char windows, despite that the layout was saved as 120x25.
```
[global_config]
  geometry_hinting = True
[keybindings]
[profiles]
  [[default]]
    font = Liberation Mono 10
    use_system_font = False
[layouts]
  [[default]]
    [[[child0]]]
      type = Window
      parent = ""
      order = 0
      position = 2294:564
      maximised = False
      fullscreen = False
      size = 1336, 701
      title = stevea@russula:~/.config/terminator
      last_active_term = c07ab505-85ee-41c1-948c-0f509fce0ffd
      last_active_window = True
    [[[terminal1]]]
      type = Terminal
      parent = child0
      order = 0
      profile = default
      uuid = c07ab505-85ee-41c1-948c-0f509fce0ffd
[plugins]

```

This one w 12pt font opens as 2x1 char window, despite saving layout at 120c25.
```
[global_config]
  geometry_hinting = True
[keybindings]
[profiles]
  [[default]]
    font = Liberation Mono 12
    use_system_font = False
[layouts]
  [[default]]
    [[[child0]]]
      type = Window
      parent = ""
      order = 0
      position = 2294:564
      maximised = False
      fullscreen = False
      size = 1336, 554
      title = stevea@russula:~/.config/terminator
      last_active_term = c07ab505-85ee-41c1-948c-0f509fce0ffd
      last_active_window = True
    [[[terminal1]]]
      type = Terminal
      parent = child0
      order = 0
      profile = default
      uuid = c07ab505-85ee-41c1-948c-0f509fce0ffd
[plugins]
```

**Comment by steveja** [comment]
I just tried the mattrose config above, and it presented a normal size window (~188x31).

**Comment by mattrose** [comment]
I tried the configs you provided, and I was able to kind of reproduce the problem with the second one you posted, but when I tried to run the same config with debug mode enabled, it actually worked fine.

Is there a reason you have geography hinting turned on?

**Comment by steveja** [comment]
"Window geometry hints" sounded from the description like a good idea when I toggled it on years ago. .   Turning that flag off is my current work around.  I have no strong reason to use it.

**Comment by mattrose** [comment]
I would just turn it off.  I think it used to do something a long time ago, but it doesn't seem to do anything but bad things anymore.  I'm going to open an associated bug to remove the option entirely.  I have no idea why this would have been exposed to the user in the first place, as it's not really applicable.
