### ISSUE TITLE
Terminator doesn't launches

### ISSUE THREAD

**Issue by M4xSec** [gnome-terminator/terminator#731]
**Describe the bug**
While launching Terminator it gives following error-
You need to install the python bindings for gobject, gtk and pango to run Terminator.

**To Reproduce**
Try to run terminator

I know it's issue with the python packages dependencies and I've tried installing all the dependencies but still it's not working

**Comment by mattrose** [comment]
I need more info than that to help you.  If you're getting that error message, it means that the dependencies aren't installed properly.  
What OS/distro are you using?  
Have you followed the instructions in https://github.com/gnometerminator/terminator/blob/master/INSTALL.md ? 
specifically installed the packages listed below, if you're on one of those 5 distros?


 Fedora/CentOS: python3-gobject python3-configobj python3-psutil vte291 
                keybinder3 intltool gettext
 Debian/Ubuntu: python3-gi python3-gi-cairo python3-psutil python3-configobj 
                gir1.2-keybinder-3.0 gir1.2-vte-2.91 gettext intltool dbus-x11 
 FreeBSD:       py37-psutil py37-configobj keybinder-gtk3 py37-gobject3 gettext 
                intltool libnotify vte3
