### ISSUE TITLE
[Feature] Have the ability to set custom geometry permanently

### ISSUE THREAD

**Issue by qodroi** [gnome-terminator/terminator#737]
Hi, I've taken a look at the manual page and at the GUI settings, yet I didn't find any option to set a custom geometry value. The current default one is 80x24, and I wanna be able to change it, what can we do about that? `--geometry` simply opens a new window, and it doesn't what I want, though I can just change the launch command, it'd be nice to implement it.

I see that with `geometry_hints`, the columns and rows change themselves based on the font size.

 I'll see if I can implement it myself.

**Comment by mattrose** [comment]
Change the default layout and that will save whatever combination of windows and sizes you want

**Comment by mattrose** [comment]
And that's not what geometry_hint does

**Comment by qodroi** [comment]
> Change the default layout and that will save whatever combination of windows and sizes you want

Nice, manually resizing the window then saving the layout profile works, though I'd never guess that this is what need to be done.
