### ISSUE TITLE
long lines with wrap enabled are mishandled

### ISSUE THREAD

**Issue by caedmon-kitty** [gnome-terminator/terminator#740]
Before opening an issue, please try starting terminator with an empty config
file, by issuing `terminator -u -g /dev/null` and see if it starts normally.

If it does, and you still want to open the bug, then please attach the
config file, usually found at `$HOME/.config/terminator/config` to the issue

Fill out as many of these fields as you can

**Describe the bug**
If a line longer than the terminal's width (i.e., for example a 100 character line in an 80x24 window) the line is truncated if wrap mode is disabled and wrapped if wrap mode is enabled via the escaped sequence (printf "\e%s" "[?7h").

Selecting the wrapped line using the left mouse button and pasting the line using the middle button results in 2 lines with a linefeed character inserted where the line was wrapped.

**To Reproduce**
Set wrapped mode by entering the command - printf "\e%s" "[?7h") (or equivalent).
cat a file with lines longer than the terminal width.
Use the mouse (left button) to select and copy a line.
Paste the line using the middle mouse button into the terminal window or another X11 app.
You will see two lines separated by a linefeed which was not in the original line printed out.

**Expected behavior**
The line should be copied as it was printed - not by inserting extra characters.

**Screenshots**

**Desktop (please complete the following information):**
 - OS or Linux Distribution: Fedora
 - Version 37
 - Display Technology: X11

**Additional context**
Tried with multiple other terminal emulators and they do it correctly - no extra linefeed.

Tried to attach config file but go an error - "Something went wrong".  If needed I'll paste it in.

**Comment by mattrose** [comment]
Does this happen with gnome-terminal?

**Comment by caedmon-kitty** [comment]
I have never used gnome-terminal.  In fact it is not installed on my system.  I have used alacritty and kitty for a long time.  I am looking for an emulator with terminator's features and like it except for this bug.

**Comment by mattrose** [comment]
can you install the vte-devel package and see if this happens in the terminal called vte-2.91?  I think this may be a problem with the underlying library and I want to make sure before I open a bug with them.  I have not been able to reproduce the problem on any of my own machines.
