### ISSUE TITLE
Long delay before able to enter password

### ISSUE THREAD

**Issue by Infinality** [gnome-terminator/terminator#745]
**Describe the bug**
When I launch terminator with multiple SSH destinations, it will spend about 10 seconds drawing all the squares, then it will sit for 2 minutes before any of the login banners and password prompts are displayed.  It's so long that I suspect something isn't functioning correctly either in terminator or the config.  If I SSH directly to any of the systems it doesn't take this long.  The issue only happens when using terminator.  Redacted config attached.  Thank you.

**Desktop (please complete the following information):**
 - OS or Linux Distribution: RHEL8
 - Version:  terminator-1.92-2.el8.noarch
 - Display Technology:  X-forwarded to Xming on Windows

[terminator.zip](https://github.com/gnome-terminator/terminator/files/11287502/terminator.zip)

**Comment by Vulcalien** [comment]
I've tested the config file you sent, both in v1.92 and the current master version.
I changed the ssh lines to run a real ssh request towards my localhost server.

On my tests, it behaves as expected: half of the windows are closed after 3 seconds, the other half open an ssh connection.

Hopefully, this is a bug fixed in newer releases. It might be helpful for you to try that on the latest version of Terminator.

***

That being said, I used a localhost SSH server with virtually no ping time.

**Comment by Infinality** [comment]
Interesting...  so I'm running terminator over an X-Forwarded SSH connection, using Xming on the Windows side to render the terminator window.  However, if I log into the Gnome desktop on that same system and launch terminator with the native X on the server, the problem goes away.  So, I suspect it's trying to do something that doesn't play nice with X-forwarded Xming.  Thank you for checking into it.

**Comment by Infinality** [comment]
For what it's worth, I ran terminator with --debug and here's where it hangs:

Terminal::spawn_child: Forking shell: "/bin/bash" with args: ['/bin/bash', '-c', 'ssh [redacted] -t ". /etc/bashrc; pwd; bash -l"']
ConfigBase::get_item: ConfigBase::get_item: title_hide_sizetext found in globals: False
ConfigBase::get_item: ConfigBase::get_item: title_use_system_font found in globals: True
Terminator::find_window_by_uuid: searching self.terminals for: urn:uuid:2e95e1e2-beab-4086-b233-8399b23e3cfe
Terminator::find_window_by_uuid: checking: urn:uuid:2e95e1e2-beab-4086-b233-8399b23e3cfe (<window.Window object at 0x7fe3f92d64c8 (terminatorlib+window+Window at 0x564dbfcce260)>)

[hangs here for like 2 minutes]
