### ISSUE TITLE
Context Menu not showing in v2.1.3

### ISSUE THREAD

**Issue by crux14** [gnome-terminator/terminator#746]
**Describe the bug**
After upgrading from 2.1.2 to 2.1.3, context menu does not show up by right-click.

**To Reproduce**
Open the terminal window, and then right-click.

**Desktop:**
 - OS or Linux Distribution: Debian sid
 - Display Technology: X11

With some bisect, I found that this commit (548a51c6bb11d696902db6544c715b5b32fac78e) had something to do with this issue.
The issue was fixed after I manually reverted this commit as follows.

```python
[terminatorlib/terminal_popup_menu.py]

     def add_layout_launcher(self, menu):
         """Add the layout list to the menu"""
-        item = self.menu_item(Gtk.MenuItem, 'layout_launcher', '_Layouts...')
+        # Replacing self.menu_item things with the old ones
+        item = Gtk.MenuItem.new_with_mnemonic(_('_Layouts...'))
+        # item = self.menu_item(Gtk.MenuItem, 'layout_launcher', '_Layouts...')
```

**Comment by mbway** [comment]
I am also experiencing this issue on Arch linux / KDE Plasma.
Every time I right click nothing appears and the following traceback is printed to the syslog:
```
Traceback (most recent call last):
  File "terminatorlib/terminal.py", line 1031, in on_buttonpress
    right_click[0](*right_click[1])
  File "terminatorlib/terminal.py", line 1077, in popup_menu
    menu.show(widget, event)
  File "terminatorlib/terminal_popup_menu.py", line 304, in show
    self.add_layout_launcher(menu)
  File "terminatorlib/terminal_popup_menu.py", line 329, in add_layout_launcher
    item = self.menu_item(Gtk.MenuItem, 'layout_launcher', '_Layouts...')
  File "terminatorlib/terminal_popup_menu.py", line 55, in menu_item
    mask    = self.get_menu_item_mask(maskstr)
  File "terminatorlib/terminal_popup_menu.py", line 33, in get_menu_item_mask
    maskstr = maskstr.lower()
AttributeError: 'NoneType' object has no attribute 'lower'
```
The error can be fixed by replacing line 33 with
```
        maskstr = '' if maskstr is None else maskstr.lower()
```
(but I don't know if that's the best fix)

**Comment by crux14** [comment]
Hi, @mbway

I think your problem should be related to this issue #724.
But unfortunately, that is not my case because my issue occurs in the current master branch containing with the fix PR for the issue #724.

**Comment by mbway** [comment]
ah, sorry I assumed my problem was a recent regression and your issue had the same symptom

**Comment by crux14** [comment]
I checked again on my end, but somehow the issue was fixed.
While debugging, it seems like I was messing around and things got a little strange.
It turns out it was the same issue as yours after all.
