### ISSUE TITLE
Resize borderless window

### ISSUE THREAD

**Issue by dnyazali** [gnome-terminator/terminator#75]
I've upgraded from a quite old version of terminator (v0.98) to the latest available one (v1.91) and want to use the same config as I've previously been using, which works fine! However, I am running into trouble when trying to resize the window.

In my config I've set the "borderless = True"-option which prevents me to resize the "window frame". I did not have the same issue with the previous version (v0.98). Is there any way to use a border-less option and still be able to resize the window?

**Comment by mattrose** [comment]
hmm, I'm gonna have to think on this one a bit.  The "borderless" option has likely changed going from gtk2 to gtk3 and I don't know whether we'll be able to get the old behaviour back, tbh.

**Comment by awsms** [comment]
I've always been using the borderless windows since I use terminator, and didn't know you could resize them at some point. Would be a very welcomed feature for the newer releases!

**Comment by mattrose** [comment]
Hmm, this seems to be a solution https://stackoverflow.com/questions/13638782/resize-borderless-window-with-vpaned-in-pythongtk3

**Comment by mattrose** [comment]
You can use keyboard shortcuts to move and resize.  I tested out the instructions on this page and it works.  https://help.gnome.org/users/gnome-help/stable/shell-windows-states.html.en 

I'm going to close this.  feel free to re-open if you have further problems.
