### ISSUE TITLE
Cannot open preferences on bionic

### ISSUE THREAD

**Issue by kapilbajaj1** [gnome-terminator/terminator#751]
**Describe the bug**
Preferences popup doesn't show up on selecting Preferences form right click menu

Following error is logged:
_Failed to find preferences.glade
'ascii' codec can't decode byte 0xe2 in position 41136: ordinal not in range(128)_

**To Reproduce**
Right click and select Preferences

**Additional context**
Issue is not seen after adding encoding as utf-8 while opening preferences.glade.
```
+++ /usr/lib/python3/dist-packages/terminatorlib/prefseditor.py
@@ -198,7 +198,7 @@
             # Figure out where our library is on-disk so we can open our
             (head, _tail) = os.path.split(config.__file__)
             librarypath = os.path.join(head, 'preferences.glade')
-            gladefile = open(librarypath, 'r')
+            gladefile = open(librarypath, 'r', encoding='utf-8')
             gladedata = gladefile.read()
         except Exception as ex:
             print("Failed to find preferences.glade")
```

**Comment by mattrose** [comment]
What version of python are you running?  I can't reproduce that at all.

**Comment by VersaNetworksSecurity** [comment]
I am using python 2.7.17 on bionic. If remove that patch, I can recreate the issue every time.

$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.6 LTS
Release:	18.04
Codename:	bionic

$ python --version
Python 2.7.17

> What version of python are you running? I can't reproduce that at all.

**Comment by mattrose** [comment]
We stopped supporting Python2 a few releases back.  There's just no infrastructure to support it since it went EOL in 2020
