### ISSUE TITLE
Terminator 2.1.1 has extra grey thick bars

### ISSUE THREAD

**Issue by tawmoto** [gnome-terminator/terminator#755]
Hi, I updated my Ubuntu from Xubuntu 20.04 to 22.04 (so X11) and I noticed that the new terminator (2.1.1) has extra thick bars everywhere and I dont understand why.

I tried to mark them with yellow in the pics.
Thanks

![image](https://user-images.githubusercontent.com/35702340/236490482-2d676b05-9cc9-4ac0-a873-c063b1b0f4a4.png)

**Comment by mattrose** [comment]
Can you please follow the steps in the issue template?  There's valuable information that would allow me to help you with this
