### ISSUE TITLE
Does not resize from shell running inside

### ISSUE THREAD

**Issue by aik** [gnome-terminator/terminator#759]
`print("\033[8;{};{}t".format(y, x))` (python3 code) or
`resize -s 20 20` (shell)
do work when run inside `gnome-terminal` but not `terminator` 2.1.3/fedora36 - the size does not change, is there a workaround?

The idea is to reset the terminator window size to the remote tmux window size from a script.

**Comment by mattrose** [comment]
That works in neither terminal emulator for me, can you be a little bit more specific about your setup?

**Comment by egmontkob** [comment]
I've just noticed that it's cross-posted as https://github.com/gnunn1/tilix/issues/2167.
