### ISSUE TITLE
No focus in right click menu

### ISSUE THREAD

**Issue by benmotyka** [gnome-terminator/terminator#761]
**Describe the bug**
When user right clicks in terminal, sometimes they lose focus from the pop-up menu and are unable to choose anything 

**To Reproduce**
Right click on any terminal and quickly move mouse to the place where pop-up menu opens

**Expected behavior**
Pop-up menu should keep focus properly, and items should be clickable

**Screenshots**
![terminator_issue](https://github.com/gnome-terminator/terminator/assets/60940080/d4e88197-4120-4463-8fc0-aee66ec2e6b3)

**Desktop (please complete the following information):**
 - Arch Linux
 - Display Technology: Wayland 
- terminator 2.1.3, kde plasma

**Comment by benmotyka** [comment]
Interesting fact: this issue **does not occur** on my second PC:
- Arch Linux 
- Wayland 
- Gnome

Everything seems to be very responsive there

**Comment by Vulcalien** [comment]
That's odd. Maybe it's the combination of kde and wayland that causes the problem.

Is Terminator the only application where you experience this?

**Comment by Vulcalien** [comment]
I suppose it's a system library malfunctioning in that case. Feel free to reopen if you find out that it's terminator doing something wrong instead.
