### ISSUE TITLE
Re-size the width of Terminator, the Shell Prompt will repeatedly increase in the terminal windows.

### ISSUE THREAD

**Issue by XinLong-Li** [gnome-terminator/terminator#762]
> Before opening an issue, please try starting terminator with an empty config
> file, by issuing `terminator -u -g /dev/null` and see if it starts normally.
> 
> 
> If it does, and you still want to open the bug, then please attach the
> config file, usually found at `$HOME/.config/terminator/config` to the issue
> 
> Fill out as many of these fields as you can

The Problem still exists in Terminator with an empty config file.

**Describe the bug**
When I re-size the width of Terminator, the Shell Prompt will repeatedly increase in the terminal windows. Details can be seen in Screenshots. 

**To Reproduce**
Open Terminator. 
Drag to change the width of the Terminator windows. First, reduce the width and make the Shell Prompt display in two or more lines, then increase the width significantly. 

**Expected behavior**
No matter how you drag to change the width of the terminal, there should always be only one prompt.

**Screenshots**
The second screenshot is the terminator with an empty config.
![image](https://github.com/gnome-terminator/terminator/assets/31212285/897befca-9477-4a02-9f4e-d122481a540d)

![image](https://github.com/gnome-terminator/terminator/assets/31212285/d3ad9c9a-fd5d-4222-9179-0e9093cbda99)

**Desktop (please complete the following information):**
 - OS or Linux Distribution: Ubuntu
 - Version: 20.04
 - Display Technology: X11

**Comment by Vulcalien** [comment]
I'm pretty sure there is nothing that can be done in our part to fix that behavior.

When a Terminator window gets resized, the terminal size will change. Then, the shell will notice the change in size and rewrite the prompt, in order for the user to see it on the visible section.

So, if I'm not mistaken, it's really a shell behavior. The same problem should be observed in every other terminal emulator.

**Comment by XinLong-Li** [comment]
> 
Oh, that seems true. When I resize the terminal that Ubuntu pre-installed, it has a limitation for the minimum width. The width limitation guarantee that the Shell prompt will not break the line. Therefore, Ubuntu's built-in terminal doesn't have this issue. Maybe that's a good point.



> I'm pretty sure there is nothing that can be done in our part to fix that behavior.
> 
> When a Terminator window gets resized, the terminal size will change. Then, the shell will notice the change in size and rewrite the prompt, in order for the user to see it on the visible section.
> 
> So, if I'm not mistaken, it's really a shell behavior. The same problem should be observed in every other terminal emulator.
