### ISSUE TITLE
Terminator layouts don't respect any more the number of columns

### ISSUE THREAD

**Issue by ericzolf** [gnome-terminator/terminator#766]
**Describe the bug**
Under Fedora 37, I could store a layout with 3 terminals side by side, and they would have the same number of columns as I've stored it (2 times 80 characters and one time 82 characters). Since Fedora 38, the 2nd terminal has too few columns (62) and the 3rd one has too many (105), and I can't find a way to make Terminator restore the layout correctly

**To Reproduce**
1. make 3 terminals side by side, the right-most one has a different (smaller font) profile so that I can have roughly the same number of columns in each terminal
2. resize the terminals to have the same width roughly (80-80-82 in my case)
3. save the hence created layout (I overwrote 'default')
4. close Terminator and re-open it in the saved layout

**Expected behavior**
The widths chosen before saving the layout are respected, and I don't need each time to resize the terminals to make them fit for work.

**Screenshots**
n/a

**Desktop (please complete the following information):**
 - OS or Linux Distribution: Fedora
 - Version 38 (terminator-2.1.3-1.fc38)
 - Display Technology: X11

**Additional context**
I've got the same issue on a laptop upgraded from F37 to F38, and on a fresh new laptop directly installed with F38.
I already reported the error to Fedora but thought I might be more successful here: https://bugzilla.redhat.com/show_bug.cgi?id=2203849

I've probably switched from F37 to F38 around mid/end of April, so I should have had already the same version of Terminator, updated to 2.1.3 10th of March, but I can't be 100% positive.

[config](https://github.com/gnome-terminator/terminator/files/11633328/config.txt)

**Comment by mattrose** [comment]
Weird, it doesn't seem to be saving the ratios for some of the windows when I try that.  I'll look into it when I get the chance

**Comment by mattrose** [comment]
Even more weird commit c8cd50ba9a7c1b4ecac83c2336122d4133cfabe2 is the one that broke things.  It doesn't seem related, but then again, handle_size is taken into account when laying things out.

I will try and find a better way of fixing that.

**Comment by mattrose** [comment]
Banged my head on this for a while, and decided to just revert the commit.  It sacrifices a tiny bit of usability for predictability.
