### ISSUE TITLE
Logger plugin crashes with "TypeError: 'NoneType' object is not subscriptable"

### ISSUE THREAD

**Issue by cbspidi** [gnome-terminator/terminator#776]
Starting the "terminator" without the config file gives the same results.

Fill out as many of these fields as you can

**Describe the bug**
The logger plugin does not work with the new gnome-terminal (tested it on ubuntu 23.04 and on the rolling release of Arch), the plugin crashes with "TypeError: 'NoneType'"

**To Reproduce**
Start the logger, select the destination file, produce a terminal output (example: ps -Af), and stop the logger. The logger will fail to stop and no content is written to the output file.

**Expected behavior**
Termina output is written to output file

**Screenshots**
```bash
Error log from debug mode:
Window::on_window_state_changed: fullscreen=False, maximised=False
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/terminatorlib/plugins/logger.py", line 61, in save
    self.write_content(terminal, last_saved_row, last_saved_col, row, col)
  File "/usr/lib/python3.11/site-packages/terminatorlib/plugins/logger.py", line 48, in write_content
    fd.write(content[:-1])
             ~~~~~~~^^^^^
TypeError: 'NoneType' object is not subscriptable

```

**Desktop (please complete the following information):**
 - Linux Ubuntu
 - Version 23.04
 - Display Technology:  Tested on both Wayland and X11 (ubuntu 23.04 wayland and arch was on X11)

**Comment by mattrose** [comment]
Can you tell me what version of vte you're running?

you should be able to just run `dpkg -L | grep vte`

I have a feeling that it's related to this:

>Note: since 0.68, passing a non-[None](https://docs.python.org/3/library/constants.html#None) array parameter is deprecated. Starting with 0.72, passing a non-[None](https://docs.python.org/3/library/constants.html#None) array parameter will make this function itself return [None](https://docs.python.org/3/library/constants.html#None).

Unfortunately I can't make any sense of this sentence.

**Comment by cbspidi** [comment]
Hi @mattrose , 
Im running vte 0.72.2-1,   

```bash
$ pacman -Q | grep  vte           
vte-common 0.72.2-1
vte3 0.72.2-1
```

**Comment by mattrose** [comment]
It definitely works with vte 0.70.  I can't figure out what I need to change to make my call compatible with the newer version, so I've opened https://gitlab.gnome.org/GNOME/vte/-/issues/2633

**Comment by mattrose** [comment]
Vte.Terminal().get_text_range erroneously returns None as of vte 0.72 basically as a bug in the introspection attributes, see the vte bug details. There is a new, undocumented call get_text_range_format that does work in 0.72, so I'll plug that method call in to the plugin for now.  Patch incoming

**Comment by mattrose** [comment]
I still need to test that patch on an older vte, but it should work there as well as on 0.72 and newer.
