### ISSUE TITLE
Implement OSC52 functionality to use clipboard

### ISSUE THREAD

**Issue by mjmar01** [gnome-terminator/terminator#779]
## Is your feature request related to a problem? Please describe.
There are some CLI tools that can set clipboard content to enhance workflows. These tools currently don't work completely in terminator.

## Describe the solution you'd like
Other terminal emulators often support OSC-52 escape sequences which allows this functionality. See: https://www.reddit.com/r/vim/comments/k1ydpn/a_guide_on_how_to_copy_text_from_anywhere/

## Describe alternatives you've considered
Alternative would be to not use terminator ):

That doesn't work for me

## Additional context
Originally grabbed my attention when using [soft-serve](https://github.com/charmbracelet/soft-serve). This could also be used as a test case:
```
ssh git.charm.sh
# Press "c" to copy clone URL
# -> Not in clipboard
```

**Comment by mattrose** [comment]
OSC52 is ... a very contentious feature.  It is not on the roadmap currently as it is seen as too ripe for abuse.  See https://gitlab.gnome.org/GNOME/vte/-/issues/2495 for far too many gory details

**Comment by monperrus** [comment]
For the record, https://github.com/gnome-terminator/terminator/pull/1110 is a tentative solution to this issue without any VTE change.
