### ISSUE TITLE
Display horizontal transparent line between terminals.

### ISSUE THREAD

**Issue by Tanatole** [gnome-terminator/terminator#781]
Since a few weeks or months, after an upgrade, I got a thin transparent line between my horizontal split terminals in terminator. (Sorry about lack of precision, I don't remember when it happened exactly.)

I opened `terminator -u -g /dev/null` to show you a screenshot :

**Screenshots**

![image](https://github.com/gnome-terminator/terminator/assets/30662425/49fca59a-637a-4f49-92a5-8b8b97e76b79)

**Desktop (please complete the following information):**
 - OS or Linux Distribution: Linux Mint 21.1 Vera
 - Terminator version : 2.1.1-1
 - Display Technology: X11

Kind regards,
Anatole

**Comment by mattrose** [comment]
This has to do with the separator line not having css properties in whatever theme Linux Mint is using.  It's a common problem with Mint.  Does it work with the default GNOME adwaita theme?

**Comment by Tanatole** [comment]
> This has to do with the separator line not having css properties in whatever theme Linux Mint is using. It's a common problem with Mint. Does it work with the default GNOME adwaita theme?

Thanks a lot, you're absolutely right. Indeed, gnome adwaita has this css property. I switched to this theme.

Kind regards.

**Comment by Tanatole** [comment]
I then close issue...
