### ISSUE TITLE
Terminator v2.1.3 Errors on macOS Ventura

### ISSUE THREAD

**Issue by avsion** [gnome-terminator/terminator#787]
Before opening an issue, please try starting terminator with an empty config
file, by issuing `terminator -u -g /dev/null` and see if it starts normally.

If it does, and you still want to open the bug, then please attach the
config file, usually found at `$HOME/.config/terminator/config` to the issue

Fill out as many of these fields as you can

**Describe the bug**

when i run these commands terminator is opening however i get the below errors 
`terminator` `terminator -u -g /dev/null`
Unable to open ‘/etc/xdg/terminator/config’ for reading and/or writing.
([Errno 2] No such file or directory: '/etc/xdg/terminator/config')
ConfigBase::load: Unable to open /etc/xdg/terminator/config ([Errno 2] No such file or directory: '/etc/xdg/terminator/config')
Unable to load Keybinder module. This means the hide_window shortcut will be unavailable
Unable to bind hide_window key, another instance/window has it.
PluginRegistry::load_plugins: Importing plugin command_notify.py failed: Namespace Notify not available
ActivityWatch plugin unavailable as we cannot import Notify
PluginRegistry::load_plugins: Importing plugin activitywatch.py failed: module 'activitywatch' has no attribute 'AVAILABLE'

**To Reproduce**

when i run these commands terminator is opening however i get the below errors 
`terminator` `terminator -u -g /dev/null`
also 
mac terminal will not detached /has to stay open. if i close it terminator will close as well.
when terminator is open no icon exist on the dock

**Expected behavior**

open using terminator command without error for full functionality 
detach terminator and keep the session\window open.
have a terminator icon on the dock.

**Screenshots**

**Desktop (please complete the following information):**
 - OS or Linux Distribution: [e.g. FreeBSD or Ubuntu] 
 macOS Ventura 
 - Version [e.g. 20.04] 
 13.4.1 (22F82)
 - Display Technology: 
 AFAIK  X11

**Additional context**
![Screenshot 2023-07-11 at 11 50 58](https://github.com/gnome-terminator/terminator/assets/41312349/af8dcdca-1c25-419e-ac0a-ebb463af92b2)

**Comment by mattrose** [comment]
Are you sure it's not opening an instance of terminator behind the active window?  It looks like it's starting OK.
