### ISSUE TITLE
When in broadcast mode single character(letter) is taking as double.

### ISSUE THREAD

**Issue by skmdab** [gnome-terminator/terminator#788]
Hi,

My issue is when i am in broadcast mode with two or more layouts and when i type a single letter(character) in present layout the other all layouts taking one character as two characters.

**Comment by mattrose** [comment]
This is actually an ibus issue, not a terminator issue.  Please see #674 for more details. 

tl;dr is:  Issue `ibus exit` when you're affected by this.

**Comment by skmdab** [comment]
Thank you fixed... @mattrose

**Comment by bmullan** [comment]
I just had this happen with Terminator to me on Ubuntu 22.04.2.2 LTS.

The following ***fixed the Double Character "broadcast" in Terminator*** for me!

The fix was from a French language web page and it said:  

---

**Steps:**

Find out where the terminator launch script is located?

> **$ whereis terminator**
> **terminator: /usr/bin/terminator /usr/share/terminator /usr/share/man/man1/terminator.1.gz**

Edit the launch script:

> **$ sudo nano /usr/bin/terminator**

***Insert the following lines right after the "imports"*** at the beginning of the file:

> **## Modify to stop double character broadcast**
> _**os.environ['DBUS_SESSION_BUS_ADDRESS']=''**_
> **## End of modify broadcast twice**

    Save Changes

**Comment by sakrow** [comment]
> I just had this happen with Terminator to me on Ubuntu 22.04.2.2 LTS.
> 
> The following _**fixed the Double Character "broadcast" in Terminator**_ for me!
> 
> The fix was from a French language web page and it said:
> 
> **Steps:**
> 
> Find out where the terminator launch script is located?
> 
> > **$ whereis terminator**
> > **terminator: /usr/bin/terminator /usr/share/terminator /usr/share/man/man1/terminator.1.gz**
> 
> Edit the launch script:
> 
> > **$ sudo nano /usr/bin/terminator**
> 
> _**Insert the following lines right after the "imports"**_ at the beginning of the file:
> 
> > **## Modify to stop double character broadcast**
> > _**os.environ['DBUS_SESSION_BUS_ADDRESS']=''**_
> > **## End of modify broadcast twice**
> 
> _**Save Changes**_
> 
> Restart Terminator & double character broadcasts will be gone.

Sorry for opening this issue, but I have a "new issue" after applying it.

After applying, when I click on a new URL through the terminator, Firefox tells me that:

```
Firefox is already running, but not responding. To use Firefox, you must first close the existing Firefox process, restart your device, or use a different profile.
```

And I can't find the solution. When I change the "default browser" to Chrome, this doesn't happen.

I only find that: https://computing.help.inf.ed.ac.uk/FAQ/firefox-wont-start

But when applied, Firefox creates a new cloned window, not a new tab.

Does anyone know what can I do?
