### ISSUE TITLE
In krusader terminator option --working-directory=DIR doesn't work

### ISSUE THREAD

**Issue by Pilat66** [gnome-terminator/terminator#793]
In krusader, the terminator option **--working-directory=DIR** does not work.
But the terminator **--working-directory DIR** option works correctly **without specifying the equals character**
At the same time, the form of writing options without the '=' symbol is not specified in the documentation.

**Comment by mattrose** [comment]
I'm not sure what I can do to fix this.  Running both versions of the command from bash, or any other shell works fine.  I would open a krusader issue.
