### ISSUE TITLE
custom plugins are not found when using `--display`

### ISSUE THREAD

**Issue by agroszer** [gnome-terminator/terminator#795]
- OS or Linux Distribution: Ubuntu
 - Version 22.04
 - Display Technology: X11 (vcXsrv on WSL2)
 - terminator version: 2.1.3

Tried to install EditorPlugin, wondered why it does not show up in the list.
Turns out if I start terminator with `terminator --display=$DISPLAY` to make it recognize the display, custom plugins are not listed.
Custom plugins get listed with just running `terminator`.

**Comment by mattrose** [comment]
You shouldn't need to run --display=$DISPLAY ever.  That flag is only if the $DISPLAY variable is not set correctly.  In your case it's a complete no-op.
