### ISSUE TITLE
Include global menu/preferences button in the window title bar

### ISSUE THREAD

**Issue by waldyrious** [gnome-terminator/terminator#799]
**Is your feature request related to a problem? Please describe.**
As a new user of Terminator, it took me a while after I installed it to figure out how to open the Preferences dialog (I had to open the right-click/context menu). This is not discoverable and makes the first experience harder than necessary.

**Describe the solution you'd like**

It would be nice if there was a visible "menu" button somewhere in the UI — for example, in the window's title bar. Here's how Terminator currently looks:

![image](https://github.com/gnome-terminator/terminator/assets/478237/d6317f93-c2de-4548-bff7-e88d5c6381dc)

For example, here's Gedit:

![image](https://github.com/gnome-terminator/terminator/assets/478237/3d5c3126-52f4-4730-8fab-e20ef56e2a11)

**Describe alternatives you've considered**
Perhaps reusing the layout menu that already has a visible button in the titlebar (or a separate button next to it) could be an option, but since that titlebar is terminal-specific, rather than global to the entire app, I'm afraid that would make things confusing and muddy users' mental model of how the app works.

**Comment by mattrose** [comment]
I actually coded this a while back but dropped it due to lack of interest.  There's a few ways to bring up the preferences window, I'm not sure we need another.
