### ISSUE TITLE
python3 needs to be in the shebang line for fedora.

### ISSUE THREAD

**Issue by mattrose** [gnome-terminator/terminator#8]
If I try to run the terminator script in Fedora now, I get:

```
/usr/bin/env: 'python': No such file or directory
```

Should we change this to python3?

**Comment by FernandoBasso** [comment]
I installed Xubuntu 22.04 in one of my machines, and observed I get the same error if running terminator from master. `python3` in the shebang line solves it. Checked how they package it for this distribution, and and they also use `python3`:

```text
$ sed -n 1p /usr/bin/terminator 
#!/usr/bin/python3
```

On Arch Linux I never had such a problem when running Terminator from master.

**Comment by mattrose** [comment]
@FernandoBasso You need to install `python-is-python3` (IIRC) package on ubuntu to have it make the symbolic link.  You probably did that on arch and don't remember.;
