### ISSUE TITLE
cwd.get_pid_cwd is a mess.

### ISSUE THREAD

**Issue by mattrose** [gnome-terminator/terminator#80]
This should be just a call to the python psutil module, instead it's a load of special case code for Linux, freebsd and sunos, with a call to psutil only if it's available, which it always is because terminator will not run without it.

as far as I know the psutil module works on all the platforms that are already covered by the special case code.

**Comment by egmontkob** [comment]
Well, instead: Terminator shouldn't peek into the child process's cwd at all, it should rely on the OSC 7 sequence and VTE's corresponding API (`get_current_directory_uri()`) to get the directory.

**Comment by mattrose** [comment]
Yeah, I've actually been looking at that as part of some other stuff.  

This was to clean up a *bunch* of ancient crufty code that never gets called anymore.  If we can use the vte API, then we can get rid of the dependency on psutil, and clean up some more.  I'll open a new bug specifically for that.
