### ISSUE TITLE
Explain what "Smart copy" means

### ISSUE THREAD

**Issue by waldyrious** [gnome-terminator/terminator#800]
**Is your feature request related to a problem? Please describe.**
In the Preferences window, there's a "Smart copy" checkbox but it's not clear what it does.

**Describe the solution you'd like**
It would be nice if, when hovering the checkbox or its label, a tooltip appeared explaining what this actually does.

**Describe alternatives you've considered**
Alternatives to a tooltip could be a clearer/more explicit label, or an explanatory text under the label (in a less conspicuous font size and color) with a more detailed description.

**Comment by mattrose** [comment]
I don't want to be that guy, but... 

https://gnome-terminator.readthedocs.io/en/latest/preferences.html

Tooltips would be a nice addition, but they're not implemented anywhere in the preferences UI.  Documentation is your best bet.
