### ISSUE TITLE
Button to save/apply preferences

### ISSUE THREAD

**Issue by waldyrious** [gnome-terminator/terminator#801]
**Is your feature request related to a problem? Please describe.**
In the preferences window, there is no explicit way "save" or "apply" the definitions to the main window. Most preferences are applied automatically and one actually just needs to move focus back into the main window to see the effect; but since this is not immediately clear, most people might be tempted to instead click the "close" button — which also works, but makes tweaking the preferences a more cumbersome process.

**Describe the solution you'd like**
An explicit button to apply the preferences would make it more user-friendly to interactively modify the preferences.

**Describe alternatives you've considered**
Maybe an even better approach would be to refresh the main window whenever a setting is changed in the preferences, but I'm not sure if this is feasible or desirable.

**Comment by mattrose** [comment]
In master we now have a "Discard Changes" button.  I hope that's good enough, as I don't want to add more buttons to that bottom row of the prefs window.
