### ISSUE TITLE
keyboard-shortcut-support-for-plugins-code-decoupling

### ISSUE THREAD

**Issue by vssdeo** [gnome-terminator/terminator#805]
This bug/issue separates the KeyBind utility code where the plugins have the capability to register short cuts which can then be edited via preferences window. The issue 681 had this code and plugin both. Now this separates the utility code from plugin.

Details Ref:  functionalities of the plugin https://github.com/gnome-terminator/terminator/issues/681 along with screenshots

A separate issue is seen where the keyboard signals attached to window are not caught by new windows but work on multiple tabs of same window they work fine. I have tried to look into it and tried to address it by one approach. https://github.com/gnome-terminator/terminator/pull/682/commits/37c77161f2905c39780dc28c1eecd0f945d7f9ab

**Comment by vssdeo** [comment]
Examples on how to use:
https://github.com/gnome-terminator/terminator/issues/706
https://github.com/gnome-terminator/terminator/pull/682

**Comment by mattrose** [comment]
Assuming the merged code fixes this issue
