### ISSUE TITLE
Plugins don't receive keboard signals on newly opened windows

### ISSUE THREAD

**Issue by vssdeo** [gnome-terminator/terminator#808]
Some plugins using KeyBindUtil https://github.com/gnome-terminator/terminator/issues/805 don't receive Key events in newly opened window / terminal. Reloading  of plugins helps and gives plugins an option to reconnect terminal events. This patch given on way or opens up a discussion on this and to test this.

**DEPENDENCY** 

Examples:

https://github.com/gnome-terminator/terminator/issues/706
https://github.com/gnome-terminator/terminator/pull/682

**Comment by mattrose** [comment]
Assuming that the merged code fixes this.  Please reopen if this isn't the case
