### ISSUE TITLE
Cannot resize/move/maximize terminal window

### ISSUE THREAD

**Issue by amritabithi** [gnome-terminator/terminator#812]
Before opening an issue, please try starting terminator with an empty config
file, by issuing `terminator -u -g /dev/null` and see if it starts normally.
Following those instructions will start it normally, although attached at the border to the terminal window I am calling from, and is destroyed when the calling terminal is closed.
I also got this output when doing the above command:
```
amrita@:~$ terminator -u -g /dev/null

** (terminator:42621): WARNING **: 12:19:47.853: Binding '<Shift><Control><Alt>a' failed!
Unable to bind hide_window key, another instance/window has it.
```

If it does, and you still want to open the bug, then please attach the
config file, usually found at `$HOME/.config/terminator/config` to the issue
Attached to this message at the bottom.

Fill out as many of these fields as you can

**Describe the bug**
Window is not movable and cannot be resized.  It was not like this when I first installed it yesterday.

**To Reproduce**
Just try to open a window and move it or resize it.

**Expected behavior**
When I first installed I could move and resize the window normally.

**Screenshots**

**Desktop (please complete the following information):**
 - OS or Linux Distribution: [e.g. FreeBSD or Ubuntu]
 - Version [e.g. 20.04]
 - Display Technology: Wayland or X11
Linux 22.04 Focal Fossa, Nero desktop (not Jammy Jellyfish)

**Additional context**
My fonts also became corrupted and unable to change back, so setting them in the preferences had no effect on the fonts, so I just kept setting them to default and to something else, and back to default, until it finally recognized it.  The font issue happened before the not movable/resize problem, almost as if that process of setting the fonts corrupted something.

Config file is attached:
[config.txt](https://github.com/gnome-terminator/terminator/files/12325348/config.txt)

**Comment by mattrose** [comment]
I think you may have a long-running instance of terminator that is interfering with your debugging.
Can you make sure you have no instances of terminator running, by issuing `ps auxw | grep terminator | grep -v grep` from another terminal and making sure the list of processes is empty?
