### ISSUE TITLE
Theme option disapear from context menu

### ISSUE THREAD

**Issue by yancelawang** [gnome-terminator/terminator#813]
Hello,

I can't find theme option in context menu. And also no themes option in prefererences>plugin. Btw, i use terminator version 2.1.3. Has this feature been removed?

**Comment by mattrose** [comment]
There has never been a "theme" option in the context menu in any version I've seen, nor in the Preferences menu.  There is "Colors" in the Profiles Tab in the Preferences, but I've never seen a Themes menu.

Can you respond with a config file or some kind of screenshots of what you're expecting to see?

**Comment by yancelawang** [comment]
Thanks for your fast respons. I  never documented those menu by screenshot. but i found the picture on reddit what i used before. i'm not sure (remember) if it feature build-in or third-party plug-in. 
![2023-08-24_04-02-36](https://github.com/gnome-terminator/terminator/assets/36460186/a304d69d-63f8-40cd-9aa9-0c832c8f3b99)

**Comment by mattrose** [comment]
That looks like a 3rd party plugin https://github.com/EliverLara/terminator-themes.  you may need to reinstall if you upgraded from one of the older python2 versions.

**Comment by yancelawang** [comment]
Okay. Thanks for your information.
