### ISSUE TITLE
Support for two-finger screen scrolling

### ISSUE THREAD

**Issue by monperrus** [gnome-terminator/terminator#814]
**Is your feature request related to a problem? Please describe.**
When I do two-finger scrolling, the problem is that it does shell history scrolling instead of screen scroling (expected behavior).

**Describe the solution you'd like**
A configuration option to enable scrolling with two-fingers scrolling on the touchpad.

**Describe alternatives you've considered**
Switch to Gnome Terminal which has option `View -> Hide Alternate Screen`, see https://apple.stackexchange.com/questions/235029/in-terminal-how-to-exit-the-two-fingers-history-scrolling-mode 
But Terminator is so much better.

**Additional context**
n-a

**Comment by mattrose** [comment]
I don't see this.  Are you using screen or tmux?  If so the best way to fix this it in screenrc.  https://bugs.launchpad.net/ubuntu/+source/screen/+bug/106995/comments/9 has a good fix for this.

**Comment by monperrus** [comment]
I'm using tmux. The fix is to set in `tmux.conf`

    set -g mouse on

Thanks!
