### ISSUE TITLE
Add preferences about default window size

### ISSUE THREAD

**Issue by KaitaoQiu** [gnome-terminator/terminator#815]
![image](https://github.com/gnome-terminator/terminator/assets/85727393/e44ab21e-e62d-46a0-8765-c24ffb4decfe)
When I press ctrl alt T to wake my terminal, the default size is too big (The ideal size in my mind is 1/4 of the whole screen)
I think it would be nice to **have an option in the preferences menu to set the default width and height of the terminal in pixels**. This way, I don't have to adjust the window size every time I open terminator or modify the config file manually. I hope you can consider adding this feature. Thank you for your work on terminator.

**Comment by mattrose** [comment]
You can save the width and height in the default layout.  Just set up the window the size that you want, open the Preferences window and go to the layouts tab, select the default layout, and click on the save button.

For more details see https://gnome-terminator.readthedocs.io/en/latest/layouts.html

**Comment by KaitaoQiu** [comment]
Cool, is there any template on the layout? ;)

**Comment by KaitaoQiu** [comment]
Oh, I found it on `~/.config/terminator/config`
