### ISSUE TITLE
Adjust size / resize cursor area is 1px

### ISSUE THREAD

**Issue by damonsmith** [gnome-terminator/terminator#820]
(ran with `terminator -u -g /dev/null` and I still see the issue)

**Describe the bug**
The mouse cursor area to resize the panels inside the terminator frame is only 1px and very hard to find

**To Reproduce**
hover over resize area between panels

**Expected behavior**
A wider resize area to match Gnome's standard resize cursor behaviour

**Screenshots**
[Kooha-2023-08-29-07-59-35.webm](https://github.com/gnome-terminator/terminator/assets/1510028/478e1187-5be8-4d88-abb6-1e40a047e053)

**Desktop (please complete the following information):**
Arch Linux
Gnome v44.2
Wayland

**Additional context**

**Comment by mattrose** [comment]
You can change the size of the separator size and thus the resize handle in the Preferences window.
