### ISSUE TITLE
FCITX input method does not work in Version 2.1.2  anymore 

### ISSUE THREAD

**Issue by i18nde** [gnome-terminator/terminator#828]
Before opening an issue, please try starting terminator with an empty config
file, by issuing `terminator -u -g /dev/null` and see if it starts normally.

If it does, and you still want to open the bug, then please attach the
config file, usually found at `$HOME/.config/terminator/config` to the issue

`[global_config]
  window_state = maximise
[keybindings]
[profiles]
  [[default]]
    background_darkness = 0.9
    background_type = transparent
    scrollback_infinite = True
    custom_command = im-config -s fcitx
    title_transmit_bg_color = "#1a5fb4"
    title_use_system_font = False
    title_font = JetBrains Mono Semi-Bold 12
[layouts]
  [[default]]
    [[[window0]]]
      type = Window
      parent = ""
    [[[child1]]]
      type = Terminal
      parent = window0
[plugins]`

Fill out as many of these fields as you can

**Describe the bug**
If I switch to FCITX input method, it does not work anymore in the new version. With GNOME-Terminal, UXterm ans MLTerm there is no problem, works just fine. And all GUI Apps will work fine too.

**To Reproduce**
CTRL+Space should switch.

**Expected behavior**
I should be able to input Chinese libpinyin or sunpinyin with FCITX.

**Screenshots**

**Desktop (please complete the following information):**
 - Linux Mint LMDE
 - Version 6
 - Display Technology:  X11

**Additional context**

**Comment by Thomas-Tsai** [comment]
I have the same problem in my terminator version is 2.1.2-2 with Debian. GCIN is my input method and can't input any Chinese characters now.

**Comment by Thomas-Tsai** [comment]
oh, I checked #670 and upgrade to 2.1.3-1, input is fine now. 

Thank You.
