### ISSUE TITLE
Profile per window

### ISSUE THREAD

**Issue by jrvidal** [gnome-terminator/terminator#831]
:wave: Thanks for your work on Terminator :heart: 

I have a somewhat involved custom setup where I use Terminator as my "IDE". Among other things, I try to use one dedicated profile per (major) project, so each Terminator window is visually distinctive. One issue with this approach is that if I open:

```bash
# Project 1, window 1
$ terminator --profile project1

# Project 2, window 2
$ terminator --profile project2
```

opening a tab in the first window shows me the colors for "project2".

Ideally, it would be nice to have some sort of "per-window" settings. I imagine the current behavior is somewhat related to the fact that we have a single DBus server listening to commands coming from CLI invocations. I think I've read somewhere that a nested layout of servers is a future possibility?

<details>
Apart from the profile thing, I also re-skin Terminator as a completely different desktop application, so I have "terminal windows" and "IDE windows". I suspect supporting this on Terminator proper would require some serious trickery with `WM_CLASS` that might leave it as out of scope.
</details>

**Comment by Vulcalien** [comment]
Hey! I think the "Re-use profiles for new terminals" feature does that you are asking for.

From the `terminator_config` manpage:
```
always_split_with_profile = boolean
    Specify whether splits/tabs will continue to use the profile of their peer terminal.
    If set to False, they will always use the default profile.
    Default value: False
```

The setting can be found in Preferences > Global > (right side) > Re-use profiles for new terminals. Let us know if that works for you!

---

We should consider setting the default to True, because it seems like a mostly desirable behavior.

**Comment by jrvidal** [comment]
That totally works, thank you for bearing with me :pray:
