### ISSUE TITLE
Crash after unzooming a single terminal inside a tab

### ISSUE THREAD

**Issue by Vulcalien** [gnome-terminator/terminator#835]
**To Reproduce**
Open Terminator. Open a tab. Zoom the single terminal in it (Ctrl+Shift+X), then unzoom it.

**Desktop:** (pretty sure it's not relevant)
 - OS or Linux Distribution: Linux Mint
 - Version: 21
 - Display Technology: X11

**Describe the bug**
Terminator crashes when unzooming a single terminal inside a tab. When there are 2 or more terminals, the issue doesn't occur. I did a git bisect, and found that the commit introducing the bug is `11639159`, pushed for PR #810. The problems seems to be here:
```python
#notify plugins of tab-change
dbg("emit tab-change for tabpos: %s " % tabpos)
term_widget.emit('tab-change', tabpos)
self.set_current_page(tabpos)
widget.grab_focus()
```
in `Notebook.newtab`. The problem disappears when `term_widget.emit('tab-change', tabpos)` is removed.

When it doesn't crash, I see an extremely large number of new tabs, all containing the same terminal. Maybe it gets confused by the fact there is only one terminal..?

**Comment by vssdeo** [comment]
Let me also look into this, this PR seems to be mine.

**Comment by vssdeo** [comment]
Removed the tab-change emit code. New pull request has a decoupled plugin code using focus-in event.

**Comment by Vulcalien** [comment]
I can gladly state that it's fixed now!

**Comment by vssdeo** [comment]
> I can gladly state that it's fixed now!

@Vulcalien thanks for finding this bug on time, else It would have been difficult. In addition thanks to you I was able to implement the code in a simpler way.

**Comment by Vulcalien** [comment]
> I was able to implement the code in a simpler way

That's great, glad to be helpful!
