### ISSUE TITLE
Support confirm the request before killing the terminal

### ISSUE THREAD

**Issue by Aatroy** [gnome-terminator/terminator#836]
![image](https://github.com/gnome-terminator/terminator/assets/76672938/8de34787-888e-4eab-adda-2695da54ad1d)

Like this in Ubuntu origin terminal

**Comment by mattrose** [comment]
This may be fixed in master, but can you translate the window contents so I can be sure?

**Comment by mattrose** [comment]
Gonna say this is fixed in master
