### ISSUE TITLE
terminator bug： txt_lines = txt.split( "\r\n" )

### ISSUE THREAD

**Issue by githubwys** [gnome-terminator/terminator#839]
**Describe the bug:**

ususlly, when draping a file into the window of a terminator and then drop it, the command line "XXX@XXX-PC:~$ " will show the path of the file.
However, when I pull a file into the window of a terminator, the terminator cannot get path of the file.
I check the ubuntu system Log, the msg is " txt_lines = txt.split( "\r\n" ) " ,sent by x-terminal-emul, as shown in figure.

**To Reproduce:** 
I use ubuntu20.04 and I installed conda, so that my system defalut python is python3.11 in conda. I used command " sudo apt install terminator " to install the terminator. all functionof terminator is ok except dropping file in it.

I check the reason maybe that terminator bases on python2( all file in terminatorlib seem base on python2 ), but in my ubuntu20.04, the first command in file terminator (“/usr/bin/terminator” ) is "#/usr/bin/python3". THen I confirmed that, in ubuntu18.04, the first command is "/usr/bin/python" and the defalut python in ubuntu18 is python2. I maybe find the problem but I donot know how todeal with it.  

```bash
#!/usr/bin/python3
#    Terminator - multiple gnome terminals in one window
#    Copyright (C) 2006-2010  cmsj@tenshu.net
#
#    This program is free software; you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, version 2 only.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program; if not, write to the Free Software
#    Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301  
#    USA

"""Terminator by Chris Jones <cmsj@tenshu.net>"""

import sys
import os
import psutil
import pwd
```

 The error log, " txt_lines = txt.split( "\r\n" ) " , seems like the difference  between python2 and python3. 

But I donot know how to install terminator based on python2 in ubuntu20.04 by apt-get. 

Thanks for all your help.

**Comment by mattrose** [comment]
Terminator runs fine on python3.  What version are you running.

**Comment by githubwys** [comment]
Hi, mattrose
my default python3 is python3.11.5 in conda. I think the script "/usr/bin/terminator" uses the default python3. 

details indormation :
the ubuntu20.04lts default python3 is python3.8.10. but When I installed conda the sysytem default python3 changed to python3.11.5 in conda
![2023-10-27 15-26-52屏幕截图](https://github.com/gnome-terminator/terminator/assets/49638146/d219c747-aa5a-4916-bec2-7f1385c75efe)

**Comment by githubwys** [comment]
> Terminator runs fine on python3. What version are you running.

Hi, mattrose
my default python3 is python3.11.5 in conda. I think the script "/usr/bin/terminator" uses the default python3.

details indormation :
the ubuntu20.04lts default python3 is python3.8.10. but When I installed conda the sysytem default python3 changed to python3.11.5 in conda
![2023-10-27 15-26-52屏幕截图](https://github.com/gnome-terminator/terminator/assets/49638146/15d2ca81-1fca-4442-b9a0-ae0a5d930d34)

**Comment by githubwys** [comment]
More Information:

when I drop a file into the terminator. I cannot get the file path in the command line, and the Ubuntu Logs shows as the figure attached.
![Screenshot from 2023-10-27 15-41-06](https://github.com/gnome-terminator/terminator/assets/49638146/8b942d78-5f64-430d-86e8-e9d5be870294)

**Comment by mattrose** [comment]
What version of terminator are you running?

This is most likely a known bug, fixed in a later version

**Comment by githubwys** [comment]
my terminator version is 1.91-4.
thank you, I will install a new version and have a try.

**Comment by githubwys** [comment]
Hi, Dear mattrose, 
I install a new version 2.1.3, but I may also meet the same problem that I can't get the file path.

**Comment by githubwys** [comment]
![image](https://github.com/gnome-terminator/terminator/assets/49638146/9ec14fc7-dd07-4910-a15c-9b4bd212a657)

**Comment by githubwys** [comment]
> ![image](https://user-images.githubusercontent.com/49638146/283139584-9ec14fc7-dd07-4910-a15c-9b4bd212a657.png)

Here is the screenshot. I start a terminator in ubuntu terminal. Then I draw a picture to the  terminator to get the picture path, the error accurs as it shown in ubuntu terminal.

**Comment by githubwys** [comment]
![image](https://github.com/gnome-terminator/terminator/assets/49638146/16925295-bfba-4569-b1b5-2b88b70e910b)
 this screenshot shows that my terminator version is 2.1.3-1, which should be a new version.

**Comment by githubwys** [comment]
I would be appreciate if you could help me, thank you.
