### ISSUE TITLE
Open new terminator (`Ctrl + Alt + T`) sometime will crash and close ALL terminator windows

### ISSUE THREAD

**Issue by kocoten1992** [gnome-terminator/terminator#840]
**Describe the bug**
Hello, when I open a new terminator, there is a chance it will freeze for a second and then close ALL terminator windows.

**To Reproduce**
Steps to reproduce the behavior: On ubuntu wayland, press (`Ctrl + Alt + T`), it usually will open a new terminator window, but there is a small chance (I'm not sure what trigger it) it will freeze for a second and then crash all terminator windows.

**Expected behavior**
A new window open normally

**Screenshots**
Cannot be screenshots

**Desktop (please complete the following information):**
 - OS or Linux Distribution: Ubuntu
 - Version 23.04
 - Display Technology: Wayland

**Additional context**
I already try open as many window as I could (30+), it not crashing due to number.

The file config: https://gist.github.com/kocoten1992/c3ff5090fd899461826c93974a035e15

The closest issue is this https://github.com/gnome-terminator/terminator/issues/714

But I don't see it mention in release of `v2.1.3`, this issue is quite critical since all work could be lost at any second, could we release a new version soon?

**Comment by kocoten1992** [comment]
Oh this could be a new issue, I do not have `last_active_window` in my config.

**Comment by mattrose** [comment]
If you could get the output from when it crashes that would be  the first step in diagnosing the problem.  Can you check the logs for the gui that you're using to see if it catches any output when it crashes next

**Comment by kocoten1992** [comment]
I mean, I wish to have an input guidance back then to help iron this out, now I settle with alacritty so can't help you.
