### ISSUE TITLE
Issues with Terminal reloading

### ISSUE THREAD

**Issue by DeaDvey** [gnome-terminator/terminator#850]
**Describe the bug**
On compiled from source version of Terminator with the --reload (-R) feature, the reloading doesn't work, I get this error message:
```
 $ terminator -R
Traceback (most recent call last):
  File "/usr/bin/terminator", line 92, in <module>
    dbus_service = ipc.DBusService()
                   ^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/terminatorlib/ipc.py", line 48, in __init__
    self.prepare_attributes()
  File "/usr/lib/python3.11/site-packages/terminatorlib/ipc.py", line 65, in prepare_attributes
    raise dbus.exceptions.DBusException(
dbus.exceptions.DBusException: Couldn't get DBus name net.tenshu.Terminator2c167fcb65036abc0f3dbe526aaa2db94: Name exists
```

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/terminator", line 117, in <module>
    ipc.reload_configuration()
TypeError: reload_configuration() missing 1 required positional argument: 'session'

**To Reproduce**
On source version of Terminator, built from source, type "terminator -R"

**Expected behavior**
I expect the config file to reload to a new theme

**Screenshots**
![image](https://github.com/gnome-terminator/terminator/assets/104674266/8b866be6-cb1e-43ae-8d1b-b904ebdecb30)

**Desktop (please complete the following information):**
 - OpenSUSE TumbleWeed
 - Wayland (Hyprland)

**Additional context**
I need to reload from terminal I want to be able to switch themes by pressing a button on my waybar, the config file updates correctyly, I just want terminator to reload without opening preferences and hitting close.

**Comment by DeaDvey** [comment]
It also has the same error on KDE X11, so it doesn't _seem_ to be due to Hyprland, I could be wrong though

**Comment by AtomsForPeace** [comment]
You can try my branch and see if it fixes this for you. Works for me now.
