### ISSUE TITLE
terminator.py get_focussed_terminal always returns none

### ISSUE THREAD

**Issue by vssdeo** [gnome-terminator/terminator#852]
cross checking Calling function `get_focussed_terminal` in **terminator.py**  always returns None for all calls. 

Using `terminal.get_vte().has_focus()`  in some scenarios like working with event tab-change returns None for first call, rest are ok. For others events like focus-in it seems to be working fine.  I guess depends on how the event is being handled and in what context.

Just of ref there is  is_focus() for Gtk Widget. Ref: https://lazka.github.io/pgi-docs/Gtk-3.0/classes/Widget.html#Gtk.Widget.is_focus or to set has_focus property for the first call also.

**Comment by mattrose** [comment]
@vssdeo can you make a pull request out of this commit and reference this issue?

**Comment by vssdeo** [comment]
@mattrose i think its done and closed with Ref: https://github.com/gnome-terminator/terminator/pull/856
