### ISSUE TITLE
Window splits are transparent, showing screen behind

### ISSUE THREAD

**Issue by noblerh** [gnome-terminator/terminator#854]
OS:  Linux Mint 21.2, xfce, 64bit
cmptr:  Compulab FitLet2 ordered as  "MintBox Mini 2 Pro"
Detailed info is appended below.

I recently installed Mint 21.2 from scratch on a new SSD.  After a few weeks, I installed Terminator using the Software Manager.

**Describe the bug**
Terminator opens and appears to work correctly.  Then I split the initial window with Right Click -> Split <vertical or horizontal> .  Instead of a clean split between the two windows, a thin band of transparency along the split (several pixels wide) shows whatever is behind Terminator on the screen; either the wallpaper (default LM wallpaper) or any other window.  This happens for both horizontal and vertical splits.  No change when the Terminator window is maximized or reduced to a smaller window; the transparent strips persist.

I uninstalled/reinstalled Terminator.  Same behavior.  

Exit Terminator, deleted the config file, restarted Terminator.  Same behavior.

No other programs have window problems, only Terminator.

**Screenshots**
Screenshots (2) show full screen and reduced, both with transparent splits:
![scrn_Terminator_2023-10-23_14-28-04](https://github.com/gnome-terminator/terminator/assets/32045666/d4a0f89f-d1d0-433d-ad76-b752df1cef45)
![scrn_Terminator_2023-10-23_14-41-28](https://github.com/gnome-terminator/terminator/assets/32045666/5b5cb25f-4df3-478d-82c3-25cf448a321f)

**Desktop (please complete the following information):**
 nobler@MBMA:~/.config/terminator$ inxi -Fxxxzr
System:
  Kernel: 5.15.0-86-generic x86_64 bits: 64 compiler: gcc v: 11.4.0
    Desktop: Xfce 4.18.1 tk: Gtk 3.24.33 info: xfce4-panel wm: xfwm 4.18.0
    vt: 7 dm: LightDM 1.30.0 Distro: Linux Mint 21.2 Victoria
    base: Ubuntu 22.04 jammy
Machine:
  Type: Desktop Mobo: Compulab model: fitlet2 v: 1.1
    serial: <superuser required> UEFI: American Megatrends
    v: FLT2.MBM2.0.46.02.01 date: 03/07/2021
CPU:
  Info: quad core model: Intel Celeron J3455 bits: 64 type: MCP
    smt: <unsupported> arch: Goldmont rev: 9 cache: L1: 224 KiB L2: 2 MiB
  Speed (MHz): avg: 1685 high: 2188 min/max: 800/2300 cores: 1: 1354
    2: 1081 3: 2188 4: 2118 bogomips: 11980
  Flags: ht lm nx pae sse sse2 sse3 sse4_1 sse4_2 ssse3 vmx
Graphics:
  Device-1: Intel HD Graphics 500 driver: i915 v: kernel ports: active: DP-1
    empty: HDMI-A-1,HDMI-A-2 bus-ID: 00:02.0 chip-ID: 8086:5a85 class-ID: 0300
  Display: x11 server: X.Org v: 1.21.1.4 compositor: xfwm v: 4.18.0 driver:
    X: loaded: modesetting unloaded: fbdev,vesa gpu: i915 display-ID: :0.0
    screens: 1
  Screen-1: 0 s-res: 1600x1200 s-dpi: 96 s-size: 423x317mm (16.7x12.5")
    s-diag: 529mm (20.8")
  Monitor-1: DP-1 model: Dell 2007FP serial: <filter> res: 1600x1200 hz: 60
    dpi: 111 size: 367x275mm (14.4x10.8") diag: 514mm (20.2") modes:
    max: 1600x1200 min: 720x400
  OpenGL: renderer: Mesa Intel HD Graphics 500 (APL 2)
    v: 4.6 Mesa 23.0.4-0ubuntu1~22.04.1 direct render: Yes
Audio:
  Device-1: Intel Celeron N3350/Pentium N4200/Atom E3900 Series Audio Cluster
    driver: snd_hda_intel v: kernel bus-ID: 00:0e.0 chip-ID: 8086:5a98
    class-ID: 0403
  Sound Server-1: ALSA v: k5.15.0-86-generic running: yes
  Sound Server-2: PulseAudio v: 15.99.1 running: yes
  Sound Server-3: PipeWire v: 0.3.48 running: yes
Network:
  Device-1: Intel Wireless 8260 driver: iwlwifi v: kernel pcie:
    speed: 2.5 GT/s lanes: 1 bus-ID: 01:00.0 chip-ID: 8086:24f3 class-ID: 0280
  IF: wlp1s0 state: down mac: <filter>
  Device-2: Intel I211 Gigabit Network driver: igb v: kernel pcie:
    speed: 2.5 GT/s lanes: 1 port: e000 bus-ID: 02:00.0 chip-ID: 8086:1539
    class-ID: 0200
  IF: enp2s0 state: down mac: <filter>
  Device-3: Intel I211 Gigabit Network driver: igb v: kernel pcie:
    speed: 2.5 GT/s lanes: 1 port: d000 bus-ID: 03:00.0 chip-ID: 8086:1539
    class-ID: 0200
  IF-ID-1: eno1 state: up speed: 1000 Mbps duplex: full mac: <filter>
Bluetooth:
  Device-1: Intel Bluetooth wireless interface type: USB driver: btusb v: 0.8
    bus-ID: 1-8:5 chip-ID: 8087:0a2b class-ID: e001
  Report: hciconfig ID: hci0 rfk-id: 0 state: up address: <filter>
    bt-v: 2.1 lmp-v: 4.2 sub-v: 100 hci-v: 4.2 rev: 100
Drives:
  Local Storage: total: 3.16 TiB used: 362.53 GiB (11.2%)
  ID-1: /dev/mmcblk0 model: GE8QT size: 238.5 GiB type: SSD
    serial: <filter> scheme: MBR
  ID-2: /dev/sda vendor: Transcend model: TS128GMTS430S size: 119.24 GiB
    speed: 6.0 Gb/s type: SSD serial: <filter> rev: S86A scheme: GPT
  ID-3: /dev/sdb type: USB vendor: SanDisk model: Cruzer Glide
    size: 28.67 GiB type: N/A serial: <filter> rev: 1.00 scheme: MBR
  ID-4: /dev/sdc type: USB vendor: Western Digital model: WD Elements 25A1
    size: 1.82 TiB type: N/A serial: <filter> rev: 1012 scheme: GPT
  ID-5: /dev/sdd type: USB vendor: SanDisk model: Cruzer Fit
    size: 58.73 GiB type: N/A serial: <filter> rev: 1.00 scheme: MBR
  ID-6: /dev/sde type: USB vendor: Western Digital model: WD10EADS-114BB1
    size: 930.86 GiB type: N/A serial: <filter> rev: 2003 scheme: MBR
Partition:
  ID-1: / size: 94.32 GiB used: 18.76 GiB (19.9%) fs: ext4 dev: /dev/sda1
  ID-2: /boot/efi size: 951.1 MiB used: 6.1 MiB (0.6%) fs: vfat
    dev: /dev/sda2
Swap:
  ID-1: swap-1 type: partition size: 15.87 GiB used: 186 MiB (1.1%)
    priority: -2 dev: /dev/sda3
Sensors:
  System Temperatures: cpu: 34.0 C mobo: N/A
  Fan Speeds (RPM): N/A
Repos:
  Packages: 2467 apt: 2460 flatpak: 7
  No active apt repos in: /etc/apt/sources.list
  Active apt repos in: /etc/apt/sources.list.d/official-package-repositories.list
    1: deb http://packages.linuxmint.com victoria main upstream import backport
    2: deb http://archive.ubuntu.com/ubuntu jammy main restricted universe multiverse
    3: deb http://archive.ubuntu.com/ubuntu jammy-updates main restricted universe multiverse
    4: deb http://archive.ubuntu.com/ubuntu jammy-backports main restricted universe multiverse
    5: deb http://security.ubuntu.com/ubuntu/ jammy-security main restricted universe multiverse
  Active apt repos in: /etc/apt/sources.list.d/vivaldi.list
    1: deb [arch=amd64] https://repo.vivaldi.com/stable/deb/ stable main
Info:
  Processes: 257 Uptime: 18d 21h 4m wakeups: 0 Memory: 7.58 GiB
  used: 3.5 GiB (46.2%) Init: systemd v: 249 runlevel: 5 Compilers:
  gcc: 11.4.0 alt: 11/12 Shell: Bash v: 5.1.16 running-in: xfce4-terminal
  inxi: 3.3.13

***eof***

**Comment by tompreuss** [comment]
I think this is because you're on Mint and they're not setting a CSS property correctly in the theme you're using, see https://github.com/gnome-terminator/terminator/issues/781, https://github.com/gnome-terminator/terminator/issues/441, and https://github.com/gnome-terminator/terminator/issues/293 for others with the same issue, and specifically https://github.com/gnome-terminator/terminator/issues/293#issuecomment-761613693 for an easy fix/workaround.

**Comment by noblerh** [comment]
Thank you for your quick and helpful response. I set the color to "rgb(200,200,200)" and it works.  
Glad to be back using Terminator again!
I will submit a ticket on the LM forum, recommending that this be fixed.
