### ISSUE TITLE
Loading config file does not appear to work

### ISSUE THREAD

**Issue by miguelriemoliveira** [gnome-terminator/terminator#860]
I there. Thanks for the great work creating and maintaining terminator. This is very useful for me.

**Describe the bug**
I am trying to use two different config files to be able to change the titlebar colors.

I have one config which is the standard, located in **~.config/terminator/config**, which sets yellow colors

```yaml
[global_config]
  title_transmit_fg_color = "#f6f5f4"
  title_transmit_bg_color = "#f5c211"
  title_receive_fg_color = "#77767b"
  title_receive_bg_color = "#f8e45c"
  title_inactive_fg_color = "#77767b"
  title_inactive_bg_color = "#c0bfbc"
  inactive_color_offset = 0.7961783439490446
  suppress_multiple_term_dialog = True
  always_split_with_profile = True
[keybindings]
[profiles]
  [[default]]
    background_color = "#ffffff"
    cursor_color = "#aaaaaa"
    foreground_color = "#000000"
    scrollback_infinite = True
    copy_on_selection = True
    background_image = /home/mike/Pictures/terminator_focal.png
  [[focal]]
    cursor_color = "#aaaaaa"
    exit_action = hold
    use_custom_command = True
    custom_command = distrobox enter focal
[layouts]
  [[default]]
    [[[window0]]]
      type = Window
      parent = ""
    [[[child1]]]
      type = Terminal
      parent = window0
[plugins]
```

If we launch terminator without any option we get a yellow titlebar terminal, like this:

![image](https://github.com/gnome-terminator/terminator/assets/11350998/cf83b4d9-1ff2-48ca-b655-020938bade21)

Then I created a second config file which sets green title colors, and placed it in **~.config/terminator/config_green**:

```yaml
[global_config]
  title_transmit_fg_color = "#f6f5f4"
  title_transmit_bg_color = "#f5c211"
  title_receive_fg_color = "#77767b"
  title_receive_bg_color = "#f8e45c"
  title_inactive_fg_color = "#77767b"
  title_inactive_bg_color = "#c0bfbc"
  inactive_color_offset = 0.7961783439490446
  suppress_multiple_term_dialog = True
  always_split_with_profile = True
[keybindings]
[profiles]
  [[focal]]
    cursor_color = "#aaaaaa"
    exit_action = hold
    use_custom_command = True
    custom_command = distrobox enter focal
[layouts]
  [[default]]
    [[[window0]]]
      type = Window
      parent = ""
    [[[child1]]]
      type = Terminal
      parent = window0
[plugins]
```

Then I try to run the terminator with this config_green file like this:

    terminator --config ~.config/terminator/config_green

The problem is that running this green config  I still get a terminator window with yellow titlebars, instead of the expected green titlebars.

What am I missing?

**Desktop (please complete the following information):**
 - Distributor ID:	Linuxmint
 -  Description:	Linux Mint 21.1
 - Release:	21.1
 - Codename:	vera

**Comment by mattrose** [comment]
The problem is is that the second terminator command is querying dbus to see if there are any running instances of terminator running, and if there are, they run with that config, rather than the config you specified on the command line.  To get this to work you should run any subsequent terminator commands with `terminator -u --config $config_file`. Or alternately, you should ensure that all your config files have "Enable DBUS" unchecked.

**Comment by mattrose** [comment]
Please close if this answers your question

**Comment by miguelriemoliveira** [comment]
Thanks @mattrose . I understand now.
