### ISSUE TITLE
terminator bug： can't get file path

### ISSUE THREAD

**Issue by githubwys** [gnome-terminator/terminator#861]
Describe the bug:

 I install a new version 2.1.3, but I may also meet the same problem that I can't get the file path.
![image](https://github.com/gnome-terminator/terminator/assets/49638146/a471f9ae-4857-4e09-b75a-7a9d3f953674)
Here is the screenshot. I start a terminator in ubuntu terminal. Then I draw a picture to the terminator to get the picture path, the error accurs as it shown in ubuntu terminal.

I would be appreciate if you could help me, thank you.

**Comment by githubwys** [comment]
![image](https://github.com/gnome-terminator/terminator/assets/49638146/845a25f4-b0a5-4559-9ee6-afd2ab03fffb)
this screenshot shows that my terminator version is 2.1.3-1, which should be a new version.

**Comment by mattrose** [comment]
This is fixed in master, but hasn't been a release yet.  I hope to get a release out in the next few days
