### ISSUE TITLE
Feature Request - Add the possibility to add padding for the output

### ISSUE THREAD

**Issue by MadHatterENV** [gnome-terminator/terminator#867]
**Is your feature request related to a problem? Please describe.**
selecting text etc .. are not always possible, due to the text sticking to the uttermost leftside of the screen.

**Describe the solution you'd like**
Add somewhere the possibility to add some additional space (pixels) between the first letters of output.
It will be visual appealing but also more usefull when selecting the text from left to right.

![2023_12_24--115800_Window](https://github.com/gnome-terminator/terminator/assets/48444875/62d90b10-2f97-4a57-90f5-12b078f83af4)

As you can see, i've added a screenshot where the prompt is a bit more indented.
But that has been done in my .bashrc file where my PS1 CLI is configured, the padding should also be for the rest of the output.

Kind Regards.

**Comment by egmontkob** [comment]
> selecting text etc .. are not always possible

This is not true. You can always start selecting text at the left half of the leftmost character cell. It might be a bit inconvenient, too  narrow to position your mouse, but possible.

Anyway. To increase the default padding of 1px, place something like this in your `~/.config/gtk-3.0/gtk.css`

```
vte-terminal {
    padding: 1px 1px 1px 10px;
}
```

and restart Terminator.

**Comment by FernandoBasso** [comment]
I use the same solution. My `$HOME/.config/gtk-3.0/gtk.css` looks like this:

```css
/**
 * Works for Gtk and VTE-based terminal emulators..
 */
vte-terminal,
terminal-window {
  padding: 8px 8px 8px 8px;
  -vte-terminal-inner-border: 12px 12px 18px 12px;
}
```
I don't remember why I have the inner border setting thing :sweat_smile:, but it was probably necessary at some point or for some other terminal.
