### ISSUE TITLE
drag and drop file from file-manager to terminator-release 2.1.3 causes a crash

### ISSUE THREAD

**Issue by DrReD** [gnome-terminator/terminator#871]
**Describe the bug**
drag and drop file from file-manager to terminator in the current release causes a crash

**Expected behavior**
URL of the file is pasted in the terminal window.

**Desktop (please complete the following information):**
 - Fedora 39 OS, but really OS independent,
 - terminator 2.1.3-4.fc39.1.noarch
 - Independent of Display Technology: 

**Additional context**
The solution is present in the main branch but not e in the current (Mar 1, 2023) release.
https://github.com/gnome-terminator/terminator/issues/727
https://github.com/gnome-terminator/terminator/pull/728

**Comment by mattrose** [comment]
A release is coming soon now.
