### ISSUE TITLE
preferences -> layout -> add/save does nothing

### ISSUE THREAD

**Issue by stolpeo** [gnome-terminator/terminator#877]
**Describe the bug**
I want to save a layout I created. Going to preferences -> layout and clicking add or save does nothing. The config file doesn't change. The config file exists in `~/.config/terminator/config`

**To Reproduce**
See above.

**Expected behavior**
Layout is saved

**Desktop (please complete the following information):**
 - Ubuntu 22.04 LTS

**Additional context**
Terminator 2.1.1

```
[global_config]
  case_sensitive = False
[keybindings]
[profiles]
  [[default]]
    background_color = "#282828"
    cursor_color = "#aaaaaa"
    foreground_color = "#ebdbb2"
    scrollback_infinite = True
    palette = "#282828:#cc241d:#98971a:#d79921:#458588:#b16286:#689d6a:#a89984:#928374:#fb4934:#b8bb26:#fabd2f:#83a598:#d3869b:#8ec07c:#ebdbb2"
  [[development]]
    cursor_color = "#aaaaaa"
[layouts]
  [[default]]
    [[[window0]]]
      type = Window
      parent = ""
    [[[child1]]]
      type = Terminal
      parent = window0
      profile = development
[plugins]
```

**Comment by mattrose** [comment]
Fixed in #882
