### ISSUE TITLE
Neovim incompatible keybindings

### ISSUE THREAD

**Issue by scippio** [gnome-terminator/terminator#881]
**Describe the bug**
When I set the keymap for Super/Win key in my neovim Lua config like that (Win+n):
```
vim.keymap.set('n','<D-n>','<cmd>echo "it works!"<cr>')
```
**To Reproduce**
Add above config into init.lua ...

**Expected behavior**
:]

**Desktop (please complete the following information):**
 - Archlinux
 - Display Technology: Wayland

**Additional context**
It working in kitty terminal without any problems.

**Comment by mattrose** [comment]
It looks like vte is not handling the super (Windows) key the same way that kitty does.  This looks like a vte bug.  I'll try and diagnose it and open an upstream bug, but I probably won't be able to do it until Monday at the earliest.

**Comment by mattrose** [comment]
Opened https://gitlab.gnome.org/GNOME/vte/-/issues/2738 and have some interesting input from @egmontkob in there.  

The short answer is, there's really no agreement on what to do with <super>-<letter> key combinations, so if you want that  key combination to work, the best answer right now is to stick with kitty, as that seems to do what you want in that situation.  Not to say that we won't work on it, but it'll probably be a slow process.
