### ISSUE TITLE
[Feature request] Possibility to enlarge edge bar of a tab

### ISSUE THREAD

**Issue by nautics889** [gnome-terminator/terminator#885]
**Is your feature request related to a problem? Please describe.**

I usually use mouse to resize tabs in Terminator. To manage the size of a tab I have to click on tab's edge and drag it on my desire. See screenshot below.
<details open>
  <summary>Screenshot</summary>
  
![Screenshot_2024-02-13_212131](https://github.com/gnome-terminator/terminator/assets/31508183/88e93a76-2528-4afc-a45d-3bfccb04d0a8)

The edge I've mentioned is a thin white strip in red cirle.
</details>

I work with Terminator on different devices with different resolution and screen format. Sometimes it's quite difficult to hit this edge to resize my tab. See GIF below.
<details open>
  <summary>GIF</summary>
  
![terminator-resize-2-to-gif2](https://github.com/gnome-terminator/terminator/assets/31508183/5a54ffe6-656d-446d-a253-2e650deb69c4)

I could hit that border only with 3 attempts :) Of course, I exaggerate here a bit, but it's only for the sake of demonstration. It annoys me a bit during my worktime.
</details>

___

**Describe the solution you'd like**

I would like to have a config option for configuring that border width for tabs if it's possible.

I bet there are some hotkeys for resizing tabs, but it'd be great for me to make it more convenient to manage size via mouse.

**Comment by mattrose** [comment]
Terminal Separator Size in Preferences is what you're looking for.  `handle_size` in the config file

**Comment by nautics889** [comment]
> Terminal Separator Size in Preferences is what you're looking for. `handle_size` in the config file

Thank you a lot, you've made my day. 
Apologies for the hasty issue creating.
