### ISSUE TITLE
If I save windows layout, terminator will be fullscreen when it start

### ISSUE THREAD

**Issue by Hiro527** [gnome-terminator/terminator#89]
Version: 1.91
Linux Debian arm64

If I save window layout on settings, it will be fullscreen when it start .
I checked fullscreen option in ~/.config/terminator/config of layout section but it was False.
If I delete that section, it wont cause. I wanna use my own layout but i cant...

**Comment by mattrose** [comment]
Can you try installing the latest version (I think 1.92 is available from the debian repos), or master, and see if you can reproduce it with the latest version?

**Comment by mattrose** [comment]
I couldn't reproduce this, and I haven't heard back.  I'm going to assume this is fixed.  If not, please reopen.
