### ISSUE TITLE
Improve approach to move an internal terminal within a terminal

### ISSUE THREAD

**Issue by manueljordan** [gnome-terminator/terminator#892]
Hello and thanks for this tool.

I read the [Dragging and dropping a terminal](https://terminator-gtk3.readthedocs.io/en/latest/gettingstarted.html#dragging-and-dropping-a-terminal) section. Sadly the two approaches based with the _mouse_ are tricky. I mean I can drag the internal terminal and move it to other place within the same terminal but in the moment to drop/release practically it always returns to the same place.

Pls, could you consider in create a special shortcut to move to the next or previous position? It for complex layouts. Or even better, through the right click to open the _contextual menu_ include the options such as:

* Move to next position
* Move to previous position

Therefore in same way that I can navigate among the internal terminals within the terminal through `alt + arrow key`,  do possible to move the internal terminal among the other internal terminals too.

Thanks for your understanding.

**Comment by mattrose** [comment]
Personally, if I want to move my windows around and I don't want to use the mouse I use the rotate keybinds.  This moves the window to the next position in the clockwise direction, or counter-clockwise.  Can you let me know if this will satisfy this issue?

**Comment by manueljordan** [comment]
Thanks for the reply 

>  if I want to move my windows around and I don't want to use the mouse I use the rotate keybinds

Interesting, is it documented? It to know how to accomplish that approach. Remember, I want move an internal terminal to other position among the other internal terminals within the same parent terminal.

> This moves the window to the next position in the clockwise direction, or counter-clockwise.

Has sense, I hope it works without any complexity about the layout

> Can you let me know if this will satisfy this issue?

Yes. But let me try it, I need the answer of the 1rst question.

Thank You

**Comment by manueljordan** [comment]
I tested the command it works as expected for simple layouts. So your suggestion is correct and valuable. Thank You.
It is documented at the [Using the keyboard](https://terminator-gtk3.readthedocs.io/en/latest/gettingstarted.html#using-the-keyboard) section.

**Comment by mattrose** [comment]
Closing this, then.  Thanks for the feedback
