### ISSUE TITLE
only the last added layout is used

### ISSUE THREAD

**Issue by amisk** [gnome-terminator/terminator#901]
Hello.

I had a layout that worked wonderfully.
I then added a second layout. The layout itself is the same, so the arrangements are the same, but the command that is executed when a subterminal starts is different.

But it seems that no matter which layout I want to start, it only starts the last one I added.
If I remove it again in the config file, I get the previous layout running.

I tried adding the second layout through the gui. When this showed that issue, I removed the layout in the config file, copied the previous layout with a different name and changed the commands. But it still shows the issue.

I run it on Linux Mint 21.3 and it is terminator 2.1.1

Thanks.

**Comment by mattrose** [comment]
Can you try this in the latest master?  I think this issue is fixed

**Comment by mattrose** [comment]
This is fixed in 2.1.3 apparently

**Comment by amisk** [comment]
It indeed works in 2.1.3. Thank you.
