### ISSUE TITLE
Text select on Ubuntu 24.04 doest not copy to clipboard for system use

### ISSUE THREAD

**Issue by breaker1nine** [gnome-terminator/terminator#905]
I'm on the brand new LTS release of Ubuntu 24.04:  
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=24.04
DISTRIB_CODENAME=noble
DISTRIB_DESCRIPTION="Ubuntu 24.04 LTS"

The select to copy text that works with previous releases of Ubuntu does not copy text to the clipboard for use in other applications . It does work fine within Terminator. 

I've tried turning "Smart Copy" on and off, which I think enables/disables this feature. 

The right-click then selectingt 'copy' works, but one of the features that makes Terminator great is the ability to quickly copy text to the clipboard by highlighting it, and it's not working in Ubunut 24.04.

**Comment by breaker1nine** [comment]
Any updates on this? I thought there was a possibility that the issue might be hardware-related as my 24.04 installation is on a new Asus laptop but I upgraded my Dell XPS laptop from 22.04 to 24.04, where this feature worked perfectly, and the upgrade broke it.

**Comment by mattrose** [comment]
I just tried this on Fedora 40, which should have about the same version of GNOME, if not newer, and I was unable to reproduce it.

I'm in the middle of updating my ubuntu VM 24.04 so I should have more later.

**Comment by breaker1nine** [comment]
> I just tried this on Fedora 40, which should have about the same version of GNOME, if not newer, and I was unable to reproduce it.
> 
> I'm in the middle of updating my ubuntu VM 24.04 so I should have more later.

Thanks, @mattrose

**Comment by mattrose** [comment]
I installed Ubuntu 24.04 and I was unable to reproduce what I thought was your problem.
I selected text using the left mouse button and successfully pasted the selected text into both firefox, and gnome-terminal using the middle mouse button  

Can you confirm that this is what you did?

**Comment by breaker1nine** [comment]
I'm using my laptop's mousepad which has no middle mouse button function. I've tried with an older Dell XPS and current Asus UX3405.

I'm doing what I've done for years: 
1. Select text with the left mouse button in Terminal and try to CTRL-C to paste into other apps
or 
2. <right-click> and select 'Paste'.  

With either of these methods the text that I've highlighted doesn't end up in the clipboard for other apps (Firefox or Gnome Terminal - I just tried it again with both) to use. 

Since moving to 24.04, whatever was in the clipboard before attempting to select-to-copy gets pasted, or if there was nothing in the clipboard befpre attempting select-to-copy, nothing gets pasted.

**Comment by breaker1nine** [comment]
@mattrose - I just borrowed a usb mouse to test, and can confirm that middle-click-to-paste works to paste selected text from Terminator into Chrome. 
I don't use a mouse and this would be disruptive to workflow.

**Comment by mattrose** [comment]
You need to go into the default profile and click the radio button that says "Copy on Selection". That fixed it for me on ubuntu 24.04

Please reopen if you're still having problems

**Comment by breaker1nine** [comment]
I'm so embarrased. 
I thought I'd looked in the Profile for this setting but apparently my search wasn't good enough.

I found the radio button and ticked it.  
This is working fine. 
Thanks  @mattrose !

**Comment by mattrose** [comment]
No problem.  It took me a moment to figure this out.

**Comment by Gitroma** [comment]
> I'm on the brand new LTS release of Ubuntu 24.04: DISTRIB_ID=Ubuntu DISTRIB_RELEASE=24.04 DISTRIB_CODENAME=noble DISTRIB_DESCRIPTION="Ubuntu 24.04 LTS"
> 
> The select to copy text that works with previous releases of Ubuntu does not copy text to the clipboard for use in other applications . It does work fine within Terminator.
> 
> I've tried turning "Smart Copy" on and off, which I think enables/disables this feature.
> 
> The right-click then selectingt 'copy' works, but one of the features that makes Terminator great is the ability to quickly copy text to the clipboard by highlighting it, and it's not working in Ubunut 24.04.

I Fixed this way:

sudo apt install nemo

Done!! Enjoy!!

**Comment by emotroshylov** [comment]
> You need to go into the default profile and click the radio button that says "Copy on Selection". That fixed it for me on ubuntu 24.04
> 
> Please reopen if you're still having problems

Hi
Where can I find default profile ?
