### ISSUE TITLE
more than a year since issue #727 fix and no release yet

### ISSUE THREAD

**Issue by H4-b** [gnome-terminator/terminator#906]
**Is your feature request related to a problem? Please describe.**

It's been more than a year since this bug is fixed, but there is no way to get it other than compiling from source

**Describe the solution you'd like**

a new version with the "recent" patches added

**Describe alternatives you've considered**

 adding an unstable branch to the repo if the current patches add instability

**Comment by knedl1k** [comment]
UP!

**Comment by mattrose** [comment]
https://github.com/gnome-terminator/terminator/releases/tag/v2.1.4
