### ISSUE TITLE
Zoom preset

### ISSUE THREAD

**Issue by jmle** [gnome-terminator/terminator#909]
**Is your feature request related to a problem? Please describe.**
I have several screens in my home setup, and the one holding the terminal is smaller. I can't properly see the letters, so I need to zoom in manually every time I open a new window.

**Describe the solution you'd like**
I would like the zoom to be an adjustable preference.

**Describe alternatives you've considered**
I considered changing cell width/height, but it's not the same. Looks bad.

**Additional context**
I haven't been able to find a way of doing this; if there is one, please accept my apologies for posting this.

**Comment by mattrose** [comment]
Change the font size in the default profile instead.

I'm gonna close this, if this doesn't fix your problem, reopen it.
