### ISSUE TITLE
Select-by-word characters to select part of content

### ISSUE THREAD

**Issue by timur-g** [gnome-terminator/terminator#910]
This is a question or feature request, IDK (could not find, so excuse me if that exists).
In some terminals there is "Select-by-word characters" with value of -A-Za-z0-9,./?%&#:_=+@~ to select part of content between chars.
Like if content is sha:12345 to select only 12345. Is that possible?

**Comment by mattrose** [comment]
In Terminator there is too.  https://gnome-terminator.readthedocs.io/en/latest/preferences.html#general

**Comment by timur-g** [comment]
Thanks, I somehow did not see it. 
BUT, it does not seem to work, as when I double click sha:12345 I expect that only 12345 is selected (as : is in the list), while all is selected.

**Comment by timur-g** [comment]
Sorry, but this does not work for me. Please see  ![image](https://github.com/user-attachments/assets/1eb2a56c-899b-4daa-9e50-57097ab6020d)
