### ISSUE TITLE
Terminator failed to launch on FreeBSD 14.1-RELEASE (cairo issue).

### ISSUE THREAD

**Issue by jfoucry** [gnome-terminator/terminator#916]
Before opening an issue, please try starting terminator with an empty config
file, by issuing `terminator -u -g /dev/null` and see if it starts normally.

No luck.

If it does, and you still want to open the bug, then please attach the
config file, usually found at `$HOME/.config/terminator/config` to the issue

I removed my config.

Fill out as many of these fields as you can

**Describe the bug**
Terminator failed to launch on FreeBSD-14.1-RELEASE (latest version). Same error form the source or the package.
`Traceback (most recent call last):
  File "/usr/local/bin/terminator", line 47, in <module>
    import terminatorlib.optionparse
  File "/usr/local/lib/python3.11/site-packages/terminatorlib/optionparse.py", line 22, in <module>
    from terminatorlib.terminator import Terminator
  File "/usr/local/lib/python3.11/site-packages/terminatorlib/terminator.py", line 14, in <module>
    from . import borg
  File "/usr/local/lib/python3.11/site-packages/terminatorlib/borg.py", line 11, in <module>
    from .util import dbg
  File "/usr/local/lib/python3.11/site-packages/terminatorlib/util.py", line 21, in <module>
    import cairo
ModuleNotFoundError: No module named 'cairo'`

I installed
`py311-cairo-1.21.0,1
py311-cairocffi-1.4.0
py311-cairosvg-2.7.1_1
`
And all the requirement needed (updated them to python3.11)
Clone project sources and apply the `INSTALL.md` instructions

**To Reproduce**
On FreeBSD 14-RELEASE. install the requirement, install ALL cairo package, compile as described in the document, launch terminator and got the error (see above).

**Expected behavior**
Terminator actually launch and work as expected.

**Desktop (please complete the following information):**
 - FreeBSD
 - 14.1-RELEASE
 - X11

**Comment by mattrose** [comment]
At a guess you're probably missing the cairo gobject introspection files.  I have no idea how those packages are built or run on FreeBSD, and I don't currently have a FreeBSD machine to try it out  Did you try just installing it from pkg or ports?

**Comment by jfoucry** [comment]
Hello,

I install it by the pkg tool. I try to compile the port with no success. 
I will look at `cairo gobject introspection`

**Comment by jfoucry** [comment]
Hello again,

I just install some missing or bad install py311-<libraries> (`cairo` and `six` which look bad installed) and now I can use terminator again.
Thanks for your time and the project

**Comment by mattrose** [comment]
Glad it worked out!
