### ISSUE TITLE
When I bind it to a group and input it on one terminal, it will repeat multiple times on the other terminal

### ISSUE THREAD

**Issue by Xiangjincheng** [gnome-terminator/terminator#918]
[config.md](https://github.com/user-attachments/files/15791113/config.md)

**Describe the bug**
When I bind it to a group and input it on one terminal, it will repeat multiple times on the other terminal

**To Reproduce**
1.ctrl+shift+e :to create a terminator;
2.super+g: binding them;
3.input anything

**Screenshots**
![Screenshot from 2024-06-11 23-10-35](https://github.com/gnome-terminator/terminator/assets/78129965/f9d44c1a-3b26-4f92-b8ab-9484e802240a)

**Desktop (please complete the following information):**
-No LSB modules are available.
-Distributor ID:	Ubuntu
-Description:	Ubuntu 24.04 LTS
-Release:	24.04
-Codename:	noble

**Comment by mattrose** [comment]
IBUS bug.  See #674 for some ideas on how to fix it.
