### ISSUE TITLE
Title bar color selection per panel.

### ISSUE THREAD

**Issue by pbnf** [gnome-terminator/terminator#927]
**Add Ability to Set Title Bar Color Per Panel**
 
**Description:**
 
Requesting the addition of a feature to customize the color of the title bar for each panel in Terminator.
 
**Proposed Functionality:**
 
- Allow users to set a custom color for each panel's title bar.
- Include a right-click option on the title bar that opens a color palette chooser.
 
**Benefits:**
 
- **Enhanced Organization:** Quickly identify and switch between panels based on color coding.
- **Improved Productivity:** Reduces the cognitive load of managing multiple terminal sessions.
- **Customization:** Adds personalization to the user experience.

Ty.

**Comment by mattrose** [comment]
You should be able to set titlebar colours by profile, which would do most of this feature.

**Comment by pbnf** [comment]
Profile indeed does the trick. this feature request is redundant.
