### ISSUE TITLE
Get rid of title bar

### ISSUE THREAD

**Issue by donjan** [gnome-terminator/terminator#952]
**Is your feature request related to a problem? Please describe.**
Since Terminator has its own little title bars per pane, the GTK window title bar is superfluous. It can be removed by undecorating the window in 'Preferences > Window borders', but that also removes the borders/shadows and makes Terminator uncomfortable to distinguish against other screen content.

**Describe the solution you'd like**
A checkbox 'Preferences > Window title' to remove the title bar (headerbar in modern GTK), but leave the borders intact (actually just the shadows are sufficient).
Alternatively, the existing window borders checkbox, but with an option to add back shadows.

**Describe alternatives you've considered**
I've tried toying around in `~/.config/gtk-3.0/gtk.css`, but didn't find any `.terminator-terminal-window ...` that would affect the window title bar.

**Comment by donjan** [comment]
I've been trying a couple of things without any visible effect:
- Modify `terminatorlib/window.py::Window.set_borderless`
```python
    def set_borderless(self, value):
        """Set the state of the window border from the supplied value"""
        #self.set_decorated (not value)
        self.set_titlebar (None)
```

- Add to the bottom of `terminatorlib/terminator.py::Terminator.new_window` a line that should set the decorations to border-only in a drawn window: `window.set_decorations(Gdk.WMDecoration.BORDER)`

**Comment by mattrose** [comment]
I looked through all the GTK API docs and I don't see a way of doing what you're asking, which is likely why nothing you've tried has worked.  I'm going to close off this bug, but please feel free to re-open if you've found a way, or open a PR.
