### ISSUE TITLE
Simbols not shown properly

### ISSUE THREAD

**Issue by acampove** [gnome-terminator/terminator#955]
Before opening an issue, please try starting terminator with an empty config
file, by issuing `terminator -u -g /dev/null` and see if it starts normally.

If it does, and you still want to open the bug, then please attach the
config file, usually found at `$HOME/.config/terminator/config` to the issue

Fill out as many of these fields as you can

**Describe the bug**
I am seeing things like this:

![image](https://github.com/user-attachments/assets/3b24811d-5a42-4375-b2bd-3f40996f1e57)

when I use terminator with midnight-commander. The same sort of stuff seems to happen with neovim:

![image](https://github.com/user-attachments/assets/095eeef2-0a01-46c3-a4ba-5609038184f9)

this does not happen when I use other terminals. 

**To Reproduce**

I am using WSL2, but I do not believe it has to do with  WSL2.  I use terminator 2.1.1

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS or Linux Distribution: [e.g. FreeBSD or Ubuntu]
 - Version [e.g. 20.04]
 - Display Technology: Wayland or X11

Linux ubuntu 5.15.153.1-microsoft-standard-WSL2 #1 SMP Fri Mar 29 23:14:13 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux

echo $XDG_SESSION_TYPE

shows tty

**Additional context**

**Comment by FernandoBasso** [comment]
Is the terminal under WSL  using fonts (like nerd fonts) that support those symbols?

**Comment by acampove** [comment]
> Is terminator on WSL using fonts (like nerd fonts) that support those symbols?

I do not really know. Is there a way to check that?

**Comment by acampove** [comment]
> > > Is terminator on WSL using fonts (like nerd fonts) that support those symbols?
> > 
> > 
> > I do not really know. Is there a way to check that?
> 
> Basically from the preferences -> profiles -> font. Then you can select a font that has support for fancy symbols.
> 
> Are the screenshots you posted something from a file explorer from vim or emacs, or from an `ls` command?

Thanks, I found it:

![image](https://github.com/user-attachments/assets/b982a3f1-3d82-4d52-ba47-56279629994b)

but a lot of symbols seem to have those boxes when I select them. The screen shots are from nnn file explorer and neovim respectively.

**Comment by FernandoBasso** [comment]
Could be some quirk of running terminator under WSL, but I would first guess you just need to install something like nerd fonts and select one of them. I don't have a windows machine to test, but it is probably possible.

**Comment by mattrose** [comment]
This is a font rendering thing.  There's not much we can do about this

**Comment by acampove** [comment]
@mattrose Yeah, I agree. In any case, I moved out of WSL2 and I am found the same problem with gnome-terminal in alma9. What I did was:

```bash
wget -P ~/.local/share/fonts https://github.com/ryanoasis/nerd-fonts/releases/download/v3.0.2/JetBrainsMono.zip \
&& cd ~/.local/share/fonts \
&& unzip JetBrainsMono.zip \
&& rm JetBrainsMono.zip \
&& fc-cache -fv
```

which installs new fonts from:

https://www.nerdfonts.com/font-downloads

and that seems to work.
