### ISSUE TITLE
Output lines disappear when resizing terminal window

### ISSUE THREAD

**Issue by gkatev** [gnome-terminator/terminator#964]
**Describe the bug**
When the shell prompt overflows into a second line, resizing Terminator's window causes part of the text in the terminal (the last line) to disappear.

**To Reproduce**
1. Open a terminator window.
2. Navigate to a directory with a long path and/or resize the window, so that the shell prompt (which we assume includes the full path to the current dir), takes up a second line.
3. Get some output to appear, e.g. by reading this file: [lorem.txt](https://github.com/user-attachments/files/17939188/lorem.txt)
4. Enlarge the window, so that the shell prompt no longer takes up two lines.
5. Notice that the last line of the output previously visible on the terminal has now disappeared.
6. You can again reduce and increase the size of the window in the same manner, and the next line will go as well.

**Expected behavior**
We would never want output to disappear. Even if it must get garbled up under certain circumstances (e.g. too small window?), we would expect all to be normal once the circumstances improve.

**Video**

https://github.com/user-attachments/assets/b3f39bff-215a-423c-91cd-fb76f2b93835

**Desktop:**
- Arch Linux X11

**Comment by egmontkob** [comment]
Unfortunately your shell (presumably `bash`) instructs the terminal to overwrite that line, and Terminator (actually VTE behind it) just obeys this instruction.

Please see https://gitlab.gnome.org/GNOME/gnome-terminal/-/issues/7998 for detailed explanation.

(Also https://gitlab.gnome.org/GNOME/vte/-/issues/2686 is relevant; it's a far-fetched idea that probably won't ever be implemented.)

**Comment by egmontkob** [comment]
I can easily believe that `zsh` suffers from the same issue, I'm not familiar with `zsh`.

I'm sorry but I don't know if any such discussion has ever taken place with either of these shells' developers, nor whether `zsh` perhaps does have a corresponding feature (config option) already implemented; I'm almost certain `bash`/`readline` doesn't (I read its changelog at every major release).

When I implemented rewrapping the lines in VTE 11 years ago, I surely could have given a heads-up to the devs of these shells but I didn't, I thought they'd notice it and sort it out on their own, or at least others would report it. After all, VTE wasn't the first (nor the last) terminal to behave like this.

It's somewhat a mystery to me how two popular shells could both have missed this so far. Maybe their devs use terminals that don't rewrap and no one bothered to report this issue to them. Maybe they discussed it, blamed these "modern" terminals and refused to adapt to this new behavior. Maybe something else. I don't know.

**Comment by egmontkob** [comment]
Yes, VTE adjusts not just the cursor but also the saved cursor position.

**Comment by gkatev** [comment]
I tried applying the aforementioned patch, it did kind of work, but not all that robustly. In the simple slow resize case it did fix the issue, but with some more stress or when using F11 it failed. Anyway...
