### ISSUE TITLE
Add URL Handler

### ISSUE THREAD

**Issue by timur-g** [gnome-terminator/terminator#975]
This is a kind request for help to add another URL handler. There is explanation at https://gnome-terminator.readthedocs.io/en/latest/plugins.html but I would need practical solution.
When adding URL handler, is it correct to put something lke the following (please correct) to ~/.config/terminator/plugins/gerrit,py? Supposedly it should work, but when added there, I do not see it in the list plugins to enable.

As fo the content, there it gives sample:
```
class LaunchpadBugURLHandler(plugin.URLHandler):
  capabilities = ['url_handler']
  handler_name = 'launchpad_bug'
  match = '\\b(lp|LP):?\s?#?[0-9]+(,\s*#?[0-9]+)*\\b'

  def callback(self, url):
    for item in re.findall(r'[0-9]+', url):
      return('https://bugs.launchpad.net/bugs/%s' % item)
```

 My modification does not work. Expected match is `sha:abc123`. Expected URL to open is https://gerrit.site.org/abc123 . 
```
import terminatorlib.plugin as plugin
AVAILABLE = ['GerritCommitURLHandler']

class GerritCommitURLHandler(plugin.URLHandler):
    """Gerrit Commit URL handler, if the URL starts with sha"""
    capabilities = ['url_handler']
    handler_name = 'gerrit_commit'
    match = '\\sha:*\\b'
    nameopen = "Open Gerrit commit"
    namecopy = "Copy Gerrit URL"

    def callback(self, url):
        """Look for the number in the supplied string and return it as a URL"""
        for item in re.findall(r'[0-9]+', url):
            url = 'https://gerrit.site.org/%s' % item
            return(url)
```
The site in Third party plugins mentions https://github.com/rail/dotfiles/blob/master/terminator_bugzilla_handler.py but that link is dead.

**Comment by mattrose** [comment]
I would just change the regex it looks for from `match = '\\sha:*\\b'` to something more like `match = '\bsha:[0-9a-fA-F]*\b' assuming the gerrit commit url is a hex format of the commit hash.  I would also play around with that regex in something like regex101.com to make sure it matches what you want and doesn't match what you don't

HTH

**Comment by timur-g** [comment]
Main issue now is that sha:abc123 is not URL, for example in the result of `git log`. I do not care about limiting the content.
Future issue would be to open URL (if I get it).

Side issue is that ~/.config/terminator/plugins/gerrit,py somehow does not appear in the plugin list, but it does when added to  /usr/lib/python3/dist-packages/terminatorlib/plugins/url_handlers.py
Seems it depens on something, as I tried editor_plugin.py there and it appears (but cannot be selected).

**Comment by mattrose** [comment]
that's what the callback section does.  Makes it so that string turns into a clickable link to the site specified.

**Comment by timur-g** [comment]
Thanks.  Working now.
