### ISSUE TITLE
Why we use python in shebang

### ISSUE THREAD

**Issue by egmontkob** [gnome-terminator/terminator#98]
I recommend to change `#!/usr/bin/env python` to `#!/usr/bin/env python3`.

Terminator now works fine with python3. Python2 has EOLed.

For a couple of years going, distributions will probably still ship both versions, and it's going to be a mess whether `python` points to `python2` or `python3` on various systems.

So, referring to `python` means that the project needs to keep supporting and testing for both versions in parallel, which is probably a neverending source of bugs, and is developer time not well spent.

(I happened to notice this because my Ubuntu 20.04 complained that it couldn't load the `configobj` module; 20.04 no longer ships its `python2` version, only the `python3` one, whereas my `python` symlink still points to `python2`. I've continuously upgraded through earlier Ubuntu releases, I don't know if a fresh install would default to `python3`, or if I removed `python2` then whether the `python` symlink would be updated to `python3`.)

**Comment by mattrose** [comment]
This should be covered by the setup.py install routine as part of the package installation.  I'm not sure who's in charge of the Ubuntu package, but I just installed a fresh version of ubuntu 20.04 so I can check that out.  I know python 2 is EOL and unsupported, but there are still a lot of environments where it's still critical, so we're still trying to stay compatible with it for now.

**Comment by mattrose** [comment]
Just checked ubuntu 20.04 from fresh install, and it worked fine.  I think that if the ubuntu package requires python3-configobj and it's not installed, the ubuntu package should install it as a dependency.

**Comment by egmontkob** [comment]
> This should be covered by the setup.py

I didn't run setup.py, I just ran `./terminator` from the checked-out tree. This used to work up until recently. If you say it's no longer supported, that's fair.

> but there are still a lot of environments where it's still critical, so we're still trying to stay compatible with it for now.

This shouldn't be about python2 being installed or not. This should be about python3 and only about python3.

Are there really systems where a new enough (what's the exact version requirement?) python3 isn't available, but it's important to have the latest and greatest Terminator? Makes no sense to me. Anyone with such an old system should be fine with Stephen's python2-based 1.91, or the dual-python just-forked-the-project-and-released-here 1.92.

In my opinion, for further development of the project, you should ignore this negligible user base, get rid of any sign of python2, and any chance of (intentionally or accidentally) using that as the interpreter.

**Comment by lazyfrosch** [comment]
This is all about best practices, the scripts are meant to be run in a development environment, such as virtualenvs. There `python` is an alias or symlink, which points to the correct Python binary.

When you want to use a Python tool outside of a development environment, you should always install it. And there you can pick `python3` to do it. All installed scripts will have the correct shebang.

Current best-practice in Python is to completely avoid console scripts with shebangs, but generate them by pointing to a module's (main) function. I tend to do that at some point.

Also see:
* https://mail.python.org/pipermail/tutor/2007-June/054816.html
* #8

**Comment by egmontkob** [comment]
> Current best-practice in Python is to completely avoid console scripts with shebangs, but generate them by pointing to a module's (main) function.

As per the link you provided, you do this so that it doesn't matter whether it's `/usr/bin/python` or `/usr/local/bin/python` or `/opt/python` or `/home/joesmith/python` etc. Yup the `/usr/bin/env python` trick is the well-known solution for this problem. But it's not related to picking the proper one of python2 vs. python3.

Look, it's your project, your decision. But maintaining python2 support in parallel to python3 is an utter waste of developer resources. Or if you decide to require python3, you don't lose anything by placing this in the shebang like – along with the `env` wrapper, but you win the possibility of easier testing, and you exclude the possibility of accidentally starting up with the wrong interpreter on ad-hoc setups. Just my 2 cents.

**Comment by lazyfrosch** [comment]
Hard coding `python3` is not a good idea as well. I mentioned it in the documentation now.
