### ISSUE TITLE
When opening a new window, terminator automatically switch to the last tab of the first window.

### ISSUE THREAD

**Issue by freud14** [gnome-terminator/terminator#99]
Hi,

When I already have a terminator window opened with multiple tabs, if I open another window of terminator, the tab of the first window switches to its rightmost tab. I searched on Google and strangely found no bug report about that. I'm using Gnome on Ubuntu 20.04.

Steps to reproduce:
1. Open a terminator window
2. Open a new tab in the terminator window opened in 1.
3. Switch back to the first tab in the terminator window opened in 1.
4. Open a new terminator window.

Step 4 should trigger a change of tab in the terminator window opened in 1 for the rightmost tab.

This is quite annoying. Let me know whether you are able to reproduce the bug.

Thank you.

**Comment by ameiji** [comment]
I have the same issue. 
When I start a new instance of terminator, by a hotkey from gnome shell, an already opened termintator window switches to it's last tab.
Contrarywise, if I issue a "new_window" command by terminator's hotkey, this tab switch doesn't happen.

**Comment by freud14** [comment]
>  Contrarywise, if I issue a "new_window" command by terminator's hotkey, this tab switch doesn't happen.

Yes indeed.

**Comment by mattrose** [comment]
Ah, I was wondering why I couldn't reproduce this earlier, as I always open a new window in terminator.  I'll see if I can do it some other way.

**Comment by mattrose** [comment]
I've been playing around with this and I've figured out why this is happening.  Basically when you issue terminator from a command, it assumes it's starting from scratch each time, so it automatically goes to the first tab on any window with multiple tabs.  Now I just have to figure out how to stop it from doing that...

**Comment by mattrose** [comment]
Investigated some more this evening and confirmed that if you use the command `remotinator new_window` rather than `terminator` to open a new window the problem doesn't happen which means it's definitely how the terminator script spawns the window.  Unfortunately, the way the terminator script spawns the window is a mess.

**Comment by freud14** [comment]
Hi, I investigated a bit. It seems that terminator calls the [`new_window_cmdline`](https://github.com/gnome-terminator/terminator/blob/master/terminatorlib/ipc.py#L69) method in the DBus service whereas reminator calls the [`new_window`](https://github.com/gnome-terminator/terminator/blob/master/terminatorlib/ipc.py#L89) method which absolutely does not do the same thing as the former. I think it does so in order to be able to accept command line arguments. By looking at the code of `layout_done` in `Terminator`, I've found that commenting the line [`term.ensure_visible_and_focussed()`](https://github.com/gnome-terminator/terminator/blob/master/terminatorlib/terminator.py#L386) "solves" the bug. I'm not familiar at all with the codebase of Terminator, so I wouldn't know what this line is useful for and how to avoid calling it to all terminator window but to call only when it's relevant.

**Comment by mattrose** [comment]
OMG, you're now officially ahead of me on this one Thanks!  I took a break over the weekend, but I'll look into this soon.  I'll have to chew on this to figure out if `ensure_visible_and_focussed` does the right thing, and where else it's used, if anywhere.

**Comment by mattrose** [comment]
You were on the right track.  I actually did pretty much the same thing as you did, but removed a **whole** bunch of other code at the same time.

I think it was cycling through all the open tabs to make sure they they had `last_active_term` set.  That's the only reason I can think of to do that.

**Comment by freud14** [comment]
The impression I have is that in the case where multiple windows are opened at the same time, you may want them all to be displayed to the user. So maybe this is what this code is doing?

**Comment by freud14** [comment]
Thank you very much for your help.

**Comment by avasalya** [comment]
this solution works, by https://bugs.launchpad.net/terminator/+bug/1508531/comments/8

~/.config/terminator/config

`[global_config]
  dbus = False`

**Comment by freud14** [comment]
Hi @avasalya , there has been a fix for this a while ago and it is available in new versions.

**Comment by ak2766** [comment]
Hi @freud14   and thank you for your input in this rather annoying behaviour of Terminator.

Unfortunately for us still on Ubuntu 20.04.4 LTS (even at this very late stage in its lifecycle), what @avasalya suggests is the only solution for those reliant on `apt upgrade` or `apt dist-upgrade` for system updates.  This has been irking me for eons and I for one am glad he shared as it has resolved that problem for me.
